-- P5: Legal Stack - Complete Lesson Expansion
-- Add remaining lessons to complete all 12 modules (33 additional lessons)
-- Version: 3.0.0
-- Date: 2025-08-21

BEGIN;

-- Add remaining lessons for modules 4-12 (33 lessons total)
DO $$
DECLARE
    p5_product_id text;
    module_4_id text;
    module_5_id text;
    module_6_id text;
    module_7_id text;
    module_8_id text;
    module_9_id text;
    module_10_id text;
    module_11_id text;
    module_12_id text;
BEGIN
    SELECT id INTO p5_product_id FROM "Product" WHERE code = 'P5';
    SELECT id INTO module_4_id FROM "Module" WHERE "productId" = p5_product_id AND "orderIndex" = 4;
    SELECT id INTO module_5_id FROM "Module" WHERE "productId" = p5_product_id AND "orderIndex" = 5;
    SELECT id INTO module_6_id FROM "Module" WHERE "productId" = p5_product_id AND "orderIndex" = 6;
    SELECT id INTO module_7_id FROM "Module" WHERE "productId" = p5_product_id AND "orderIndex" = 7;
    SELECT id INTO module_8_id FROM "Module" WHERE "productId" = p5_product_id AND "orderIndex" = 8;
    SELECT id INTO module_9_id FROM "Module" WHERE "productId" = p5_product_id AND "orderIndex" = 9;
    SELECT id INTO module_10_id FROM "Module" WHERE "productId" = p5_product_id AND "orderIndex" = 10;
    SELECT id INTO module_11_id FROM "Module" WHERE "productId" = p5_product_id AND "orderIndex" = 11;
    SELECT id INTO module_12_id FROM "Module" WHERE "productId" = p5_product_id AND "orderIndex" = 12;
    
    -- Module 4: Employment Law Excellence (4 lessons)
    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", metadata, "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, module_4_id, 13, 'Employment Contract Design', 'Master comprehensive employment agreement creation for all roles and levels.', '["Design role-specific employment templates", "Create comprehensive policy integration", "Implement performance-based protections", "Establish clear termination protocols"]'::jsonb, '[{"title": "Employment Contract Template Library", "type": "template", "isPremium": true}, {"title": "Policy Integration Checklist", "type": "checklist", "isPremium": true}, {"title": "HR Legal Compliance Guide", "type": "guide", "isPremium": true}]'::jsonb, 85, 110, 1, '{"difficulty": "Advanced", "category": "Employment Law"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_4_id, 14, 'Employee Relations & Policies', 'Build bulletproof HR policies that prevent disputes and ensure compliance.', '["Create comprehensive employee handbook", "Design performance management systems", "Implement grievance procedures", "Establish disciplinary frameworks"]'::jsonb, '[{"title": "Employee Handbook Template", "type": "template", "isPremium": true}, {"title": "Performance Management System", "type": "system", "isPremium": true}, {"title": "Grievance Process Framework", "type": "framework", "isPremium": true}]'::jsonb, 90, 120, 2, '{"difficulty": "Intermediate", "category": "HR Policies"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_4_id, 15, 'Compliance & Labor Law', 'Navigate complex labor law requirements and maintain full compliance.', '["Audit current labor law compliance", "Create compliance monitoring systems", "Design regulatory reporting frameworks", "Implement violation prevention protocols"]'::jsonb, '[{"title": "Labor Law Compliance Audit", "type": "audit", "isPremium": true}, {"title": "Regulatory Reporting Templates", "type": "template", "isPremium": true}, {"title": "Violation Prevention Toolkit", "type": "toolkit", "isPremium": true}]'::jsonb, 95, 125, 3, '{"difficulty": "Expert", "category": "Labor Law"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_4_id, 16, 'Workplace Safety & Protection', 'Create comprehensive workplace safety and employee protection systems.', '["Design workplace safety protocols", "Implement harassment prevention systems", "Create incident reporting procedures", "Establish safety training programs"]'::jsonb, '[{"title": "Workplace Safety Manual", "type": "manual", "isPremium": true}, {"title": "Harassment Prevention Toolkit", "type": "toolkit", "isPremium": true}, {"title": "Incident Response Templates", "type": "template", "isPremium": true}]'::jsonb, 80, 105, 4, '{"difficulty": "Intermediate", "category": "Workplace Safety"}'::jsonb, now(), now()),

    -- Module 5: Dispute Prevention & Resolution (4 lessons)
    (gen_random_uuid()::text, module_5_id, 17, 'Dispute Prevention Systems', 'Build proactive systems to identify and prevent legal disputes before they escalate.', '["Create dispute early warning systems", "Design conflict resolution protocols", "Implement mediation frameworks", "Establish escalation procedures"]'::jsonb, '[{"title": "Dispute Prevention Matrix", "type": "tool", "isPremium": true}, {"title": "Conflict Resolution Playbook", "type": "playbook", "isPremium": true}, {"title": "Mediation Process Templates", "type": "template", "isPremium": true}]'::jsonb, 85, 115, 1, '{"difficulty": "Advanced", "category": "Dispute Prevention"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_5_id, 18, 'Alternative Dispute Resolution', 'Master arbitration, mediation, and other ADR mechanisms for efficient dispute resolution.', '["Design ADR clause library", "Create arbitrator selection criteria", "Implement mediation protocols", "Establish enforcement procedures"]'::jsonb, '[{"title": "ADR Clause Template Library", "type": "template", "isPremium": true}, {"title": "Arbitrator Database", "type": "database", "isPremium": true}, {"title": "Mediation Training Resources", "type": "training", "isPremium": true}]'::jsonb, 90, 120, 2, '{"difficulty": "Expert", "category": "ADR"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_5_id, 19, 'Litigation Management', 'Prepare and manage litigation processes efficiently when disputes cannot be avoided.', '["Create litigation readiness assessment", "Design case management systems", "Implement document preservation", "Establish legal team coordination"]'::jsonb, '[{"title": "Litigation Readiness Checklist", "type": "checklist", "isPremium": true}, {"title": "Case Management Templates", "type": "template", "isPremium": true}, {"title": "Document Preservation Guide", "type": "guide", "isPremium": true}]'::jsonb, 95, 130, 3, '{"difficulty": "Expert", "category": "Litigation"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_5_id, 20, 'Settlement & Recovery', 'Optimize settlement negotiations and debt recovery processes for maximum efficiency.', '["Design settlement negotiation strategies", "Create recovery action frameworks", "Implement enforcement mechanisms", "Establish collection procedures"]'::jsonb, '[{"title": "Settlement Strategy Playbook", "type": "playbook", "isPremium": true}, {"title": "Debt Recovery Templates", "type": "template", "isPremium": true}, {"title": "Enforcement Toolkit", "type": "toolkit", "isPremium": true}]'::jsonb, 80, 110, 4, '{"difficulty": "Advanced", "category": "Settlement"}'::jsonb, now(), now()),

    -- Module 6: Data Protection & Privacy Compliance (4 lessons)
    (gen_random_uuid()::text, module_6_id, 21, 'Privacy Framework Design', 'Build comprehensive privacy frameworks compliant with global and Indian regulations.', '["Conduct privacy impact assessment", "Design data protection policies", "Create consent management systems", "Implement privacy by design"]'::jsonb, '[{"title": "Privacy Impact Assessment Tool", "type": "tool", "isPremium": true}, {"title": "Data Protection Policy Templates", "type": "template", "isPremium": true}, {"title": "Consent Management Framework", "type": "framework", "isPremium": true}]'::jsonb, 100, 140, 1, '{"difficulty": "Expert", "category": "Data Privacy"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_6_id, 22, 'GDPR & IT Act Compliance', 'Navigate complex GDPR and IT Act requirements for bulletproof compliance.', '["Audit GDPR compliance status", "Implement IT Act requirements", "Create cross-border transfer protocols", "Design violation response procedures"]'::jsonb, '[{"title": "GDPR Compliance Audit Kit", "type": "audit", "isPremium": true}, {"title": "IT Act Implementation Guide", "type": "guide", "isPremium": true}, {"title": "Data Transfer Agreement Templates", "type": "template", "isPremium": true}]'::jsonb, 110, 150, 2, '{"difficulty": "Expert", "category": "Regulatory Compliance"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_6_id, 23, 'Data Security & Breach Response', 'Implement robust data security measures and effective breach response protocols.', '["Design data security frameworks", "Create breach response procedures", "Implement incident management", "Establish notification protocols"]'::jsonb, '[{"title": "Data Security Assessment Tool", "type": "tool", "isPremium": true}, {"title": "Breach Response Playbook", "type": "playbook", "isPremium": true}, {"title": "Incident Management Templates", "type": "template", "isPremium": true}]'::jsonb, 95, 125, 3, '{"difficulty": "Advanced", "category": "Data Security"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_6_id, 24, 'Privacy Technology Implementation', 'Deploy cutting-edge privacy technologies for automated compliance and protection.', '["Implement privacy management tools", "Design automated compliance systems", "Create privacy dashboards", "Establish monitoring protocols"]'::jsonb, '[{"title": "Privacy Management System Guide", "type": "guide", "isPremium": true}, {"title": "Automated Compliance Templates", "type": "template", "isPremium": true}, {"title": "Privacy Monitoring Dashboard", "type": "dashboard", "isPremium": true}]'::jsonb, 90, 120, 4, '{"difficulty": "Expert", "category": "Privacy Technology"}'::jsonb, now(), now()),

    -- Module 7: Regulatory Compliance Automation (3 lessons)
    (gen_random_uuid()::text, module_7_id, 25, 'Multi-Regulatory Framework', 'Design comprehensive systems managing compliance across multiple regulatory bodies.', '["Map all applicable regulations", "Create compliance matrix", "Design unified reporting systems", "Implement cross-regulatory monitoring"]'::jsonb, '[{"title": "Regulatory Mapping Tool", "type": "tool", "isPremium": true}, {"title": "Compliance Matrix Template", "type": "template", "isPremium": true}, {"title": "Unified Reporting System", "type": "system", "isPremium": true}]'::jsonb, 105, 145, 1, '{"difficulty": "Expert", "category": "Regulatory Framework"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_7_id, 26, 'Compliance Automation Tools', 'Implement advanced automation tools for seamless regulatory compliance management.', '["Deploy compliance automation software", "Create automated reporting systems", "Implement violation alerts", "Design compliance dashboards"]'::jsonb, '[{"title": "Compliance Automation Guide", "type": "guide", "isPremium": true}, {"title": "Automated Reporting Templates", "type": "template", "isPremium": true}, {"title": "Compliance Dashboard Setup", "type": "setup", "isPremium": true}]'::jsonb, 95, 130, 2, '{"difficulty": "Advanced", "category": "Compliance Automation"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_7_id, 27, 'Regulatory Change Management', 'Stay ahead of regulatory changes with proactive monitoring and adaptation systems.', '["Create regulatory change monitoring", "Design adaptation procedures", "Implement update protocols", "Establish change communication"]'::jsonb, '[{"title": "Regulatory Monitoring System", "type": "system", "isPremium": true}, {"title": "Change Management Templates", "type": "template", "isPremium": true}, {"title": "Update Communication Framework", "type": "framework", "isPremium": true}]'::jsonb, 85, 115, 3, '{"difficulty": "Intermediate", "category": "Change Management"}'::jsonb, now(), now()),

    -- Module 8: Corporate Governance Excellence (3 lessons)
    (gen_random_uuid()::text, module_8_id, 28, 'Board Governance Systems', 'Establish world-class board governance structures and management processes.', '["Design board charter and structure", "Create board meeting protocols", "Implement director duties framework", "Establish governance reporting"]'::jsonb, '[{"title": "Board Charter Template", "type": "template", "isPremium": true}, {"title": "Board Meeting Management Kit", "type": "kit", "isPremium": true}, {"title": "Director Duties Guide", "type": "guide", "isPremium": true}]'::jsonb, 90, 125, 1, '{"difficulty": "Advanced", "category": "Board Governance"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_8_id, 29, 'Shareholder Relations & Rights', 'Manage shareholder relations and protect shareholder rights through proper governance.', '["Create shareholder communication strategy", "Design voting procedures", "Implement rights protection", "Establish dispute resolution"]'::jsonb, '[{"title": "Shareholder Relations Toolkit", "type": "toolkit", "isPremium": true}, {"title": "Voting Procedure Templates", "type": "template", "isPremium": true}, {"title": "Rights Protection Framework", "type": "framework", "isPremium": true}]'::jsonb, 85, 115, 2, '{"difficulty": "Intermediate", "category": "Shareholder Relations"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_8_id, 30, 'Compliance & Reporting Excellence', 'Master corporate compliance reporting and regulatory disclosure requirements.', '["Audit corporate compliance status", "Create reporting automation", "Design disclosure procedures", "Implement monitoring systems"]'::jsonb, '[{"title": "Corporate Compliance Audit", "type": "audit", "isPremium": true}, {"title": "Reporting Automation System", "type": "system", "isPremium": true}, {"title": "Disclosure Procedure Templates", "type": "template", "isPremium": true}]'::jsonb, 95, 130, 3, '{"difficulty": "Expert", "category": "Corporate Compliance"}'::jsonb, now(), now()),

    -- Module 9: M&A Legal Readiness (3 lessons)
    (gen_random_uuid()::text, module_9_id, 31, 'Due Diligence Preparation', 'Prepare comprehensive due diligence materials for seamless M&A transactions.', '["Create virtual data room", "Organize legal documentation", "Prepare disclosure schedules", "Implement access controls"]'::jsonb, '[{"title": "Data Room Setup Guide", "type": "guide", "isPremium": true}, {"title": "Due Diligence Checklist", "type": "checklist", "isPremium": true}, {"title": "Disclosure Schedule Templates", "type": "template", "isPremium": true}]'::jsonb, 100, 140, 1, '{"difficulty": "Expert", "category": "Due Diligence"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_9_id, 32, 'Transaction Documentation', 'Master complex transaction documentation for acquisitions, mergers, and investments.', '["Design transaction structure", "Create definitive agreements", "Implement closing conditions", "Establish post-closing procedures"]'::jsonb, '[{"title": "Transaction Agreement Templates", "type": "template", "isPremium": true}, {"title": "Closing Checklist", "type": "checklist", "isPremium": true}, {"title": "Post-Closing Procedures", "type": "procedures", "isPremium": true}]'::jsonb, 110, 155, 2, '{"difficulty": "Expert", "category": "Transaction Law"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_9_id, 33, 'Integration & Post-Merger', 'Execute seamless legal integration processes for successful post-merger operations.', '["Plan legal integration roadmap", "Merge corporate structures", "Integrate compliance systems", "Establish unified governance"]'::jsonb, '[{"title": "Legal Integration Playbook", "type": "playbook", "isPremium": true}, {"title": "Corporate Structure Merger Guide", "type": "guide", "isPremium": true}, {"title": "Unified Governance Framework", "type": "framework", "isPremium": true}]'::jsonb, 95, 135, 3, '{"difficulty": "Expert", "category": "Post-Merger Integration"}'::jsonb, now(), now()),

    -- Module 10: International Legal Expansion (3 lessons)
    (gen_random_uuid()::text, module_10_id, 34, 'Cross-Border Legal Framework', 'Navigate complex international legal requirements for global business expansion.', '["Analyze target market regulations", "Design multi-jurisdiction structure", "Create compliance frameworks", "Establish local partnerships"]'::jsonb, '[{"title": "International Legal Analysis Tool", "type": "tool", "isPremium": true}, {"title": "Multi-Jurisdiction Structure Guide", "type": "guide", "isPremium": true}, {"title": "Cross-Border Compliance Templates", "type": "template", "isPremium": true}]'::jsonb, 105, 145, 1, '{"difficulty": "Expert", "category": "International Law"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_10_id, 35, 'International Contracts & Agreements', 'Create bulletproof international agreements covering multiple jurisdictions and legal systems.', '["Design international contract templates", "Navigate jurisdiction clauses", "Implement dispute resolution", "Establish enforcement mechanisms"]'::jsonb, '[{"title": "International Contract Library", "type": "template", "isPremium": true}, {"title": "Jurisdiction Analysis Framework", "type": "framework", "isPremium": true}, {"title": "International Dispute Resolution Guide", "type": "guide", "isPremium": true}]'::jsonb, 100, 140, 2, '{"difficulty": "Expert", "category": "International Contracts"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_10_id, 36, 'Global Compliance Management', 'Manage compliance across multiple countries with unified systems and reporting.', '["Create global compliance matrix", "Design unified reporting systems", "Implement multi-country monitoring", "Establish local representation"]'::jsonb, '[{"title": "Global Compliance Management System", "type": "system", "isPremium": true}, {"title": "Multi-Country Reporting Templates", "type": "template", "isPremium": true}, {"title": "Local Representation Guide", "type": "guide", "isPremium": true}]'::jsonb, 95, 135, 3, '{"difficulty": "Expert", "category": "Global Compliance"}'::jsonb, now(), now()),

    -- Module 11: Legal Technology & Automation (3 lessons)
    (gen_random_uuid()::text, module_11_id, 37, 'Legal Tech Implementation', 'Deploy cutting-edge legal technology for enhanced efficiency and compliance.', '["Evaluate legal tech solutions", "Implement contract management", "Deploy compliance automation", "Create legal dashboards"]'::jsonb, '[{"title": "Legal Tech Evaluation Matrix", "type": "tool", "isPremium": true}, {"title": "Contract Management System Setup", "type": "setup", "isPremium": true}, {"title": "Legal Dashboard Templates", "type": "template", "isPremium": true}]'::jsonb, 90, 125, 1, '{"difficulty": "Advanced", "category": "Legal Technology"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_11_id, 38, 'AI & Legal Automation', 'Harness artificial intelligence for document review, contract analysis, and legal research.', '["Implement AI document review", "Deploy contract analysis tools", "Create legal research systems", "Establish AI governance"]'::jsonb, '[{"title": "AI Legal Implementation Guide", "type": "guide", "isPremium": true}, {"title": "Contract Analysis Tool Setup", "type": "setup", "isPremium": true}, {"title": "AI Governance Framework", "type": "framework", "isPremium": true}]'::jsonb, 100, 140, 2, '{"difficulty": "Expert", "category": "AI Legal Tech"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_11_id, 39, 'Legal Operations Excellence', 'Build world-class legal operations with metrics, efficiency, and strategic alignment.', '["Design legal operations framework", "Implement performance metrics", "Create efficiency protocols", "Establish strategic alignment"]'::jsonb, '[{"title": "Legal Operations Playbook", "type": "playbook", "isPremium": true}, {"title": "Legal Metrics Dashboard", "type": "dashboard", "isPremium": true}, {"title": "Strategic Alignment Framework", "type": "framework", "isPremium": true}]'::jsonb, 95, 130, 3, '{"difficulty": "Advanced", "category": "Legal Operations"}'::jsonb, now(), now()),

    -- Module 12: Professional Certification & Mastery (6 comprehensive lessons)
    (gen_random_uuid()::text, module_12_id, 40, 'Legal Mastery Assessment', 'Comprehensive assessment of your legal knowledge and implementation capabilities.', '["Complete comprehensive legal assessment", "Identify knowledge gaps", "Create improvement plan", "Prepare for certification"]'::jsonb, '[{"title": "Legal Mastery Assessment Tool", "type": "assessment", "isPremium": true}, {"title": "Gap Analysis Framework", "type": "framework", "isPremium": true}, {"title": "Certification Preparation Guide", "type": "guide", "isPremium": true}]'::jsonb, 120, 200, 1, '{"difficulty": "Expert", "category": "Assessment"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_12_id, 41, 'Case Study Implementation', 'Apply your legal knowledge to real-world startup scenarios and complex legal challenges.', '["Analyze complex legal scenarios", "Develop comprehensive solutions", "Present implementation strategies", "Defend legal recommendations"]'::jsonb, '[{"title": "Legal Case Study Library", "type": "case_study", "isPremium": true}, {"title": "Solution Development Framework", "type": "framework", "isPremium": true}, {"title": "Legal Presentation Templates", "type": "template", "isPremium": true}]'::jsonb, 150, 250, 2, '{"difficulty": "Expert", "category": "Case Studies"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_12_id, 42, 'Legal Strategy Presentation', 'Present comprehensive legal strategy to expert panel for evaluation and feedback.', '["Prepare comprehensive legal strategy", "Create professional presentation", "Present to expert panel", "Incorporate expert feedback"]'::jsonb, '[{"title": "Legal Strategy Template", "type": "template", "isPremium": true}, {"title": "Presentation Guidelines", "type": "guide", "isPremium": true}, {"title": "Expert Feedback Framework", "type": "framework", "isPremium": true}]'::jsonb, 180, 300, 3, '{"difficulty": "Expert", "category": "Strategy Presentation"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_12_id, 43, 'Professional Network Building', 'Build professional relationships within the legal community and startup ecosystem.', '["Identify key legal professionals", "Create networking strategy", "Build relationship frameworks", "Establish ongoing connections"]'::jsonb, '[{"title": "Legal Professional Directory", "type": "directory", "isPremium": true}, {"title": "Networking Strategy Guide", "type": "guide", "isPremium": true}, {"title": "Relationship Management System", "type": "system", "isPremium": true}]'::jsonb, 90, 125, 4, '{"difficulty": "Intermediate", "category": "Professional Networking"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_12_id, 44, 'Certification Examination', 'Complete comprehensive certification examination covering all aspects of startup legal mastery.', '["Take comprehensive certification exam", "Demonstrate legal expertise", "Pass certification requirements", "Receive official certification"]'::jsonb, '[{"title": "Certification Study Guide", "type": "guide", "isPremium": true}, {"title": "Practice Examination Bank", "type": "exam", "isPremium": true}, {"title": "Certification Requirements", "type": "requirements", "isPremium": true}]'::jsonb, 240, 500, 5, '{"difficulty": "Expert", "category": "Certification"}'::jsonb, now(), now()),
    (gen_random_uuid()::text, module_12_id, 45, 'Legal Mastery Graduation', 'Graduate as a certified legal professional with comprehensive startup law expertise.', '["Complete final assessment", "Receive professional certification", "Join alumni network", "Access ongoing resources"]'::jsonb, '[{"title": "Professional Certification", "type": "certificate", "isPremium": true}, {"title": "Alumni Network Access", "type": "network", "isPremium": true}, {"title": "Ongoing Resource Library", "type": "library", "isPremium": true}]'::jsonb, 60, 100, 6, '{"difficulty": "Graduate", "category": "Graduation"}'::jsonb, now(), now());
END $$;

COMMIT;

-- Final verification
SELECT 'P5 Complete Status' as status, 
       (SELECT COUNT(*) FROM "Module" WHERE "productId" IN (SELECT id FROM "Product" WHERE code = 'P5')) as modules,
       (SELECT COUNT(*) FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" IN (SELECT id FROM "Product" WHERE code = 'P5'))) as lessons;