-- P18: Operations & Supply Chain Mastery Course Migration
-- 40 days, 8 modules, comprehensive operations infrastructure

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P18',
        'Operations & Supply Chain Mastery',
        'Build world-class operations infrastructure from process design to scaling - 8 modules covering SOPs, supply chain, vendor management, quality systems, inventory, logistics, cost optimization, and scaling. 70% of Indian startups struggle with operational inefficiencies.',
        5999,
        40,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P18';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: Process Design (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'Process Design', 'Master the foundations of operational excellence - SOPs, workflow design, and process optimization', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'Operations Strategy Fundamentals', 'Learn why 70% of Indian startups struggle with operational inefficiencies. Understand the operations value chain from procurement to delivery. Define your operations philosophy: cost leadership vs differentiation vs focus. Map your current operations landscape and identify critical gaps.', '["Document your operations philosophy in 3-5 sentences", "Map your end-to-end operations value chain", "Identify top 5 operational pain points", "Create operations improvement priority matrix"]'::jsonb, '{"templates": ["Operations Value Chain Template", "Gap Analysis Matrix"], "tools": ["Operations Maturity Assessment"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'Standard Operating Procedures (SOPs)', 'Master the art of creating SOPs that drive consistency and quality. Understand SOP hierarchy: policies, procedures, work instructions. Learn the SMART format for actionable SOPs. Create version control and update mechanisms.', '["Identify 10 critical processes needing SOPs", "Create SOP template for your organization", "Write SOP for most critical process", "Set up SOP review and approval workflow"]'::jsonb, '{"templates": ["SOP Master Template", "SOP Index Register"], "tools": ["SOP Documentation System"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'Workflow Design & Mapping', 'Design efficient workflows using process mapping techniques. Learn BPMN notation for clear process visualization. Identify bottlenecks, redundancies, and improvement opportunities. Create swimlane diagrams for cross-functional processes.', '["Create process map for order-to-delivery flow", "Identify 3 major bottlenecks in current workflow", "Design improved workflow with time savings", "Document handoff points between teams"]'::jsonb, '{"templates": ["BPMN Process Template", "Swimlane Diagram Template"], "tools": ["Process Mapping Software Guide"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'Process Optimization Techniques', 'Apply lean principles to eliminate waste in operations. Learn the 8 types of waste (TIMWOODS). Implement value stream mapping for process improvement. Use Kaizen methodology for continuous improvement.', '["Conduct waste audit on key process", "Create value stream map (current state)", "Design future state value stream map", "Plan 3 quick-win improvement initiatives"]'::jsonb, '{"templates": ["Value Stream Mapping Template", "Waste Identification Checklist"], "tools": ["Lean Assessment Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Process Metrics & KPIs', 'Define and track key process performance indicators. Understand cycle time, throughput, and efficiency metrics. Create process dashboards for real-time visibility. Set up alerts for process deviations.', '["Define 5 critical process KPIs", "Set baseline measurements for each KPI", "Create process performance dashboard", "Establish KPI review cadence"]'::jsonb, '{"templates": ["Process KPI Framework", "Dashboard Template"], "tools": ["Process Analytics Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: Supply Chain Fundamentals (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'Supply Chain Fundamentals', 'Build robust supply chain infrastructure - supplier selection, procurement strategies, and logistics basics', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'Supply Chain Strategy Design', 'Design supply chain strategy aligned with business goals. Understand push vs pull supply chain models. Learn about supply chain network design. Balance cost, speed, and flexibility trade-offs.', '["Define your supply chain strategy objectives", "Map current supply chain network", "Identify strategic supply chain decisions", "Create supply chain risk assessment"]'::jsonb, '{"templates": ["Supply Chain Strategy Canvas", "Network Design Template"], "tools": ["Supply Chain Maturity Assessment"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'Supplier Identification & Selection', 'Master supplier identification across India. Use supplier discovery platforms and trade directories. Evaluate suppliers using comprehensive criteria. Conduct effective supplier visits and audits.', '["Identify 5 potential suppliers for key material", "Create supplier evaluation scorecard", "Conduct supplier capability assessment", "Document supplier qualification process"]'::jsonb, '{"templates": ["Supplier Evaluation Scorecard", "Supplier Audit Checklist"], "tools": ["Supplier Discovery Platform Guide"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'Procurement Process Excellence', 'Design efficient procurement workflows. Create purchase requisition and approval systems. Implement competitive bidding processes. Master purchase order management and tracking.', '["Design procurement approval matrix", "Create RFQ template and process", "Set up PO tracking system", "Establish procurement SLAs"]'::jsonb, '{"templates": ["RFQ Template", "Purchase Order Template", "Procurement SLA Document"], "tools": ["Procurement Management System"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Logistics Fundamentals', 'Understand logistics modes in India: road, rail, air, sea. Learn about freight costs and optimization. Navigate customs and regulatory requirements. Design inbound and outbound logistics flows.', '["Map current logistics network", "Compare logistics mode costs", "Identify logistics optimization opportunities", "Create logistics provider evaluation criteria"]'::jsonb, '{"templates": ["Logistics Cost Calculator", "Mode Selection Matrix"], "tools": ["Freight Rate Comparison Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'Supply Chain Visibility', 'Implement supply chain tracking and visibility. Use technology for real-time shipment tracking. Create supply chain control tower concepts. Monitor supplier performance dashboards.', '["Identify visibility gaps in supply chain", "Evaluate tracking technology options", "Design supply chain dashboard", "Set up supplier performance monitoring"]'::jsonb, '{"templates": ["Supply Chain Dashboard Template", "Visibility Requirements Doc"], "tools": ["Supply Chain Tracking Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: Vendor Management (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'Vendor Management', 'Master vendor relationships - evaluation frameworks, contract negotiations, and performance management', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'Vendor Evaluation Framework', 'Create comprehensive vendor evaluation systems. Define evaluation criteria: quality, cost, delivery, service. Implement vendor scoring and ranking methodologies. Build vendor tiering for strategic management.', '["Define vendor evaluation criteria weights", "Create vendor scorecard template", "Evaluate top 5 vendors using scorecard", "Establish vendor tier classifications"]'::jsonb, '{"templates": ["Vendor Scorecard Template", "Vendor Tiering Matrix"], "tools": ["Vendor Evaluation Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'Vendor Contracts & Agreements', 'Draft effective vendor contracts with all essential clauses. Include quality specifications, delivery terms, and penalties. Navigate Indian contract law requirements. Handle contract renewals and amendments.', '["Create master vendor agreement template", "Define standard terms and conditions", "Include quality and delivery SLAs", "Set up contract management system"]'::jsonb, '{"templates": ["Vendor Agreement Template", "SLA Definition Template"], "tools": ["Contract Management System"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'Vendor Negotiation Strategies', 'Master negotiation tactics for better terms. Understand total cost of ownership approach. Learn win-win negotiation frameworks. Handle difficult vendor negotiations professionally.', '["Prepare negotiation strategy for key vendor", "Calculate total cost of ownership", "Identify negotiation leverage points", "Create negotiation playbook"]'::jsonb, '{"templates": ["Negotiation Preparation Checklist", "TCO Calculator"], "tools": ["Negotiation Strategy Builder"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'Vendor Relationship Management', 'Build strategic vendor partnerships beyond transactions. Implement vendor development programs. Create joint improvement initiatives. Manage vendor communication and feedback.', '["Identify strategic vendors for partnership", "Design vendor development program", "Create quarterly business review format", "Set up vendor communication cadence"]'::jsonb, '{"templates": ["QBR Template", "Vendor Development Plan"], "tools": ["Vendor Relationship Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'Vendor Performance Monitoring', 'Track and improve vendor performance continuously. Define vendor KPIs and metrics. Implement vendor report cards. Handle underperforming vendors effectively.', '["Define vendor KPIs by category", "Create vendor performance dashboard", "Implement monthly performance reviews", "Design vendor improvement action plans"]'::jsonb, '{"templates": ["Vendor KPI Framework", "Performance Report Card"], "tools": ["Vendor Performance Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Quality Systems (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Quality Systems', 'Build quality infrastructure - quality control, ISO fundamentals, and Six Sigma introduction', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Quality Management Fundamentals', 'Understand quality management principles and philosophy. Learn about quality costs: prevention, appraisal, failure. Define quality policy and objectives. Create quality culture in your organization.', '["Draft quality policy statement", "Identify current quality costs", "Define quality objectives for next quarter", "Plan quality awareness program"]'::jsonb, '{"templates": ["Quality Policy Template", "Quality Cost Calculator"], "tools": ["Quality Maturity Assessment"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'Quality Control Systems', 'Implement incoming, in-process, and final inspection systems. Create inspection checklists and sampling plans. Set up quality checkpoints in production. Document and track quality defects.', '["Design quality inspection workflow", "Create inspection checklist templates", "Define sampling plan methodology", "Set up defect tracking system"]'::jsonb, '{"templates": ["Inspection Checklist Template", "Sampling Plan Guide"], "tools": ["Quality Inspection App"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'ISO 9001 Fundamentals', 'Understand ISO 9001:2015 quality management system requirements. Learn about documentation requirements and process approach. Prepare for ISO certification journey. Calculate ROI of ISO certification for startups.', '["Study ISO 9001:2015 requirements", "Conduct gap analysis against ISO", "Create ISO implementation roadmap", "Estimate certification timeline and cost"]'::jsonb, '{"templates": ["ISO Gap Analysis Checklist", "ISO Implementation Plan"], "tools": ["ISO Readiness Assessment"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Six Sigma Introduction', 'Learn Six Sigma DMAIC methodology basics. Understand process capability and sigma levels. Apply basic statistical tools for quality improvement. Identify Six Sigma project opportunities.', '["Learn DMAIC methodology basics", "Identify process improvement opportunity", "Calculate current process sigma level", "Plan first Six Sigma project"]'::jsonb, '{"templates": ["DMAIC Project Template", "Process Capability Calculator"], "tools": ["Six Sigma Tools Kit"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Root Cause Analysis & CAPA', 'Master root cause analysis techniques: 5 Whys, Fishbone, Pareto. Implement Corrective and Preventive Action (CAPA) system. Create effective problem-solving teams. Prevent recurrence of quality issues.', '["Learn 5 Whys and Fishbone techniques", "Analyze recent quality issue using RCA", "Create CAPA process and forms", "Train team on problem-solving methods"]'::jsonb, '{"templates": ["RCA Template", "CAPA Form"], "tools": ["Root Cause Analysis Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: Inventory Management (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'Inventory Management', 'Master inventory control - stock optimization, reorder points, and safety stock calculations', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'Inventory Classification & Analysis', 'Implement ABC-XYZ inventory classification. Understand inventory turnover and holding costs. Analyze slow-moving and obsolete inventory. Create inventory health metrics.', '["Classify inventory using ABC-XYZ analysis", "Calculate inventory turnover ratio", "Identify slow-moving inventory items", "Create inventory health dashboard"]'::jsonb, '{"templates": ["ABC-XYZ Analysis Template", "Inventory Health Scorecard"], "tools": ["Inventory Classification Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'Demand Forecasting Basics', 'Learn demand forecasting methods for inventory planning. Understand seasonality and trend analysis. Use historical data for predictions. Handle forecast accuracy and bias.', '["Analyze historical demand patterns", "Apply basic forecasting methods", "Calculate forecast accuracy metrics", "Create demand forecast for key items"]'::jsonb, '{"templates": ["Demand Forecasting Template", "Forecast Accuracy Tracker"], "tools": ["Forecasting Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Reorder Point & EOQ', 'Calculate optimal reorder points for inventory items. Apply Economic Order Quantity (EOQ) formula. Balance ordering costs vs holding costs. Implement automated reorder triggers.', '["Calculate reorder points for A-class items", "Apply EOQ formula for key materials", "Set up reorder alerts in system", "Document reorder policies"]'::jsonb, '{"templates": ["Reorder Point Calculator", "EOQ Calculation Template"], "tools": ["Inventory Planning Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'Safety Stock Optimization', 'Calculate optimal safety stock levels. Understand service level vs inventory cost trade-off. Account for demand and supply variability. Implement dynamic safety stock adjustments.', '["Calculate safety stock for critical items", "Define service level targets", "Analyze demand variability", "Create safety stock policy document"]'::jsonb, '{"templates": ["Safety Stock Calculator", "Service Level Matrix"], "tools": ["Safety Stock Optimization Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Inventory Control Systems', 'Implement inventory management systems and processes. Set up cycle counting and physical inventory audits. Create inventory adjustment procedures. Integrate with accounting for accurate costing.', '["Design cycle counting program", "Create inventory adjustment workflow", "Set up inventory reconciliation process", "Implement inventory controls"]'::jsonb, '{"templates": ["Cycle Count Schedule", "Inventory Adjustment Form"], "tools": ["Inventory Management System"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Logistics & Distribution (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Logistics & Distribution', 'Build distribution excellence - 3PL partnerships, warehousing, and last-mile delivery optimization', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, '3PL Selection & Management', 'Evaluate and select third-party logistics providers. Understand 3PL service models and pricing. Create RFP process for logistics partners. Set up 3PL performance monitoring.', '["Define 3PL requirements and scope", "Create 3PL evaluation criteria", "Prepare RFP for logistics services", "Design 3PL performance scorecard"]'::jsonb, '{"templates": ["3PL RFP Template", "3PL Evaluation Matrix"], "tools": ["3PL Comparison Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'Warehousing Strategy', 'Design optimal warehouse network for India. Understand warehouse location selection criteria. Learn warehouse layout and storage optimization. Implement warehouse management best practices.', '["Analyze warehouse location options", "Design warehouse layout for efficiency", "Calculate storage capacity requirements", "Create warehouse operations SOP"]'::jsonb, '{"templates": ["Warehouse Layout Template", "Location Analysis Framework"], "tools": ["Warehouse Capacity Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Distribution Network Design', 'Design efficient distribution network across India. Understand hub-and-spoke vs direct shipping models. Optimize distribution costs and delivery times. Plan for tier 2 and tier 3 city coverage.', '["Map current distribution network", "Analyze distribution cost by region", "Design optimized distribution model", "Plan tier 2/3 city expansion"]'::jsonb, '{"templates": ["Distribution Network Map", "Cost-to-Serve Analysis"], "tools": ["Network Optimization Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Last-Mile Delivery Excellence', 'Master last-mile delivery challenges in India. Evaluate delivery partners and aggregators. Implement delivery tracking and communication. Optimize delivery costs and customer experience.', '["Evaluate last-mile delivery options", "Design delivery SLA framework", "Set up customer delivery notifications", "Create delivery exception handling process"]'::jsonb, '{"templates": ["Last-Mile Partner Evaluation", "Delivery SLA Template"], "tools": ["Delivery Tracking Integration"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Returns & Reverse Logistics', 'Design efficient returns management process. Implement reverse logistics for product returns. Minimize returns through quality and packaging. Handle returns analytics and improvement.', '["Design returns process workflow", "Create returns policy document", "Set up reverse logistics with partners", "Implement returns analytics"]'::jsonb, '{"templates": ["Returns Policy Template", "Reverse Logistics Process"], "tools": ["Returns Management System"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: Cost Optimization (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'Cost Optimization', 'Drive operational efficiency - cost analysis, process improvements, and waste elimination', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'Operations Cost Analysis', 'Understand your operations cost structure in detail. Break down costs: materials, labor, overhead, logistics. Identify cost drivers and improvement opportunities. Create cost transparency across operations.', '["Map complete operations cost structure", "Identify top 10 cost drivers", "Calculate cost per unit/transaction", "Create cost tracking dashboard"]'::jsonb, '{"templates": ["Cost Structure Template", "Cost Driver Analysis"], "tools": ["Operations Cost Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Efficiency Improvement Methods', 'Apply proven efficiency improvement techniques. Implement time and motion studies. Optimize labor productivity and utilization. Use technology for efficiency gains.', '["Conduct time study on key process", "Calculate current labor productivity", "Identify efficiency improvement opportunities", "Create efficiency improvement roadmap"]'::jsonb, '{"templates": ["Time Study Template", "Productivity Calculator"], "tools": ["Efficiency Analysis Tool"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Waste Reduction Strategies', 'Identify and eliminate waste across operations. Apply lean waste elimination principles. Implement 5S workplace organization. Create waste tracking and reduction programs.', '["Conduct waste walk in operations", "Quantify waste by category", "Implement 5S in pilot area", "Create waste reduction targets"]'::jsonb, '{"templates": ["Waste Audit Checklist", "5S Implementation Guide"], "tools": ["Waste Tracking Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Procurement Cost Reduction', 'Reduce procurement costs through strategic sourcing. Implement competitive bidding effectively. Negotiate better terms with suppliers. Explore alternative materials and suppliers.', '["Identify top spend categories", "Create strategic sourcing plan", "Conduct competitive bidding for key items", "Negotiate improved terms with suppliers"]'::jsonb, '{"templates": ["Spend Analysis Template", "Sourcing Strategy Framework"], "tools": ["Procurement Savings Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'Logistics Cost Optimization', 'Reduce logistics and transportation costs. Optimize routing and load planning. Consolidate shipments for better rates. Negotiate with logistics partners effectively.', '["Analyze current logistics costs", "Identify consolidation opportunities", "Optimize delivery routes", "Renegotiate logistics contracts"]'::jsonb, '{"templates": ["Logistics Cost Analysis", "Route Optimization Template"], "tools": ["Transportation Cost Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Scaling Operations (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Scaling Operations', 'Scale operations effectively - automation, capacity planning, and multi-location management', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Operations Automation Strategy', 'Identify automation opportunities in operations. Evaluate automation technologies and ROI. Plan automation implementation roadmap. Balance automation with human capabilities.', '["Identify top automation candidates", "Calculate automation ROI for each", "Create automation prioritization matrix", "Plan pilot automation project"]'::jsonb, '{"templates": ["Automation Opportunity Assessment", "ROI Calculator"], "tools": ["Automation Readiness Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Capacity Planning & Management', 'Plan and manage operational capacity effectively. Understand capacity utilization and bottlenecks. Create capacity expansion strategies. Balance demand with available capacity.', '["Calculate current capacity utilization", "Identify capacity constraints", "Create capacity expansion plan", "Design demand-capacity balancing process"]'::jsonb, '{"templates": ["Capacity Planning Template", "Utilization Dashboard"], "tools": ["Capacity Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Multi-Location Operations', 'Manage operations across multiple locations. Standardize processes across sites. Handle inter-location transfers and coordination. Create location performance benchmarking.', '["Document standard processes for all locations", "Set up inter-location coordination", "Create location performance metrics", "Design location benchmarking system"]'::jsonb, '{"templates": ["Multi-Site SOP Template", "Location Benchmarking Framework"], "tools": ["Multi-Location Dashboard"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Operations Technology Stack', 'Build integrated operations technology infrastructure. Evaluate ERP, WMS, TMS solutions for startups. Implement operations analytics and reporting. Create technology roadmap for operations.', '["Assess current operations technology", "Evaluate ERP/WMS/TMS options", "Create technology integration plan", "Design operations analytics framework"]'::jsonb, '{"templates": ["Technology Evaluation Matrix", "Integration Roadmap"], "tools": ["Operations Tech Stack Guide"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Operations Excellence Roadmap', 'Create comprehensive operations excellence strategy. Build operations team capabilities. Establish continuous improvement culture. Design operations governance framework.', '["Create 12-month operations roadmap", "Define operations team structure", "Plan continuous improvement program", "Establish operations governance"]'::jsonb, '{"templates": ["Operations Roadmap Template", "CI Program Framework"], "tools": ["Operations Excellence Assessment"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
