-- P25: EdTech Mastery Course Migration
-- 45 days, 9 modules, comprehensive EdTech startup guide for India

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P25',
        'EdTech Mastery',
        'Complete guide to building EdTech startups in India - 9 modules covering NEP 2020 compliance, UGC/AICTE approvals, curriculum design, LMS development, student data privacy, monetization models, and scaling strategies. India EdTech market projected at $10.4 billion by 2025.',
        6999,
        45,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P25';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: EdTech Landscape (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'EdTech Landscape', 'Understand India''s EdTech ecosystem - market size, segments, key players, and emerging opportunities', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'India EdTech Market Overview', 'India is the world''s second-largest EdTech market after the US. Market size: $6 billion in 2023, projected to reach $10.4 billion by 2025. 600+ million internet users with growing smartphone penetration. COVID-19 accelerated digital adoption by 10 years. Understand the post-pandemic consolidation and sustainable growth phase.', '["Research current EdTech market size", "Map top 50 EdTech companies by segment", "Identify 3 underserved market opportunities", "Analyze EdTech funding trends"]'::jsonb, '{"templates": ["EdTech Market Analysis Framework", "Competitor Mapping Matrix"], "tools": ["Market Size Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'EdTech Market Segments', 'Understand key segments: K-12 supplementary (largest - Byju''s, Vedantu), test prep (Unacademy, Physics Wallah), higher education (upGrad, Great Learning), skill development (Coursera, Simplilearn), language learning (Duolingo, Cuemath English), and B2B/school tech (Classplus, Teachmint). Each segment has different dynamics, margins, and scale requirements.', '["Analyze each EdTech segment deeply", "Calculate segment-wise TAM/SAM/SOM", "Study 2 successful companies per segment", "Select your target segment"]'::jsonb, '{"templates": ["Segment Analysis Template", "TAM Calculator"], "tools": ["Segment Comparison Tool"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'EdTech Business Models', 'Understand EdTech business models: B2C subscription (Netflix for learning), B2C course purchase, freemium with premium conversion, B2B SaaS to schools/institutions, B2B2C (through employers), hybrid online-offline, and cohort-based courses. Learn unit economics and customer acquisition costs for each model.', '["Study unit economics by business model", "Calculate CAC and LTV benchmarks", "Analyze margin structures", "Select business model for your venture"]'::jsonb, '{"templates": ["Business Model Comparison", "Unit Economics Calculator"], "tools": ["Model Selection Framework"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'EdTech Success Stories', 'Learn from Indian EdTech successes and failures. Byju''s: $22 billion peak valuation, aggressive acquisition strategy, current challenges. Physics Wallah: profitable unicorn, community-driven growth, teacher-centric model. Unacademy: test prep disruption, educator platform approach. Understand what works and what doesn''t in Indian EdTech.', '["Analyze 5 successful EdTech companies", "Study 3 failed EdTech ventures", "Document success factors", "Identify common failure patterns"]'::jsonb, '{"templates": ["Case Study Analysis Framework", "Success Factor Matrix"], "tools": ["EdTech Benchmarking Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Defining Your EdTech Opportunity', 'Define your EdTech startup opportunity. Identify target audience: age group, income level, geography, learning goals. Choose between horizontal (broad subjects) vs vertical (specialized) focus. Validate demand through customer interviews. Create initial business model canvas.', '["Define target audience persona", "Conduct 20 customer discovery interviews", "Create business model canvas", "Validate problem-solution fit"]'::jsonb, '{"templates": ["Audience Persona Template", "Interview Guide"], "tools": ["Opportunity Validation Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: NEP 2020 (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'NEP 2020', 'Navigate National Education Policy 2020 - opportunities, compliance requirements, and implementation strategies', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'NEP 2020 Overview', 'National Education Policy 2020 is India''s first education policy in 34 years. Key changes: 5+3+3+4 structure replacing 10+2, emphasis on foundational literacy and numeracy, multi-disciplinary education, mother tongue instruction, vocational integration, and digital infrastructure. Understand the implementation timeline and state-wise adoption.', '["Study NEP 2020 document thoroughly", "Map key changes affecting your segment", "Understand implementation timeline", "Identify state-wise adoption status"]'::jsonb, '{"templates": ["NEP 2020 Summary Guide", "Implementation Timeline"], "tools": ["NEP Compliance Checker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'NEP Opportunities for EdTech', 'Identify EdTech opportunities from NEP 2020. Assessment technology (moving away from rote), foundational literacy and numeracy (3-8 years), multilingual content, vocational skills integration, credit transfer systems (Academic Bank of Credits), and online degree programs. Each change creates new market opportunities.', '["Map NEP changes to product opportunities", "Prioritize opportunities by market size", "Analyze competition in each opportunity", "Select focus area aligned with NEP"]'::jsonb, '{"templates": ["NEP Opportunity Matrix", "Market Sizing Template"], "tools": ["NEP Opportunity Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'Foundational Literacy & Numeracy', 'Address NIPUN Bharat mission for foundational literacy and numeracy by Grade 3. Huge opportunity: 150+ million children in 3-8 age group. Create assessment tools, mother-tongue content, teacher training solutions. Understand state government procurement and CSR-funded programs.', '["Study NIPUN Bharat guidelines", "Design FLN assessment product", "Plan multilingual content strategy", "Identify government partnership opportunities"]'::jsonb, '{"templates": ["FLN Assessment Framework", "Content Localization Guide"], "tools": ["FLN Product Planner"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Academic Bank of Credits', 'Leverage Academic Bank of Credits (ABC) system. Students can accumulate credits from multiple institutions for degree completion. Create credit transfer platforms, micro-credential programs, and modular learning pathways. Understand DigiLocker integration and NAD (National Academic Depository).', '["Understand ABC framework", "Design micro-credential programs", "Plan credit accumulation pathways", "Integrate with DigiLocker"]'::jsonb, '{"templates": ["ABC Integration Guide", "Micro-credential Framework"], "tools": ["Credit Pathway Designer"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'SWAYAM & Digital Infrastructure', 'Integrate with government digital infrastructure. SWAYAM offers free online courses from 200+ universities. DIKSHA is the national platform for school education. Understand how to complement (not compete with) government platforms. Explore content contribution and technology partnership opportunities.', '["Study SWAYAM course structure", "Explore DIKSHA integration options", "Identify partnership opportunities", "Plan complementary content strategy"]'::jsonb, '{"templates": ["SWAYAM Partnership Guide", "DIKSHA Integration Checklist"], "tools": ["Platform Integration Planner"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: UGC/AICTE Approvals (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'UGC/AICTE Approvals', 'Navigate regulatory approvals - UGC, AICTE, NAAC recognition for online programs and partnerships', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'Online Degree Regulations', 'Understand UGC regulations for online degrees. Only top NAAC-accredited universities (A++ and A+) can offer online degrees. EdTech companies can partner as Online Programme Managers (OPM). Regulations allow 40% courses online for conventional programs. Navigate recognition requirements and restrictions.', '["Study UGC online degree regulations", "Identify eligible universities for partnership", "Understand OPM role and restrictions", "Map approval process"]'::jsonb, '{"templates": ["UGC Regulation Summary", "University Partnership Criteria"], "tools": ["Eligibility Checker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'University Partnership Models', 'Structure university partnerships effectively. Models: OPM (Online Programme Management), content licensing, joint certification, corporate training partnerships. Understand revenue share models (typically 30-50% to EdTech). Navigate exclusive vs non-exclusive arrangements and marketing restrictions.', '["Define partnership model preference", "Create partnership proposal", "Negotiate revenue share terms", "Draft partnership agreement"]'::jsonb, '{"templates": ["University Partnership Template", "Revenue Share Model"], "tools": ["Partnership Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'AICTE Regulations for Technical Education', 'Navigate AICTE regulations for technical courses. Understand approval process for management, engineering, pharmacy programs. AICTE permits online delivery with specific guidelines. Know the difference between approved programs and skill courses. Handle AICTE internship, industry connect requirements.', '["Study AICTE online education guidelines", "Identify AICTE approval requirements", "Map approved technical institutions", "Plan AICTE-compliant programs"]'::jsonb, '{"templates": ["AICTE Compliance Checklist", "Technical Program Guidelines"], "tools": ["AICTE Navigator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'Skill Development Certifications', 'Operate in skill development space with NSDC/Sector Skill Council recognition. NCVET (National Council for Vocational Education and Training) provides framework. Create NSQF (National Skills Qualifications Framework) aligned programs. Partner with Sector Skill Councils for industry-recognized certifications.', '["Understand NSQF levels and requirements", "Identify relevant Sector Skill Councils", "Design NSQF-aligned curriculum", "Apply for Sector Skill Council recognition"]'::jsonb, '{"templates": ["NSQF Alignment Guide", "SSC Partnership Template"], "tools": ["Skill Certification Navigator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'International Certifications', 'Offer international certifications in India. Partner with global certification bodies: AWS, Google, Microsoft, Coursera, edX. Understand UGC stance on foreign degrees and certifications. Navigate recognition for employment vs formal education. Create globally relevant programs with local delivery.', '["Identify relevant international certifications", "Partner with global certification bodies", "Understand recognition limitations", "Design global certification programs"]'::jsonb, '{"templates": ["Global Partnership Framework", "Certification Recognition Guide"], "tools": ["International Certification Planner"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Content & Curriculum (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Content & Curriculum', 'Design engaging curriculum - instructional design, content creation, assessment, and learning outcomes', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Instructional Design Fundamentals', 'Master instructional design for online learning. Apply learning theories: behaviorism, cognitivism, constructivism. Use ADDIE model: Analysis, Design, Development, Implementation, Evaluation. Design for active learning, not passive consumption. Understand attention spans and cognitive load in digital learning.', '["Study ADDIE methodology", "Define learning objectives using Bloom''s taxonomy", "Design course structure and flow", "Plan assessment strategy"]'::jsonb, '{"templates": ["ADDIE Planning Template", "Learning Objectives Framework"], "tools": ["Course Structure Designer"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'Video Content Production', 'Create engaging video content - the core of EdTech. Types: talking head, animated explainers, screen recordings, live teaching, documentary style. Understand production quality requirements and costs. Set up studio: lighting, audio, camera, teleprompter. Plan for vernacular content production.', '["Define video content style", "Set up basic production studio", "Create video production workflow", "Plan vernacular content strategy"]'::jsonb, '{"templates": ["Video Production Checklist", "Studio Setup Guide"], "tools": ["Production Cost Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'Interactive Content & Gamification', 'Make learning engaging through interactivity. Implement gamification: points, badges, leaderboards, streaks. Create interactive elements: quizzes, simulations, virtual labs, case studies. Use H5P and similar tools for interactivity. Balance engagement with learning outcomes.', '["Design gamification framework", "Create interactive content library", "Implement progress tracking", "Test engagement metrics"]'::jsonb, '{"templates": ["Gamification Design Canvas", "Interactive Content Framework"], "tools": ["Engagement Metrics Dashboard"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Assessment & Certification', 'Design effective assessments for learning validation. Types: formative (during learning), summative (end of course), proctored exams. Implement AI-powered proctoring for high-stakes exams. Create meaningful certifications that have employer recognition. Handle certificate fraud prevention.', '["Design assessment strategy", "Implement proctoring solution", "Create certificate design and security", "Partner with employers for recognition"]'::jsonb, '{"templates": ["Assessment Design Framework", "Certificate Template"], "tools": ["Proctoring Solution Comparison"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Content Localization', 'Localize content for Indian diversity. 22 official languages, regional curriculum variations. Decide between dubbing, subtitles, and native language production. Understand regional market sizes: Hindi (500M), Bengali (100M), Tamil (75M), Telugu (85M). Plan scalable localization workflow.', '["Prioritize languages by market size", "Design localization workflow", "Budget for translation/dubbing", "Create regional content team structure"]'::jsonb, '{"templates": ["Localization Strategy Template", "Language Prioritization Matrix"], "tools": ["Localization Cost Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: LMS & Tech (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'LMS & Technology', 'Build or buy learning technology - LMS selection, development, mobile apps, and AI integration', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'LMS Build vs Buy Decision', 'Decide between building custom LMS or using existing platforms. Buy options: Moodle (open source), Canvas, Thinkific, Teachable, Graphy (Indian). Build considerations: differentiation, control, cost ($200K-1M for custom). Hybrid approach: customize open source. Most EdTech startups should start with buy, then build for scale.', '["Evaluate LMS options", "Calculate build vs buy costs", "Assess customization needs", "Make platform decision"]'::jsonb, '{"templates": ["LMS Comparison Matrix", "Build vs Buy Calculator"], "tools": ["LMS Selection Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'LMS Features & Architecture', 'Design LMS for optimal learning experience. Core features: course management, video hosting, assessments, progress tracking, certificates. Advanced features: AI recommendations, adaptive learning, collaborative learning, offline access. Plan for scale: microservices architecture, CDN for video, cloud infrastructure.', '["Define LMS feature requirements", "Design system architecture", "Plan for scalability", "Select technology stack"]'::jsonb, '{"templates": ["LMS Feature Checklist", "Architecture Design Template"], "tools": ["Tech Stack Selector"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Mobile App Strategy', 'Build mobile-first experience for Indian learners. 70% EdTech consumption is on mobile. Decide between native (iOS/Android), hybrid (React Native/Flutter), or PWA. Design for low-bandwidth scenarios and offline learning. Handle app store optimization and user acquisition through apps.', '["Define mobile app strategy", "Choose development approach", "Design for offline learning", "Plan app store optimization"]'::jsonb, '{"templates": ["Mobile App Feature Spec", "Offline Learning Framework"], "tools": ["App Development Cost Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'AI in EdTech', 'Implement AI for personalized learning. Use cases: adaptive learning paths, AI tutoring, automated assessment, content recommendations, chatbots for support, writing assistants, language learning AI. Understand AI/ML integration: build, buy, or API. Balance AI with human teaching.', '["Identify AI use cases for your product", "Evaluate AI solution options", "Plan AI implementation roadmap", "Ensure ethical AI use"]'::jsonb, '{"templates": ["AI Use Case Canvas", "AI Implementation Roadmap"], "tools": ["AI Solution Comparison"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Live Learning Infrastructure', 'Build live learning capability. Understand video conferencing: Zoom, BigBlueButton, Jitsi, or custom WebRTC. Handle scale: Unacademy''s 100K concurrent users, Byju''s live classes. Implement breakout rooms, whiteboard, polls, recording. Manage bandwidth and latency across India.', '["Select live learning platform", "Design live class features", "Plan for concurrent user scale", "Test across Indian network conditions"]'::jsonb, '{"templates": ["Live Class Feature Spec", "Scaling Architecture Guide"], "tools": ["Live Platform Comparison"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Student Data Privacy (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Student Data Privacy', 'Protect learner data - privacy regulations, children''s data, consent management, and security', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'India Data Protection Framework', 'Navigate Digital Personal Data Protection Act 2023 (DPDP). Understand data fiduciary obligations, consent requirements, and data principal rights. EdTech-specific concerns: learning data, assessment data, behavioral data. Implement privacy by design. Prepare for Data Protection Board of India oversight.', '["Study DPDP Act requirements", "Map personal data collected", "Implement consent management", "Create privacy policy compliant with DPDP"]'::jsonb, '{"templates": ["DPDP Compliance Checklist", "Data Mapping Template"], "tools": ["Privacy Compliance Tracker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'Children''s Data Protection', 'Handle children''s data with extra care. DPDP requires verifiable parental consent for children under 18. Restrictions on targeted advertising to children. Understand COPPA (US) requirements if serving international markets. Design age-appropriate experiences and data collection minimization.', '["Implement age verification", "Design parental consent flow", "Minimize data collection for children", "Create child-safe platform features"]'::jsonb, '{"templates": ["Parental Consent Template", "Age Verification Guide"], "tools": ["Children Privacy Checker"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Learning Data Ethics', 'Handle learning data ethically. Learning analytics can improve outcomes but raise privacy concerns. Implement data minimization: collect only what''s needed. Provide learner data portability. Avoid discriminatory use of learning data. Balance personalization with privacy.', '["Define learning data collection policy", "Implement data minimization", "Create data portability feature", "Establish ethical data use guidelines"]'::jsonb, '{"templates": ["Learning Data Policy Template", "Ethics Guidelines"], "tools": ["Data Ethics Assessment"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Security & Breach Response', 'Implement robust security for learner data. Requirements: encryption (at rest and in transit), access controls, security audits, penetration testing. Create incident response plan. Handle data breach notification as per DPDP (72 hours to Data Protection Board). Train team on security practices.', '["Implement encryption standards", "Conduct security audit", "Create incident response plan", "Train team on security"]'::jsonb, '{"templates": ["Security Checklist", "Incident Response Template"], "tools": ["Security Assessment Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'International Privacy Compliance', 'Comply with international privacy laws for global learners. GDPR (Europe) requirements for EU users. CCPA/CPRA (California) for US users. Understand data localization requirements. Implement region-specific privacy controls and cookie consent.', '["Map international user base", "Implement GDPR compliance", "Create region-specific privacy controls", "Handle cross-border data transfers"]'::jsonb, '{"templates": ["GDPR Compliance Checklist", "International Privacy Matrix"], "tools": ["Privacy Compliance Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: Monetization (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'Monetization', 'Build sustainable revenue - pricing strategies, subscription models, B2B sales, and unit economics', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'Pricing Strategy', 'Design pricing for Indian market. Understand price sensitivity: India ARPU $3-10/month vs US $30-100/month. Price points that work: ₹99-499/month subscription, ₹999-9,999 course bundles, ₹50,000-2,00,000 for career programs. Test pricing through A/B experiments. Consider regional pricing variations.', '["Research competitor pricing", "Design pricing tiers", "Plan A/B pricing tests", "Create regional pricing strategy"]'::jsonb, '{"templates": ["Pricing Strategy Framework", "A/B Test Plan"], "tools": ["Price Optimization Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Subscription vs One-Time Purchase', 'Choose revenue model based on content and audience. Subscription works for: ongoing learning, skill development, test prep with limited time. One-time purchase works for: specific courses, certifications, career programs. Hybrid models: subscription + premium content. Understand LTV implications of each model.', '["Evaluate subscription vs one-time for your product", "Calculate LTV under each model", "Design pricing architecture", "Plan conversion optimization"]'::jsonb, '{"templates": ["Revenue Model Comparison", "LTV Calculator"], "tools": ["Monetization Model Selector"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'B2B EdTech Sales', 'Sell to institutions and enterprises. B2B segments: schools, colleges, coaching institutes, corporates. Understand procurement cycles: schools (April-May), corporates (Q4 budgeting). Create enterprise pricing: per user, per school, or platform license. Build sales team for institutional sales.', '["Identify B2B target segments", "Create enterprise pricing", "Build institutional sales process", "Develop B2B sales team"]'::jsonb, '{"templates": ["B2B Sales Playbook", "Enterprise Pricing Template"], "tools": ["B2B Pipeline Tracker"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Income Share & Job Guarantee', 'Implement outcome-based pricing. Income Share Agreements (ISA): pay percentage of salary after placement. Job guarantee models: refund if not placed within timeframe. Understand financing requirements and legal structure. ISA works for: bootcamps, career transition programs. Risk management for outcome guarantees.', '["Design ISA or job guarantee program", "Create legal ISA framework", "Plan placement infrastructure", "Calculate risk and pricing"]'::jsonb, '{"templates": ["ISA Agreement Template", "Job Guarantee Policy"], "tools": ["ISA Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'Unit Economics Optimization', 'Achieve sustainable unit economics. Target metrics: CAC payback under 12 months, LTV/CAC ratio > 3. Reduce CAC through organic growth, referrals, and efficient paid marketing. Increase LTV through retention, upsells, and engagement. Monitor cohort economics for course-level profitability.', '["Calculate current unit economics", "Identify CAC reduction levers", "Plan LTV improvement initiatives", "Set up cohort analytics"]'::jsonb, '{"templates": ["Unit Economics Dashboard", "Cohort Analysis Template"], "tools": ["EdTech Economics Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: EdTech Marketing (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'EdTech Marketing', 'Acquire learners profitably - digital marketing, content marketing, influencer partnerships, and growth hacking', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'EdTech Customer Journey', 'Map the EdTech customer journey: awareness, consideration, conversion, onboarding, engagement, retention, referral. Understand decision makers: students, parents, or employers. Long consideration cycles: test prep (3-6 months), degree programs (6-12 months). Design marketing for each journey stage.', '["Map customer journey for your product", "Identify key decision makers", "Define conversion funnel stages", "Create stage-specific content plan"]'::jsonb, '{"templates": ["Customer Journey Map", "Decision Maker Analysis"], "tools": ["Funnel Analytics Dashboard"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Performance Marketing', 'Execute paid marketing efficiently. Channels: Google (search, YouTube), Meta (Facebook, Instagram), and emerging (ShareChat, Moj for vernacular). EdTech-specific: target exam dates, admission cycles, career transitions. Optimize for enrolled user, not just lead. Typical CAC: ₹500-2,000 for courses, ₹5,000-20,000 for degree programs.', '["Set up tracking and attribution", "Launch search campaigns", "Test social ad creatives", "Optimize for downstream conversions"]'::jsonb, '{"templates": ["Campaign Structure Template", "Ad Creative Framework"], "tools": ["Performance Marketing Dashboard"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Content & SEO Strategy', 'Build organic growth through content. Create valuable educational content: blog posts, YouTube videos, free courses. Target high-intent keywords: "best [topic] course", "[exam] preparation", "learn [skill] online". Build topical authority in your domain. Content marketing has longest payback but lowest CAC.', '["Conduct keyword research", "Create content calendar", "Launch YouTube channel", "Build SEO-optimized blog"]'::jsonb, '{"templates": ["Content Calendar Template", "SEO Checklist"], "tools": ["Keyword Research Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Influencer & Teacher Marketing', 'Leverage educators and influencers. Partner with teachers who have student following: YouTube educators, coaching teachers. Create affiliate/referral programs. Understand teacher economics: commission vs salary models. Build teacher as brand (Physics Wallah model) or platform brand (Unacademy model).', '["Identify relevant educators/influencers", "Design affiliate program", "Create educator partnership terms", "Build teacher acquisition funnel"]'::jsonb, '{"templates": ["Affiliate Program Template", "Educator Partnership Agreement"], "tools": ["Influencer ROI Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Referral & Community Growth', 'Build viral growth through referrals and community. Design referral programs: free months, course discounts, cash rewards. Create learner communities: Discord, Telegram, WhatsApp groups. Leverage peer learning and social proof. Target NPS > 50 for sustainable referral growth.', '["Design referral program", "Launch community platforms", "Create peer learning features", "Measure and optimize NPS"]'::jsonb, '{"templates": ["Referral Program Framework", "Community Building Guide"], "tools": ["Referral Analytics Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: Scaling EdTech (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'Scaling EdTech', 'Scale your EdTech venture - fundraising, team building, geographic expansion, and exit strategies', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'EdTech Fundraising', 'Raise capital for EdTech growth. Understand investor landscape: Tiger Global, Sequoia, General Atlantic (large rounds), early stage VCs (Blume, Nexus, Matrix). EdTech valuations have corrected post-2022: focus on unit economics, not just GMV. Prepare data room with cohort metrics, retention, and LTV.', '["Build investor target list", "Prepare EdTech-specific pitch deck", "Document cohort metrics", "Start investor conversations"]'::jsonb, '{"templates": ["EdTech Pitch Deck", "Investor Data Room"], "tools": ["Fundraising Tracker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Building EdTech Team', 'Build team for scale. Key roles: content/curriculum team, technology team, marketing, sales (for B2B/high-ticket), student success, operations. Hire educators with digital content skills. Balance full-time vs contract content creators. Create educator development programs.', '["Define org structure for scale", "Identify key hiring priorities", "Create educator recruitment process", "Build employee value proposition"]'::jsonb, '{"templates": ["EdTech Org Chart", "Hiring Plan Template"], "tools": ["Team Planning Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'Vernacular & Tier 2/3 Expansion', 'Expand to vernacular and smaller cities. Tier 2/3 cities: 70% of India''s internet growth. Vernacular content: 10x larger market than English. Adapt content for regional curriculum and exam patterns. Build regional marketing and sales teams. Price for smaller city affordability.', '["Prioritize vernacular languages", "Adapt content for regional needs", "Build regional teams", "Test regional pricing"]'::jsonb, '{"templates": ["Regional Expansion Playbook", "Vernacular Content Strategy"], "tools": ["Regional Market Analyzer"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'International Expansion', 'Expand beyond India. Target markets: Middle East (Indian curriculum schools), Southeast Asia, Africa. Understand market-specific needs and competition. Navigate regulatory requirements in each country. Consider acquisition vs organic entry. Build international teams.', '["Evaluate international markets", "Study regulatory requirements", "Plan market entry strategy", "Build international partnerships"]'::jsonb, '{"templates": ["International Expansion Framework", "Market Entry Checklist"], "tools": ["Global Market Comparison"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'M&A & Exit Strategies', 'Plan exit for EdTech startup. Exit options: strategic acquisition (Byju''s acquired 15+ companies), PE buyout, IPO (limited EdTech IPOs so far), merger. Understand EdTech valuations: 3-8x revenue for profitable companies. Build for acquisition: clean cap table, solid metrics, defensible position. Recent exits: Toppr (Byju''s), WhiteHat Jr (Byju''s), Great Learning (Byju''s).', '["Define exit strategy", "Build acquisition readiness", "Maintain clean documentation", "Build acquirer relationships"]'::jsonb, '{"templates": ["Exit Planning Framework", "M&A Readiness Checklist"], "tools": ["Valuation Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
