-- P22: E-commerce & D2C Mastery Course Migration
-- 50 days, 10 modules, comprehensive e-commerce and D2C business framework

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
    v_mod_10_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;
    v_mod_10_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P22',
        'E-commerce & D2C Mastery',
        'Complete e-commerce and D2C business framework - 10 modules covering business models, legal compliance, e-commerce regulations, payments, logistics, marketplace selling, D2C websites, customer experience, marketing, and scaling. India''s e-commerce market is $200B+ by 2026.',
        7999,
        50,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P22';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: E-commerce Business Models (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'E-commerce Business Models', 'Master e-commerce and D2C business models, unit economics, and market positioning', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'India E-commerce Market Overview', 'India''s e-commerce market is projected at $200B by 2026. Understand market segments: B2C, B2B, C2C, social commerce, quick commerce. Learn about 1,500+ D2C brands and their growth patterns. Identify whitespace in categories and geographies.', '["Research India e-commerce market size and growth", "Identify top 20 D2C brands and their categories", "Map e-commerce value chain", "Analyze 3 successful D2C case studies"]'::jsonb, '{"templates": ["E-commerce Market Analysis Template", "Competitive Landscape Map"], "tools": ["D2C Brand Database"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'D2C vs Marketplace vs Hybrid Models', 'Evaluate business models: pure D2C, marketplace-first, omnichannel hybrid. Understand trade-offs: margins vs reach, control vs scale. Learn from Mamaearth, boAt, Lenskart journeys. Choose the right model for your category.', '["Evaluate D2C vs marketplace for your product", "Calculate margin comparison", "Design channel strategy", "Create hybrid rollout plan"]'::jsonb, '{"templates": ["Business Model Comparison", "Channel Strategy Template"], "tools": ["Model Selector Tool"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'E-commerce Unit Economics', 'Master e-commerce unit economics: CAC, LTV, AOV, repeat rate, contribution margin. Understand category-specific benchmarks. Calculate profitability at scale. Design for sustainable growth.', '["Calculate your unit economics", "Benchmark against category leaders", "Identify profitability levers", "Create unit economics dashboard"]'::jsonb, '{"templates": ["Unit Economics Calculator", "Benchmark Database"], "tools": ["Profitability Analyzer"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'Category Selection & Positioning', 'Select winning categories: market size, competition, margins, logistics complexity. Understand India-specific category dynamics: beauty, fashion, electronics, grocery. Position your brand for differentiation.', '["Evaluate category opportunity", "Analyze competition intensity", "Define brand positioning", "Create differentiation strategy"]'::jsonb, '{"templates": ["Category Analysis Framework", "Positioning Template"], "tools": ["Category Opportunity Analyzer"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Building Your E-commerce Team', 'Build e-commerce organization: digital marketing, supply chain, customer experience, technology. Understand hiring for D2C: growth marketers, merchandisers, logistics heads. Create lean team for early stage.', '["Define key roles for e-commerce startup", "Research e-commerce salary benchmarks", "Create hiring prioritization", "Design org structure for scale"]'::jsonb, '{"templates": ["E-commerce Org Chart Template", "Key Hire JD Library"], "tools": ["E-commerce Salary Benchmarking"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: Legal Compliance for E-commerce (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'Legal Compliance for E-commerce', 'Master e-commerce legal requirements - registration, contracts, consumer protection, and IP', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'Business Registration for E-commerce', 'Complete business registration: Pvt Ltd, LLP, sole proprietorship considerations. Obtain GST registration with e-commerce specific requirements. Understand MSME registration benefits. Handle multi-state registration.', '["Choose appropriate business structure", "Complete GST registration", "Register for MSME benefits", "Plan multi-state compliance"]'::jsonb, '{"templates": ["Registration Checklist", "GST E-commerce Guide"], "tools": ["Registration Tracker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'Consumer Protection Act 2019', 'Navigate Consumer Protection Act 2019 for e-commerce. Understand consumer rights: return, refund, product liability. Implement grievance redressal mechanisms. Handle consumer court proceedings.', '["Review CPA 2019 e-commerce provisions", "Design return/refund policy", "Set up grievance redressal", "Create product liability protection"]'::jsonb, '{"templates": ["CPA Compliance Checklist", "Grievance Policy Template"], "tools": ["Consumer Law Compliance Tracker"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'Terms & Conditions for E-commerce', 'Draft e-commerce terms of service, privacy policy, return policy. Understand cookie policy and consent requirements. Create compliant user agreements. Handle age verification for restricted products.', '["Draft terms of service", "Create privacy policy", "Design return/refund policy", "Implement consent mechanisms"]'::jsonb, '{"templates": ["E-commerce Terms Template", "Privacy Policy Template"], "tools": ["Policy Generator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Trademark & Brand Protection', 'Register trademarks for brand and products. Navigate domain name protection. Handle counterfeit and brand abuse on marketplaces. Implement brand registry on Amazon, Flipkart.', '["File trademark applications", "Secure relevant domains", "Register on brand registry programs", "Design anti-counterfeit strategy"]'::jsonb, '{"templates": ["Trademark Application Checklist", "Brand Registry Guide"], "tools": ["Domain Monitoring Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'Category-Specific Licenses', 'Obtain category-specific licenses: FSSAI for food, drug license for cosmetics/ayurvedic, BIS for electronics. Understand labeling requirements. Navigate import licenses for sourcing. Handle product certifications.', '["Identify required category licenses", "Apply for FSSAI/drug license", "Complete BIS certification", "Design compliant packaging"]'::jsonb, '{"templates": ["License Requirement Matrix", "Labeling Compliance Checklist"], "tools": ["License Application Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: E-commerce Regulations & Compliance (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'E-commerce Regulations & Compliance', 'Navigate India''s e-commerce regulations, FDI policy, and data protection requirements', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'E-commerce Rules 2020', 'Master Consumer Protection (E-Commerce) Rules 2020. Understand seller/marketplace entity obligations. Implement country of origin and seller disclosure. Handle fall-back liability provisions.', '["Review E-commerce Rules 2020 in detail", "Implement mandatory disclosures", "Design seller compliance framework", "Create compliance monitoring system"]'::jsonb, '{"templates": ["E-commerce Rules Compliance Checklist", "Disclosure Template"], "tools": ["Compliance Tracker Dashboard"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'FDI Policy for E-commerce', 'Navigate FDI policy for e-commerce: marketplace vs inventory model. Understand B2B vs B2C FDI restrictions. Handle related party transaction rules. Plan entity structure for foreign investment.', '["Review current FDI policy", "Assess marketplace vs inventory model", "Design compliant entity structure", "Plan for foreign investment"]'::jsonb, '{"templates": ["FDI Compliance Matrix", "Entity Structure Guide"], "tools": ["FDI Policy Tracker"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'Data Protection for E-commerce', 'Implement DPDP Act compliance for e-commerce. Design customer consent mechanisms. Handle cross-border data transfer for international operations. Create data retention and deletion policies.', '["Assess DPDP Act applicability", "Design consent framework", "Implement data security measures", "Create data governance policy"]'::jsonb, '{"templates": ["DPDP Compliance Checklist", "Consent Management Template"], "tools": ["Data Privacy Assessment Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'Advertising & Marketing Compliance', 'Navigate ASCI guidelines for e-commerce advertising. Understand influencer disclosure requirements. Handle comparative advertising rules. Implement compliant flash sale and discount communications.', '["Review ASCI advertising guidelines", "Create influencer disclosure policy", "Design compliant ad templates", "Implement sale compliance"]'::jsonb, '{"templates": ["ASCI Compliance Checklist", "Influencer Agreement"], "tools": ["Ad Compliance Checker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'GST for E-commerce', 'Master GST for e-commerce: TCS compliance, multi-state registration, e-invoicing. Handle marketplace GST collection and reporting. Implement ITC optimization. Navigate reverse charge mechanism.', '["Set up GST TCS compliance", "Implement e-invoicing", "Design GST reporting workflow", "Optimize input tax credit"]'::jsonb, '{"templates": ["E-commerce GST Compliance Guide", "TCS Reporting Template"], "tools": ["GST Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Payment & Checkout Optimization (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Payment & Checkout Optimization', 'Build seamless payment experiences with high conversion and fraud prevention', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Payment Gateway Integration', 'Integrate payment gateways: Razorpay, PayU, Cashfree, Paytm. Understand pricing models and negotiation strategies. Implement smart routing for payment success. Handle international payments for export.', '["Compare payment gateway options", "Negotiate pricing based on volume", "Implement failover routing", "Set up international payments"]'::jsonb, '{"templates": ["PG Comparison Matrix", "Integration Checklist"], "tools": ["Payment Success Analyzer"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'UPI & Digital Payments', 'Master UPI integration for e-commerce: QR, intent, collect. Implement UPI AutoPay for subscriptions. Handle BNPL integration: Simpl, LazyPay, ZestMoney. Design for digital payment first India.', '["Integrate UPI payment options", "Set up UPI AutoPay", "Evaluate BNPL partners", "Design mobile payment UX"]'::jsonb, '{"templates": ["UPI Integration Guide", "BNPL Partner Comparison"], "tools": ["Digital Payment Dashboard"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'COD Management', 'Optimize Cash on Delivery: verification, fraud prevention, RTO reduction. Implement COD to prepaid conversion strategies. Handle COD remittance and reconciliation. Design COD pricing and availability rules.', '["Design COD verification workflow", "Implement fraud detection", "Create RTO reduction strategy", "Set up COD reconciliation"]'::jsonb, '{"templates": ["COD Management Framework", "Fraud Prevention Checklist"], "tools": ["COD Analytics Dashboard"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Checkout Optimization', 'Design high-converting checkout: guest checkout, address autofill, saved payments. Implement cart abandonment recovery. A/B test checkout flows. Handle checkout security and trust signals.', '["Audit current checkout conversion", "Implement guest checkout", "Set up cart recovery automation", "Design A/B testing roadmap"]'::jsonb, '{"templates": ["Checkout Optimization Checklist", "A/B Testing Framework"], "tools": ["Conversion Rate Analyzer"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Payment Fraud Prevention', 'Implement payment fraud detection: device fingerprinting, velocity checks, ML models. Handle chargebacks and disputes. Navigate RBI fraud reporting. Design fraud rule engine.', '["Implement fraud detection system", "Create chargeback handling SOP", "Design fraud rule engine", "Set up fraud monitoring dashboard"]'::jsonb, '{"templates": ["Fraud Prevention Framework", "Chargeback Playbook"], "tools": ["Fraud Detection Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: Logistics & Fulfillment (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'Logistics & Fulfillment', 'Build efficient fulfillment operations - warehousing, shipping, and returns management', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'Fulfillment Strategy', 'Design fulfillment strategy: self-fulfillment, 3PL, fulfillment-by-marketplace. Understand trade-offs: cost vs control vs speed. Plan warehouse network for pan-India coverage. Evaluate dark stores for quick commerce.', '["Evaluate fulfillment options", "Calculate cost comparison", "Design warehouse network", "Plan fulfillment scalability"]'::jsonb, '{"templates": ["Fulfillment Strategy Template", "Cost Comparison Calculator"], "tools": ["Warehouse Location Analyzer"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'Warehouse Operations', 'Set up warehouse operations: receiving, putaway, picking, packing, dispatch. Implement WMS (Warehouse Management System). Design for efficiency and accuracy. Handle seasonal capacity planning.', '["Set up warehouse SOP", "Evaluate WMS options", "Design layout for efficiency", "Plan seasonal scaling"]'::jsonb, '{"templates": ["Warehouse SOP Template", "WMS Comparison Matrix"], "tools": ["Warehouse Efficiency Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Shipping Partner Management', 'Select and manage shipping partners: Delhivery, Blue Dart, DTDC, Ecom Express. Negotiate shipping rates based on volume. Implement multi-carrier strategy. Handle shipping aggregators: Shiprocket, Pickrr.', '["Compare shipping partners", "Negotiate volume discounts", "Implement shipping aggregator", "Design carrier allocation logic"]'::jsonb, '{"templates": ["Carrier Comparison Template", "Rate Negotiation Playbook"], "tools": ["Shipping Cost Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'Returns & Reverse Logistics', 'Design returns management: return window, condition criteria, refund processing. Implement reverse pickup logistics. Handle return-to-origin (RTO) reduction. Monetize returns through recommerce.', '["Design returns policy", "Set up reverse logistics", "Create RTO reduction strategy", "Plan recommerce operations"]'::jsonb, '{"templates": ["Returns Policy Template", "Reverse Logistics SOP"], "tools": ["RTO Analytics Dashboard"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Inventory Management', 'Master inventory management: demand forecasting, safety stock, reorder points. Implement SKU rationalization. Handle multi-location inventory. Design for working capital efficiency.', '["Implement demand forecasting", "Calculate optimal inventory levels", "Set up inventory allocation", "Design inventory dashboard"]'::jsonb, '{"templates": ["Inventory Management Template", "Demand Forecasting Model"], "tools": ["Inventory Optimization Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Marketplace Selling Mastery (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Marketplace Selling Mastery', 'Master selling on Amazon, Flipkart, Meesho, and other Indian marketplaces', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'Amazon India Selling', 'Master Amazon India: seller registration, FBA vs FBM, catalog optimization. Understand A+ content, Brand Store, and advertising. Navigate Seller Central and performance metrics. Handle Amazon account health.', '["Complete Amazon seller registration", "Optimize product listings", "Set up Amazon advertising", "Design A+ content"]'::jsonb, '{"templates": ["Amazon Listing Template", "Advertising Playbook"], "tools": ["Amazon Keyword Research Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'Flipkart Selling Strategy', 'Master Flipkart selling: seller onboarding, catalog management, Flipkart Fulfillment. Understand Flipkart advertising and brand visibility. Navigate Seller Hub and performance management. Handle Big Billion Days preparation.', '["Complete Flipkart registration", "Optimize Flipkart listings", "Set up Flipkart ads", "Plan sale event strategy"]'::jsonb, '{"templates": ["Flipkart Listing Template", "Sale Preparation Checklist"], "tools": ["Flipkart Analytics Dashboard"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Social Commerce Platforms', 'Sell on Meesho, GlowRoad, Shop101 for Tier 2/3 reach. Understand reseller network dynamics. Design products for social commerce. Handle commission structures and margins.', '["Onboard on social commerce platforms", "Design social commerce products", "Create reseller enablement", "Plan social commerce strategy"]'::jsonb, '{"templates": ["Social Commerce Playbook", "Reseller Kit Template"], "tools": ["Social Commerce Analytics"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Marketplace Advertising', 'Master marketplace advertising: sponsored products, brands, display ads. Understand bidding strategies and ACOS optimization. Implement campaign structure best practices. Handle seasonal advertising scaling.', '["Set up advertising campaigns", "Optimize ACOS targets", "Design campaign structure", "Plan seasonal scaling"]'::jsonb, '{"templates": ["Advertising Campaign Template", "ACOS Optimization Guide"], "tools": ["Ad Performance Dashboard"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Multi-Marketplace Strategy', 'Manage multi-marketplace presence: catalog sync, pricing consistency, inventory allocation. Implement listing management tools. Handle marketplace-specific promotions. Design channel-specific strategies.', '["Implement multi-channel listing tool", "Design pricing strategy per channel", "Create inventory allocation rules", "Plan channel differentiation"]'::jsonb, '{"templates": ["Multi-Channel Strategy", "Pricing Matrix Template"], "tools": ["Channel Management Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: D2C Website & Technology (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'D2C Website & Technology', 'Build high-converting D2C website with the right technology stack', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'E-commerce Platform Selection', 'Choose e-commerce platform: Shopify, WooCommerce, Magento, custom. Understand trade-offs: cost, flexibility, scalability. Evaluate India-specific options: Dukaan, Bikayi. Plan for headless commerce.', '["Evaluate platform options", "Calculate TCO for each option", "Assess customization needs", "Create platform selection scorecard"]'::jsonb, '{"templates": ["Platform Comparison Matrix", "TCO Calculator"], "tools": ["Platform Selector Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Website Design & UX', 'Design high-converting D2C website: homepage, PDP, collection pages, checkout. Implement mobile-first design for India. Create trust signals and social proof. Handle vernacular and accessibility.', '["Design website wireframes", "Implement mobile-first approach", "Add trust signals", "Plan vernacular support"]'::jsonb, '{"templates": ["Website Design Checklist", "UX Best Practices Guide"], "tools": ["Heatmap Analysis Tool"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Product Information Management', 'Implement PIM for catalog management: product data, images, videos, variants. Design for SEO-optimized product pages. Handle user-generated content: reviews, Q&A. Manage product photography.', '["Set up PIM system", "Create product content guidelines", "Implement review collection", "Design photography standards"]'::jsonb, '{"templates": ["PIM Requirements", "Content Guidelines Template"], "tools": ["Product Content Analyzer"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'E-commerce Tech Stack', 'Build complete tech stack: OMS, CRM, marketing automation, analytics. Integrate systems for unified operations. Implement CDP for customer data. Handle tech stack for scale.', '["Design tech stack architecture", "Evaluate integration options", "Implement key integrations", "Plan tech roadmap"]'::jsonb, '{"templates": ["Tech Stack Template", "Integration Checklist"], "tools": ["Tech Stack Comparison"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'Website Performance & SEO', 'Optimize website performance: Core Web Vitals, page speed, mobile performance. Implement technical SEO for e-commerce. Handle site structure and internal linking. Design for organic discovery.', '["Audit website performance", "Implement SEO best practices", "Optimize page speed", "Create SEO content strategy"]'::jsonb, '{"templates": ["SEO Audit Checklist", "Technical SEO Guide"], "tools": ["Performance Monitoring Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Customer Experience Excellence (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Customer Experience Excellence', 'Build exceptional customer experience for retention and advocacy', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Customer Support Excellence', 'Build customer support: channels, response times, resolution quality. Implement support tools: Freshdesk, Zendesk, Intercom. Design self-service options. Handle escalation and VIP support.', '["Design support channel strategy", "Implement support platform", "Create knowledge base", "Set up escalation workflow"]'::jsonb, '{"templates": ["Support SLA Template", "Knowledge Base Structure"], "tools": ["Support Platform Comparison"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Order Experience Optimization', 'Optimize order experience: confirmation, tracking, delivery updates. Implement WhatsApp for order communication. Handle delivery feedback collection. Design unboxing experience.', '["Set up order communication flow", "Implement WhatsApp notifications", "Design unboxing experience", "Create feedback collection"]'::jsonb, '{"templates": ["Order Communication Template", "Unboxing Design Guide"], "tools": ["Notification Automation Tool"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Loyalty & Retention Programs', 'Design loyalty programs: points, tiers, referrals, subscriptions. Implement retention marketing: win-back, cross-sell. Handle customer lifetime value optimization. Create community and advocacy programs.', '["Design loyalty program structure", "Implement referral program", "Create win-back campaigns", "Plan community building"]'::jsonb, '{"templates": ["Loyalty Program Template", "Retention Playbook"], "tools": ["LTV Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Personalization & CRM', 'Implement personalization: product recommendations, personalized emails, dynamic content. Build CRM for customer 360 view. Handle segmentation and targeting. Design for 1:1 customer relationships.', '["Implement recommendation engine", "Set up CRM system", "Create customer segments", "Design personalization rules"]'::jsonb, '{"templates": ["Personalization Playbook", "CRM Setup Guide"], "tools": ["Segmentation Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Customer Feedback & NPS', 'Collect and act on customer feedback: NPS, CSAT, product reviews. Implement feedback loops for improvement. Handle negative feedback and recovery. Build customer advisory programs.', '["Set up NPS measurement", "Create feedback collection system", "Design recovery playbook", "Plan advisory board"]'::jsonb, '{"templates": ["NPS Implementation Guide", "Feedback Analysis Template"], "tools": ["Customer Feedback Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: E-commerce Marketing (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'E-commerce Marketing', 'Master e-commerce marketing - performance, content, influencer, and retention marketing', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'Performance Marketing', 'Master performance marketing: Meta Ads, Google Ads, programmatic. Understand attribution and ROAS optimization. Implement creative testing frameworks. Handle scaling and budget allocation.', '["Set up Meta and Google Ads", "Create attribution model", "Design creative testing plan", "Implement budget allocation"]'::jsonb, '{"templates": ["Performance Marketing Playbook", "Creative Testing Framework"], "tools": ["ROAS Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Influencer Marketing', 'Build influencer marketing program: discovery, outreach, collaboration. Understand micro vs macro influencers for D2C. Implement affiliate and ambassador programs. Handle influencer compliance (ASCI).', '["Create influencer discovery process", "Design collaboration framework", "Implement affiliate program", "Ensure ASCI compliance"]'::jsonb, '{"templates": ["Influencer Brief Template", "Affiliate Program Structure"], "tools": ["Influencer Discovery Platform"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'Content & Social Media', 'Create content strategy for e-commerce: product content, lifestyle content, UGC. Manage social media: Instagram, YouTube, Pinterest for commerce. Implement social commerce features. Handle content calendar.', '["Create content strategy", "Set up social media calendar", "Implement UGC collection", "Design social commerce"]'::jsonb, '{"templates": ["Content Strategy Template", "Social Media Calendar"], "tools": ["Content Planning Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'Email & WhatsApp Marketing', 'Master e-commerce email marketing: lifecycle campaigns, promotional emails, triggered emails. Implement WhatsApp Business for marketing. Handle automation and personalization. Design for deliverability.', '["Set up email automation", "Implement WhatsApp marketing", "Create email templates", "Design automation workflows"]'::jsonb, '{"templates": ["Email Marketing Playbook", "WhatsApp Campaign Template"], "tools": ["Email Automation Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'Sale Events & Promotions', 'Plan sale events: festive sales, flash sales, exclusive launches. Design promotion structures: discounts, bundles, GWP. Handle sale operations and inventory. Maximize revenue during peak events.', '["Plan annual sale calendar", "Design promotion structure", "Create sale operations playbook", "Implement sale analytics"]'::jsonb, '{"templates": ["Sale Planning Template", "Promotion Structure Guide"], "tools": ["Promotion ROI Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 10: Scaling E-commerce Operations (Days 46-50)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_10_id, v_product_id, 'Scaling E-commerce Operations', 'Scale e-commerce business - omnichannel, international expansion, and exit readiness', 10, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_10_id, 46, 'Omnichannel Expansion', 'Expand to offline: EBOs (Exclusive Brand Outlets), shop-in-shops, quick commerce. Design omnichannel experience: BOPIS, endless aisle. Implement unified inventory. Handle offline partnerships with retail chains.', '["Design omnichannel strategy", "Plan retail expansion", "Implement unified inventory", "Create partnership framework"]'::jsonb, '{"templates": ["Omnichannel Strategy Template", "Retail Expansion Plan"], "tools": ["Retail Location Analyzer"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 47, 'International Expansion', 'Expand internationally: UAE, US, UK for Indian D2C brands. Navigate cross-border logistics and customs. Handle international payments and taxes. Design for global customers.', '["Assess international market opportunity", "Plan cross-border logistics", "Set up international payments", "Create localization strategy"]'::jsonb, '{"templates": ["International Expansion Playbook", "Customs Compliance Guide"], "tools": ["Market Opportunity Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 48, 'Private Label & Manufacturing', 'Build private label capabilities: contract manufacturing, quality control. Design product development process. Handle inventory planning for new products. Navigate OEM partnerships.', '["Identify manufacturing partners", "Design QC process", "Plan product development pipeline", "Create supplier management system"]'::jsonb, '{"templates": ["Manufacturing Partner Evaluation", "Product Development Template"], "tools": ["Supplier Management Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 49, 'D2C Funding & Valuation', 'Navigate D2C funding landscape: angel, VC, PE investors. Understand D2C valuation metrics: revenue multiples, growth rates. Prepare data room for due diligence. Handle strategic investment from retail corporates.', '["Create investor target list", "Prepare financial metrics", "Build data room", "Design fundraising strategy"]'::jsonb, '{"templates": ["D2C Pitch Deck Template", "Data Room Checklist"], "tools": ["Valuation Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 50, 'Exit & IPO Readiness', 'Prepare for exit: strategic acquisition by retail corporates, PE buyout, IPO. Understand D2C M&A landscape in India. Build governance and compliance for exit readiness. Navigate Nykaa, Mamaearth IPO lessons.', '["Assess exit options", "Implement governance standards", "Prepare exit documentation", "Build investor relations"]'::jsonb, '{"templates": ["Exit Readiness Checklist", "IPO Preparation Guide"], "tools": ["Exit Valuation Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
