-- P27: Real Estate & PropTech Course Migration
-- 50 days, 10 modules, comprehensive real estate and proptech mastery for Indian startups

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
    v_mod_10_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;
    v_mod_10_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P27',
        'Real Estate & PropTech Mastery',
        'Complete guide to real estate startups in India - from RERA compliance to smart city integration. 10 modules covering property regulations, construction permits, proptech technology, real estate finance, co-living/co-working, and scaling strategies. India $200B+ real estate market transforming through technology.',
        7999,
        50,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P27';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: PropTech Landscape (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'PropTech Landscape', 'Understand Indian real estate tech ecosystem - market segments, opportunities, and transformation trends', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'India Real Estate Overview', 'Explore India $200B+ real estate sector: residential (60%), commercial (20%), retail and hospitality (20%). Understand key markets: Mumbai, Delhi-NCR, Bangalore, Hyderabad, Pune. Study market cycles, price trends, and demand drivers. Learn about organized vs unorganized sector dynamics.', '["Study real estate market size by segment and city", "Understand demand-supply dynamics in key markets", "Research price trends and affordability", "Map key developers and market players"]'::jsonb, '{"templates": ["India Real Estate Market Map", "City-wise Market Analysis Template"], "tools": ["Real Estate Market Intelligence"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'PropTech Segments Deep Dive', 'Explore proptech verticals: property search platforms, construction tech, property management, brokerage tech, home services, smart buildings. Study successful Indian proptech startups: NoBroker, Housing.com, Square Yards, HomeLane, Livspace. Identify underserved segments.', '["Map all proptech segments with market size", "Research 10 successful Indian proptech startups", "Identify your target segment and positioning", "Create competitive landscape analysis"]'::jsonb, '{"templates": ["PropTech Segment Matrix", "Startup Case Study Framework"], "tools": ["PropTech Landscape Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'Real Estate Regulations Overview', 'Navigate regulatory framework: RERA Act 2016, state variations, land laws, foreign investment rules (FDI). Understand registration and stamp duty mechanisms. Learn about GST on real estate transactions. Study impact of regulations on proptech models.', '["Study RERA Act provisions and compliance", "Research state-wise RERA variations", "Understand land acquisition laws", "Map FDI regulations for real estate"]'::jsonb, '{"templates": ["Real Estate Regulation Handbook", "State RERA Comparison"], "tools": ["Regulatory Compliance Checker"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'Technology Transformation Trends', 'Explore technology disruption: virtual reality for property viewing, AI for pricing and matching, blockchain for title verification, IoT for smart buildings, drones for site monitoring. Understand technology adoption barriers and solutions.', '["Identify technology applications for your proptech idea", "Research technology adoption in Indian real estate", "Study global proptech technology trends", "Create technology integration roadmap"]'::jsonb, '{"templates": ["PropTech Technology Stack", "Digital Transformation Framework"], "tools": ["PropTech Technology Database"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Building PropTech Strategy', 'Define proptech startup strategy: target segment, geography, customer personas, technology stack, business model. Create go-to-market approach for fragmented real estate market. Plan for long sales cycles and high transaction values.', '["Define target segment and geography", "Create customer persona profiles", "Design revenue model with unit economics", "Plan market entry strategy"]'::jsonb, '{"templates": ["PropTech Business Model Canvas", "Customer Acquisition Playbook"], "tools": ["PropTech Strategy Builder"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: RERA Compliance (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'RERA Compliance', 'Master RERA registration, compliance, agent licensing, and buyer protection requirements', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'RERA Act Fundamentals', 'Master Real Estate (Regulation and Development) Act 2016: objectives, applicability, key provisions. Understand mandatory project registration for 500 sqm+ or 8 units+. Learn about 70% escrow requirement. Study state-wise RERA implementation status.', '["Study RERA Act key provisions", "Understand project registration requirements", "Research state RERA authority rules", "Map RERA impact on your business model"]'::jsonb, '{"templates": ["RERA Compliance Guide", "State RERA Comparison Matrix"], "tools": ["RERA Applicability Checker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'Project Registration Process', 'Navigate RERA project registration: eligibility, documentation, online portal submission. Prepare project details: land titles, approvals, timeline, layout plans. Understand quarterly update requirements. Manage project modifications and extensions.', '["Compile RERA registration documents", "Prepare detailed project information", "Submit registration on state RERA portal", "Set up quarterly compliance calendar"]'::jsonb, '{"templates": ["RERA Registration Checklist", "Project Documentation Template"], "tools": ["RERA Portal Navigation Guide"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'Agent Registration', 'Obtain RERA agent registration: eligibility criteria, application process, fees, validity. Understand agent responsibilities and obligations. Create compliant brokerage operations. Manage renewal and compliance requirements.', '["Apply for RERA agent registration", "Understand agent obligations under RERA", "Design compliant brokerage process", "Set up registration renewal system"]'::jsonb, '{"templates": ["Agent Registration Application", "Brokerage Compliance Guide"], "tools": ["Agent Registration Tracker"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Buyer Protection Provisions', 'Understand RERA buyer protections: clear sale agreements, carpet area definition, interest for delays, defect liability period (5 years). Learn about RERA complaint and adjudication process. Build buyer-friendly processes.', '["Study buyer protection provisions", "Create RERA-compliant sale agreements", "Understand complaint resolution process", "Design transparent buyer communication"]'::jsonb, '{"templates": ["RERA-Compliant Agreement Template", "Buyer Rights Guide"], "tools": ["RERA Complaint Process Guide"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'RERA Compliance Technology', 'Build RERA compliance technology: automated reporting, document management, timeline tracking, buyer portal. Create compliance dashboards for developers. Integrate with RERA portals. Study RegTech opportunities in real estate.', '["Design RERA compliance system", "Build automated reporting workflow", "Create developer compliance dashboard", "Develop buyer transparency portal"]'::jsonb, '{"templates": ["RERA Tech Architecture", "Compliance Automation Framework"], "tools": ["RERA Compliance Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: Real Estate Regulations (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'Real Estate Regulations', 'Navigate land laws, property registration, title verification, and urban development regulations', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'Land Laws in India', 'Master land law framework: Transfer of Property Act, Registration Act, state land revenue codes. Understand agricultural land restrictions. Navigate land ceiling laws. Study conversion of agricultural to non-agricultural land.', '["Study Transfer of Property Act provisions", "Research state land revenue laws", "Understand agricultural land restrictions", "Map land conversion requirements"]'::jsonb, '{"templates": ["Land Law Summary Guide", "State Land Regulations Matrix"], "tools": ["Land Law Compliance Navigator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'Property Registration Process', 'Navigate property registration: stamp duty calculation, registration process, document requirements. Understand e-registration systems in various states. Learn about registration timelines and costs. Handle registration challenges.', '["Calculate stamp duty and registration fees", "Prepare registration documents", "Navigate e-registration portal", "Create property transfer checklist"]'::jsonb, '{"templates": ["Registration Document Checklist", "Stamp Duty Calculator Guide"], "tools": ["E-Registration Portal Navigator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'Title Verification and Due Diligence', 'Master title verification: chain of ownership, encumbrance certificate, revenue records, court case search. Build due diligence process for property transactions. Leverage technology for title verification. Create title guarantee solutions.', '["Design title verification process", "Build due diligence checklist", "Research title tech solutions", "Create risk assessment framework"]'::jsonb, '{"templates": ["Title Verification Checklist", "Due Diligence Process Guide"], "tools": ["Title Search Automation Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'Urban Development Regulations', 'Navigate urban planning: Master Plans, zoning regulations, FAR/FSI norms, development control rules. Understand building bylaws and restrictions. Study single window clearance systems. Learn about development authority processes.', '["Study city master plan for target areas", "Understand zoning and FAR regulations", "Map building bylaw requirements", "Navigate development authority process"]'::jsonb, '{"templates": ["Urban Planning Compliance Guide", "Development Regulation Matrix"], "tools": ["Zoning and FAR Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'FDI in Real Estate', 'Understand FDI regulations: automatic route provisions, construction development conditions, minimum capitalization, lock-in period. Navigate ECB for real estate. Study FEMA compliance for property ownership by NRIs/foreigners.', '["Study FDI policy for real estate sector", "Understand construction development conditions", "Research NRI property investment rules", "Map foreign investment compliance"]'::jsonb, '{"templates": ["FDI Compliance Guide", "NRI Investment Handbook"], "tools": ["Foreign Investment Compliance Checker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Construction Permits (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Construction Permits', 'Master building approvals, environmental clearances, occupancy certificates, and single window systems', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Building Plan Approval', 'Navigate building plan approval: application process, documentation, authority review, approval timeline. Understand sanctioned plan requirements. Handle plan modifications. Study online building permission systems (OBPS).', '["Prepare building plan approval documents", "Apply through online building permission system", "Understand plan sanction conditions", "Create approval tracking system"]'::jsonb, '{"templates": ["Building Plan Approval Checklist", "Document Preparation Guide"], "tools": ["OBPS Navigation Platform"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'Environmental Clearances', 'Master environmental compliance: EIA notification applicability, prior EC requirements, Environmental Clearance process. Navigate state pollution control board consents. Understand green building certifications. Handle construction stage monitoring.', '["Determine EC applicability for project", "Apply for environmental clearance", "Obtain pollution control board consents", "Set up environmental monitoring"]'::jsonb, '{"templates": ["Environmental Clearance Guide", "PCB Consent Application"], "tools": ["EC Applicability Checker"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'NOCs and Multi-Agency Clearances', 'Navigate NOC requirements: fire, aviation, traffic, water, electricity, telecom. Understand agency-wise requirements and processes. Create NOC tracking and management. Study integrated approval systems.', '["Map all NOC requirements for project", "Apply for individual agency NOCs", "Create NOC tracking dashboard", "Handle NOC conditions and compliance"]'::jsonb, '{"templates": ["NOC Requirement Matrix", "Multi-Agency Application Guide"], "tools": ["NOC Tracking System"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Occupancy and Completion Certificates', 'Secure Occupancy Certificate: pre-conditions, inspection requirements, documentation, common issues. Understand deemed approval provisions. Handle OC delays and disputes. Navigate part OC for phased projects.', '["Prepare OC application with all documents", "Ensure project completion as per sanctioned plan", "Handle inspection requirements", "Obtain completion certificate"]'::jsonb, '{"templates": ["OC Application Checklist", "Project Completion Guide"], "tools": ["OC Readiness Assessment"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Building Approval Tech Solutions', 'Build construction permit technology: approval tracking, document management, compliance monitoring, stakeholder collaboration. Study AutoDCR and OBPS integration. Create permit management platforms for developers and authorities.', '["Design approval management system", "Build document tracking platform", "Create compliance dashboard", "Integrate with government systems"]'::jsonb, '{"templates": ["Approval Tech Architecture", "Integration Framework"], "tools": ["Construction Permit Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: PropTech Technology (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'PropTech Technology', 'Build proptech solutions with VR/AR, AI pricing, blockchain, IoT, and construction tech', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'Virtual Property Experience', 'Build VR/AR property solutions: 360-degree virtual tours, augmented reality staging, interactive floor plans. Understand technology stack: 3D capture, rendering, VR headset compatibility. Study successful implementations: Matterport, REimagine Home.', '["Design virtual property experience platform", "Select 3D capture technology", "Build VR tour creation workflow", "Create AR staging solution"]'::jsonb, '{"templates": ["VR/AR Technology Guide", "Virtual Tour Best Practices"], "tools": ["3D Property Capture Platform"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'AI-Powered Property Intelligence', 'Implement AI in proptech: property valuation algorithms, price prediction, lead scoring, demand forecasting. Build machine learning models with Indian real estate data. Create personalized property recommendations.', '["Design AI valuation model architecture", "Collect and prepare training data", "Build recommendation engine", "Create price prediction algorithm"]'::jsonb, '{"templates": ["AI Model Design Framework", "Data Collection Strategy"], "tools": ["PropTech AI Development Kit"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Blockchain for Real Estate', 'Apply blockchain: property tokenization, smart contracts for transactions, title registry, fractional ownership. Understand regulatory considerations for tokenized real estate in India. Study global implementations and lessons.', '["Design blockchain architecture for real estate", "Create smart contract templates", "Build tokenization platform", "Address regulatory compliance"]'::jsonb, '{"templates": ["Blockchain Architecture Guide", "Smart Contract Templates"], "tools": ["Real Estate Tokenization Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'IoT and Smart Buildings', 'Build smart building solutions: energy management, security systems, access control, facility management. Understand IoT infrastructure: sensors, connectivity, data platforms. Create building automation systems for commercial and residential.', '["Design smart building IoT architecture", "Select sensor and gateway technology", "Build building management platform", "Create energy optimization system"]'::jsonb, '{"templates": ["Smart Building Design Guide", "IoT Infrastructure Plan"], "tools": ["Building Automation Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Construction Technology', 'Explore construction tech: project management software, BIM (Building Information Modeling), drone monitoring, prefab construction. Study contech startups: Infra.Market, BuildSupply. Build solutions for construction efficiency.', '["Evaluate construction tech solutions", "Implement BIM for project design", "Design construction monitoring system", "Build supply chain platform"]'::jsonb, '{"templates": ["ConTech Implementation Guide", "BIM Adoption Framework"], "tools": ["Construction Project Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Real Estate Finance (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Real Estate Finance', 'Master property financing - home loans, construction finance, REITs, and alternative funding', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'Home Loan Ecosystem', 'Navigate home loan market: banks, HFCs, NBFCs. Understand loan products, eligibility criteria, interest rates. Study digital lending trends. Build home loan comparison and distribution platforms.', '["Map home loan providers and products", "Understand eligibility and documentation", "Design loan comparison platform", "Create lender partnership model"]'::jsonb, '{"templates": ["Home Loan Market Guide", "Lender Comparison Matrix"], "tools": ["Home Loan EMI Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'Developer Finance', 'Master developer financing: construction finance, project loans, land acquisition funding. Understand developer loan structures: term loans, overdraft, LRD. Navigate NBFC and bank financing options. Study alternative funding sources.', '["Understand developer loan products", "Prepare project finance documentation", "Build developer finance advisory", "Create construction finance platform"]'::jsonb, '{"templates": ["Developer Finance Guide", "Project Loan Documentation"], "tools": ["Construction Finance Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'REITs and Fractional Ownership', 'Understand REITs in India: Embassy, Mindspace, Brookfield. Learn about REIT regulations, listing requirements, investor participation. Explore fractional ownership platforms. Build REIT data and analysis platforms.', '["Study REIT structure and regulations", "Research listed REITs in India", "Understand fractional ownership models", "Design REIT analytics platform"]'::jsonb, '{"templates": ["REIT Investment Guide", "Fractional Ownership Framework"], "tools": ["REIT Analysis Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Alternative Real Estate Investment', 'Explore alternative investments: AIFs for real estate, private credit, mezzanine funding, LRD securitization. Understand regulatory framework for alternative investments. Build alternative investment platforms with proper licensing.', '["Map alternative investment options", "Understand AIF regulations for real estate", "Design alternative investment platform", "Create investor education content"]'::jsonb, '{"templates": ["Alternative Investment Guide", "AIF Compliance Framework"], "tools": ["Alternative Investment Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Proptech in Lending', 'Build proptech lending solutions: digital mortgage origination, property valuation, document verification, loan marketplace. Partner with lenders for distribution. Create embedded lending in property platforms.', '["Design digital mortgage platform", "Build property valuation system", "Create lender integration", "Develop embedded lending features"]'::jsonb, '{"templates": ["Digital Lending Architecture", "Lender Partnership Framework"], "tools": ["PropTech Lending Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: Co-living & Co-working (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'Co-living & Co-working', 'Build managed spaces business - co-living, co-working, student housing, and senior living', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'Co-living Business Model', 'Master co-living: market opportunity (millennials, students, young professionals), business models (asset-light, owned), unit economics. Study successful operators: Stanza Living, Zolo, CoHo. Design co-living product and experience.', '["Research co-living market size and segments", "Study successful co-living operators", "Design co-living product offering", "Create unit economics model"]'::jsonb, '{"templates": ["Co-living Business Plan", "Unit Economics Calculator"], "tools": ["Co-living Market Analyzer"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Co-working Space Operations', 'Build co-working business: location selection, space design, membership models, community building. Study operators: WeWork, Awfis, 91springboard. Understand post-COVID flexible workspace trends. Create technology-enabled operations.', '["Design co-working space concept", "Create membership and pricing tiers", "Build community engagement program", "Develop operations technology stack"]'::jsonb, '{"templates": ["Co-working Business Model", "Space Design Guidelines"], "tools": ["Coworking Space Planner"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Property Acquisition and Leasing', 'Master property acquisition: location analysis, lease negotiation, landlord relationships, portfolio management. Understand lease structures: revenue share, fixed rent, hybrid. Create scalable property acquisition engine.', '["Develop location selection criteria", "Create lease negotiation playbook", "Build landlord relationship process", "Design portfolio management system"]'::jsonb, '{"templates": ["Lease Agreement Template", "Location Analysis Framework"], "tools": ["Property Acquisition Tracker"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Student and Senior Housing', 'Explore specialty housing: student accommodation near universities, senior living with healthcare integration. Understand specific requirements, regulations, partnerships. Design specialized housing products.', '["Research student housing market", "Study senior living requirements", "Design specialty housing concept", "Create partnership model with institutions"]'::jsonb, '{"templates": ["Student Housing Business Plan", "Senior Living Design Guide"], "tools": ["Specialty Housing Analyzer"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'Technology for Managed Spaces', 'Build managed space technology: booking systems, access control, community apps, facility management. Create seamless resident/member experience. Integrate IoT for smart spaces. Study PropTech stack for operators.', '["Design space management platform", "Build resident/member app", "Implement access control system", "Create facility management dashboard"]'::jsonb, '{"templates": ["Space Tech Architecture", "Member App Requirements"], "tools": ["Managed Space Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Brokerage & Aggregation (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Brokerage & Aggregation', 'Transform real estate brokerage with technology, marketplaces, and new business models', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Digital Brokerage Models', 'Reimagine real estate brokerage: discount brokerage, tech-enabled agents, virtual brokerage. Study NoBroker, Housedo, Compass models. Understand brokerage economics and technology disruption. Design broker-friendly technology.', '["Research digital brokerage models", "Study NoBroker success factors", "Design brokerage technology platform", "Create agent productivity tools"]'::jsonb, '{"templates": ["Digital Brokerage Business Model", "Agent Productivity Framework"], "tools": ["Brokerage Platform Builder"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Property Marketplace Development', 'Build property marketplace: listing management, search and discovery, lead generation, transaction support. Create multi-sided platform balancing buyers, sellers, and agents. Study Housing.com, 99acres, MagicBricks.', '["Design marketplace architecture", "Build listing management system", "Create search and discovery features", "Develop lead distribution system"]'::jsonb, '{"templates": ["Marketplace Design Framework", "Platform Feature Roadmap"], "tools": ["Property Marketplace Platform"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Lead Generation and Management', 'Master real estate lead generation: digital marketing, SEO, content, partnerships. Build lead management: scoring, nurturing, distribution. Create conversion optimization systems. Understand real estate customer journey.', '["Design lead generation strategy", "Build lead scoring model", "Create nurturing workflows", "Develop conversion tracking system"]'::jsonb, '{"templates": ["Lead Gen Strategy Guide", "CRM Configuration Template"], "tools": ["Real Estate Lead Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Transaction Management', 'Build transaction management: documentation, legal support, finance facilitation, post-sale services. Create end-to-end transaction platform. Integrate with RERA and registration systems. Ensure compliance throughout.', '["Design transaction workflow", "Build document management system", "Create legal support integration", "Develop post-sale service platform"]'::jsonb, '{"templates": ["Transaction Process Guide", "Documentation Checklist"], "tools": ["Transaction Management Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Rental and Property Management', 'Build rental platform: tenant discovery, rent collection, maintenance, eviction support. Create property management services for landlords. Study PropTech solutions: NestAway, RentMantra. Design technology for rental operations.', '["Design rental marketplace", "Build tenant verification system", "Create rent collection platform", "Develop maintenance management"]'::jsonb, '{"templates": ["Rental Platform Architecture", "Property Management SOP"], "tools": ["Rental Management Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: Smart City Integration (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'Smart City Integration', 'Leverage smart city mission - urban infrastructure, municipal tech, and government partnerships', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'Smart City Mission Overview', 'Understand Smart City Mission: 100 cities, ₹2 lakh crore investment, Special Purpose Vehicles (SPVs). Study smart city components: urban mobility, energy, water, governance, safety. Identify proptech opportunities in smart cities.', '["Study Smart City Mission structure", "Research selected smart cities", "Map proptech opportunities", "Identify potential SPV partnerships"]'::jsonb, '{"templates": ["Smart City Guide", "Opportunity Mapping Framework"], "tools": ["Smart City Database"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Urban Infrastructure Tech', 'Build urban infrastructure solutions: traffic management, parking systems, waste management, utility monitoring. Understand smart city tenders and procurement. Partner with infrastructure companies and city administrations.', '["Design urban tech solution", "Understand smart city procurement", "Build infrastructure partnership model", "Create city administration engagement"]'::jsonb, '{"templates": ["Urban Tech Business Plan", "City Partnership Proposal"], "tools": ["Urban Infrastructure Platform"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'Municipal Tech Solutions', 'Create municipal technology: property tax systems, building permission automation, GIS mapping, citizen services. Understand municipal IT procurement. Build solutions for urban local bodies. Study successful implementations.', '["Research municipal tech requirements", "Design e-governance solution", "Build GIS-enabled platform", "Create citizen service interface"]'::jsonb, '{"templates": ["Municipal Tech Architecture", "E-Governance Framework"], "tools": ["Municipal Technology Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'Sustainable Real Estate', 'Build green real estate solutions: energy efficiency, water conservation, waste management, green certifications (IGBC, GRIHA). Create sustainability technology for buildings. Study ESG in real estate investments.', '["Design sustainability platform", "Build energy efficiency tools", "Create green certification support", "Develop ESG reporting system"]'::jsonb, '{"templates": ["Sustainability Tech Guide", "Green Building Framework"], "tools": ["Building Sustainability Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'Government Partnership Strategy', 'Develop government partnerships: tender participation, PPP models, pilot programs. Navigate government procurement (GeM, state portals). Build credibility with urban development authorities. Create sustainable government business.', '["Develop government partnership strategy", "Register on procurement portals", "Design pilot program proposals", "Build government relationship process"]'::jsonb, '{"templates": ["Government Partnership Guide", "PPP Proposal Template"], "tools": ["Tender Tracking Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 10: Scaling PropTech (Days 46-50)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_10_id, v_product_id, 'Scaling PropTech', 'Scale proptech venture - funding, expansion, partnerships, and exit strategies', 10, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_10_id, 46, 'PropTech Funding Landscape', 'Navigate proptech funding: VC investors, strategic investors (developers, banks), family offices. Study proptech valuations and recent funding rounds. Understand investor expectations and due diligence. Prepare for fundraise.', '["Map proptech investors in India", "Study recent funding rounds", "Prepare funding documentation", "Create investor outreach plan"]'::jsonb, '{"templates": ["PropTech Investor Database", "Funding Preparation Guide"], "tools": ["PropTech Funding Tracker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 47, 'Geographic Expansion', 'Plan proptech expansion: market selection, localization, team building, regulatory navigation. Understand city-wise real estate variations. Create expansion playbook. Study successful multi-city proptech scaling.', '["Create city expansion priority matrix", "Develop market entry playbook", "Build local team hiring plan", "Design localization strategy"]'::jsonb, '{"templates": ["Expansion Planning Guide", "City Launch Checklist"], "tools": ["Market Expansion Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 48, 'Strategic Partnerships', 'Build strategic partnerships: developers, banks, insurance companies, home services. Create value through ecosystem partnerships. Navigate partner negotiations. Study successful proptech partnerships.', '["Identify strategic partnership opportunities", "Design partnership value propositions", "Create partner engagement process", "Build partnership management system"]'::jsonb, '{"templates": ["Partnership Strategy Guide", "Partner Proposal Template"], "tools": ["Partnership Management Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 49, 'International Expansion', 'Plan international expansion: market selection (GCC, SEA, Africa), regulatory understanding, localization. Partner with international real estate players. Study PropTech global expansion stories.', '["Research international market opportunities", "Understand target market regulations", "Design international go-to-market", "Plan international partnerships"]'::jsonb, '{"templates": ["International Expansion Guide", "Market Research Template"], "tools": ["Global PropTech Database"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 50, 'Exit and Value Creation', 'Plan long-term value creation: strategic acquirers (developers, portals, tech companies), IPO readiness, private equity. Understand proptech M&A landscape. Study successful proptech exits in India and globally.', '["Study proptech M&A landscape", "Identify potential strategic acquirers", "Build IPO readiness roadmap", "Create value creation dashboard"]'::jsonb, '{"templates": ["Exit Planning Guide", "Value Creation Framework"], "tools": ["PropTech Valuation Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
