-- P21: HealthTech & Medical Devices Course Migration
-- 55 days, 11 modules, comprehensive HealthTech regulatory and business framework

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
    v_mod_10_id TEXT;
    v_mod_11_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;
    v_mod_10_id := gen_random_uuid()::text;
    v_mod_11_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P21',
        'HealthTech & Medical Devices',
        'Complete HealthTech regulatory and business framework - 11 modules covering telemedicine regulations, medical device classification, drug regulations, ABDM integration, clinical trials, quality certifications, healthcare partnerships, funding, government schemes, and scaling. India''s healthcare market is $372B by 2025.',
        8999,
        55,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P21';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: HealthTech Landscape in India (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'HealthTech Landscape in India', 'Understand India''s HealthTech ecosystem, market opportunities, and regulatory environment', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'India HealthTech Market Overview', 'India''s healthcare market is projected at $372B by 2025. Understand segments: telemedicine, diagnostics, med-tech, pharma tech, hospital tech. Learn about 8,000+ HealthTech startups and $4B+ funding. Identify opportunities in Tier 2/3 healthcare access.', '["Research India HealthTech market size and segments", "Identify top 20 HealthTech unicorns and startups", "Map the HealthTech value chain", "Analyze 3 successful HealthTech case studies"]'::jsonb, '{"templates": ["HealthTech Market Analysis Template", "Competitive Landscape Map"], "tools": ["HealthTech Ecosystem Database"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'HealthTech Business Models', 'Master HealthTech models: B2C (patient apps), B2B (hospital SaaS), B2B2C (insurance partnerships), D2C (health products). Understand revenue models: subscription, transaction, licensing, device sales. Analyze unit economics in healthcare.', '["Evaluate 5 HealthTech business models", "Calculate CAC and LTV for healthcare", "Design your HealthTech business model canvas", "Identify key healthcare partnerships needed"]'::jsonb, '{"templates": ["HealthTech Business Model Canvas", "Healthcare Revenue Calculator"], "tools": ["Unit Economics Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'Healthcare Regulatory Overview', 'Navigate multi-regulator environment: CDSCO, ICMR, NMC, state drug controllers. Understand licensing requirements by business type. Learn about regulatory pathways for different products. Prepare compliance infrastructure.', '["Identify applicable regulators for your HealthTech", "List required licenses and registrations", "Research regulatory timelines", "Create regulatory compliance roadmap"]'::jsonb, '{"templates": ["Regulatory Mapping Template", "License Requirements Matrix"], "tools": ["Healthcare Regulator Database"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'HealthTech Funding Landscape', 'Access HealthTech-focused investors: Sequoia, Lightspeed, Khosla Ventures, HealthQuad. Understand sector-specific due diligence: clinical validation, regulatory pathway, reimbursement. Navigate strategic investors from pharma and hospitals.', '["Identify 20 HealthTech-focused investors", "Prepare HealthTech-specific pitch deck", "Understand clinical validation requirements", "Build relationships with strategic investors"]'::jsonb, '{"templates": ["HealthTech Pitch Deck Template", "Investor Database"], "tools": ["HealthTech Valuation Benchmark"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Building Your HealthTech Team', 'Hire for regulated healthcare: medical directors, quality assurance, regulatory affairs. Understand MBBS/MD requirements for certain roles. Build clinical advisory board. Create culture of patient safety and innovation.', '["Define key roles for HealthTech startup", "Understand medical professional requirements", "Identify regulatory affairs talent", "Design clinical advisory board"]'::jsonb, '{"templates": ["HealthTech Org Chart Template", "Key Hire JD Library"], "tools": ["Healthcare Salary Benchmarking"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: Telemedicine Regulations (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'Telemedicine Regulations', 'Master telemedicine practice guidelines, platform requirements, and compliance', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'Telemedicine Practice Guidelines 2020', 'Master MCI/NMC Telemedicine Practice Guidelines. Understand RMP (Registered Medical Practitioner) requirements. Learn about first consult vs follow-up regulations. Navigate prescription guidelines for telemedicine.', '["Review Telemedicine Guidelines in detail", "Understand RMP registration requirements", "Learn prescription restrictions", "Create compliant consultation workflow"]'::jsonb, '{"templates": ["Telemedicine Guidelines Summary", "Compliance Checklist"], "tools": ["Prescription Validator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'Telemedicine Platform Requirements', 'Build compliant telemedicine platform: video consultation, chat, document sharing. Implement patient identification and consent. Create medical record keeping systems. Handle prescription generation and e-pharmacy integration.', '["Design telemedicine platform architecture", "Implement patient consent workflow", "Set up EHR integration", "Create prescription management system"]'::jsonb, '{"templates": ["Platform Requirements Checklist", "Consent Templates"], "tools": ["Telemedicine Tech Stack Comparison"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'E-Pharmacy Regulations', 'Navigate e-pharmacy draft rules and current regulations. Understand retail drug license requirements. Implement prescription validation systems. Handle controlled substance restrictions.', '["Review e-pharmacy regulatory status", "Understand drug license requirements", "Design prescription verification workflow", "Create controlled substance compliance"]'::jsonb, '{"templates": ["E-Pharmacy Compliance Matrix", "Drug License Guide"], "tools": ["Prescription Verification System"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Telemedicine for Specialists', 'Navigate specialist telemedicine: dermatology, psychiatry, radiology teleservices. Understand specialty-specific guidelines. Implement diagnostic support for teleconsultation. Handle referral workflows.', '["Identify specialty telemedicine opportunities", "Understand specialty-specific restrictions", "Design diagnostic integration", "Create referral management system"]'::jsonb, '{"templates": ["Specialty Guidelines Summary", "Diagnostic Integration Checklist"], "tools": ["Specialist Network Builder"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'Cross-Border Telemedicine', 'Understand cross-border medical practice regulations. Navigate medical tourism via telemedicine. Handle international patient data compliance. Implement multi-currency billing for medical services.', '["Review cross-border practice regulations", "Understand data localization requirements", "Design international patient workflow", "Implement compliant billing systems"]'::jsonb, '{"templates": ["Cross-Border Compliance Guide", "International Patient Checklist"], "tools": ["Multi-Currency Medical Billing"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: Medical Device Classification & Registration (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'Medical Device Classification & Registration', 'Navigate CDSCO medical device regulations - classification, registration, and compliance', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'Medical Device Classification', 'Understand CDSCO device classification: Class A (low risk) to Class D (high risk). Learn about Software as Medical Device (SaMD) classification. Navigate combination products. Assess your device classification accurately.', '["Determine your device risk classification", "Review CDSCO classification rules", "Assess SaMD classification if applicable", "Document classification rationale"]'::jsonb, '{"templates": ["Device Classification Matrix", "SaMD Classification Guide"], "tools": ["Classification Decision Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'Medical Device Registration Process', 'Navigate CDSCO registration: manufacturing license, import license, registration certificate. Understand SUGAM portal submission process. Prepare technical documentation and test reports. Handle registration timeline expectations.', '["Identify required registration pathway", "Gather technical documentation", "Prepare SUGAM portal application", "Plan registration timeline"]'::jsonb, '{"templates": ["Registration Checklist by Class", "Technical File Template"], "tools": ["SUGAM Portal Guide"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'Clinical Evidence Requirements', 'Understand clinical evaluation requirements by device class. Navigate clinical investigation approval process. Implement post-market clinical follow-up. Handle biocompatibility and performance testing.', '["Assess clinical evidence requirements", "Design clinical evaluation plan", "Identify testing laboratories", "Plan post-market surveillance"]'::jsonb, '{"templates": ["Clinical Evaluation Plan Template", "Testing Requirements Matrix"], "tools": ["Lab Directory India"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'Software as Medical Device (SaMD)', 'Navigate SaMD regulations in India: CDSCO guidance, IEC 62304 compliance. Understand AI/ML-based SaMD special considerations. Implement software lifecycle management. Handle SaMD change management.', '["Review CDSCO SaMD guidance", "Implement IEC 62304 compliance", "Design AI/ML validation approach", "Create change management process"]'::jsonb, '{"templates": ["SaMD Regulatory Pathway", "Software Lifecycle Template"], "tools": ["AI/ML Validation Framework"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'Manufacturing & Quality System', 'Implement Quality Management System per ISO 13485. Understand manufacturing license requirements. Navigate Good Manufacturing Practices (GMP) for devices. Handle facility audits and inspections.', '["Implement ISO 13485 QMS", "Design manufacturing facility layout", "Prepare for GMP audit", "Create quality documentation system"]'::jsonb, '{"templates": ["ISO 13485 Implementation Guide", "GMP Checklist"], "tools": ["QMS Documentation System"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Drug Regulations & Pharma Tech (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Drug Regulations & Pharma Tech', 'Navigate drug regulations for pharma tech solutions and digital therapeutics', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Drugs and Cosmetics Act Overview', 'Understand Drugs and Cosmetics Act 1940 and Rules 1945. Navigate CDSCO drug approval process. Learn about Schedule H, H1, X classifications. Understand drug pricing under NPPA.', '["Review D&C Act key provisions", "Understand drug scheduling", "Learn DPCO pricing regulations", "Identify applicable sections for your business"]'::jsonb, '{"templates": ["D&C Act Summary", "Drug Schedule Quick Reference"], "tools": ["Drug Classification Checker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'Digital Therapeutics (DTx)', 'Understand digital therapeutics regulatory pathway. Navigate evidence requirements for DTx. Implement prescription digital therapeutics workflow. Handle reimbursement strategies for DTx.', '["Assess DTx regulatory requirements", "Design clinical evidence plan", "Create prescription DTx workflow", "Plan reimbursement strategy"]'::jsonb, '{"templates": ["DTx Regulatory Framework", "Clinical Evidence Plan"], "tools": ["DTx Classification Tool"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'Pharma Supply Chain Technology', 'Build pharma supply chain solutions: track and trace, cold chain monitoring, inventory management. Navigate drug serialization requirements. Implement GS1 standards for pharma. Handle DAVA compliance.', '["Understand serialization requirements", "Design track and trace system", "Implement cold chain monitoring", "Create GS1 compliance framework"]'::jsonb, '{"templates": ["Serialization Implementation Guide", "Cold Chain Checklist"], "tools": ["GS1 Barcode Generator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Nutraceuticals & AYUSH Products', 'Navigate FSSAI regulations for nutraceuticals. Understand AYUSH licensing requirements. Implement quality standards for traditional medicine tech. Handle claims and advertising regulations.', '["Review FSSAI nutraceutical regulations", "Understand AYUSH product licensing", "Design quality assurance framework", "Create compliant marketing materials"]'::jsonb, '{"templates": ["Nutraceutical Licensing Guide", "AYUSH Compliance Checklist"], "tools": ["Claims Validation Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Generic Drug & API Tech', 'Understand generic drug opportunity in India. Navigate API manufacturing regulations. Implement batch manufacturing systems. Handle export documentation and WHO PQ.', '["Assess generic drug tech opportunities", "Understand API licensing requirements", "Design batch management system", "Plan export compliance framework"]'::jsonb, '{"templates": ["API Licensing Guide", "Batch Record Template"], "tools": ["WHO PQ Requirement Checker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: Digital Health Data & ABDM (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'Digital Health Data & ABDM', 'Integrate with Ayushman Bharat Digital Mission and health data exchange ecosystem', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'ABDM Ecosystem Overview', 'Understand Ayushman Bharat Digital Mission: ABHA ID, Health Facility Registry, Health Professional Registry. Learn about National Digital Health Blueprint. Navigate integration opportunities and requirements.', '["Study ABDM architecture and components", "Understand ABHA ID creation process", "Explore integration opportunities", "Plan ABDM-enabled product features"]'::jsonb, '{"templates": ["ABDM Integration Roadmap", "Ecosystem Component Map"], "tools": ["ABDM Sandbox Access Guide"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'Health Information Exchange', 'Implement ABDM-compliant health data exchange. Understand consent manager integration. Navigate Personal Health Records (PHR) app requirements. Handle interoperability standards: FHIR, SNOMED, ICD.', '["Design HIE architecture", "Integrate consent management", "Implement FHIR standards", "Create PHR app features"]'::jsonb, '{"templates": ["HIE Integration Guide", "FHIR Implementation Checklist"], "tools": ["Interoperability Validator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Health ID & Facility Registry', 'Implement ABHA ID creation and linking. Navigate Health Facility Registry integration. Understand Health Professional Registry requirements. Handle demographic and clinical data standards.', '["Integrate ABHA ID creation", "Connect to HFR for facility validation", "Implement HPR verification", "Design data standardization layer"]'::jsonb, '{"templates": ["ABHA Integration Checklist", "Registry Connection Guide"], "tools": ["ABDM API Sandbox"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'Health Data Security & Privacy', 'Implement DPDP Act compliance for health data. Navigate health data localization requirements. Handle sensitive health information categories. Design privacy-by-design architecture.', '["Assess health data classification", "Implement data localization", "Design consent management for health", "Create privacy impact assessment"]'::jsonb, '{"templates": ["Health Data Security Policy", "Privacy Framework"], "tools": ["Health Data Compliance Checker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Unified Health Interface (UHI)', 'Navigate Unified Health Interface for service discovery. Implement UHI for appointment booking and teleconsultation. Understand UHI gateway requirements. Design UHI-enabled healthcare marketplace.', '["Study UHI architecture and protocols", "Implement UHI discovery services", "Design UHI-enabled features", "Plan UHI certification process"]'::jsonb, '{"templates": ["UHI Integration Guide", "Service Discovery Template"], "tools": ["UHI Sandbox Environment"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Clinical Trials & Research (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Clinical Trials & Research', 'Navigate clinical trial regulations and build clinical research technology solutions', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'Clinical Trial Regulations in India', 'Understand New Drugs and Clinical Trials Rules 2019. Navigate CDSCO clinical trial approval process. Learn about CTRI registration requirements. Handle ethics committee approval process.', '["Review CT Rules 2019 key provisions", "Understand CDSCO approval pathway", "Learn CTRI registration process", "Identify ethics committee requirements"]'::jsonb, '{"templates": ["CT Rules Summary", "Approval Timeline Template"], "tools": ["CTRI Registration Guide"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'Clinical Trial Technology (CTMS)', 'Build Clinical Trial Management Systems for India. Implement patient recruitment and screening tools. Design electronic data capture (EDC) systems. Handle randomization and blinding.', '["Design CTMS architecture", "Implement EDC functionality", "Create patient recruitment module", "Build randomization system"]'::jsonb, '{"templates": ["CTMS Requirements", "EDC Design Template"], "tools": ["CTMS Platform Comparison"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Real World Evidence & Registries', 'Build RWE platforms for post-market studies. Implement patient registries and outcomes tracking. Navigate regulatory acceptance of RWE in India. Design observational study workflows.', '["Design RWE collection architecture", "Implement patient registry system", "Create outcomes tracking dashboard", "Plan RWE regulatory strategy"]'::jsonb, '{"templates": ["RWE Platform Requirements", "Registry Design Template"], "tools": ["Outcomes Analysis Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Biobanking & Sample Management', 'Understand biobanking regulations in India. Implement LIMS for clinical samples. Handle bioethics and consent for sample storage. Navigate international sample transfer regulations.', '["Review biobanking regulatory requirements", "Design LIMS implementation", "Create bioethics consent framework", "Plan sample transfer compliance"]'::jsonb, '{"templates": ["Biobank Consent Template", "LIMS Requirements"], "tools": ["Sample Tracking System"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Decentralized Clinical Trials', 'Implement decentralized/hybrid clinical trial models. Navigate regulatory acceptance for remote trials. Design home-based clinical assessments. Handle telemedicine in clinical trials.', '["Assess DCT feasibility for India", "Design remote assessment protocols", "Implement home nursing network", "Create DCT technology platform"]'::jsonb, '{"templates": ["DCT Protocol Template", "Remote Assessment Guide"], "tools": ["DCT Platform Builder"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: Quality Certifications & Standards (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'Quality Certifications & Standards', 'Achieve quality certifications for healthcare products and services', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'ISO 13485 Implementation', 'Implement ISO 13485 Quality Management System for medical devices. Understand documentation requirements. Navigate certification body selection. Handle surveillance audits and maintenance.', '["Conduct ISO 13485 gap assessment", "Develop QMS documentation", "Select certification body", "Plan implementation timeline"]'::jsonb, '{"templates": ["ISO 13485 Gap Assessment", "QMS Documentation Template"], "tools": ["Certification Body Comparison"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'CE Marking & MDR Compliance', 'Navigate CE marking for EU market access. Understand MDR (Medical Device Regulation) requirements. Implement EU technical documentation. Handle Notified Body engagement.', '["Assess CE marking requirements", "Prepare technical documentation", "Identify Notified Body", "Plan MDR transition strategy"]'::jsonb, '{"templates": ["MDR Compliance Checklist", "Technical File Template"], "tools": ["Notified Body Directory"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'US FDA Registration', 'Navigate FDA 510(k) and De Novo pathways. Understand FDA registration and listing requirements. Implement FDA QSR compliance. Handle FDA establishment inspection.', '["Determine FDA regulatory pathway", "Prepare 510(k) submission", "Implement QSR requirements", "Plan FDA inspection readiness"]'::jsonb, '{"templates": ["510(k) Submission Template", "QSR Compliance Checklist"], "tools": ["FDA Pathway Selector"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'NABH & NABL Accreditation', 'Navigate NABH accreditation for healthcare facilities. Understand NABL accreditation for laboratories. Implement accreditation-ready processes. Handle accreditation maintenance.', '["Assess NABH/NABL requirements", "Implement pre-accreditation changes", "Prepare for accreditation assessment", "Plan continuous compliance"]'::jsonb, '{"templates": ["NABH Standards Checklist", "NABL Compliance Guide"], "tools": ["Accreditation Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'IEC & ISO Standards for HealthTech', 'Implement IEC 62304 for medical software. Navigate IEC 60601 for medical electrical equipment. Understand ISO 14971 risk management. Handle cybersecurity standards IEC 62443.', '["Assess applicable IEC/ISO standards", "Implement IEC 62304 compliance", "Conduct ISO 14971 risk assessment", "Design cybersecurity framework"]'::jsonb, '{"templates": ["Standards Applicability Matrix", "Risk Management File"], "tools": ["Standards Compliance Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Healthcare Partnerships & Distribution (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Healthcare Partnerships & Distribution', 'Build partnerships with hospitals, clinics, insurers, and pharma companies', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Hospital & Clinic Partnerships', 'Navigate hospital procurement and vendor empanelment. Understand hospital decision-making: clinical, procurement, IT, finance. Design pilot programs for hospital adoption. Handle integration with Hospital Information Systems.', '["Identify target hospital segments", "Create hospital pitch deck", "Design pilot program structure", "Plan HIS integration approach"]'::jsonb, '{"templates": ["Hospital Partnership Proposal", "Pilot Program Template"], "tools": ["Hospital Database India"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Insurance & TPA Integration', 'Partner with health insurers and TPAs. Navigate cashless claim integration. Implement pre-authorization workflows. Handle claim adjudication technology.', '["Identify target insurers and TPAs", "Design cashless integration", "Create pre-authorization workflow", "Plan claims technology solution"]'::jsonb, '{"templates": ["Insurer Partnership Proposal", "Integration Checklist"], "tools": ["TPA Directory India"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Pharma Company Partnerships', 'Partner with pharma for patient support programs. Navigate KOL engagement and medical education. Design clinical data partnerships. Handle co-marketing and co-development.', '["Identify pharma partnership opportunities", "Design patient support program", "Create medical education platform", "Plan clinical data partnership"]'::jsonb, '{"templates": ["Pharma Partnership Framework", "PSP Design Template"], "tools": ["Pharma Partner Database"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Government & Public Health', 'Partner with government health programs: Ayushman Bharat, NHM, state schemes. Navigate government procurement processes (GeM). Implement public health surveillance solutions. Handle CSR partnerships in healthcare.', '["Identify government program opportunities", "Register on GeM portal", "Design public health solutions", "Plan CSR partnership approach"]'::jsonb, '{"templates": ["Government Partnership Proposal", "GeM Registration Guide"], "tools": ["Government Scheme Database"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Medical Device Distribution', 'Build medical device distribution network. Navigate dealer and distributor regulations. Implement service and maintenance networks. Handle medical device training programs.', '["Design distribution strategy", "Create dealer agreement template", "Plan service network", "Design training program"]'::jsonb, '{"templates": ["Distribution Agreement", "Service Network Plan"], "tools": ["Distributor Database"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: HealthTech Funding & Investment (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'HealthTech Funding & Investment', 'Navigate HealthTech-specific funding landscape and investor expectations', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'HealthTech Investor Landscape', 'Identify HealthTech-focused investors: HealthQuad, Chiratae, Lightspeed, Sequoia Health. Understand sector-specific due diligence. Navigate corporate VC from pharma and hospital chains. Build relationships with healthcare angels.', '["Create target investor list", "Research investor portfolio and thesis", "Identify warm introduction paths", "Build investor relationship tracker"]'::jsonb, '{"templates": ["HealthTech Investor Database", "Outreach Template"], "tools": ["Investor CRM"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'HealthTech Pitch Deck', 'Create compelling HealthTech pitch: clinical validation, regulatory pathway, reimbursement strategy. Demonstrate healthcare domain expertise. Present unit economics for healthcare. Handle regulatory risk questions.', '["Create HealthTech pitch deck", "Prepare clinical evidence summary", "Design regulatory timeline slide", "Practice handling objections"]'::jsonb, '{"templates": ["HealthTech Pitch Deck Template", "Clinical Summary Format"], "tools": ["Pitch Deck Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'Healthcare Due Diligence', 'Navigate HealthTech-specific due diligence: regulatory pathway validation, clinical evidence review, IP assessment. Handle medical device certification questions. Prepare for technical deep dives.', '["Prepare regulatory due diligence pack", "Create clinical evidence summary", "Document IP portfolio", "Build technical documentation"]'::jsonb, '{"templates": ["Due Diligence Checklist", "Data Room Structure"], "tools": ["Document Preparation Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'Grants & Non-Dilutive Funding', 'Access healthcare grants: BIRAC, DBT, DST, Grand Challenges. Navigate international health grants: Gates Foundation, Wellcome Trust. Apply for innovation challenges and competitions. Handle grant compliance and reporting.', '["Identify applicable grants", "Prepare grant applications", "Plan grant compliance system", "Create reporting framework"]'::jsonb, '{"templates": ["Grant Application Template", "Compliance Tracker"], "tools": ["Grant Database India"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'Strategic & Corporate Investment', 'Navigate strategic investment from pharma, hospital chains, insurers. Understand strategic vs financial investor trade-offs. Design partnership-first investment approach. Handle acquisition discussions.', '["Identify strategic investor targets", "Design partnership proposal", "Prepare for strategic discussions", "Plan exit scenarios"]'::jsonb, '{"templates": ["Strategic Investment Proposal", "Partnership Terms Framework"], "tools": ["Strategic Partner Database"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 10: Government Health Schemes & Programs (Days 46-50)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_10_id, v_product_id, 'Government Health Schemes & Programs', 'Leverage government health initiatives and schemes for HealthTech growth', 10, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_10_id, 46, 'Ayushman Bharat Ecosystem', 'Navigate Ayushman Bharat PM-JAY for empanelment. Understand PMJAY package rates and claim process. Integrate with AB-PMJAY IT systems. Handle beneficiary verification and claim settlement.', '["Understand PMJAY empanelment process", "Review package rate structure", "Plan IT integration", "Design claim workflow"]'::jsonb, '{"templates": ["PMJAY Integration Guide", "Empanelment Checklist"], "tools": ["Package Rate Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 47, 'National Health Mission (NHM)', 'Partner with NHM for maternal, child, and disease control programs. Navigate state health mission engagement. Implement community health worker technology. Handle immunization and surveillance solutions.', '["Identify NHM partnership opportunities", "Engage with state health missions", "Design CHW technology solution", "Plan program integration"]'::jsonb, '{"templates": ["NHM Partnership Proposal", "Program Design Template"], "tools": ["State Health Mission Directory"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 48, 'Make in India for Medical Devices', 'Leverage Make in India incentives for medical devices. Navigate PLI scheme for medical devices. Access NATHEALTH and industry associations. Handle domestic manufacturing benefits.', '["Assess PLI scheme eligibility", "Apply for Make in India benefits", "Join industry associations", "Plan domestic manufacturing"]'::jsonb, '{"templates": ["PLI Application Guide", "Manufacturing Incentive Tracker"], "tools": ["PLI Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 49, 'State Health Programs', 'Navigate state-specific health schemes and programs. Access state health innovation funds. Partner with state medical corporations. Handle state-level procurement and empanelment.', '["Map state health programs", "Identify state innovation funds", "Connect with state health officials", "Plan multi-state rollout"]'::jsonb, '{"templates": ["State Scheme Database", "State Engagement Plan"], "tools": ["State Health Directory"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 50, 'Healthcare Startup Incubators', 'Access healthcare-focused incubators: BIRAC BioNest, KIIT-TBI, Startup Health India. Navigate accelerator programs. Handle grant-linked incubation. Build mentor network in healthcare.', '["Identify relevant incubators", "Apply to accelerator programs", "Access incubator resources", "Build mentor relationships"]'::jsonb, '{"templates": ["Incubator Application Template", "Mentor Engagement Plan"], "tools": ["HealthTech Incubator Directory"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 11: Scaling HealthTech Operations (Days 51-55)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_11_id, v_product_id, 'Scaling HealthTech Operations', 'Scale HealthTech business across geographies and prepare for exit', 11, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_11_id, 51, 'Scaling Healthcare Operations', 'Scale healthcare delivery: clinical operations, quality assurance, patient safety. Implement clinical governance frameworks. Handle regulatory compliance at scale. Design operational excellence for healthcare.', '["Design clinical operations scaling plan", "Implement clinical governance", "Build quality assurance system", "Create patient safety framework"]'::jsonb, '{"templates": ["Clinical Governance Framework", "Operations Scaling Plan"], "tools": ["Quality Dashboard"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 52, 'Geographic Expansion', 'Expand to Tier 2/3 India: hub and spoke models, mobile health units. Navigate international expansion: FDA, CE marking, WHO PQ. Understand GIFT City for health tech exports. Plan multi-geography licensing.', '["Design Tier 2/3 expansion strategy", "Plan international market entry", "Prepare for multi-geography licensing", "Create expansion timeline"]'::jsonb, '{"templates": ["Expansion Playbook", "International Strategy Template"], "tools": ["Market Opportunity Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 53, 'Technology Platform Scaling', 'Scale HealthTech infrastructure: HIPAA-equivalent security, high availability, interoperability. Implement AI/ML for clinical decision support. Handle health data analytics at scale. Design API-first healthcare platform.', '["Design scalable architecture", "Implement security certifications", "Build analytics infrastructure", "Create API platform"]'::jsonb, '{"templates": ["Tech Scaling Roadmap", "Security Framework"], "tools": ["Infrastructure Cost Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 54, 'HealthTech M&A Landscape', 'Understand HealthTech M&A dynamics: strategic acquisitions by pharma, hospitals, insurers. Navigate CDSCO approval for device company M&A. Build M&A-ready documentation and data room. Evaluate acquisition vs organic growth.', '["Analyze recent HealthTech M&A", "Prepare M&A data room", "Understand regulatory M&A approvals", "Create M&A readiness checklist"]'::jsonb, '{"templates": ["M&A Readiness Checklist", "Data Room Template"], "tools": ["HealthTech Valuation Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 55, 'IPO & Exit Readiness', 'Prepare for public markets: SEBI requirements, healthcare financial audits. Understand HealthTech IPO case studies globally and in India. Navigate pre-IPO funding and governance. Build investor relations for healthcare.', '["Assess IPO readiness gaps", "Implement corporate governance", "Plan pre-IPO capital raise", "Build investor relations capability"]'::jsonb, '{"templates": ["IPO Readiness Checklist", "Governance Framework"], "tools": ["IPO Timeline Planner"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
