-- P17: Product Development & Validation Course Migration
-- 50 days, 10 modules, comprehensive product management framework

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
    v_mod_10_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;
    v_mod_10_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P17',
        'Product Development & Validation',
        'Master the complete product lifecycle from customer discovery to product leadership. 10 comprehensive modules covering MVP design, user research, agile methodologies, product metrics, and growth experimentation. Build products that users love.',
        6999,
        50,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P17';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: Customer Discovery (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'Customer Discovery', 'Master problem interviews, Jobs-to-be-Done framework, and customer segmentation to deeply understand your target users', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'The Art of Problem Interviews', 'Learn why 42% of startups fail because they build products nobody wants. Master the Mom Test - asking questions that reveal truth, not validation. Understand the difference between customer problems and product ideas. Design interview scripts that uncover real pain points without leading questions.', '["Read The Mom Test core principles", "Draft 10 open-ended problem discovery questions", "Identify 5 potential customers to interview", "Set up first 3 customer discovery calls"]'::jsonb, '{"templates": ["Problem Interview Script Template", "Customer Discovery Tracker"], "tools": ["Interview Question Generator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'Jobs-to-be-Done Framework', 'Understand the JTBD theory - customers hire products to make progress. Learn functional, emotional, and social dimensions of jobs. Map the job story format: When [situation], I want to [motivation], so I can [outcome]. Analyze switching triggers and anxieties.', '["Identify 3 jobs your customers are trying to accomplish", "Write job stories for each customer segment", "Map the 4 forces of progress for your product", "Document switching triggers and barriers"]'::jsonb, '{"templates": ["JTBD Canvas Template", "Forces of Progress Worksheet"], "tools": ["Job Story Builder"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'Customer Segmentation Deep Dive', 'Move beyond demographics to behavioral segmentation. Identify early adopters vs mainstream customers. Create customer archetypes with specific characteristics. Prioritize segments based on pain intensity and willingness to pay.', '["Define 3-5 distinct customer segments", "Create detailed customer archetype profiles", "Score segments on pain intensity (1-10)", "Identify your beachhead market segment"]'::jsonb, '{"templates": ["Customer Segment Matrix", "Archetype Profile Template"], "tools": ["Segment Prioritization Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'Synthesizing Customer Insights', 'Transform raw interview data into actionable insights. Use affinity mapping to identify patterns. Create insight statements that drive product decisions. Build your customer evidence repository.', '["Conduct 5 customer discovery interviews", "Create affinity map from interview notes", "Write 5 key insight statements", "Build customer quotes and evidence repository"]'::jsonb, '{"templates": ["Affinity Mapping Template", "Insight Statement Framework"], "tools": ["Interview Analysis Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Problem Validation Scorecard', 'Evaluate problem-solution fit quantitatively. Create scoring criteria for problem validation. Set thresholds for proceeding to solution phase. Document learnings and pivot triggers.', '["Create problem validation scorecard with criteria", "Score your current problem hypothesis", "Define go/no-go thresholds", "Document pivot or persevere decision"]'::jsonb, '{"templates": ["Problem Validation Scorecard", "Pivot Decision Framework"], "tools": ["Validation Metrics Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: Market Validation (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'Market Validation', 'Calculate TAM/SAM/SOM, conduct competitive analysis, and validate market size with data-driven approaches', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'TAM SAM SOM Analysis', 'Master the top-down and bottom-up market sizing approaches. Calculate Total Addressable Market using industry data. Define your Serviceable Addressable Market based on geographic and segment focus. Estimate realistic Serviceable Obtainable Market for investor conversations.', '["Calculate TAM using top-down approach", "Define SAM with geographic and segment filters", "Estimate SOM for first 3 years", "Create market sizing slides for pitch deck"]'::jsonb, '{"templates": ["Market Sizing Template", "TAM SAM SOM Calculator"], "tools": ["Industry Data Sources Guide"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'Competitive Landscape Mapping', 'Build comprehensive competitive analysis beyond direct competitors. Identify indirect and substitute solutions. Create feature comparison matrices. Understand competitor positioning and pricing strategies.', '["Identify 10+ direct and indirect competitors", "Create competitive feature matrix", "Analyze competitor pricing models", "Map competitor positioning on 2x2 matrix"]'::jsonb, '{"templates": ["Competitive Analysis Template", "Feature Comparison Matrix"], "tools": ["Competitor Intelligence Tracker"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'Finding Your Competitive Moat', 'Identify sustainable competitive advantages. Evaluate network effects, switching costs, and economies of scale. Assess brand and proprietary technology opportunities. Build defensibility into your product strategy.', '["Evaluate 7 types of competitive moats", "Identify your strongest 2-3 moat opportunities", "Plan moat-building activities", "Document competitive advantage thesis"]'::jsonb, '{"templates": ["Competitive Moat Assessment", "Defensibility Planning Canvas"], "tools": ["Moat Strength Evaluator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Market Timing Analysis', 'Assess why now is the right time for your product. Identify enabling technologies and regulatory changes. Understand macro trends supporting your thesis. Evaluate market readiness and adoption curves.', '["List 5 why now factors for your product", "Analyze technology and regulatory enablers", "Map to technology adoption lifecycle", "Create market timing thesis"]'::jsonb, '{"templates": ["Why Now Framework", "Market Timing Canvas"], "tools": ["Trend Analysis Dashboard"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'Market Validation Synthesis', 'Combine customer discovery and market analysis. Create your market opportunity thesis. Set market validation milestones. Prepare for investor market diligence.', '["Create market opportunity summary", "Synthesize customer and market learnings", "Set market validation success criteria", "Prepare market section for pitch deck"]'::jsonb, '{"templates": ["Market Opportunity Thesis", "Validation Milestone Tracker"], "tools": ["Market Validation Scorecard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: MVP Design (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'MVP Design', 'Master feature prioritization using MoSCoW method, design effective prototypes, and choose the right MVP approach', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'Feature Prioritization Frameworks', 'Learn multiple prioritization methods: RICE, ICE, Value vs Effort. Master the MoSCoW method for startup MVPs. Create weighted scoring models. Balance user needs with business goals.', '["List all potential features for your product", "Score features using RICE framework", "Apply MoSCoW categorization", "Create prioritized feature backlog"]'::jsonb, '{"templates": ["RICE Scoring Template", "MoSCoW Prioritization Matrix"], "tools": ["Feature Prioritization Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'Defining Your MVP Scope', 'Understand the true meaning of Minimum Viable Product. Identify the core value proposition to test. Remove nice-to-have features ruthlessly. Set clear MVP success criteria.', '["Define your core value hypothesis", "Identify the single most important feature", "List features to explicitly exclude", "Set 3 measurable MVP success criteria"]'::jsonb, '{"templates": ["MVP Scope Definition Canvas", "Feature Cut Worksheet"], "tools": ["MVP Success Criteria Builder"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'Prototype Tools and Techniques', 'Choose the right fidelity level for your prototype. Master no-code tools: Figma, Bubble, Webflow, Glide. Understand when to use paper vs clickable vs coded prototypes. Build prototypes that test specific hypotheses.', '["Select appropriate prototype fidelity", "Choose prototyping tool based on needs", "Create your first clickable prototype", "Define what the prototype will test"]'::jsonb, '{"templates": ["Prototype Planning Template", "Tool Selection Matrix"], "tools": ["No-Code Tool Comparison Guide"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'MVP Types and Selection', 'Explore different MVP approaches: Wizard of Oz, Concierge, Landing Page, Single Feature. Match MVP type to your hypothesis and resources. Understand build vs fake tradeoffs. Plan your validation experiment.', '["Evaluate 5 MVP types for your product", "Select the most appropriate MVP approach", "Design your MVP validation experiment", "Create MVP development timeline"]'::jsonb, '{"templates": ["MVP Type Selection Guide", "Validation Experiment Canvas"], "tools": ["MVP Approach Decision Tree"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'MVP Launch Strategy', 'Plan your MVP launch for maximum learning. Define target users for initial launch. Set up analytics and feedback collection. Create iteration cadence based on learnings.', '["Define MVP launch audience criteria", "Set up analytics tracking plan", "Create feedback collection mechanism", "Plan first 3 iteration sprints"]'::jsonb, '{"templates": ["MVP Launch Checklist", "Analytics Setup Guide"], "tools": ["Launch Readiness Scorecard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: User Research (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'User Research', 'Conduct usability testing, design surveys, collect feedback systematically, and create actionable user personas', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Usability Testing Fundamentals', 'Design effective usability tests that reveal true user behavior. Set up testing environments and recording tools. Write task-based test scripts. Analyze usability issues with severity ratings.', '["Set up usability testing tool (Hotjar, Maze)", "Write 5 task-based usability test scenarios", "Recruit 5 users for usability testing", "Create usability issue severity rating system"]'::jsonb, '{"templates": ["Usability Test Script Template", "Issue Severity Rating Guide"], "tools": ["Usability Testing Tool Comparison"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'Survey Design and Execution', 'Create surveys that yield actionable insights. Avoid common survey biases and leading questions. Choose between NPS, CSAT, CES metrics. Achieve statistically significant sample sizes.', '["Design customer satisfaction survey", "Include NPS question with follow-up", "Define target sample size for significance", "Set up survey distribution channels"]'::jsonb, '{"templates": ["Survey Question Library", "Sample Size Calculator"], "tools": ["Survey Platform Comparison"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'Continuous Feedback Collection', 'Implement in-app feedback mechanisms. Set up feedback widgets and user session recordings. Create feedback triage and prioritization process. Close the feedback loop with users.', '["Implement in-app feedback widget", "Set up session recording tool", "Create feedback categorization system", "Design feedback response workflow"]'::jsonb, '{"templates": ["Feedback Triage Matrix", "User Response Templates"], "tools": ["Feedback Tool Integration Guide"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'User Persona Development', 'Create data-driven personas based on research. Move beyond demographic-only personas. Include behaviors, goals, frustrations, and contexts. Use personas to drive product decisions.', '["Synthesize research into 3-4 distinct personas", "Include behavioral and psychographic data", "Create persona cards with key attributes", "Map personas to product features"]'::jsonb, '{"templates": ["User Persona Template", "Persona Research Synthesis"], "tools": ["Persona Builder Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Journey Mapping and Pain Points', 'Create customer journey maps from research. Identify pain points and moments of delight. Map emotional states throughout the journey. Use journey maps for feature prioritization.', '["Create end-to-end customer journey map", "Identify 5 key pain points with severity", "Map emotional highs and lows", "Prioritize improvements based on journey analysis"]'::jsonb, '{"templates": ["Customer Journey Map Template", "Pain Point Prioritization Matrix"], "tools": ["Journey Mapping Workshop Guide"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: Agile for Startups (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'Agile for Startups', 'Implement Scrum basics, master sprint planning, run effective retrospectives, and use Kanban for continuous flow', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'Scrum Fundamentals for Startups', 'Understand Scrum framework adapted for early-stage startups. Define roles: Product Owner, Scrum Master, Dev Team. Set up sprint ceremonies without excessive overhead. Balance agility with startup chaos.', '["Define Scrum roles for your team", "Set appropriate sprint duration (1-2 weeks)", "Create lightweight ceremony schedule", "Document your startup Scrum adaptations"]'::jsonb, '{"templates": ["Startup Scrum Setup Guide", "Role Definition Template"], "tools": ["Scrum Ceremony Planner"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'Sprint Planning Excellence', 'Run effective sprint planning sessions. Create user stories with acceptance criteria. Estimate stories with story points or t-shirt sizing. Set realistic sprint commitments.', '["Write user stories for top 10 backlog items", "Add acceptance criteria to each story", "Conduct team estimation session", "Plan first sprint with realistic capacity"]'::jsonb, '{"templates": ["User Story Template", "Sprint Planning Agenda"], "tools": ["Story Point Estimation Guide"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Daily Standups and Sprint Execution', 'Run 15-minute standups that add value. Track sprint progress with burndown charts. Handle blockers and impediments quickly. Maintain team focus throughout the sprint.', '["Set up daily standup format and time", "Create sprint burndown tracking", "Establish blocker escalation process", "Design sprint dashboard for visibility"]'::jsonb, '{"templates": ["Standup Meeting Format", "Burndown Chart Template"], "tools": ["Sprint Tracking Dashboard"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'Retrospectives That Drive Improvement', 'Facilitate retrospectives that uncover real issues. Use varied retrospective formats to keep engagement. Create action items that actually get implemented. Build continuous improvement culture.', '["Select retrospective format for first retro", "Facilitate retrospective with the team", "Create action items with owners", "Track action item completion over sprints"]'::jsonb, '{"templates": ["Retrospective Format Library", "Action Item Tracker"], "tools": ["Retro Facilitation Guide"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Kanban for Continuous Flow', 'Implement Kanban for teams that need flexibility. Set up Kanban board with WIP limits. Optimize flow with cycle time analysis. Choose between Scrum, Kanban, or Scrumban.', '["Create Kanban board with appropriate columns", "Set WIP limits for each stage", "Measure cycle time for improvement", "Decide Scrum vs Kanban vs Scrumban for your team"]'::jsonb, '{"templates": ["Kanban Board Setup Guide", "WIP Limit Calculator"], "tools": ["Kanban vs Scrum Decision Framework"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Product Metrics (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Product Metrics', 'Define your North Star metric, measure retention, analyze CAC and LTV, and conduct cohort analysis for growth insights', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'Defining Your North Star Metric', 'Identify the single metric that captures your core value. Understand North Star metric characteristics. Align team around North Star metric. Create supporting input metrics.', '["Evaluate 5 candidate North Star metrics", "Select your North Star with rationale", "Define 3-4 supporting input metrics", "Create North Star metric dashboard"]'::jsonb, '{"templates": ["North Star Metric Framework", "Metric Selection Criteria"], "tools": ["North Star Metric Examples by Business Type"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'Retention and Engagement Metrics', 'Measure retention with different timeframes. Understand DAU, WAU, MAU and their ratios. Define activation metrics for your product. Track feature adoption and usage patterns.', '["Define retention timeframes for your product", "Set up DAU/MAU ratio tracking", "Create activation milestone definition", "Implement feature usage tracking"]'::jsonb, '{"templates": ["Retention Curve Template", "Activation Funnel Design"], "tools": ["Retention Analysis Dashboard"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'CAC and LTV Analysis', 'Calculate Customer Acquisition Cost across channels. Understand Lifetime Value calculation methods. Analyze LTV:CAC ratio for business health. Optimize unit economics for sustainable growth.', '["Calculate CAC by acquisition channel", "Determine LTV using your revenue model", "Analyze LTV:CAC ratio", "Identify unit economics improvement opportunities"]'::jsonb, '{"templates": ["CAC Calculation Template", "LTV Model Spreadsheet"], "tools": ["Unit Economics Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Cohort Analysis Deep Dive', 'Set up cohort analysis for your product. Analyze retention cohorts over time. Identify successful vs struggling cohorts. Use cohort insights for product improvements.', '["Define cohort segmentation criteria", "Create retention cohort analysis", "Compare cohort performance over time", "Identify patterns in successful cohorts"]'::jsonb, '{"templates": ["Cohort Analysis Template", "Cohort Comparison Framework"], "tools": ["Cohort Analysis Dashboard"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Building Your Metrics Dashboard', 'Create a metrics dashboard for decision-making. Choose the right visualization for each metric. Set up alerting for metric anomalies. Review metrics in regular cadence.', '["Design your product metrics dashboard", "Select visualization types for each metric", "Set up automated alerts for key metrics", "Establish weekly metrics review ritual"]'::jsonb, '{"templates": ["Dashboard Design Template", "Metrics Review Agenda"], "tools": ["Dashboard Tool Comparison"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: Product Roadmapping (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'Product Roadmapping', 'Create effective product roadmaps, align stakeholders, prioritize features strategically, and communicate product vision', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'Roadmap Types and Formats', 'Understand different roadmap formats: timeline, now-next-later, outcome-based. Choose the right format for your stakeholders. Balance commitment with flexibility. Avoid common roadmap antipatterns.', '["Evaluate 3 roadmap format options", "Select format based on stakeholder needs", "Define roadmap time horizons", "Create first draft roadmap"]'::jsonb, '{"templates": ["Roadmap Format Examples", "Time Horizon Guidelines"], "tools": ["Roadmap Tool Comparison"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Strategic Prioritization', 'Use strategy to drive prioritization decisions. Evaluate opportunities against company goals. Create objective prioritization criteria. Handle stakeholder priority conflicts.', '["Define strategic themes for next quarter", "Create weighted prioritization criteria", "Score backlog items against strategy", "Resolve conflicting stakeholder priorities"]'::jsonb, '{"templates": ["Strategic Prioritization Framework", "Priority Conflict Resolution Guide"], "tools": ["Priority Scoring Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Stakeholder Alignment', 'Identify all roadmap stakeholders and their needs. Run effective roadmap review sessions. Handle pushback and competing demands. Build organizational buy-in for roadmap.', '["Map all stakeholders with their interests", "Schedule stakeholder alignment sessions", "Create stakeholder communication plan", "Document stakeholder feedback process"]'::jsonb, '{"templates": ["Stakeholder Map Template", "Roadmap Review Agenda"], "tools": ["Stakeholder Communication Matrix"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Roadmap Communication', 'Create different roadmap views for different audiences. Present roadmap to executives, team, and customers. Handle roadmap questions and challenges. Manage expectations around timelines.', '["Create executive summary roadmap view", "Design team-level detailed roadmap", "Prepare customer-facing roadmap", "Develop FAQ for roadmap questions"]'::jsonb, '{"templates": ["Multi-Audience Roadmap Template", "Roadmap FAQ Template"], "tools": ["Roadmap Presentation Guide"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'Roadmap Evolution and Updates', 'Set up regular roadmap review cadence. Handle scope changes and new opportunities. Communicate roadmap changes effectively. Balance consistency with responsiveness.', '["Establish quarterly roadmap review process", "Create change request evaluation criteria", "Design roadmap update communication", "Track roadmap delivery vs plan"]'::jsonb, '{"templates": ["Roadmap Review Template", "Change Communication Template"], "tools": ["Roadmap Tracking Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Growth Experimentation (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Growth Experimentation', 'Design A/B tests, implement growth loops, create viral mechanics, and build referral programs that scale', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'A/B Testing Fundamentals', 'Design statistically valid A/B tests. Calculate required sample sizes. Avoid common testing mistakes. Implement proper test analysis and decision-making.', '["Identify 3 high-impact features to test", "Calculate sample size for first test", "Design test hypothesis and success criteria", "Set up A/B testing tool integration"]'::jsonb, '{"templates": ["A/B Test Planning Template", "Sample Size Calculator"], "tools": ["A/B Testing Platform Comparison"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Growth Loops Architecture', 'Understand different types of growth loops. Design viral, content, paid, and product-led loops. Identify reinforcing mechanisms in your product. Build sustainable growth engines.', '["Map potential growth loops for your product", "Identify the strongest loop opportunity", "Design loop mechanics and triggers", "Create loop optimization plan"]'::jsonb, '{"templates": ["Growth Loop Canvas", "Loop Mechanics Worksheet"], "tools": ["Growth Loop Examples Library"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Viral Mechanics and K-Factor', 'Design viral features that drive organic sharing. Calculate and optimize K-factor. Create shareable moments in user journey. Build network effects into your product.', '["Identify shareable moments in your product", "Calculate current K-factor if applicable", "Design 3 viral feature ideas", "Create sharing incentive structure"]'::jsonb, '{"templates": ["Viral Feature Design Template", "K-Factor Calculator"], "tools": ["Viral Mechanics Playbook"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Referral Program Design', 'Create referral programs that actually work. Design two-sided incentives. Optimize referral timing and messaging. Track and improve referral performance.', '["Design referral program structure", "Create incentive tiers for both sides", "Write referral messaging and CTA", "Set up referral tracking and analytics"]'::jsonb, '{"templates": ["Referral Program Template", "Incentive Design Framework"], "tools": ["Referral Program Examples"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Experimentation Culture', 'Build a culture of continuous experimentation. Create experiment backlog and prioritization. Set up experiment documentation and learnings. Celebrate learning from failed experiments.', '["Create experiment backlog with 10+ ideas", "Prioritize experiments by impact and effort", "Set up experiment documentation system", "Design experiment review process"]'::jsonb, '{"templates": ["Experiment Backlog Template", "Experiment Documentation Format"], "tools": ["Experimentation Culture Playbook"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: Technical Product Management (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'Technical Product Management', 'Understand API design principles, manage technical debt strategically, and collaborate with engineering on system design', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'API Design for Product Managers', 'Understand API basics every PM should know. Evaluate API design decisions. Collaborate on API product requirements. Manage API versioning and deprecation.', '["Review your product API documentation", "Identify API improvements needed", "Create API requirements for new feature", "Understand API versioning strategy"]'::jsonb, '{"templates": ["API Requirements Template", "API Evaluation Checklist"], "tools": ["API Documentation Best Practices"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Managing Technical Debt', 'Understand technical debt types and impacts. Create framework for debt prioritization. Balance feature development with debt paydown. Communicate debt tradeoffs to stakeholders.', '["Inventory current technical debt with engineering", "Categorize debt by type and impact", "Create debt paydown prioritization", "Add tech debt to roadmap conversations"]'::jsonb, '{"templates": ["Technical Debt Inventory Template", "Debt Prioritization Framework"], "tools": ["Tech Debt Communication Guide"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'System Design Collaboration', 'Participate effectively in system design discussions. Understand scalability and performance requirements. Translate product needs to technical constraints. Make informed build vs buy decisions.', '["Learn system design basics for PMs", "Participate in next architecture discussion", "Document scalability requirements", "Evaluate build vs buy for next feature"]'::jsonb, '{"templates": ["System Design Requirements Template", "Build vs Buy Evaluation"], "tools": ["System Design Primer for PMs"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'Performance and Reliability', 'Define performance SLAs and targets. Understand reliability metrics (uptime, latency). Create performance requirements for features. Monitor and respond to performance issues.', '["Define performance targets for key flows", "Set up performance monitoring dashboard", "Create incident response process", "Add performance to feature specs"]'::jsonb, '{"templates": ["SLA Definition Template", "Incident Response Playbook"], "tools": ["Performance Monitoring Guide"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'Security and Compliance for PMs', 'Understand security requirements for your product. Navigate compliance requirements (GDPR, SOC2). Include security in product planning. Handle security incidents appropriately.', '["Identify applicable compliance requirements", "Review product security posture with team", "Add security requirements to PRDs", "Create security incident communication plan"]'::jsonb, '{"templates": ["Security Requirements Checklist", "Compliance Mapping Template"], "tools": ["Security for PMs Guide"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 10: Product Leadership (Days 46-50)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_10_id, v_product_id, 'Product Leadership', 'Build and lead product teams, manage stakeholders effectively, and develop long-term product strategy', 10, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_10_id, 46, 'Building Product Teams', 'Hire and develop product managers. Define PM roles and levels. Create PM career ladder. Build PM team culture and rituals.', '["Define PM role requirements", "Create PM interview process", "Design PM career progression", "Establish PM team rituals"]'::jsonb, '{"templates": ["PM Job Description Template", "PM Career Ladder"], "tools": ["PM Interview Guide"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 47, 'Stakeholder Management Excellence', 'Map and manage complex stakeholder relationships. Build influence without authority. Handle difficult stakeholders effectively. Create stakeholder communication rhythms.', '["Create comprehensive stakeholder map", "Identify challenging relationships", "Design influence strategy", "Establish stakeholder update cadence"]'::jsonb, '{"templates": ["Stakeholder Influence Map", "Communication Cadence Template"], "tools": ["Stakeholder Management Playbook"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 48, 'Product Vision and Strategy', 'Develop compelling product vision. Create multi-year product strategy. Align strategy with company goals. Communicate vision to inspire teams.', '["Write your product vision statement", "Create 3-year product strategy", "Align strategy with company OKRs", "Present vision to team and stakeholders"]'::jsonb, '{"templates": ["Product Vision Template", "Strategy Document Format"], "tools": ["Vision Communication Guide"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 49, 'Cross-Functional Leadership', 'Lead effectively across engineering, design, marketing. Build strong partnerships with each function. Navigate organizational complexity. Drive alignment on product decisions.', '["Assess cross-functional relationships", "Build deeper partnership with key functions", "Create cross-functional alignment process", "Resolve ongoing cross-functional tensions"]'::jsonb, '{"templates": ["Cross-Functional RACI Template", "Partnership Building Guide"], "tools": ["Alignment Workshop Format"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 50, 'Product Leadership Capstone', 'Synthesize all learnings into your product leadership philosophy. Create your personal development plan. Build your product leadership brand. Plan your continued growth as a product leader.', '["Document your product leadership philosophy", "Create 12-month development plan", "Build visibility for your work", "Set quarterly learning goals"]'::jsonb, '{"templates": ["Leadership Philosophy Template", "Personal Development Plan"], "tools": ["Product Leadership Community Resources"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
