-- THE INDIAN STARTUP - P21: HealthTech & Medical Devices - Enhanced Content Part 3
-- Migration: 20260204_021c_p21_healthtech_enhanced_part3.sql
-- Purpose: Continue P21 course content - Modules 7-11 (Days 31-55)
-- Depends on: 20260204_021b_p21_healthtech_enhanced_part2.sql

BEGIN;

DO $$
DECLARE
    v_product_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
    v_mod_10_id TEXT;
    v_mod_11_id TEXT;
BEGIN
    -- Get P21 product ID
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P21';

    -- ========================================
    -- MODULE 7: Pharmacy Tech (Days 31-35)
    -- ========================================
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (
        gen_random_uuid()::text,
        v_product_id,
        'Pharmacy Technology Solutions',
        'Build pharmacy technology solutions for the Indian market - understanding drug distribution regulations, pharmacy management systems, supply chain technology, and emerging opportunities in pharmaceutical logistics and retail automation.',
        6,
        NOW(),
        NOW()
    )
    RETURNING id INTO v_mod_7_id;

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt")
    VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'Pharmaceutical Distribution Landscape', 'India pharmaceutical distribution market is Rs 2.5 lakh crore annually with complex multi-tier structure. Distribution Tiers: C&F Agents (Carrying and Forwarding) handle large-volume storage and regional distribution for manufacturers. Super Stockists maintain state/regional inventory supplying to stockists. Stockists/Wholesalers supply to retail pharmacies in defined territories. Retail Pharmacies (870,000+ outlets) dispense to patients. Technology Opportunity: Legacy systems, manual processes, low digitization. Prescription tracking 15% digitized. Inventory management largely manual in Tier 2/3. Compliance documentation paper-based. Key Pain Points: Stock-outs at retail (20% average), expiry management (Rs 5,000 Cr annual waste), counterfeit drugs (25% of market in some estimates), regulatory compliance burden. Emerging Models: Direct-to-pharmacy (D2P) platforms bypassing intermediaries, tech-enabled distribution improving efficiency, cold chain technology for biologics/vaccines. Regulatory Framework: Drug licenses required at each tier, Schedule wise storage requirements, record-keeping mandates under D&C Rules.', '["Map pharmaceutical distribution chain in your target geography", "Identify technology gaps at each distribution tier", "Research existing pharmacy tech solutions and their limitations", "Define target segment: C&F, stockist, retail, or cross-tier platform"]'::jsonb, '["Pharmaceutical Distribution Market Analysis with tier-wise sizing", "Distribution Technology Gap Assessment Framework", "Pharmacy Tech Competitive Landscape Map", "Distribution Regulations Summary by license type"]'::jsonb, 90, 50, 0, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Pharmacy Management Systems', 'Pharmacy Management Systems (PMS) automate retail pharmacy operations. Current market Rs 500 crore, growing 15% annually. Core Features: Inventory Management - stock tracking, reorder points, expiry alerts, batch management. Billing and POS - prescription entry, pricing, GST compliance, payment processing. Customer Management - patient profiles, purchase history, chronic disease tracking. Compliance - Schedule H record-keeping, drug license display, sales register maintenance. Market Segmentation: Chain pharmacies (Apollo, MedPlus, Wellness Forever) - 5% of outlets, 20% of revenue, enterprise PMS. Independent pharmacies (95% of outlets) - largely unorganized, basic or no PMS. Hospital pharmacies - integrated with HIS, specialized workflows. Pricing Models: License: Rs 15,000-50,000 one-time for basic, Rs 1-5 lakh for enterprise. SaaS: Rs 500-2,000/month for independent, Rs 5,000-20,000/month for chains. Implementation: Rs 10,000-50,000 setup, training, data migration. Key Differentiators: Regional language support (critical for Tier 2/3), offline capability (connectivity issues), GST compliance automation, integration with e-pharmacy platforms.', '["Evaluate existing PMS solutions in market - features, pricing, limitations", "Define target pharmacy segment and their specific needs", "Design MVP feature set addressing core pain points", "Create go-to-market strategy for pharmacy software"]'::jsonb, '["PMS Feature Comparison Matrix for 10+ solutions", "Pharmacy Segment Needs Analysis by type and size", "PMS MVP Requirements Document template", "Pharmacy Software GTM Playbook"]'::jsonb, 90, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Drug Supply Chain Technology', 'Drug supply chain technology addresses visibility, efficiency, and compliance across pharmaceutical distribution. Market opportunity Rs 1,000+ crore annually. Key Technology Areas: Track and Trace: Serialization mandated for export, domestic requirements emerging. Bar code/QR code scanning at each supply chain node. Authentication against counterfeit. GS1 standards compliance. Temperature Monitoring: Cold chain critical for biologics, vaccines, insulin. IoT sensors for continuous monitoring. Alert systems for temperature excursion. Compliance documentation for regulators. Demand Forecasting: AI/ML for predicting pharmacy demand. Reducing stock-outs and overstocking. Seasonal variation handling. New product launch planning. Order Management: B2B ordering platforms connecting pharmacies to distributors. Automated replenishment systems. Dynamic pricing and scheme management. Integration with PMS for seamless ordering. Regulatory Requirements: DAVA (Drug Authentication and Verification Application) for certain categories. GST e-way bill integration. Drug license verification in supply chain. Schedule-wise handling requirements.', '["Identify specific supply chain problem to solve", "Research regulatory requirements affecting your solution", "Evaluate technology stack: IoT, blockchain, AI/ML applicability", "Design pilot program with willing distribution partner"]'::jsonb, '["Drug Supply Chain Technology Landscape Map", "Track and Trace Implementation Guide for Indian market", "Cold Chain Technology Requirements by product category", "Supply Chain Platform Architecture Reference"]'::jsonb, 90, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Pharmacy Automation and Robotics', 'Pharmacy automation improves accuracy, efficiency, and compliance. Nascent in India but growing rapidly. Automation Categories: Dispensing Automation: Automated tablet counting and packing. Prescription verification systems. Reduce dispensing errors (2-5% manual error rate). ROI through labor efficiency. Storage and Retrieval: Automated storage systems for high-volume pharmacies. Carousel systems for hospital pharmacies. Temperature-controlled automated storage. Inventory accuracy improvement. Compounding Automation: IV preparation robots for hospital pharmacies. Sterile compounding accuracy. Reduced contamination risk. Regulatory compliance for compounding. Prescription Processing: OCR for prescription digitization. Drug-drug interaction checking. Automatic substitution suggestions. Integration with PMS and EHR. Market Reality in India: Limited adoption due to cost (Rs 20 lakh to Rs 5 crore per system). Hospital pharmacies early adopters. Pharmacy chains evaluating for high-volume stores. Service and maintenance infrastructure undeveloped. Opportunity: Lower-cost automation suitable for Indian market, refurbished equipment distribution, automation-as-a-service models.', '["Assess automation readiness of target pharmacy segment", "Research available automation solutions and their India applicability", "Calculate ROI model for pharmacy automation investment", "Identify potential early adopter customers for pilot"]'::jsonb, '["Pharmacy Automation Technology Overview with cost-benefit analysis", "Hospital Pharmacy Automation Case Studies from India", "Automation ROI Calculator for different pharmacy types", "Automation Vendor Directory with India service capabilities"]'::jsonb, 90, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'E-Pharmacy and Digital Pharmacy Models', 'E-pharmacy represents fastest-growing segment in pharmacy tech with market at Rs 10,000+ crore. Business Models: Marketplace Model (1mg, PharmEasy, Netmeds): Platform connecting patients with licensed pharmacies. Commission on orders (15-20%). Logistics and fulfillment services. Customer acquisition and retention. Inventory-Led Model (Apollo Pharmacy, MedPlus online): Own inventory and fulfillment. Better margin control (25-30% gross). Higher capital requirement. Quality and availability assurance. Hybrid Models: Mix of own fulfillment and marketplace. Metro cities inventory-led, Tier 2/3 marketplace. Subscription services for chronic patients. B2B Focus (Medkart, mStock): Supplying to retail pharmacies. Better unit economics than B2C. Relationship-based sales. Technology and Services Differentiators: AI-powered drug substitution (generic recommendations). Prescription reminder services. Chronic disease management programs. Same-day and express delivery. Integration with telemedicine for seamless experience. Regulatory Status: Operating under existing D&C framework. Draft e-pharmacy rules awaited. State-wise license requirements. Schedule H/H1 prescription verification mandated.', '["Analyze unit economics of different e-pharmacy models", "Define your e-pharmacy differentiation strategy", "Build prescription verification and compliance workflow", "Create technology roadmap for e-pharmacy platform"]'::jsonb, '["E-Pharmacy Business Model Comparison with economics", "E-Pharmacy Regulatory Compliance Checklist", "Prescription Verification System Requirements", "E-Pharmacy Technology Architecture Reference"]'::jsonb, 90, 75, 4, NOW(), NOW());

    -- ========================================
    -- MODULE 8: Diagnostic Technology (Days 36-40)
    -- ========================================
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (
        gen_random_uuid()::text,
        v_product_id,
        'Diagnostic Technology Solutions',
        'Build diagnostic technology solutions - understanding laboratory information systems, point-of-care testing, AI-powered diagnostics, home testing devices, and the regulatory pathway for diagnostic products in India.',
        7,
        NOW(),
        NOW()
    )
    RETURNING id INTO v_mod_8_id;

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt")
    VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'India Diagnostics Market Overview', 'India diagnostics market is Rs 90,000 crore growing 12% annually, highly fragmented with 100,000+ laboratories. Market Segments: Pathology Labs (70% of market): Standalone labs, hospital labs, chain labs. Tests: Blood tests, urine analysis, histopathology. Key players: Dr Lal PathLabs, Metropolis, Thyrocare, SRL. Imaging Centers (25%): X-ray, ultrasound, CT, MRI, PET. Capital intensive, concentrated in urban areas. Key chains: Mahajan Imaging, teleradiology emerging. Point-of-Care (5% but fastest growing): Near-patient testing, rapid diagnostics. Growth driven by COVID awareness, home testing interest. Opportunity in Tier 2/3 access. Market Structure: Organized chains: 15% of revenue, 5% of labs. Standalone labs: 85% of revenue, 95% of labs. Hospital labs: Captive for inpatient, some outpatient services. Technology Gaps: LIMS penetration 20% in standalone labs. Quality management largely manual. Digital reporting limited. Inter-lab connectivity minimal. Regulatory Framework: Clinical Establishment Act (state-adopted). NABL accreditation voluntary but preferred. CDSCO regulation for diagnostic devices.', '["Research diagnostics market size and segmentation in target geography", "Identify technology gaps in lab operations", "Map competitive landscape of lab technology providers", "Define target customer segment for your solution"]'::jsonb, '["India Diagnostics Market Report with regional analysis", "Lab Technology Adoption Study by segment", "Diagnostic Tech Competitive Landscape Map", "Regulatory Framework for Diagnostic Labs"]'::jsonb, 90, 50, 0, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Laboratory Information Management Systems', 'LIMS automates laboratory operations from sample collection to report delivery. Market Rs 400 crore, growing 18% annually. Core LIMS Features: Sample Management: Registration, accessioning, tracking, storage. Barcode/RFID integration. Chain of custody documentation. Test Processing: Worklist generation, instrument interfacing, result entry, validation. Auto-calculation of derived values. Reference range management. Quality Control: QC sample tracking, Levey-Jennings charts, Westgard rules. Proficiency testing management. NABL documentation support. Reporting: Report generation, digital delivery (email, app, portal). Critical value alerts. Cumulative patient history. Integration: Billing system, HIS integration, instrument interfaces, ABDM connectivity. Market Segmentation: Enterprise LIMS: Rs 10-50 lakh, large chains and hospital networks. Mid-market LIMS: Rs 2-10 lakh, medium labs and hospitals. Cloud LIMS: Rs 5,000-20,000/month SaaS, small and standalone labs. India-Specific Requirements: Multi-branch operation support. Regional language reports. Offline capability for connectivity issues. GST compliance. NABL accreditation workflows.', '["Evaluate LIMS solutions available in Indian market", "Define feature requirements for target lab segment", "Design integration architecture with instruments and external systems", "Create implementation and pricing strategy"]'::jsonb, '["LIMS Feature Comparison for 10+ solutions", "Lab Workflow Analysis Template", "LIMS Integration Requirements by instrument type", "LIMS Pricing and Business Model Guide"]'::jsonb, 90, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Point-of-Care and Home Testing', 'Point-of-care testing (POCT) and home testing represent fastest-growing diagnostic segments, accelerated by COVID-19. POCT Categories: Glucose Testing: Glucometers ubiquitous, CGM emerging. Market Rs 3,000 crore. Players: Accu-Chek, OneTouch, Indian brands emerging. Cardiac Markers: Troponin, BNP for emergency diagnosis. Hospital and clinic POC use. Critical for chest pain evaluation. Pregnancy and Fertility: Home pregnancy tests (Rs 1,500 crore market). Ovulation tracking devices emerging. Infectious Disease: Rapid tests for malaria, dengue, HIV. COVID rapid tests normalized home testing. Regulatory pathway: In-vitro diagnostics under CDSCO. Home Testing Opportunity: COVID normalized self-testing behavior. Growing interest in preventive health monitoring. Connected devices enabling remote monitoring. Challenges: Accuracy vs lab testing, user error, interpretation support. Technology Components: Lateral flow assays (paper-based rapid tests). Biosensors (electrochemical, optical). Reader devices and smartphone integration. Connected platforms for data capture and trending. Regulatory Pathway: In-vitro diagnostic medical devices under MDR 2017. Classification typically Class B or C depending on test criticality. Home use requires additional usability and instruction validation.', '["Identify POCT or home testing opportunity aligned with capabilities", "Research regulatory pathway for your diagnostic device class", "Design clinical validation study for accuracy claims", "Create go-to-market strategy: B2C direct, B2B to clinics, or both"]'::jsonb, '["POCT Market Analysis by test category", "IVD Regulatory Pathway Guide for India", "Clinical Validation Study Design for Diagnostics", "Home Testing Go-to-Market Strategies"]'::jsonb, 90, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'AI-Powered Diagnostics', 'AI/ML is transforming diagnostics through automated interpretation, pattern recognition, and decision support. Key Application Areas: Radiology AI: X-ray, CT, MRI interpretation assistance. Tuberculosis screening from chest X-ray (Qure.ai). Mammography analysis. Fracture detection. Pathology AI: Digital pathology image analysis. Cancer grading and classification. Rare disease identification. Workflow efficiency improvement. Dermatology AI: Skin lesion analysis from images. Melanoma detection. Telemedicine integration. Consumer apps for screening. Ophthalmology AI: Diabetic retinopathy screening. Glaucoma detection. AMD identification. Retinal imaging analysis. Clinical Chemistry AI: Predictive diagnostics from lab patterns. Risk scoring from multi-parameter analysis. Anomaly detection in results. Regulatory Considerations: SaMD classification applies to diagnostic AI. Clinical validation requirements significant. CDSCO guidance evolving. FDA and CE pathways may be required for credibility/export. Business Models: SaaS to diagnostic centers. Per-read pricing for radiology. White-label to diagnostic chains. B2C screening apps (consumer wellness positioning).', '["Identify diagnostic AI opportunity matching your capabilities", "Assess training data availability and quality", "Design clinical validation approach for regulatory approval", "Evaluate build vs partner vs license strategies"]'::jsonb, '["Diagnostic AI Market Analysis with application areas", "AI SaMD Regulatory Pathway for India", "Training Data Requirements for Medical AI", "Diagnostic AI Business Model Options"]'::jsonb, 90, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Diagnostic Network and Aggregator Platforms', 'Diagnostic aggregator platforms connect patients with laboratories, improving access and convenience. Market Models: Consumer Aggregators (1mg, PharmEasy Labs, Practo): Patient-facing platforms offering lab test booking. Partner network of NABL/CAP accredited labs. Home collection services. Competitive pricing through aggregation. B2B Platforms: Connecting hospitals/clinics with reference labs. Sample logistics and report integration. Volume-based pricing. Quality assurance coordination. Franchise Models: Branded collection center networks. Standardized processes and quality. Local entrepreneur ownership. Centralized testing in regional labs. Technology Requirements: Lab partner management and onboarding. Pricing and scheme management. Sample collection scheduling and logistics. Report aggregation and delivery. Quality monitoring dashboards. Revenue Models: Commission on test booking (15-25%). Subscription for premium services. B2B pricing for hospital integrations. Value-added services (health packages, consultations). Key Success Factors: Lab partner quality and network coverage. Pricing competitiveness. Collection convenience and reliability. Report turnaround time. Customer experience in booking and results.', '["Analyze existing diagnostic aggregator platforms", "Define target geography and lab partner strategy", "Design technology platform for lab network management", "Create unit economics model for diagnostic marketplace"]'::jsonb, '["Diagnostic Aggregator Business Model Analysis", "Lab Partner Onboarding Framework", "Sample Logistics Operations Guide", "Diagnostic Platform Technology Requirements"]'::jsonb, 90, 75, 4, NOW(), NOW());

    -- ========================================
    -- MODULE 9: Hospital Management (Days 41-45)
    -- ========================================
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (
        gen_random_uuid()::text,
        v_product_id,
        'Hospital Management Systems',
        'Build hospital management technology - understanding Hospital Information Systems, Electronic Health Records, clinical workflows, revenue cycle management, and digital transformation in Indian healthcare facilities.',
        8,
        NOW(),
        NOW()
    )
    RETURNING id INTO v_mod_9_id;

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt")
    VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'Hospital Technology Landscape', 'India has 70,000+ hospitals with varying technology adoption levels. Technology adoption correlates strongly with hospital size and accreditation. Hospital Segments: Corporate Chains (5%): Apollo, Fortis, Max, Manipal - fully digitized, enterprise systems. Multi-specialty (10%): 100-300 beds, varied adoption, upgrade cycle active. Single-specialty (15%): Eye, cardiac, ortho - specialized workflows, moderate tech. Small Hospitals (30%): 20-50 beds, basic or no HIS, manual processes. Nursing Homes (40%): 10-20 beds, largely undigitized, paper records. Technology Categories: HIS/HMS (Hospital Information/Management System): Core operational system. EHR/EMR: Clinical documentation and patient records. LIMS/PACS: Laboratory and imaging systems. Pharmacy: Inventory, dispensing, billing. Finance: Billing, accounting, revenue cycle. Departmental: OT management, nursing, dietary. Market Size: Rs 2,500 crore for hospital IT, growing 15% annually. 60% of hospitals have no HIS, massive greenfield opportunity. Government: NHA pushing digitization through AB-PMJAY requirements.', '["Assess hospital technology adoption in target segment", "Identify specific pain points driving technology decisions", "Map competitive landscape of hospital IT providers", "Define value proposition for target hospital segment"]'::jsonb, '["Hospital IT Market Analysis by segment", "Technology Adoption Study by hospital type", "Hospital IT Competitive Landscape", "Hospital Buyer Persona Guide"]'::jsonb, 90, 50, 0, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Hospital Information System Architecture', 'Hospital Information System (HIS) is the central nervous system of hospital operations. Understanding architecture is essential for building or integrating with HIS. Core Modules: Registration and Admission: Patient registration, bed management, admission/discharge/transfer. OPD Management: Appointment scheduling, queue management, consultation workflow. IPD Management: Ward management, nursing documentation, physician orders. Clinical Documentation: History, examination, diagnosis, treatment notes, discharge summary. Order Management: Lab orders, radiology orders, pharmacy orders, procedure orders. Billing: Charge capture, tariff management, insurance processing, patient billing. Integration Architecture: Interface Engine: HL7/FHIR messaging for system integration. API Gateway: RESTful APIs for external application access. Database: Typically relational (PostgreSQL, MySQL, Oracle) for transactional data. Data Warehouse: Analytics and reporting data store. Document Management: Medical records, scanned documents, multimedia. Deployment Models: On-Premise: Hospital-owned infrastructure, preferred by large hospitals. Cloud/SaaS: Subscription model, growing acceptance in mid-market. Hybrid: Core on-premise, ancillary services in cloud. India-Specific Requirements: Multi-branch operations, Aadhaar integration, AB-PMJAY claims, GST compliance, ABDM readiness.', '["Study HIS architecture patterns and best practices", "Define integration requirements with existing hospital systems", "Design scalable architecture for your target market segment", "Plan deployment model appropriate for customer preferences"]'::jsonb, '["HIS Architecture Reference Guide", "Healthcare Integration Standards Overview", "Cloud vs On-Premise Decision Framework for Healthcare", "India Healthcare Compliance Requirements for IT"]'::jsonb, 90, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'Electronic Health Records Implementation', 'EHR/EMR implementation is the foundation for digital healthcare delivery and data-driven medicine. EHR Core Components: Patient Chart: Demographics, allergies, medications, problem list, immunizations. Clinical Documentation: Progress notes, assessment, plans - structured and narrative. Order Entry: CPOE (Computerized Physician Order Entry) for labs, meds, procedures. Results Review: Lab results, imaging reports, consult notes. Care Plans: Protocol-based care pathways, care coordination. Population Health: Registries, chronic disease management, preventive care tracking. Implementation Challenges: Physician Adoption: Workflow disruption, documentation burden, training needs. Data Migration: Converting paper records, legacy system data. Customization: Specialty-specific workflows, Indian clinical practices. Integration: Lab instruments, imaging systems, existing departmental systems. Cost: License, implementation, training, ongoing support. Success Factors: Executive sponsorship and clinical champion network. Phased implementation with quick wins. Continuous training and support. Feedback loops for optimization. Realistic timeline expectations (12-24 months typical). ABDM Integration: ABHA ID linking for patient identification. Care context creation for each encounter. FHIR data formatting for interoperability. Consent management for health information exchange.', '["Assess EHR readiness of target hospital segment", "Design implementation methodology for your solution", "Plan physician adoption and training approach", "Create ABDM integration roadmap for EHR product"]'::jsonb, '["EHR Implementation Best Practices Guide", "Clinical Workflow Analysis Methodology", "Physician EHR Adoption Strategies", "ABDM Integration Guide for EHR Systems"]'::jsonb, 90, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'Revenue Cycle Management Technology', 'Revenue Cycle Management (RCM) technology addresses the financial operations of healthcare, a Rs 500 crore opportunity growing 20% annually. RCM Components: Charge Capture: Automated capture of billable services from clinical documentation. Insurance Eligibility: Real-time verification of patient coverage. Claims Processing: Claim generation, submission, tracking for insurers and government schemes. Denial Management: Tracking denials, root cause analysis, appeal management. Patient Billing: Statement generation, payment plans, collection. Analytics: Revenue leakage identification, payer performance, AR aging. India-Specific Challenges: Multiple Payers: Insurance companies (50+), TPAs (30+), government schemes (AB-PMJAY, state schemes). Claim Complexity: Each payer has different formats, requirements, timelines. Manual Processes: Many hospitals still paper-based claims. Low Collection Rates: 85-90% typical vs 95%+ in mature markets. Government Schemes: AB-PMJAY: 1,900+ treatment packages, HBP (Health Benefit Packages) compliance, e-claims mandatory. CGHS/ECHS: Government employee schemes with specific rates. State Schemes: Variable requirements by state. Technology Opportunity: Claim scrubbing and validation before submission. Automated denial analysis and resubmission. Real-time eligibility and pre-authorization. Predictive analytics for revenue optimization.', '["Understand RCM pain points in target hospital segment", "Map payer landscape: insurers, TPAs, government schemes", "Design claim management workflow for your solution", "Create integration plan with hospital billing systems"]'::jsonb, '["RCM Technology Market Analysis for India", "Payer Integration Requirements Directory", "AB-PMJAY Claims Technology Guide", "RCM Analytics Framework for Healthcare"]'::jsonb, 90, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'Hospital Digital Transformation', 'Digital transformation in hospitals goes beyond IT systems to fundamentally change care delivery, operations, and patient experience. Transformation Pillars: Patient Experience: Digital front door (web, app) for appointment, information. Self-service kiosks for registration, payment. Real-time communication on wait times, results. Post-visit engagement and feedback. Clinical Transformation: Decision support integrated in workflow. AI/ML for diagnosis assistance, risk prediction. Telemedicine integration for remote consultations. Connected devices for continuous monitoring. Operational Excellence: IoT for asset tracking, equipment monitoring. Predictive maintenance for critical equipment. Supply chain optimization. Energy and facility management. Data-Driven Insights: Clinical analytics for quality improvement. Operational dashboards for efficiency. Financial analytics for performance management. Population health insights. Implementation Approach: Assessment: Current state evaluation, gap analysis, opportunity identification. Roadmap: Prioritized initiatives with timeline, investment, expected outcomes. Foundation: Core HIS/EHR as platform, data infrastructure, integration layer. Quick Wins: High-impact, low-complexity initiatives for early momentum. Scale: Enterprise-wide deployment, continuous optimization. Change Management: Leadership alignment and communication. Staff training and support. Incentive alignment with transformation goals. Continuous feedback and adaptation.', '["Conduct digital maturity assessment for target hospitals", "Define transformation roadmap with prioritized initiatives", "Design change management approach for digital adoption", "Create business case demonstrating transformation ROI"]'::jsonb, '["Hospital Digital Maturity Assessment Framework", "Digital Transformation Roadmap Template", "Healthcare Change Management Guide", "Digital Transformation ROI Calculator"]'::jsonb, 90, 75, 4, NOW(), NOW());

    -- ========================================
    -- MODULE 10: HealthTech Funding (Days 46-50)
    -- ========================================
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (
        gen_random_uuid()::text,
        v_product_id,
        'HealthTech Funding Strategies',
        'Navigate HealthTech funding landscape - understanding investor types, sector-specific due diligence, pitch strategies, grant opportunities, and building investor relationships for healthcare ventures.',
        9,
        NOW(),
        NOW()
    )
    RETURNING id INTO v_mod_10_id;

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt")
    VALUES
    (gen_random_uuid()::text, v_mod_10_id, 46, 'HealthTech Investor Landscape', 'HealthTech funding in India has matured with dedicated healthcare investors and increasing generalist interest. Understanding investor landscape is critical for efficient fundraising. Investor Categories: Healthcare-Focused VCs: HealthQuad ($150M AUM), Healthx Capital, Alkemi Partners. Deep sector expertise, longer investment horizons. Typical checks $2-15M. Portfolio synergies valuable. Generalist VCs with Healthcare: Sequoia, Lightspeed, Chiratae, Accel. Larger funds, can write bigger checks. Healthcare as one of many sectors. Require larger market opportunities. Corporate VCs/Strategic: Pharma CVCs (Cipla, Lupin), Hospital CVCs, Insurance innovation teams. Strategic angle alongside financial. Partnership opportunities pre/post investment. Longer decision timelines. Impact Investors: Omidyar, Elevar, Aavishkaar. Healthcare access thesis. Patient capital, longer horizons. Impact metrics alongside financial. Angels and Family Offices: Healthcare executives and doctors as angels. Family offices with healthcare interest. Earlier stage, relationship-driven. Can provide credibility and connections. Investment Trends: Digital health: Telemedicine, e-pharmacy, remote monitoring. Med-tech: Diagnostics, medical devices, AI/ML. Infrastructure: Hospital chains, diagnostic chains. Enablers: RCM, analytics, workflow software.', '["Create target investor list by category and stage fit", "Research portfolio companies and investment thesis of key investors", "Identify warm introduction paths through network mapping", "Track investor activity through deal announcements"]'::jsonb, '["HealthTech Investor Database with 100+ investors", "Investor Thesis Analysis for healthcare-focused funds", "Introduction Path Mapping Framework", "Investor Activity Tracker Template"]'::jsonb, 90, 50, 0, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 47, 'HealthTech Pitch and Due Diligence', 'HealthTech pitch and due diligence have sector-specific elements beyond standard startup evaluation. Understanding these enables better preparation. HealthTech Pitch Essentials: Problem Statement: Quantify healthcare problem (lives affected, cost burden, access gaps). Clinical credibility in problem definition. Team: Healthcare domain expertise (clinician, healthcare exec). Technical capability for solution. Track record in healthcare. Solution: Clinical validity and evidence base. Regulatory pathway clarity. Differentiation from existing solutions. Market: TAM/SAM/SOM with bottoms-up validation. Payer analysis (who pays: patient, insurer, government, employer). Competitive landscape and positioning. Traction: Clinical outcomes if applicable. Revenue/user metrics. Partnership/pilot success. Regulatory progress. Due Diligence Areas: Clinical Validation: Evidence base for claims. Study design and statistical validity. Comparison with alternatives. Expert clinical opinion. Regulatory: Pathway assessment for required approvals. Timeline and cost estimates. Compliance infrastructure readiness. IP and Legal: Patent portfolio if applicable. Regulatory exclusivity. Liability considerations. Technology: Technical architecture review. Security and privacy assessment. Scalability evaluation.', '["Develop HealthTech-specific pitch deck addressing sector concerns", "Prepare clinical validation summary and evidence package", "Create regulatory pathway document with timeline", "Build data room with DD-ready documentation"]'::jsonb, '["HealthTech Pitch Deck Template with sector-specific slides", "Clinical Evidence Summary Format for investors", "Regulatory Pathway Document Template", "Data Room Checklist for HealthTech DD"]'::jsonb, 90, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 48, 'Grants and Non-Dilutive Funding', 'Grants provide non-dilutive capital for healthcare innovation, particularly valuable for early-stage and R&D-intensive ventures. Major Grant Sources in India: BIRAC (Biotechnology Industry Research Assistance Council): BIG Scheme: Up to Rs 50 lakh for proof-of-concept. SBIRI: Up to Rs 1 crore for product development. BIPP: Up to Rs 5 crore for commercialization. Focus: Biotech, med-tech, diagnostics. DBT (Department of Biotechnology): Research grants through institutions. Industry partnership programs. Centers of excellence funding. DST (Department of Science and Technology): Technology development programs. NIDHI scheme for incubators. TDB (Technology Development Board): Soft loans and grants for commercialization. Support for technology transfer. International Sources: Grand Challenges: Gates Foundation supported programs. Wellcome Trust: Clinical research and capacity building. PATH: Global health innovation grants. USAID: Development Innovation Ventures. Application Strategy: Align project with funder priorities. Build consortium if required. Demonstrate clear milestones and outcomes. Budget realistically with appropriate justification. Plan for compliance and reporting requirements.', '["Identify grant programs aligned with your HealthTech venture", "Develop grant-ready project proposal", "Build relationships with grant program managers", "Create grant compliance and reporting infrastructure"]'::jsonb, '["Healthcare Grant Programs Directory for India", "BIRAC Application Guide with Tips", "Grant Proposal Template for HealthTech", "Grant Compliance Requirements Summary"]'::jsonb, 90, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 49, 'Strategic Partnerships and Corporate Investment', 'Strategic investors provide capital plus partnership value critical for healthcare ventures. Understanding strategic motivations enables better positioning. Strategic Investor Types: Pharmaceutical Companies: Interest: Digital health, patient engagement, RWE, companion diagnostics. Examples: Cipla Health Ventures, Lupin Ventures. Value: Distribution, clinical expertise, regulatory support. Process: Innovation teams, CVC, BD partnerships. Hospital Chains: Interest: Patient experience, operational efficiency, care coordination. Examples: Apollo investments in Practo, Navia. Value: Pilot sites, customer access, clinical validation. Process: Innovation programs, direct investment. Insurance Companies: Interest: Cost reduction, fraud prevention, customer engagement. Examples: HDFC Life investments, ICICI Lombard partnerships. Value: Customer access, underwriting data, distribution. Process: Innovation teams, accelerator programs. Medical Device Multinationals: Interest: Digital capabilities, India market access, innovation. Examples: Philips, GE Healthcare innovation programs. Value: R&D resources, global distribution, regulatory expertise. Process: Innovation challenges, partnerships, acquisitions. Partnership Before Investment: Pilot programs to demonstrate value. Integration partnerships showing collaboration capability. Joint go-to-market for mutual benefit. Investment often follows successful partnership.', '["Identify strategic investors aligned with your business", "Develop partnership proposals demonstrating mutual value", "Engage innovation teams and corporate development", "Structure pilot programs as investment pathway"]'::jsonb, '["Strategic Investor Mapping for HealthTech", "Corporate Partnership Proposal Template", "Innovation Program Directory (Pharma, Hospital, Insurance)", "Strategic Investor Engagement Playbook"]'::jsonb, 90, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 50, 'HealthTech Exit Strategies', 'Understanding exit landscape informs fundraising strategy, investor selection, and business building. HealthTech exits in India are maturing. Exit Pathways: Strategic Acquisition: Most common exit for HealthTech. Acquirers: Pharma companies, hospital chains, insurance, global healthcare IT. Recent examples: Tata-1mg ($450M), PharmEasy-Thyrocare. Valuation: Revenue multiples, strategic premium for capabilities. IPO: Emerging option for scaled ventures. Recent: Vijaya Diagnostics, Metropolis, Dr Lal PathLabs. Requirements: Rs 500 Cr+ revenue, profitability path, governance. Process: 18-24 months preparation. Secondary Sale: PE/growth investors buying out early VCs. Provides partial liquidity without full exit. Common at Series C+ stages. Exit Timing Considerations: Investor fund life (7-10 years typical). Strategic windows (consolidation waves, regulatory changes). Company maturity (growth, profitability, governance). Exit Preparation: Build acquirer relationships early. Maintain clean corporate structure. Document IP and regulatory assets. Prepare for due diligence continuously. Develop multiple exit pathway options.', '["Map potential acquirers for your HealthTech venture", "Build relationships with corporate development teams", "Prepare company for exit-readiness: governance, documentation", "Develop multi-pathway exit strategy"]'::jsonb, '["HealthTech M&A Landscape Analysis for India", "Acquirer Relationship Building Framework", "Exit Readiness Checklist for HealthTech", "Exit Valuation Benchmarks by Category"]'::jsonb, 90, 75, 4, NOW(), NOW());

    -- ========================================
    -- MODULE 11: Global Health Compliance (Days 51-55)
    -- ========================================
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (
        gen_random_uuid()::text,
        v_product_id,
        'Global Health Compliance',
        'Navigate international health regulations for global expansion - understanding FDA pathways, CE marking, international clinical trials, data privacy requirements, and building globally compliant health technology.',
        10,
        NOW(),
        NOW()
    )
    RETURNING id INTO v_mod_11_id;

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt")
    VALUES
    (gen_random_uuid()::text, v_mod_11_id, 51, 'US FDA Regulatory Pathways', 'FDA approval is often necessary for US market and provides global credibility. Understanding FDA pathways is essential for international expansion. FDA Product Categories: Drugs: NDA (New Drug Application) or ANDA (generic). 505(b)(2) pathway for modified drugs. IND required for clinical trials. Medical Devices: Class I: General controls, most exempt from 510(k). Class II: 510(k) premarket notification (most devices). Class III: PMA (Premarket Approval) for high-risk devices. De Novo: New device types without predicate. Software/SaMD: Regulatory framework evolving. FDA AI/ML guidance. SaMD Definition Framework adopted. Digital health software categories. 510(k) Process: Demonstrate substantial equivalence to predicate device. Timeline: 90-180 days typical. Requirements: Performance testing, biocompatibility (if applicable), software documentation. Cost: $12,000+ FDA fee, $50,000-200,000 total with testing. FDA Establishment Registration: Required before marketing. Annual registration and listing. Quality System Regulation (QSR) compliance. Subject to FDA inspection. India to US Strategy: Build for FDA from start (design controls, QSR compliance). Partner with US regulatory consultant. Consider FDA-recognized testing labs in India. Plan for FDA inspection readiness.', '["Determine FDA classification and pathway for your product", "Assess predicate devices for 510(k) if applicable", "Engage FDA regulatory consultant for pathway planning", "Build QSR-compliant quality system from start"]'::jsonb, '["FDA Device Classification Guide with pathway decision tree", "510(k) Submission Requirements Checklist", "FDA Regulatory Consultant Directory", "QSR Implementation Guide for Indian Companies"]'::jsonb, 90, 50, 0, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 52, 'EU MDR and CE Marking', 'CE marking enables European market access under Medical Device Regulation (MDR) 2017/745. Requirements have significantly increased under new MDR. MDR vs MDD Transition: MDR replaced MDD (Medical Device Directive) in May 2021. Higher classification for many devices. Increased clinical evidence requirements. Mandatory UDI (Unique Device Identification). Annual safety reporting. MDR Classification: Class I: Low risk, self-declaration possible. Class IIa, IIb: Moderate risk, Notified Body required. Class III: High risk, full conformity assessment. SaMD reclassified upward under MDR. CE Marking Process: Technical Documentation: Essential requirements checklist, design documentation, risk management (ISO 14971), clinical evaluation. Quality Management System: ISO 13485 certification required for most classes. Notified Body Engagement: Select NB with capacity and relevant expertise. Audit scheduling challenge (NB capacity constrained). Conformity Assessment: Design examination, QMS audit, technical file review. CE Declaration: Manufacturer declaration of conformity. UDI Registration: EUDAMED database registration. Indian Company Approach: Establish EU Authorized Representative. Build ISO 13485 QMS. Engage Notified Body early (capacity limited). Plan 18-24 months for MDR certification.', '["Determine EU MDR classification for your device", "Select and engage Notified Body with relevant experience", "Build technical documentation per MDR requirements", "Plan clinical evidence strategy for EU approval"]'::jsonb, '["EU MDR Classification Guide with Rule Application", "Notified Body Selection Framework", "MDR Technical Documentation Template", "Clinical Evaluation Requirements under MDR"]'::jsonb, 90, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 53, 'International Clinical Trials', 'Global clinical trials require navigating multiple regulatory frameworks while maintaining consistency and quality. Multi-Country Trial Considerations: Regulatory: Different approval requirements by country. ICH-GCP as baseline standard. Local ethics committee requirements. Import permits for investigational products. Operational: Site selection based on patient population, expertise, infrastructure. Centralized vs local coordination. Language and cultural considerations. Data: Common protocol and CRF across countries. Data privacy compliance (GDPR, local requirements). Central data management with local access. Key Markets for Trials: US: FDA IND, IRB approval, strong IP protection. EU: Clinical Trial Regulation (CTR), Ethics Committee and CA approval. India: CT Rules 2019, CDSCO and EC approval. Japan: PMDA approval, unique requirements. India as Trial Site: Large, diverse patient population. Growing clinical trial infrastructure. Competitive costs (30-40% less than US/EU). English proficiency in medical community. CT Rules 2019 provides clarity. Challenges: Earlier requirements for trials in India regardless of global data. Compensation requirements for trial injuries. Data localization considerations. Global Trial Management: Central IRB/EC strategy where possible. Standardized training across sites. Central monitoring with local presence. Unified data management platform.', '["Develop multi-country clinical trial strategy", "Identify regulatory requirements for target markets", "Build global trial operations capability or partner", "Plan data management across jurisdictions"]'::jsonb, '["Multi-Country Trial Regulatory Matrix", "Global Trial Operations Framework", "ICH-GCP Compliance Checklist", "Clinical Trial Data Management Requirements by Region"]'::jsonb, 90, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 54, 'Global Health Data Privacy', 'Health data privacy requirements vary by jurisdiction, requiring flexible architecture for global compliance. Key Privacy Frameworks: HIPAA (US): Applies to covered entities and business associates. PHI (Protected Health Information) protection. Security Rule, Privacy Rule, Breach Notification. BAA (Business Associate Agreement) required. GDPR (EU): Broad application to EU data subjects. Health data as special category (Article 9). Consent or other legal basis required. Data subject rights (access, deletion, portability). DPDP Act (India): Personal data protection framework. Health data likely treated as sensitive. Consent-based processing. Data localization provisions. Cross-Border Data Transfer: GDPR: Standard contractual clauses, adequacy decisions. HIPAA: No specific transfer restrictions, but BAA required. India: Data localization requirements emerging. Privacy Engineering Approach: Privacy by Design: Build privacy into architecture. Data Minimization: Collect only necessary data. Access Controls: Role-based, need-to-know basis. Encryption: At rest and in transit. Audit Logging: Track all data access. Consent Management: Granular, documented consent. Global Compliance Architecture: Modular architecture adapting to jurisdiction. Consent management supporting multiple frameworks. Data residency options (EU, US, India). Unified privacy policy with regional supplements.', '["Map privacy requirements for target markets", "Design privacy-compliant data architecture", "Implement consent management across jurisdictions", "Develop privacy policy and documentation"]'::jsonb, '["Global Health Data Privacy Comparison Matrix", "Privacy Architecture Design Guide for Healthcare", "Consent Management System Requirements", "Cross-Border Data Transfer Mechanisms Guide"]'::jsonb, 90, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 55, 'Building Globally Compliant HealthTech', 'Building for global markets from the start enables efficient expansion while maintaining quality and compliance. Global-Ready Architecture: Regulatory: Design controls meeting FDA, MDR, CDSCO. Quality system aligned with ISO 13485 and QSR. Risk management per ISO 14971. Software lifecycle per IEC 62304. Technical: Multi-language support architecture. Data residency flexibility. Interoperability standards (HL7 FHIR, DICOM). Security certifications (SOC 2, ISO 27001). Operational: Documentation supporting multiple submissions. Clinical evidence strategy for multiple markets. Post-market surveillance across jurisdictions. Certification Strategy: Prioritize markets based on opportunity and complexity. Often: India first (home market), then US (510(k)), then EU (CE/MDR). Build capabilities incrementally, documentation reusable across markets. Consider mutual recognition and harmonization opportunities. Partnership Strategy: Local regulatory consultants in each market. Distributors with regulatory and commercial capabilities. Clinical trial CROs with multi-country experience. Quality assurance partners for ongoing compliance. Scaling Globally: Start with regulatory planning in product design. Build QMS supporting multiple frameworks. Develop clinical evidence meeting highest bar. Create modular documentation reusable across markets. Plan commercial operations aligned with regulatory timeline.', '["Develop global regulatory strategy with market prioritization", "Design architecture supporting multi-market compliance", "Build quality system meeting international standards", "Create partnership strategy for global expansion"]'::jsonb, '["Global Market Prioritization Framework for HealthTech", "Multi-Market Quality System Architecture", "Clinical Evidence Strategy for Global Approval", "Global Expansion Playbook for Medical Devices"]'::jsonb, 90, 75, 4, NOW(), NOW());

    RAISE NOTICE 'Modules 7-11 (Days 31-55) created successfully for P21';

END $$;

COMMIT;
