-- P20: FinTech Mastery Course Migration
-- 55 days, 11 modules, comprehensive FinTech regulatory and business framework

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
    v_mod_10_id TEXT;
    v_mod_11_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;
    v_mod_10_id := gen_random_uuid()::text;
    v_mod_11_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P20',
        'FinTech Mastery',
        'Complete FinTech regulatory and business framework - 11 modules covering RBI regulations, payment gateways, UPI, digital lending, NBFC registration, InsurTech, WealthTech, crypto/blockchain, Account Aggregator framework, security, and scaling. India is the world''s fastest-growing FinTech market.',
        8999,
        55,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P20';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: FinTech Landscape in India (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'FinTech Landscape in India', 'Understand India''s FinTech ecosystem, market size, key players, and emerging opportunities', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'India FinTech Market Overview', 'India''s FinTech market is valued at $50B+ and growing at 22% CAGR. Understand the ecosystem: payments, lending, insurance, wealth, banking. Learn about 2,100+ FinTech startups and $10B+ funding. Identify whitespace opportunities in Tier 2/3 cities and underserved segments.', '["Research India FinTech market size and growth projections", "Identify top 20 FinTech unicorns and their business models", "Map the FinTech value chain and your potential position", "Analyze 3 successful FinTech case studies"]'::jsonb, '{"templates": ["FinTech Market Analysis Template", "Competitive Landscape Map"], "tools": ["FinTech Ecosystem Database"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'FinTech Business Models', 'Master various FinTech business models: B2C, B2B, B2B2C, embedded finance, Banking-as-a-Service. Understand revenue models: transaction fees, interest spread, subscription, data monetization. Analyze unit economics and path to profitability.', '["Evaluate 5 FinTech business models for your idea", "Calculate potential revenue per user/transaction", "Design your FinTech business model canvas", "Identify key partnerships needed"]'::jsonb, '{"templates": ["FinTech Business Model Canvas", "Revenue Model Calculator"], "tools": ["Unit Economics Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'Regulatory Landscape Overview', 'Navigate India''s multi-regulator FinTech environment: RBI, SEBI, IRDAI, PFRDA. Understand licensing requirements by business type. Learn about regulatory sandbox programs. Prepare for compliance from Day 1.', '["Identify applicable regulators for your FinTech", "List all required licenses and registrations", "Research regulatory sandbox eligibility", "Create regulatory compliance roadmap"]'::jsonb, '{"templates": ["Regulatory Mapping Template", "License Requirements Checklist"], "tools": ["Regulator Contact Database"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'FinTech Funding Landscape', 'Access FinTech-focused VCs: Ribbit Capital, QED, Tiger Global, Sequoia. Understand sector-specific valuation metrics. Navigate due diligence for regulated businesses. Learn about strategic investors from banks and NBFCs.', '["Identify 20 FinTech-focused investors", "Prepare FinTech-specific pitch deck", "Understand valuation benchmarks", "Build relationships with strategic investors"]'::jsonb, '{"templates": ["FinTech Pitch Deck Template", "Investor Database"], "tools": ["Valuation Benchmark Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Building Your FinTech Team', 'Hire for regulated industries: compliance officers, risk managers, tech leads. Understand BFSI talent landscape and compensation. Build relationships with regulators. Create culture of compliance and innovation.', '["Define key roles for FinTech startup", "Research BFSI salary benchmarks", "Identify compliance officer requirements", "Design compliance-first culture"]'::jsonb, '{"templates": ["FinTech Org Chart Template", "Key Hire JD Library"], "tools": ["BFSI Salary Benchmarking"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: RBI Regulatory Framework (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'RBI Regulatory Framework', 'Master RBI regulations for payments, lending, and banking - licenses, compliance, and reporting requirements', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'RBI License Categories', 'Understand RBI license types: Payment Aggregator (PA), Payment Gateway, Prepaid Payment Instruments (PPI), NBFC categories. Learn net worth requirements, fit and proper criteria. Navigate application processes and timelines.', '["Identify correct RBI license for your business", "Review net worth and capital requirements", "Understand fit and proper criteria", "Create license application timeline"]'::jsonb, '{"templates": ["RBI License Comparison Matrix", "Application Checklist"], "tools": ["License Requirement Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'Payment Aggregator Guidelines', 'Master 2020 PA guidelines: registration requirements, net worth (Rs 15 Cr by March 2023, Rs 25 Cr by March 2025). Understand escrow requirements, nodal accounts, and settlement timelines. Implement merchant onboarding due diligence.', '["Review PA guidelines and amendments", "Plan capital raise for net worth requirements", "Design merchant onboarding process", "Set up escrow account structure"]'::jsonb, '{"templates": ["PA Compliance Checklist", "Merchant Onboarding SOP"], "tools": ["Settlement Timeline Tracker"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'Digital Lending Guidelines 2022', 'Navigate RBI''s Digital Lending Guidelines: LSP regulations, FLDG restrictions, disclosure requirements. Understand direct bank account disbursement rules. Implement transparent pricing and fair practices.', '["Review Digital Lending Guidelines in detail", "Assess LSP vs regulated entity path", "Design compliant lending workflow", "Create borrower disclosure templates"]'::jsonb, '{"templates": ["DL Guidelines Compliance Matrix", "Disclosure Templates"], "tools": ["Lending Flow Designer"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'KYC and AML Compliance', 'Implement Video-KYC (V-KYC) as per RBI guidelines. Understand PMLA requirements for FinTech. Build AML/CFT framework. Navigate cross-border transaction reporting.', '["Design V-KYC process flow", "Implement AML transaction monitoring", "Create STR/CTR reporting process", "Set up KYC refresh mechanisms"]'::jsonb, '{"templates": ["V-KYC Implementation Guide", "AML Policy Template"], "tools": ["Transaction Monitoring System"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'RBI Regulatory Sandbox', 'Apply to RBI Regulatory Sandbox for innovative products. Understand eligibility criteria and application process. Learn from previous cohort successes. Plan graduation from sandbox to full license.', '["Review RBI Sandbox eligibility criteria", "Prepare sandbox application", "Design limited pilot parameters", "Plan sandbox graduation strategy"]'::jsonb, '{"templates": ["Sandbox Application Template", "Pilot Design Framework"], "tools": ["Sandbox Tracker Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: Payment Gateway & UPI Integration (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'Payment Gateway & UPI Integration', 'Build and integrate payment solutions - UPI, cards, wallets, IMPS, NEFT, and international payments', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'UPI Deep Dive', 'Master UPI architecture: PSP, TPAP, and handle registration. Understand UPI 2.0 features: mandate, international payments, credit on UPI. Implement UPI Collect, Intent, and QR flows. Navigate NPCI certification requirements.', '["Study UPI technical specifications", "Choose PSP banking partner", "Design UPI integration architecture", "Plan NPCI certification timeline"]'::jsonb, '{"templates": ["UPI Integration Checklist", "PSP Comparison Matrix"], "tools": ["UPI Flow Simulator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'Payment Gateway Integration', 'Integrate leading PGs: Razorpay, PayU, Cashfree, Paytm. Understand PG pricing models and negotiation tactics. Implement failover and smart routing. Handle refunds, chargebacks, and disputes.', '["Compare top 5 payment gateways", "Negotiate PG pricing based on volume", "Design payment failover logic", "Create chargeback handling SOP"]'::jsonb, '{"templates": ["PG Comparison Template", "Integration Checklist"], "tools": ["Payment Success Rate Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'Card Payment Processing', 'Understand card payment ecosystem: acquirers, issuers, networks. Navigate PCI-DSS compliance requirements. Implement tokenization for recurring payments. Handle EMV 3DS authentication.', '["Assess PCI-DSS compliance scope", "Choose card tokenization approach", "Implement 3DS 2.0 authentication", "Design card-on-file workflow"]'::jsonb, '{"templates": ["PCI-DSS SAQ Guide", "Tokenization Implementation Plan"], "tools": ["Compliance Assessment Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'IMPS, NEFT, RTGS Integration', 'Implement bank transfer methods for different use cases. Understand IMPS limits, NEFT/RTGS timing, and NACH for recurring. Build account validation using penny drop and account aggregator.', '["Map payment method to use case", "Integrate bank account validation", "Set up NACH for recurring", "Design settlement reconciliation"]'::jsonb, '{"templates": ["Payment Method Selection Matrix", "NACH Integration Guide"], "tools": ["Bank Transfer Simulator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'International Payments', 'Navigate cross-border payment regulations under FEMA. Understand LRS limits and documentation. Integrate international payment gateways. Handle forex and compliance for inward remittances.', '["Review FEMA cross-border requirements", "Evaluate international PG options", "Design forex rate management", "Create cross-border compliance checklist"]'::jsonb, '{"templates": ["FEMA Compliance Checklist", "Cross-border Flow Design"], "tools": ["Forex Rate Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Digital Lending Platform (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Digital Lending Platform', 'Build compliant digital lending - credit scoring, underwriting, collections, and partner bank integration', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Digital Lending Business Models', 'Understand lending models: direct NBFC, LSP (co-lending), marketplace, embedded finance. Evaluate capital efficiency and regulatory requirements. Choose model based on your strengths and risk appetite.', '["Evaluate lending business models", "Calculate capital requirements per model", "Assess technology vs license trade-offs", "Design lending product suite"]'::jsonb, '{"templates": ["Lending Model Comparison", "Product Design Template"], "tools": ["Capital Requirement Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'Credit Scoring & Underwriting', 'Build alternative credit scoring using GST, bank statements, and bureau data. Understand CIBIL, Experian, CRIF integration. Implement ML-based underwriting models. Navigate bureau data access regulations.', '["Integrate credit bureau APIs", "Design alternative data scoring model", "Build underwriting decision engine", "Create credit policy framework"]'::jsonb, '{"templates": ["Credit Scoring Model Template", "Underwriting Policy"], "tools": ["Credit Score Simulator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'Loan Origination System', 'Build end-to-end loan origination: application, document collection, verification, approval, disbursement. Implement digital agreement signing. Design loan management system.', '["Design loan application journey", "Implement e-KYC and document verification", "Set up e-sign integration", "Build loan disbursement workflow"]'::jsonb, '{"templates": ["LOS Requirements Document", "Loan Journey Map"], "tools": ["LOS Platform Comparison"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Collections & Recovery', 'Design compliant collections processes per RBI guidelines. Implement digital collections: auto-debit, reminders, payment links. Handle NPA management and recovery. Navigate DRA (Debt Recovery Agent) regulations.', '["Create collections policy and SOP", "Implement auto-debit mandates", "Design NPA monitoring dashboard", "Set up recovery tracking system"]'::jsonb, '{"templates": ["Collections Policy Template", "NPA Management Framework"], "tools": ["Collections Dashboard"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Partner Bank Integration', 'Navigate bank partnership for co-lending (CLM). Understand FLDG restrictions and alternatives. Integrate with bank CBS for disbursement and collections. Manage bank compliance requirements.', '["Identify potential co-lending partners", "Understand CLM guidelines", "Design bank integration architecture", "Negotiate partnership terms"]'::jsonb, '{"templates": ["Bank Partnership Proposal", "Integration Checklist"], "tools": ["Partner Bank Comparison"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: NBFC Registration & Compliance (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'NBFC Registration & Compliance', 'Complete NBFC registration process, ongoing compliance, and scale-up regulatory requirements', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'NBFC Categories & Selection', 'Understand NBFC categories: NBFC-ICC, NBFC-MFI, NBFC-P2P, NBFC-AA, HFC. Learn eligibility criteria for each category. Assess which category fits your business model. Understand scale-based regulation (Base, Middle, Upper Layer).', '["Analyze NBFC categories for fit", "Review minimum NOF requirements", "Understand activity restrictions", "Plan NBFC registration strategy"]'::jsonb, '{"templates": ["NBFC Category Comparison", "Eligibility Checklist"], "tools": ["NBFC Type Selector"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'NBFC Registration Process', 'Navigate RBI NBFC registration: COSMOS portal, document requirements, capital adequacy. Understand timeline expectations (6-12 months). Prepare for RBI inspection and interviews.', '["Gather NBFC application documents", "Register on COSMOS portal", "Prepare management profiles", "Create compliance infrastructure"]'::jsonb, '{"templates": ["NBFC Application Checklist", "Document Preparation Guide"], "tools": ["Application Tracker"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'NBFC Capital & Prudential Norms', 'Maintain capital adequacy (minimum 15% CRAR). Understand asset classification and provisioning norms. Implement concentration norms and exposure limits. Navigate leverage and borrowing restrictions.', '["Calculate CRAR requirements", "Set up asset classification system", "Design exposure monitoring", "Create capital planning roadmap"]'::jsonb, '{"templates": ["CRAR Calculator", "Provisioning Template"], "tools": ["Capital Adequacy Dashboard"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'NBFC Compliance & Reporting', 'Submit regulatory returns: NBS-7, ALM, quarterly returns. Implement Fair Practice Code. Handle RBI inspections and audits. Maintain required registers and records.', '["Set up regulatory reporting calendar", "Implement Fair Practice Code", "Create audit readiness checklist", "Design compliance monitoring system"]'::jsonb, '{"templates": ["Regulatory Return Templates", "Fair Practice Code Template"], "tools": ["Compliance Calendar"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Scaling NBFC Operations', 'Plan for scale-based regulation upgrades. Prepare for deposit-taking status. Navigate merger and acquisition in NBFC space. Build investor-ready compliance documentation.', '["Plan layer upgrade strategy", "Evaluate deposit-taking feasibility", "Create M&A readiness checklist", "Build compliance data room"]'::jsonb, '{"templates": ["NBFC Scaling Roadmap", "Layer Upgrade Checklist"], "tools": ["Scale Planning Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: InsurTech Framework (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'InsurTech Framework', 'Navigate IRDAI regulations for insurance distribution, aggregation, and product innovation', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'InsurTech Business Models', 'Understand InsurTech models: insurance aggregator, web aggregator, broker, corporate agent, insurance repository. Learn about embedded insurance and parametric products. Analyze successful InsurTech case studies: Policybazaar, Digit, Acko.', '["Evaluate InsurTech business models", "Analyze top 5 InsurTech players", "Identify whitespace opportunities", "Design InsurTech value proposition"]'::jsonb, '{"templates": ["InsurTech Model Comparison", "Business Model Canvas"], "tools": ["InsurTech Opportunity Analyzer"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'IRDAI Licensing Requirements', 'Navigate IRDAI licensing: insurance broker, web aggregator, corporate agent. Understand capital requirements and fit & proper criteria. Learn application process and timelines.', '["Identify correct IRDAI license type", "Review capital and qualification requirements", "Prepare license application documents", "Plan compliance infrastructure"]'::jsonb, '{"templates": ["IRDAI License Comparison", "Application Checklist"], "tools": ["License Requirement Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Insurance Distribution Compliance', 'Implement IRDAI distribution regulations: disclosure requirements, commission norms, point of sale persons (POSP). Navigate digital policy issuance requirements. Handle claims facilitation responsibilities.', '["Design compliant sales process", "Create disclosure documents", "Train POSPs as per IRDAI norms", "Set up claims assistance workflow"]'::jsonb, '{"templates": ["POSP Training Curriculum", "Disclosure Templates"], "tools": ["Commission Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Insurance Product Innovation', 'Develop innovative insurance products: sachet insurance, usage-based, parametric. Navigate IRDAI Sandbox for new products. Partner with insurers for product development. Implement micro-insurance strategies.', '["Design innovative insurance product concept", "Evaluate IRDAI Sandbox eligibility", "Identify insurer innovation partners", "Create product development roadmap"]'::jsonb, '{"templates": ["Product Innovation Template", "Sandbox Application Guide"], "tools": ["Product Design Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'InsurTech Technology Stack', 'Build insurance technology: underwriting automation, claims processing, policy administration. Implement telematics and IoT for UBI. Design customer experience for insurance. Integrate with insurer systems.', '["Design InsurTech technology architecture", "Evaluate policy admin systems", "Plan insurer integration approach", "Create claims automation workflow"]'::jsonb, '{"templates": ["InsurTech Architecture Template", "Integration Checklist"], "tools": ["Tech Stack Comparison"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: WealthTech & Investment Platforms (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'WealthTech & Investment Platforms', 'Build SEBI-compliant investment platforms - mutual funds, stocks, advisory, and portfolio management', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'WealthTech Business Models', 'Understand WealthTech models: mutual fund distributor, stock broker, RIA, PMS, AIF. Learn about robo-advisory and goal-based investing. Analyze Zerodha, Groww, Kuvera models.', '["Evaluate WealthTech business models", "Analyze unit economics of top players", "Identify target customer segment", "Design WealthTech value proposition"]'::jsonb, '{"templates": ["WealthTech Model Canvas", "Competitive Analysis Template"], "tools": ["WealthTech Opportunity Analyzer"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'SEBI Registration Requirements', 'Navigate SEBI registrations: stockbroker, investment adviser (IA), research analyst (RA), portfolio manager. Understand AMFI registration for MF distribution. Learn capital and qualification requirements.', '["Identify required SEBI registrations", "Review qualification requirements", "Prepare registration applications", "Plan compliance infrastructure"]'::jsonb, '{"templates": ["SEBI Registration Checklist", "Qualification Matrix"], "tools": ["Registration Fee Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Mutual Fund Distribution', 'Build MF distribution platform: AMFI registration, MFU/BSE STAR integration. Understand commission structures and trail income. Implement direct vs regular plan navigation. Design SIP and lumpsum workflows.', '["Complete ARN registration", "Integrate with MFU or BSE STAR", "Design investment journey", "Create investor education content"]'::jsonb, '{"templates": ["MF Distribution Checklist", "SIP Implementation Guide"], "tools": ["Commission Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Stock Broking Platform', 'Build discount broking platform: NSE/BSE membership or sub-broker model. Implement trading systems and risk management. Navigate SEBI margin rules and compliance. Design app-based trading experience.', '["Evaluate broker vs sub-broker model", "Understand exchange membership requirements", "Design trading technology stack", "Create risk management framework"]'::jsonb, '{"templates": ["Broking Platform Requirements", "Risk Management Policy"], "tools": ["Margin Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'Investment Advisory & PMS', 'Build RIA practice: SEBI IA registration, fee-only advisory model. Understand PMS regulations for HNI clients. Navigate advisory vs distribution conflict management. Implement suitability framework.', '["Evaluate IA vs PMS model", "Design advisory service offering", "Create suitability assessment process", "Build portfolio construction framework"]'::jsonb, '{"templates": ["IA Registration Checklist", "Suitability Framework"], "tools": ["Portfolio Analysis Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Crypto & Blockchain in India (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Crypto & Blockchain in India', 'Navigate crypto regulations, taxation, and blockchain applications in Indian context', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Crypto Regulatory Status in India', 'Understand current crypto legal status post Supreme Court verdict. Navigate 30% crypto tax and 1% TDS requirements. Learn about proposed Digital Rupee (CBDC). Monitor regulatory developments and potential legislation.', '["Review current crypto tax regulations", "Understand TDS compliance requirements", "Monitor Digital Rupee developments", "Assess regulatory risk for business model"]'::jsonb, '{"templates": ["Crypto Regulatory Tracker", "Tax Compliance Checklist"], "tools": ["Crypto Tax Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Crypto Exchange Operations', 'Understand crypto exchange requirements: PMLA compliance, KYC/AML. Navigate banking relationships for crypto businesses. Implement trade surveillance and reporting. Handle customer protection and custody.', '["Design KYC/AML framework for crypto", "Establish banking relationships", "Implement trade surveillance", "Create customer protection policies"]'::jsonb, '{"templates": ["Crypto AML Policy", "Custody Framework"], "tools": ["Trade Surveillance System"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Blockchain Enterprise Solutions', 'Build enterprise blockchain solutions: supply chain, trade finance, identity. Understand Hyperledger vs public blockchain choices. Navigate government blockchain initiatives. Design blockchain-based FinTech products.', '["Evaluate blockchain use cases for India", "Choose appropriate blockchain platform", "Identify enterprise pilot opportunities", "Design blockchain solution architecture"]'::jsonb, '{"templates": ["Blockchain Use Case Template", "Platform Comparison Matrix"], "tools": ["Blockchain ROI Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Digital Rupee (CBDC) Integration', 'Understand RBI Digital Rupee pilot program. Learn wholesale vs retail CBDC differences. Prepare for CBDC integration opportunities. Monitor international CBDC developments.', '["Study RBI CBDC pilot details", "Identify CBDC integration opportunities", "Understand programmable money features", "Plan CBDC readiness strategy"]'::jsonb, '{"templates": ["CBDC Integration Checklist", "Opportunity Assessment"], "tools": ["CBDC Feature Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Web3 and DeFi Considerations', 'Understand DeFi protocols and their regulatory challenges. Navigate NFT and tokenization regulations. Assess Web3 opportunities within Indian regulatory framework. Build compliant Web3 applications.', '["Analyze DeFi regulatory risks", "Evaluate NFT business opportunities", "Design compliant Web3 architecture", "Monitor global Web3 regulations"]'::jsonb, '{"templates": ["Web3 Compliance Framework", "DeFi Risk Assessment"], "tools": ["Regulatory Risk Analyzer"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: Account Aggregator Framework (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'Account Aggregator Framework', 'Leverage India''s Account Aggregator ecosystem for data-driven FinTech products', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'Account Aggregator Ecosystem', 'Understand AA framework: FIP, FIU, AA roles. Learn about DEPA (Data Empowerment and Protection Architecture). Analyze AA use cases: lending, wealth, insurance. Evaluate AA-enabled business models.', '["Study AA ecosystem architecture", "Identify FIP and FIU in your use case", "Analyze AA-based product opportunities", "Understand consent management"]'::jsonb, '{"templates": ["AA Ecosystem Map", "Use Case Template"], "tools": ["AA Partner Directory"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Becoming an FIU', 'Register as Financial Information User (FIU). Understand RBI NBFC-AA category for aggregators. Implement FIU integration with AA network. Design consent management workflows.', '["Evaluate FIU registration requirements", "Select AA technology provider", "Design consent request workflow", "Plan data security infrastructure"]'::jsonb, '{"templates": ["FIU Registration Checklist", "Integration Guide"], "tools": ["AA Tech Provider Comparison"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'AA-Based Lending Products', 'Build AA-powered lending: income verification, cash flow analysis, balance confirmation. Reduce fraud with real-time bank data. Implement instant underwriting using AA data.', '["Design AA-based credit assessment", "Build bank statement analyzer", "Create income verification workflow", "Implement fraud detection using AA"]'::jsonb, '{"templates": ["AA Credit Model Template", "Income Analysis Framework"], "tools": ["Bank Statement Analyzer"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'AA for Wealth Management', 'Aggregate investment holdings across institutions. Build consolidated portfolio views. Enable goal-based planning with complete financial picture. Implement AA for insurance and PFM.', '["Design investment aggregation service", "Build portfolio consolidation logic", "Create financial planning tools", "Implement cross-sell identification"]'::jsonb, '{"templates": ["Wealth AA Integration Guide", "Portfolio Aggregation Template"], "tools": ["Investment Analyzer"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'AA Consent & Security', 'Implement granular consent management as per AA protocol. Ensure data security and encryption requirements. Handle consent revocation and data deletion. Navigate cross-border data considerations.', '["Design consent UI/UX per AA guidelines", "Implement data encryption standards", "Create consent lifecycle management", "Build audit trail for data access"]'::jsonb, '{"templates": ["Consent Management Checklist", "Data Security Framework"], "tools": ["Consent Audit Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 10: FinTech Security & Fraud Prevention (Days 46-50)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_10_id, v_product_id, 'FinTech Security & Fraud Prevention', 'Build robust security infrastructure and fraud prevention systems for financial services', 10, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_10_id, 46, 'FinTech Security Framework', 'Implement security framework per RBI IT guidelines. Understand CERT-In reporting requirements. Design defense in depth architecture. Handle vulnerability management and penetration testing.', '["Review RBI IT security guidelines", "Design security architecture", "Plan penetration testing schedule", "Set up CERT-In reporting process"]'::jsonb, '{"templates": ["Security Policy Template", "IT Guidelines Compliance Matrix"], "tools": ["Security Assessment Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 47, 'Fraud Detection & Prevention', 'Build multi-layer fraud prevention: device fingerprinting, behavioral analytics, transaction monitoring. Implement real-time fraud scoring. Handle fraud investigation and recovery. Create fraud analytics dashboard.', '["Design fraud detection architecture", "Implement device fingerprinting", "Build transaction monitoring rules", "Create fraud investigation SOP"]'::jsonb, '{"templates": ["Fraud Prevention Framework", "Investigation Playbook"], "tools": ["Fraud Rule Builder"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 48, 'Cyber Insurance & Incident Response', 'Evaluate cyber insurance options for FinTech. Build incident response team and procedures. Create business continuity and disaster recovery plans. Handle customer communication during incidents.', '["Assess cyber insurance requirements", "Build incident response team", "Create DR/BCP plan", "Design incident communication templates"]'::jsonb, '{"templates": ["Incident Response Plan", "BCP Template"], "tools": ["Cyber Insurance Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 49, 'Data Protection & Privacy', 'Implement DPDP Act compliance for financial data. Design data classification and handling procedures. Navigate cross-border data transfer requirements. Build privacy-by-design architecture.', '["Assess DPDP Act applicability", "Classify financial data categories", "Design data handling procedures", "Create privacy impact assessment"]'::jsonb, '{"templates": ["DPDP Compliance Checklist", "Data Classification Matrix"], "tools": ["Privacy Assessment Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 50, 'Third-Party Risk Management', 'Manage vendor security for FinTech ecosystem. Implement API security and rate limiting. Navigate outsourcing guidelines from RBI. Build vendor assessment and monitoring framework.', '["Create vendor security questionnaire", "Implement API security measures", "Review RBI outsourcing guidelines", "Build vendor monitoring dashboard"]'::jsonb, '{"templates": ["Vendor Assessment Template", "API Security Checklist"], "tools": ["Vendor Risk Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 11: Scaling FinTech Operations (Days 51-55)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_11_id, v_product_id, 'Scaling FinTech Operations', 'Scale FinTech business - technology infrastructure, partnerships, expansion, and exit strategies', 11, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_11_id, 51, 'Technology Scaling', 'Scale FinTech infrastructure: cloud architecture, microservices, API-first design. Handle peak transaction volumes. Implement observability and monitoring. Optimize for latency in financial transactions.', '["Design cloud-native architecture", "Implement auto-scaling", "Set up comprehensive monitoring", "Plan for 10x volume growth"]'::jsonb, '{"templates": ["Tech Scaling Roadmap", "Architecture Design Template"], "tools": ["Infrastructure Cost Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 52, 'Strategic Partnerships', 'Build bank and NBFC partnerships for distribution. Navigate co-lending and API banking partnerships. Partner with ecosystem players: e-commerce, logistics. Implement embedded finance opportunities.', '["Identify strategic partnership opportunities", "Create partnership pitch deck", "Negotiate partnership terms", "Design integration architecture"]'::jsonb, '{"templates": ["Partnership Proposal Template", "Term Sheet Framework"], "tools": ["Partnership ROI Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 53, 'Geographic Expansion', 'Expand to Tier 2/3 India: vernacular interfaces, offline-online hybrid. Navigate international expansion regulations. Understand GIFT City opportunities for global FinTech. Plan multi-geography licensing.', '["Assess Tier 2/3 market opportunity", "Plan vernacular and offline strategy", "Evaluate GIFT City setup", "Create international expansion roadmap"]'::jsonb, '{"templates": ["Market Expansion Template", "GIFT City Guide"], "tools": ["Market Opportunity Analyzer"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 54, 'FinTech M&A Landscape', 'Understand FinTech M&A dynamics: acqui-hires, strategic acquisitions, consolidation. Navigate RBI approval for NBFC transactions. Build M&A-ready documentation and data room. Evaluate acquisition vs organic growth.', '["Analyze recent FinTech M&A deals", "Prepare M&A data room", "Understand RBI change of control approvals", "Create M&A readiness checklist"]'::jsonb, '{"templates": ["M&A Readiness Checklist", "Data Room Template"], "tools": ["Valuation Benchmark Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 55, 'IPO Readiness for FinTech', 'Prepare for public markets: SEBI IPO requirements, financial audits, corporate governance. Understand FinTech IPO case studies: Paytm, PolicyBazaar, Nykaa. Navigate pre-IPO funding rounds. Build investor relations capability.', '["Assess IPO readiness gaps", "Implement corporate governance standards", "Plan pre-IPO capital raise", "Build investor relations function"]'::jsonb, '{"templates": ["IPO Readiness Checklist", "Governance Framework"], "tools": ["IPO Timeline Planner"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
