-- P24: Manufacturing & Make in India Course Migration
-- 55 days, 11 modules, comprehensive manufacturing mastery for India

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
    v_mod_10_id TEXT;
    v_mod_11_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;
    v_mod_10_id := gen_random_uuid()::text;
    v_mod_11_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P24',
        'Manufacturing & Make in India Mastery',
        'Complete guide to manufacturing startups in India - 11 modules covering factory setup, PLI schemes, quality certifications, labor compliance, supply chain, SEZ benefits, export manufacturing, and Industry 4.0 automation. India targets $1 trillion manufacturing by 2025.',
        8999,
        55,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P24';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: Manufacturing Landscape (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'Manufacturing Landscape', 'Understand India''s manufacturing ecosystem - market size, key sectors, government initiatives, and opportunities', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'Make in India Overview', 'India''s manufacturing sector contributes 17% to GDP with target of 25% by 2025. Make in India launched in 2014 has attracted $130+ billion FDI. Key sectors: electronics (largest PLI), pharmaceuticals, automobiles, textiles, defence, and food processing. Understand the opportunity across 25 focus sectors and emerging manufacturing trends.', '["Study Make in India 25 sectors", "Identify 3 sectors aligned with your expertise", "Research sector-specific growth rates", "Map government support for each sector"]'::jsonb, '{"templates": ["Sector Analysis Framework", "Opportunity Assessment Matrix"], "tools": ["Manufacturing Sector Analyzer"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'India Manufacturing Advantages', 'Leverage India''s manufacturing strengths: 500+ million workforce, competitive labor costs ($1-3/hour vs $5-8 in China), growing domestic market of 1.4 billion consumers, improving infrastructure, and English-speaking talent. Understand the China+1 strategy driving manufacturing shift to India. Learn from success stories like Dixon, Amber, and Syrma.', '["Analyze labor cost competitiveness", "Calculate domestic market potential", "Study 5 successful Indian manufacturers", "Identify your competitive advantages"]'::jsonb, '{"templates": ["Competitive Advantage Canvas", "Manufacturing Cost Comparison"], "tools": ["Labor Cost Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'Government Manufacturing Initiatives', 'Navigate manufacturing support ecosystem: Make in India, PLI schemes (₹2 lakh crore), National Manufacturing Policy, MSME support (Udyam registration, credit schemes), and skill development programs. Understand ministry roles: DPIIT, Heavy Industries, MSME, Commerce. Map applicable schemes to your manufacturing plan.', '["List all applicable government schemes", "Understand ministry jurisdictions", "Complete Udyam registration", "Create scheme benefit roadmap"]'::jsonb, '{"templates": ["Government Scheme Navigator", "Ministry Contact Directory"], "tools": ["Scheme Eligibility Checker"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'Manufacturing Business Models', 'Choose your manufacturing model: OEM (own brand), contract manufacturing (CMO), original design manufacturing (ODM), or component supplier. Understand capital requirements, margins, and scale requirements for each model. Learn vertical integration strategies and when to outsource vs manufacture.', '["Evaluate all manufacturing models", "Calculate capital requirements", "Assess margin potential by model", "Define your manufacturing strategy"]'::jsonb, '{"templates": ["Business Model Comparison", "Capital Requirement Calculator"], "tools": ["Manufacturing Model Selector"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Manufacturing Startup Planning', 'Create comprehensive manufacturing startup plan. Define product scope, target market, and scale trajectory. Plan capital structure: equity, debt, and government incentives. Build timeline from planning to production. Understand typical manufacturing startup journey: 12-24 months to production.', '["Create manufacturing business plan", "Define 5-year scale trajectory", "Plan capital structure", "Build detailed project timeline"]'::jsonb, '{"templates": ["Manufacturing Business Plan Template", "Project Timeline Template"], "tools": ["Manufacturing Planning Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: Factory Setup (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'Factory Setup', 'Master factory planning - location selection, facility design, utilities, and statutory approvals', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'Location Selection Strategy', 'Choose optimal manufacturing location. Key factors: proximity to suppliers and customers, labor availability, infrastructure, state incentives, and land costs. Compare industrial hubs: Pune-Chakan (auto), Chennai-Sriperumbudur (electronics), Gujarat-Sanand (chemicals), UP-Noida (electronics). Evaluate industrial estates vs standalone land.', '["Create location selection criteria", "Score 5 potential locations", "Visit top 3 shortlisted sites", "Negotiate with state industrial development corporations"]'::jsonb, '{"templates": ["Location Scorecard", "Site Visit Checklist"], "tools": ["Location Comparison Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'Land Acquisition & Leasing', 'Navigate land acquisition in industrial areas. Options: MIDC (Maharashtra), GIDC (Gujarat), SIPCOT (Tamil Nadu), or private industrial parks. Understand lease vs purchase economics. Typical rates: ₹1,000-5,000/sqm in tier-2 cities, ₹5,000-15,000/sqm in metro areas. Handle title clearance and due diligence.', '["Identify land options in target location", "Conduct title due diligence", "Negotiate lease/purchase terms", "Plan phased land acquisition"]'::jsonb, '{"templates": ["Land Due Diligence Checklist", "Lease Agreement Template"], "tools": ["Land Cost Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'Facility Design & Construction', 'Design manufacturing facility for efficiency. Plan layout: production floor, warehouse, quality lab, utilities, office, and future expansion. Understand building specifications: floor load capacity, height, ventilation. Choose between pre-engineered buildings (PEB) for faster construction or RCC for flexibility. Budget construction: ₹2,500-4,500/sqft for PEB.', '["Create facility layout design", "Get quotes for PEB vs RCC", "Plan utility requirements", "Hire PMC for construction oversight"]'::jsonb, '{"templates": ["Facility Layout Template", "Construction Budget Template"], "tools": ["Factory Design Planner"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Utilities & Infrastructure', 'Plan factory utilities: power (connected load calculation, HT vs LT), water (borewells, tanker, ETP), gas (PNG pipeline or cylinders), compressed air, and waste management. Understand utility costs and reliability. Plan backup power: DG sets, solar rooftop. Handle DISCOM approvals and connections.', '["Calculate power requirements", "Plan water sourcing and treatment", "Get utility connection quotes", "Design backup power system"]'::jsonb, '{"templates": ["Utility Planning Worksheet", "DISCOM Application Guide"], "tools": ["Utility Cost Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'Factory Statutory Approvals', 'Obtain all statutory approvals before operations. Key approvals: Factory License (Factories Act), Fire NOC, Pollution Control Board consent (CTE and CTO), PESO (if hazardous), Shops & Establishments. Navigate state single-window clearance. Typical timeline: 3-6 months for all approvals.', '["List all required approvals", "Apply through single window system", "Track approval status", "Plan for inspection readiness"]'::jsonb, '{"templates": ["Approval Tracking Matrix", "Application Document Checklist"], "tools": ["Statutory Approval Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: PLI Overview (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'PLI Scheme Overview', 'Access ₹2 lakh crore PLI schemes across 14 sectors - eligibility, application, and benefit maximization', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'PLI Scheme Architecture', 'Production Linked Incentive (PLI) schemes offer 4-6% of incremental sales as incentive. 14 sectors covered: mobile phones (₹40,951 Cr), pharma (₹15,000 Cr), medical devices, automobiles, ACC battery, textiles, food processing, solar PV, white goods, steel, and more. Understand scheme design: base year, incentive rates, eligibility thresholds.', '["Study all 14 PLI schemes", "Identify schemes relevant to your sector", "Calculate potential PLI benefit", "Understand base year and increment calculations"]'::jsonb, '{"templates": ["PLI Scheme Overview Matrix", "Benefit Calculator Template"], "tools": ["PLI Eligibility Checker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'PLI Electronics & IT Hardware', 'Navigate electronics PLI: large scale electronics (mobile phones), IT hardware (laptops, tablets, servers). Mobile PLI offers 4-6% on incremental sales with ₹40,951 crore outlay. Minimum investment: ₹250 crore for domestic, ₹1,000 crore for global. Winners: Apple suppliers (Foxconn, Wistron), Samsung, Lava, Dixon.', '["Assess electronics PLI eligibility", "Calculate investment thresholds", "Study successful applicants", "Prepare application documentation"]'::jsonb, '{"templates": ["Electronics PLI Application Guide", "Investment Planning Sheet"], "tools": ["Electronics PLI Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'PLI Pharmaceuticals & Medical', 'Access pharma PLI: API/KSM (₹6,940 Cr) and formulations (₹15,000 Cr). Medical devices PLI covers high-value segments. Minimum investment: ₹3-25 crore depending on category. Focus on reducing import dependence and promoting domestic manufacturing of critical drugs and medical equipment.', '["Review pharma/medical device PLI criteria", "Identify applicable product categories", "Calculate investment and sales targets", "Prepare technical capability documentation"]'::jsonb, '{"templates": ["Pharma PLI Application Template", "Medical Device PLI Guide"], "tools": ["Pharma PLI Benefit Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'PLI Application Process', 'Master PLI application: expression of interest, detailed project report (DPR), investment commitment, and evaluation. Understand evaluation criteria: technical capability, financial strength, investment plan, and employment generation. Navigate ministry-specific portals and documentation requirements.', '["Prepare comprehensive DPR", "Document technical capabilities", "Secure financial commitments", "Submit application with all annexures"]'::jsonb, '{"templates": ["DPR Template", "Financial Commitment Letter"], "tools": ["PLI Application Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'PLI Compliance & Claims', 'Maintain PLI compliance: meet investment milestones, achieve sales targets, maintain localization requirements. File quarterly and annual claims. Handle audits and verification. Navigate PLI amendment and extension processes. Understand penalty clauses and exit provisions.', '["Set up PLI compliance system", "Create milestone tracking dashboard", "Prepare for verification audits", "File claims on schedule"]'::jsonb, '{"templates": ["PLI Compliance Checklist", "Claim Filing Template"], "tools": ["PLI Milestone Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Quality Certifications (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Quality Certifications', 'Obtain ISO, BIS, CE, and industry-specific certifications for market access and credibility', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'ISO Quality Standards', 'Implement ISO standards foundation. ISO 9001 (Quality Management) is baseline for any manufacturer. Timeline: 3-6 months for implementation, ₹2-5 lakhs for certification. Understand certification bodies: TUV, BSI, Bureau Veritas, IRQS. Plan for surveillance audits every 6-12 months.', '["Study ISO 9001:2015 requirements", "Conduct gap analysis", "Select certification body", "Plan implementation timeline"]'::jsonb, '{"templates": ["ISO 9001 Implementation Checklist", "Gap Analysis Template"], "tools": ["ISO Readiness Assessor"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'BIS Certification', 'Navigate Bureau of Indian Standards (BIS) certification. Mandatory for many products: electronics (CRS scheme), helmets, steel, cement. Process: application, factory audit, product testing, license grant. Typical timeline: 3-6 months. Costs: ₹1-5 lakhs including testing fees.', '["Check BIS mandatory list for your products", "Apply for BIS license", "Prepare for factory audit", "Submit samples for testing"]'::jsonb, '{"templates": ["BIS Application Guide", "Factory Audit Checklist"], "tools": ["BIS Product Category Finder"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'CE Marking for Export', 'Obtain CE marking for European Union market access. Understand directives applicable to your product: Machinery Directive, EMC Directive, Low Voltage Directive. Conduct conformity assessment: self-declaration or notified body. Prepare technical file and Declaration of Conformity. CE marking opens access to 27 EU countries.', '["Identify applicable CE directives", "Conduct conformity assessment", "Prepare technical documentation", "Create Declaration of Conformity"]'::jsonb, '{"templates": ["CE Technical File Template", "DoC Template"], "tools": ["CE Directive Finder"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Industry-Specific Certifications', 'Obtain sector-specific certifications. Automotive: IATF 16949, PPAP, APQP. Electronics: UL, FCC. Food: FSSAI, HACCP, ISO 22000. Pharma: WHO-GMP, US FDA. Medical devices: ISO 13485, CDSCO approval. Understand customer requirements and export market needs.', '["List required certifications for your industry", "Prioritize by customer requirements", "Plan certification roadmap", "Budget for certification costs"]'::jsonb, '{"templates": ["Certification Roadmap Template", "Industry Certification Matrix"], "tools": ["Certification Cost Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Quality Management System', 'Build comprehensive QMS beyond certification. Implement quality tools: 5S, Kaizen, Six Sigma, SPC. Create quality culture through training and incentives. Set up quality metrics and dashboards. Handle customer quality complaints effectively. Build quality as competitive advantage.', '["Implement 5S methodology", "Train team on quality tools", "Set up quality metrics dashboard", "Create customer complaint system"]'::jsonb, '{"templates": ["QMS Manual Template", "Quality Dashboard Setup"], "tools": ["Quality Metrics Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: Labor Compliance (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'Labor Compliance', 'Master factory labor laws - hiring, wages, safety, and new labor codes compliance', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'Factories Act Compliance', 'Comply with Factories Act 1948 for any premises with 10+ workers using power or 20+ without. Key requirements: working hours (48/week max), overtime limits, weekly holidays, annual leave, safety provisions. Obtain factory license before operations. Maintain statutory registers and displays.', '["Apply for Factory License", "Understand working hour limits", "Set up overtime tracking", "Display mandatory notices"]'::jsonb, '{"templates": ["Factory License Application", "Statutory Register Templates"], "tools": ["Working Hours Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'Wage & Bonus Compliance', 'Navigate wage laws: Minimum Wages Act (state-specific rates), Payment of Wages Act (timely payment), Equal Remuneration Act (no gender discrimination). Understand Payment of Bonus Act: 8.33% minimum bonus for employees earning up to ₹21,000/month. Set up compliant payroll systems.', '["Check state minimum wage rates", "Set up payroll compliance", "Calculate bonus liability", "Create wage slip format"]'::jsonb, '{"templates": ["Minimum Wage Matrix by State", "Payroll Checklist"], "tools": ["Wage Compliance Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'PF, ESI & Gratuity', 'Implement statutory benefits. PF: 12% employer + 12% employee for establishments with 20+ employees. ESI: 3.25% employer + 0.75% employee for employees earning up to ₹21,000/month. Gratuity: 15 days salary per year after 5 years service. Register and file monthly returns.', '["Register for PF and ESI", "Set up monthly contribution process", "Calculate gratuity liability", "File monthly PF/ESI returns"]'::jsonb, '{"templates": ["PF/ESI Registration Guide", "Gratuity Calculator"], "tools": ["Statutory Benefits Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'Factory Safety Compliance', 'Implement occupational safety requirements. Provide PPE (personal protective equipment), safety training, fire safety systems, first aid facilities. Conduct safety audits and drills. Handle accident reporting and compensation under Employees Compensation Act. Build safety culture.', '["Conduct safety risk assessment", "Provide appropriate PPE", "Set up safety training program", "Create emergency response plan"]'::jsonb, '{"templates": ["Safety Audit Checklist", "PPE Matrix by Operation"], "tools": ["Safety Compliance Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'New Labor Codes Preparation', 'Prepare for 4 new labor codes consolidating 29 laws. Code on Wages, Industrial Relations Code, Social Security Code, and OSH Code. Key changes: new wage definition, standing orders threshold, fixed-term employment, and social security universalization. Assess impact and update policies.', '["Study 4 new labor codes", "Conduct impact assessment", "Update HR policies", "Train HR team on changes"]'::jsonb, '{"templates": ["Labor Code Impact Assessment", "Policy Update Checklist"], "tools": ["Labor Code Compliance Guide"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Supply Chain (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Supply Chain', 'Build resilient supply chain - vendor development, procurement, inventory, and logistics', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'Supplier Identification & Evaluation', 'Build supplier base through systematic identification. Sources: IndiaMart, TradeIndia, industry associations, trade shows, OEM recommendations. Evaluate suppliers on QCDDM: Quality, Cost, Delivery, Development, Management. Conduct supplier audits before onboarding. Maintain supplier scorecards.', '["Identify 5 suppliers per critical component", "Create supplier evaluation criteria", "Conduct supplier audits", "Build supplier scorecard system"]'::jsonb, '{"templates": ["Supplier Evaluation Form", "Audit Checklist"], "tools": ["Supplier Scoring Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'Vendor Development Program', 'Develop suppliers for quality and capability improvement. Implement vendor quality agreements (VQA). Provide technical assistance and training. Create tiered supplier programs: strategic, preferred, approved. Build long-term partnerships for innovation and cost reduction.', '["Create vendor quality agreements", "Design supplier development program", "Implement supplier tiering", "Plan joint improvement projects"]'::jsonb, '{"templates": ["VQA Template", "Supplier Development Plan"], "tools": ["Vendor Performance Tracker"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Procurement Strategy', 'Optimize procurement: balance cost, quality, and supply security. Implement dual sourcing for critical components. Negotiate annual contracts vs spot buying. Use e-procurement tools. Understand total cost of ownership (TCO) beyond unit price. Handle import procurement and customs.', '["Create procurement strategy by category", "Implement dual sourcing plan", "Negotiate annual contracts", "Calculate TCO for major items"]'::jsonb, '{"templates": ["Procurement Strategy Framework", "TCO Calculator"], "tools": ["Procurement Analysis Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Inventory Management', 'Optimize inventory: balance availability with working capital. Implement ABC analysis for prioritization. Use EOQ (Economic Order Quantity) for ordering. Implement kanban for shop floor. Set up safety stock calculations. Target inventory turns improvement year-over-year.', '["Conduct ABC analysis", "Calculate EOQ for A items", "Implement kanban for production", "Set safety stock levels"]'::jsonb, '{"templates": ["ABC Analysis Template", "EOQ Calculator"], "tools": ["Inventory Optimization Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Logistics & Warehousing', 'Set up efficient logistics. Evaluate 3PL vs in-house logistics. Understand freight modes: road (most common), rail (bulk), air (urgent). Optimize warehouse layout and operations. Handle customs clearance for imports. Plan reverse logistics for returns and warranty.', '["Design warehouse layout", "Evaluate 3PL partners", "Optimize freight mix", "Set up returns process"]'::jsonb, '{"templates": ["Warehouse Layout Template", "3PL Evaluation Matrix"], "tools": ["Logistics Cost Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: SEZ & Industrial Parks (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'SEZ & Industrial Parks', 'Maximize benefits from SEZs, industrial corridors, and manufacturing clusters', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'SEZ Benefits & Operations', 'Leverage Special Economic Zone benefits: 100% income tax exemption for 5 years, 50% for next 5 years, GST exemption on inputs, duty-free imports. India has 270+ operational SEZs. Understand SEZ compliance: exports obligation, positive NFE (Net Foreign Exchange), bonding requirements.', '["Evaluate SEZ vs DTA operations", "Identify suitable SEZs", "Calculate tax benefit value", "Understand compliance requirements"]'::jsonb, '{"templates": ["SEZ Benefit Calculator", "SEZ Compliance Checklist"], "tools": ["SEZ Comparison Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Industrial Corridors', 'Leverage industrial corridor benefits. DMIC (Delhi-Mumbai), CBIC (Chennai-Bengaluru), AKIC (Amritsar-Kolkata), ECEC (East Coast), BMEC (Bengaluru-Mumbai). These offer world-class infrastructure, plug-and-play facilities, and incentives. Understand investment thresholds and benefits.', '["Study industrial corridor locations", "Evaluate corridor-specific incentives", "Visit shortlisted corridors", "Apply for corridor allotment"]'::jsonb, '{"templates": ["Corridor Comparison Matrix", "Site Selection Guide"], "tools": ["Industrial Corridor Navigator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Manufacturing Clusters', 'Join manufacturing clusters for ecosystem benefits. Examples: Pune auto cluster, Surat textiles, Coimbatore engineering, Ludhiana light engineering. Benefits: shared infrastructure, supplier proximity, skilled labor pool, knowledge sharing. Understand cluster development schemes and initiatives.', '["Identify relevant clusters for your sector", "Study cluster benefits", "Connect with cluster associations", "Plan cluster-based location"]'::jsonb, '{"templates": ["Cluster Assessment Framework", "Association Contact Directory"], "tools": ["Cluster Finder Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Private Industrial Parks', 'Evaluate private industrial parks: Mahindra World City, Lodha Industrial & Logistics Park, Adani Ports Industrial Parks. Benefits: faster setup, better infrastructure, flexibility. Compare lease vs purchase options. Understand common area maintenance (CAM) charges and facilities.', '["Compare private vs government parks", "Visit 3 private industrial parks", "Evaluate infrastructure quality", "Negotiate lease terms"]'::jsonb, '{"templates": ["Industrial Park Comparison", "Lease Negotiation Checklist"], "tools": ["Park Cost Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'State Industrial Incentives', 'Maximize state-level manufacturing incentives. Gujarat offers 7-12% capital subsidy. Maharashtra provides industrial promotion subsidy. Tamil Nadu has SIPCOT and TIDCO schemes. Compare incentives across states for your sector and scale. Layer state benefits with central schemes.', '["Compare state incentives for your sector", "Calculate total benefit package", "Apply for state incentives", "Create combined benefit roadmap"]'::jsonb, '{"templates": ["State Incentive Comparison", "Benefit Stacking Calculator"], "tools": ["State Incentive Navigator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Export Manufacturing (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Export Manufacturing', 'Build export capability - market access, trade agreements, export incentives, and compliance', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Export Market Selection', 'Choose export markets strategically. Analyze market potential: size, growth, competition, entry barriers. Leverage trade agreements: FTAs with ASEAN, Japan, Korea; preferential access to LDCs. Understand market-specific requirements: certifications, labeling, packaging. Start with 2-3 focus markets.', '["Research 10 potential export markets", "Analyze FTA benefits", "Understand certification requirements", "Select 3 priority markets"]'::jsonb, '{"templates": ["Export Market Analysis", "FTA Benefits Calculator"], "tools": ["Market Selection Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Export Incentives', 'Access export incentive schemes. RoDTEP (Remission of Duties and Taxes on Exported Products): 0.5-4.3% of FOB value. MEIS replaced by RoDTEP for merchandise exports. Export Credit Guarantee Corporation (ECGC) for risk coverage. EXIM Bank financing for export projects.', '["Understand RoDTEP rates for your products", "Register for RoDTEP benefit", "Apply for ECGC coverage", "Explore EXIM Bank financing"]'::jsonb, '{"templates": ["RoDTEP Rate Finder", "ECGC Application Guide"], "tools": ["Export Incentive Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Export Documentation', 'Master export documentation: commercial invoice, packing list, bill of lading/airway bill, certificate of origin (preferential and non-preferential), phytosanitary certificates (agricultural products), quality certificates. Understand DGFT requirements and IEC (Import Export Code).', '["Obtain IEC code", "Create standard export document templates", "Understand LC documentation requirements", "Train team on export procedures"]'::jsonb, '{"templates": ["Export Document Checklist", "Invoice Templates"], "tools": ["Document Preparation Guide"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Export Compliance', 'Ensure export compliance: restricted goods lists, export controls, dual-use items, country sanctions. Understand DGFT Export Policy and licensing requirements. Handle customs compliance: self-sealing, examination, drawback claims. Maintain export records for audit.', '["Check export restrictions for products", "Understand licensing requirements", "Set up customs compliance process", "Prepare for DGFT audit"]'::jsonb, '{"templates": ["Export Compliance Checklist", "Restricted Items Guide"], "tools": ["Export Control Checker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Export Payment & Risk', 'Manage export payment and risk. Payment terms: advance payment, letter of credit (LC), documents against payment (DP), open account. Understand forex risk and hedging. Handle buyer credit risk with ECGC. Plan for currency fluctuation impact on margins.', '["Define payment terms by customer", "Set up LC handling process", "Implement forex hedging", "Get ECGC coverage"]'::jsonb, '{"templates": ["Payment Terms Framework", "LC Checklist"], "tools": ["Forex Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: Automation & Industry 4.0 (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'Automation & Industry 4.0', 'Implement smart manufacturing - automation, IoT, data analytics, and digital transformation', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'Automation Strategy', 'Develop automation roadmap based on ROI. Prioritize: high volume repetitive tasks, quality-critical operations, hazardous processes. Calculate payback period (typically 2-3 years in India). Start with semi-automation before full automation. Plan for workforce transition and upskilling.', '["Identify automation opportunities", "Calculate ROI for each opportunity", "Prioritize automation investments", "Plan workforce transition"]'::jsonb, '{"templates": ["Automation ROI Calculator", "Prioritization Matrix"], "tools": ["Automation Readiness Assessment"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Industrial Robotics', 'Implement industrial robots: welding robots, pick-and-place, CNC loading, assembly robots. Understand robot types: articulated, SCARA, delta, collaborative (cobots). Indian robot density is 4 per 10,000 workers vs global 126. Evaluate robot suppliers: ABB, KUKA, Fanuc, Yaskawa, and Indian options.', '["Identify robot applications", "Get quotes from robot suppliers", "Calculate robot vs manual cost", "Plan robot implementation"]'::jsonb, '{"templates": ["Robot Selection Guide", "Robot ROI Template"], "tools": ["Robot Comparison Tool"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'Industrial IoT & Sensors', 'Deploy IIoT for manufacturing visibility. Implement sensors for: machine monitoring (OEE), energy monitoring, quality inspection, predictive maintenance. Connect legacy machines with retrofit solutions. Choose between cloud and edge processing. Ensure cybersecurity.', '["Identify IoT use cases", "Select sensor and connectivity solutions", "Plan data architecture", "Implement pilot IoT project"]'::jsonb, '{"templates": ["IoT Use Case Canvas", "Sensor Selection Guide"], "tools": ["IoT ROI Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'Manufacturing Analytics', 'Implement analytics for decision making. Track OEE (Overall Equipment Effectiveness): availability × performance × quality. Implement SPC (Statistical Process Control) for quality. Use predictive analytics for maintenance. Create real-time production dashboards.', '["Define key manufacturing metrics", "Implement OEE tracking", "Deploy SPC for critical processes", "Build real-time dashboard"]'::jsonb, '{"templates": ["OEE Calculation Template", "SPC Implementation Guide"], "tools": ["Manufacturing Analytics Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'Digital Twin & AI', 'Explore advanced Industry 4.0 technologies. Digital twin: virtual replica for simulation and optimization. AI/ML for quality inspection, demand forecasting, process optimization. Understand implementation complexity and costs. Start with pilot projects before enterprise rollout.', '["Evaluate digital twin opportunities", "Identify AI/ML use cases", "Plan pilot projects", "Build internal capabilities"]'::jsonb, '{"templates": ["Digital Twin Feasibility", "AI Use Case Assessment"], "tools": ["Industry 4.0 Maturity Assessment"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 10: Scaling (Days 46-50)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_10_id, v_product_id, 'Scaling Manufacturing', 'Scale operations - capacity expansion, multi-plant operations, and growth management', 10, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_10_id, 46, 'Capacity Planning', 'Plan capacity expansion systematically. Understand demand forecasting and capacity utilization targets (80-85% optimal). Evaluate expansion options: add shifts, debottleneck, brownfield expansion, greenfield plant. Calculate capacity expansion investment and lead time (typically 12-18 months for new plant).', '["Forecast demand for 5 years", "Identify capacity bottlenecks", "Evaluate expansion options", "Create capacity expansion roadmap"]'::jsonb, '{"templates": ["Capacity Planning Template", "Demand Forecasting Model"], "tools": ["Capacity Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 47, 'Multi-Plant Operations', 'Manage multi-plant manufacturing. Design plant network: centralized vs distributed. Standardize processes and quality across plants. Implement ERP for visibility. Handle transfer pricing and inter-plant logistics. Balance load across plants.', '["Design multi-plant strategy", "Standardize processes", "Implement ERP integration", "Set up inter-plant logistics"]'::jsonb, '{"templates": ["Multi-Plant Strategy Framework", "Process Standardization Guide"], "tools": ["Plant Network Optimizer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 48, 'Operational Excellence', 'Implement operational excellence for sustainable growth. Deploy lean manufacturing: value stream mapping, waste elimination, continuous flow. Implement TPM (Total Productive Maintenance). Create kaizen culture with employee involvement. Benchmark against best-in-class manufacturers.', '["Conduct value stream mapping", "Implement lean tools", "Launch TPM program", "Create kaizen program"]'::jsonb, '{"templates": ["VSM Template", "TPM Implementation Guide"], "tools": ["Lean Assessment Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 49, 'Manufacturing Finance', 'Manage manufacturing finance for growth. Understand working capital cycle and optimization. Access manufacturing finance: term loans, working capital, bill discounting, channel finance. Maintain EBITDA margins while scaling. Plan for capital efficiency improvements.', '["Optimize working capital cycle", "Evaluate financing options", "Improve EBITDA margins", "Plan capital efficiency projects"]'::jsonb, '{"templates": ["Working Capital Optimization", "Finance Options Comparison"], "tools": ["Manufacturing Finance Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 50, 'Manufacturing Talent', 'Build manufacturing talent for scale. Recruit from ITIs, polytechnics, and engineering colleges. Develop technical training programs. Create career paths for shop floor to management. Retain talent through ESOPs and growth opportunities. Build manufacturing leadership pipeline.', '["Create hiring plan for growth", "Develop training programs", "Design career progression paths", "Implement retention strategies"]'::jsonb, '{"templates": ["Manufacturing Hiring Plan", "Training Curriculum Template"], "tools": ["Talent Planning Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 11: Advanced Strategies (Days 51-55)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_11_id, v_product_id, 'Advanced Strategies', 'Master advanced manufacturing strategies - M&A, partnerships, sustainability, and exit planning', 11, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_11_id, 51, 'Strategic Partnerships', 'Build strategic manufacturing partnerships. Types: technology licensing, joint ventures, contract manufacturing relationships, supplier partnerships. Indian JV examples: Maruti-Suzuki, Hero-Honda (historical), Tata-Starbucks. Navigate partnership structures and governance.', '["Identify partnership opportunities", "Evaluate potential partners", "Structure partnership terms", "Set up governance framework"]'::jsonb, '{"templates": ["Partnership Evaluation Matrix", "JV Structure Template"], "tools": ["Partnership ROI Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 52, 'Manufacturing M&A', 'Grow through acquisitions. Understand manufacturing M&A rationale: capacity acquisition, technology access, customer relationships, geographic expansion. Navigate due diligence for manufacturing: equipment condition, quality systems, environmental liabilities, labor issues. Plan post-merger integration.', '["Identify acquisition targets", "Conduct manufacturing due diligence", "Negotiate acquisition terms", "Plan integration"]'::jsonb, '{"templates": ["M&A Target Evaluation", "Manufacturing Due Diligence Checklist"], "tools": ["Acquisition Synergy Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 53, 'Sustainable Manufacturing', 'Implement sustainability for competitiveness and compliance. Focus areas: energy efficiency, water conservation, waste management, carbon footprint reduction. Understand EPR (Extended Producer Responsibility) compliance. Obtain sustainability certifications. Meet customer ESG requirements.', '["Conduct sustainability assessment", "Implement energy efficiency projects", "Set up waste management", "Plan carbon footprint reduction"]'::jsonb, '{"templates": ["Sustainability Assessment", "Carbon Footprint Calculator"], "tools": ["ESG Compliance Tracker"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 54, 'Manufacturing IPO Readiness', 'Prepare for public listing. Understand SEBI requirements for manufacturing companies. Build corporate governance infrastructure. Implement financial controls and reporting. Prepare DRHP with manufacturing-specific disclosures. Learn from recent manufacturing IPOs: Dixon, Happiest Minds, Syrma.', '["Assess IPO readiness", "Implement corporate governance", "Prepare financial documentation", "Select investment banker"]'::jsonb, '{"templates": ["IPO Readiness Checklist", "DRHP Preparation Guide"], "tools": ["IPO Timeline Planner"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 55, 'Exit & Succession Planning', 'Plan exit strategies for manufacturing businesses. Options: IPO, strategic sale to larger player, PE/financial buyer, management buyout, family succession. Understand manufacturing valuations: revenue multiple, EBITDA multiple, asset-based. Prepare for exit: clean financials, reduced key-person risk, documented processes.', '["Define exit strategy", "Prepare business for sale", "Build management depth", "Document key processes"]'::jsonb, '{"templates": ["Exit Planning Framework", "Valuation Checklist"], "tools": ["Business Valuation Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
