-- P18: Operations & Supply Chain - Enhanced Migration (Part 1: Modules 1-4)
-- 40 days, 8 modules, comprehensive operations framework for Indian startups
-- India-specific: Make in India, MSME ecosystem, Udyam, DGFT, Indian 3PL providers, GST logistics

BEGIN;

DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;

    -- Insert/Update Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P18',
        'Operations & Supply Chain',
        'Master operations and supply chain excellence for Indian startups. 40 days, 8 modules covering operations strategy, supply chain design, vendor management, inventory control, warehouse management, logistics optimization, quality systems, and scaling operations. India-specific guidance on Make in India compliance, MSME vendor ecosystem, Udyam registration, DGFT import regulations, Indian 3PL providers, and GST on logistics.',
        5999,
        40,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P18';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: Operations Strategy for Indian Startups (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'Operations Strategy for Indian Startups', 'Master make vs buy decisions, capacity planning, and location selection with India-specific considerations including Make in India initiative, state incentives, and infrastructure assessment', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'Operations Strategy Framework for India',
    'Operations strategy in India must account for unique market characteristics including diverse infrastructure quality, labor skill variations, regulatory complexity, and regional market differences. Indian startups face a 70% operational inefficiency rate, with supply chain disruptions costing an average of 6-8% of revenue annually. The operations value chain in India spans procurement (navigating 63 million MSMEs), manufacturing (Make in India compliance), logistics (fragmented 3PL market worth Rs 2.5 lakh crore), and delivery (last-mile challenges in 7,000+ towns). Operations philosophy must balance three approaches: Cost Leadership (targeting price-sensitive 80% of Indian consumers), Differentiation (premium positioning for top 15% income segment), and Focus (regional or niche specialization). Cost leadership in India leverages low labor costs (average manufacturing wage Rs 350-500/day vs Rs 3,000+ in China), abundant raw materials, and large domestic market. Differentiation requires superior quality systems, faster delivery (same-day becoming standard in metros), and customer experience. Focus strategy works well given India''s regional diversity - Tamil Nadu for auto components, Gujarat for textiles, Maharashtra for pharma. Create operations capability map identifying core competencies vs commoditized activities. Indian startups should master 2-3 core operational capabilities rather than trying to excel everywhere. Common capability choices: supply chain agility for D2C brands, manufacturing quality for B2B suppliers, distribution reach for FMCG, and technology integration for tech-enabled services. Align operations strategy with funding stage: bootstrapped companies prioritize capital efficiency, funded companies can invest in infrastructure ahead of demand.',
    '["Document your operations philosophy statement aligned with overall business strategy", "Map end-to-end operations value chain with India-specific considerations", "Identify top 5 operational pain points with quantified impact on revenue/margins", "Create operations capability matrix identifying core competencies to build"]'::jsonb,
    '{"templates": ["Operations Strategy Canvas India", "Value Chain Mapping Template", "Capability Assessment Framework", "Operations Philosophy Worksheet"], "tools": ["Operations Maturity Assessment India", "Competitive Operations Benchmarking", "Capability Gap Analyzer", "Strategy Alignment Checker"]}'::jsonb, 75, 50, 1, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_1_id, 2, 'Make vs Buy Decision Framework for India',
    'The make vs buy decision in India is influenced by unique factors including the robust MSME ecosystem (63 million registered units under Udyam), labor laws affecting in-house manufacturing, GST implications, and government incentives for domestic production. Strategic framework for India: Analyze total cost of ownership (TCO) including hidden costs specific to Indian context - GST input credits (lost if supplier is unregistered), quality inspection costs (higher for outsourced), inventory carrying costs (15-20% annually with high interest rates), and logistics costs (5-18% GST based on service type). Make decision indicators: proprietary technology or process, core competitive advantage, quality control critical, reliable suppliers unavailable, capacity utilization benefits, and Make in India incentives applicable. Buy decision indicators: non-core activity, specialized capability required, demand uncertainty high, capital constraints, and vendor ecosystem mature. Indian market considerations: Strong arguments for outsourcing include mature MSME clusters (Ludhiana for textiles, Coimbatore for pumps, Rajkot for engineering), labor law complexity for direct hiring, and reduced capital intensity. Arguments for in-house include quality control (70% of Indian suppliers fail first quality audit), IP protection (weak enforcement), and production agility. Hybrid models gaining popularity: assemble in-house with outsourced components, design in-house with contract manufacturing, and anchor supplier relationships with partial backward integration. Calculate breakeven volumes for make vs buy scenarios accounting for learning curve - Indian workforce typically requires 2-3x training time vs established markets.',
    '["Complete TCO analysis comparing make vs buy for top 5 cost components", "Evaluate each component against make vs buy decision criteria", "Assess MSME supplier ecosystem for buy candidates", "Create hybrid strategy identifying optimal sourcing mix"]'::jsonb,
    '{"templates": ["Total Cost of Ownership Calculator India", "Make vs Buy Decision Matrix", "Supplier Ecosystem Assessment", "Hybrid Sourcing Strategy Template"], "tools": ["TCO Comparison Tool", "Decision Criteria Weightage Calculator", "MSME Cluster Database", "Breakeven Analysis Calculator"]}'::jsonb, 75, 50, 2, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_1_id, 3, 'Capacity Planning for Indian Market Dynamics',
    'Capacity planning in India requires managing higher demand volatility than mature markets. Indian demand patterns show strong seasonality: Diwali season (October-November) drives 3-4x normal demand for consumer goods, wedding season (November-February) for ethnic wear and jewelry, harvest season for agri-inputs, and fiscal year-end (March) for B2B purchases. Capacity planning framework: Start with demand forecasting using multiple methods - historical analysis (adjust for GST implementation in 2017, COVID in 2020-21), market sizing (bottom-up from target customer segments), and leading indicators (Google Trends, industry reports from IBEF, CII). Convert demand to capacity requirements considering Indian efficiency factors: assume 85-90% capacity utilization target (not 95%+ due to power fluctuations, labor issues), account for longer changeover times (workforce skill levels), and buffer for quality rejections (5-15% depending on process maturity). Capacity options in India: Owned capacity offers control but requires capital (typical manufacturing setup Rs 50 lakhs to Rs 5 crores), leased capacity reduces upfront investment (industrial parks in tier 2 cities Rs 8-15/sqft/month), contract manufacturing provides flexibility (minimum order quantities typically Rs 5-10 lakhs), and capacity sharing arrangements with complementary businesses. Capacity scalability planning: identify capacity constraints by stage (0-1 year, 1-3 years, 3-5 years), plan capacity additions ahead of demand (6-12 month lead time for equipment), and maintain strategic partnerships for overflow capacity. Indian-specific considerations: power availability and backup costs (diesel genset adds Rs 15-20/kWh), water supply (critical for food processing, textiles), and skilled labor availability varies by location.',
    '["Create demand forecast incorporating Indian seasonality patterns and market dynamics", "Calculate capacity requirements with Indian efficiency adjustments", "Evaluate capacity options: owned, leased, contract manufacturing", "Design capacity scaling roadmap with trigger points and lead times"]'::jsonb,
    '{"templates": ["Indian Demand Forecasting Template", "Capacity Requirements Calculator", "Capacity Options Comparison Matrix", "Capacity Scaling Roadmap"], "tools": ["Seasonality Analysis Tool", "Efficiency Factor Database", "Equipment Lead Time Tracker", "Capacity Investment Calculator"]}'::jsonb, 75, 50, 3, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_1_id, 4, 'Location Selection for Operations in India',
    'Location selection in India involves evaluating state-level policies, infrastructure quality, labor availability, and market access across vastly different operating environments. Location selection framework: Score locations across key criteria - Market proximity (customer concentration, delivery time requirements), Supplier proximity (raw material sources, MSME clusters), Infrastructure (power reliability, road connectivity, port access), Labor (availability, skill levels, wage rates, union activity), Regulatory environment (state policy, ease of business ranking, single window clearance), and Incentives (state subsidies, SEZ benefits, DMIC corridor). Top manufacturing destinations by sector: Automotive (Tamil Nadu, Maharashtra, Gujarat), Electronics (Karnataka, Tamil Nadu, Andhra Pradesh), Textiles (Tamil Nadu, Gujarat, Maharashtra), Pharma (Telangana, Gujarat, Himachal Pradesh), and Food Processing (Maharashtra, Gujarat, Andhra Pradesh). Tier 2 city advantages: 30-40% lower real estate costs than metros, lower wage expectations (Rs 15,000-20,000 vs Rs 25,000-35,000 for skilled workers), state incentives for non-metro investment, and improving infrastructure under Smart Cities Mission. Warehouse location considerations: proximity to consumption centers (Delhi NCR, Mumbai, Bangalore, Chennai handle 60% of e-commerce volumes), GST optimization (state-to-state movements attract IGST), multi-modal connectivity (rail, road, air), and labor availability for warehouse operations. Industrial park vs standalone: industrial parks offer plug-and-play infrastructure, common facilities, and better security, but less flexibility in expansion. Consider NIMZ (National Investment and Manufacturing Zones), textile parks, and food parks for sector-specific benefits.',
    '["Create location evaluation scorecard with weighted criteria", "Shortlist 3-5 potential locations based on sector-specific requirements", "Conduct site visits assessing infrastructure and labor availability", "Analyze state incentive schemes and regulatory requirements for shortlisted locations"]'::jsonb,
    '{"templates": ["Location Selection Scorecard India", "Site Visit Checklist", "State Incentive Comparison Matrix", "Infrastructure Assessment Template"], "tools": ["DPIIT State Rankings Database", "Industrial Land Price Tracker", "Labor Wage Comparator", "Logistics Cost Calculator by Location"]}'::jsonb, 75, 50, 4, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_1_id, 5, 'Operations Excellence Roadmap Creation',
    'Building an operations excellence roadmap requires understanding current maturity and systematically building capabilities. Operations maturity levels for Indian startups: Level 1 (Reactive) - fire-fighting mode, no documented processes, founder-dependent operations; Level 2 (Defined) - basic SOPs exist, some metrics tracked, team hired but not specialized; Level 3 (Managed) - processes standardized, performance measured, improvement initiatives underway; Level 4 (Optimized) - data-driven decisions, continuous improvement culture, predictive operations; Level 5 (World-class) - industry benchmarks exceeded, operations as competitive advantage. Typical Indian startup maturity: seed-stage at Level 1, Series A at Level 2, Series B target Level 3. Roadmap creation process: assess current maturity through operations audit (cover process documentation, team capabilities, technology usage, performance metrics, supplier relationships), identify target maturity for 12-24 months based on growth plans, prioritize improvement areas using impact vs effort matrix, and create phased implementation plan. Quick wins for immediate impact (0-3 months): document top 10 critical processes, implement basic inventory tracking, establish supplier performance scorecards, and set up operations dashboards. Foundation building (3-6 months): ERP or operations management system implementation, quality management system basics, team training programs, and vendor development initiatives. Optimization phase (6-12 months): process automation opportunities, advanced analytics for decision-making, ISO certification preparation, and supply chain risk management. Indian startup operations budget benchmark: allocate 2-5% of revenue for operations improvement initiatives, higher in manufacturing (5-8%), lower in services (1-3%).',
    '["Complete operations maturity assessment across all capability areas", "Define target maturity state for each area over 12-24 months", "Prioritize improvement initiatives using impact vs effort framework", "Create phased operations excellence roadmap with milestones and resource requirements"]'::jsonb,
    '{"templates": ["Operations Maturity Assessment India", "Target State Definition Worksheet", "Improvement Initiative Prioritization Matrix", "Operations Excellence Roadmap Template"], "tools": ["Maturity Gap Analyzer", "Resource Planning Calculator", "Milestone Tracking System", "Operations Budget Benchmarking"]}'::jsonb, 75, 50, 5, NOW(), NOW());

    -- Module 2: Supply Chain Design (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'Supply Chain Design', 'Design robust supply chains with domestic sourcing from MSME ecosystem, import strategies under DGFT regulations, and multi-tier supplier networks', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'Supply Chain Strategy Design for Indian Market',
    'Supply chain strategy in India must balance cost efficiency with resilience, given infrastructure challenges and demand volatility. Indian supply chain characteristics: fragmented supplier base (63 million MSMEs, 95% micro enterprises), infrastructure gaps (logistics cost 13-14% of GDP vs 8-10% globally), regulatory complexity (GST compliance across states), and demand unpredictability (festival seasons, agricultural dependency). Supply chain strategy options: Efficient supply chain (low-cost focus) suits stable demand products like commodities, FMCG staples - focus on cost minimization, high utilization, inventory reduction. Responsive supply chain (flexibility focus) suits fashion, electronics, seasonal products - focus on speed, capacity buffers, postponement strategies. Risk-hedging supply chain suits import-dependent or single-source products - focus on pooling inventory, multiple suppliers, safety stocks. Agile supply chain combines responsive and risk-hedging for innovative products with high demand uncertainty. Indian market typically requires hybrid strategies: agile for new product launches, efficient for established SKUs, and risk-hedged for critical components. Supply chain network design decisions: number of suppliers (single vs dual vs multiple sourcing), number of warehouses (centralized vs distributed), transportation modes (road dominates with 60% share, rail 30%, air/sea 10%), and inventory positioning (push vs pull, centralized vs decentralized). Design principles for India: build buffer capacity for festival demand spikes, maintain safety stocks for monsoon disruptions, develop alternate suppliers for critical inputs, and optimize for GST implications in interstate movements.',
    '["Define supply chain strategy aligned with product characteristics and competitive priorities", "Map current supply chain network with all nodes and flows", "Identify supply chain vulnerabilities and disruption risks", "Design target supply chain configuration with resilience considerations"]'::jsonb,
    '{"templates": ["Supply Chain Strategy Selection Framework", "Network Mapping Template", "Risk Assessment Matrix", "Target State Design Canvas"], "tools": ["Supply Chain Typology Analyzer", "Network Visualization Tool", "Vulnerability Assessment Checklist", "Configuration Optimization Model"]}'::jsonb, 75, 50, 1, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_2_id, 7, 'Domestic Sourcing from MSME Ecosystem',
    'India''s MSME sector is the backbone of domestic sourcing with 63 million registered enterprises employing 110 million people and contributing 30% to GDP. Udyam registration (replaced Udyog Aadhaar in 2020) classifies MSMEs: Micro (investment up to Rs 1 crore, turnover up to Rs 5 crore), Small (investment up to Rs 10 crore, turnover up to Rs 50 crore), Medium (investment up to Rs 50 crore, turnover up to Rs 250 crore). Benefits of MSME sourcing: 25% procurement target for central PSUs (sub-target of 4% from SC/ST and 3% from women entrepreneurs), priority sector lending ensures supplier viability, cluster advantages for specialized components, and relationship-based business culture enables flexibility. MSME discovery platforms: Government e-Marketplace (GeM) for public sector, IndiaMART (60 million products, 6 million suppliers), TradeIndia, Alibaba India for private sector, and NSIC registered supplier database. Cluster-based sourcing advantages: Ludhiana for hosiery and bicycle parts, Tirupur for knitwear, Rajkot for engineering components, Sivakasi for printing and fireworks, Moradabad for brassware, and Firozabad for glass. MSME supplier challenges: inconsistent quality (implement incoming inspection), informal documentation practices (help with GST compliance), limited capacity (develop backup suppliers), and working capital constraints (consider faster payment terms or supply chain financing). Supplier development approach: conduct capability assessments, provide technical assistance for quality improvement, support for technology upgradation under Credit Linked Capital Subsidy Scheme (CLCSS), and connect with MSME development programs.',
    '["Identify MSME clusters relevant to your sourcing requirements", "Register on GeM and IndiaMART for supplier discovery", "Develop supplier qualification criteria for MSME vendors", "Create MSME supplier development program for key vendors"]'::jsonb,
    '{"templates": ["MSME Supplier Discovery Checklist", "Supplier Qualification Criteria MSME", "Cluster Analysis Template", "Supplier Development Program Framework"], "tools": ["Udyam Registration Verification", "GeM Supplier Search Guide", "MSME Cluster Database India", "Supplier Capability Assessment Tool"]}'::jsonb, 75, 50, 2, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_2_id, 8, 'Import Strategies Under DGFT Regulations',
    'Import sourcing requires navigating DGFT (Directorate General of Foreign Trade) regulations, customs procedures, and landed cost optimization. Import regulatory framework: DGFT issues Import-Export Code (IEC) mandatory for imports (online registration via DGFT website, one-time Rs 500 fee), Foreign Trade Policy 2023 (valid until March 2028) governs import-export procedures, and Customs Act 1962 regulates duties and clearance. Import classification: Freely importable goods (most industrial inputs), Restricted goods (require license - electronics, some chemicals), Prohibited goods (certain chemicals, ivory, hazardous waste), and Canalized goods (government agency imports only - petroleum, fertilizers). Import duty structure: Basic Customs Duty (BCD) varies by HS code (0-100%), Integrated GST (IGST) on imports (18% standard), Social Welfare Surcharge (10% on BCD), and Anti-dumping/Safeguard duties on specific products from specific countries. Landed cost calculation: CIF value + BCD + Social Welfare Surcharge + IGST + clearing charges (CHA fees Rs 3,000-10,000 per shipment) + port handling (Rs 5,000-15,000) + transportation. Import sourcing decisions: evaluate total landed cost vs domestic alternatives, consider import substitution schemes (PLI benefits for domestic manufacturing), assess supply chain risk from single-country dependence, and factor currency risk (hedge for high-value regular imports). Documentation requirements: commercial invoice, packing list, bill of lading/airway bill, certificate of origin, bill of entry, and product-specific certificates (FSSAI for food, BIS for electronics). Customs clearance optimization: use Authorized Economic Operator (AEO) program for faster clearance, leverage Free Trade Agreements (India-ASEAN, India-Korea, India-Japan) for reduced duties.',
    '["Obtain Import-Export Code (IEC) from DGFT", "Calculate landed cost for key import items including all duties and charges", "Evaluate FTA benefits for importing from partner countries", "Create import documentation checklist and clearance process"]'::jsonb,
    '{"templates": ["Landed Cost Calculator India", "Import Documentation Checklist", "FTA Benefit Analysis Template", "Customs Clearance Process Map"], "tools": ["IEC Registration Guide", "HS Code Lookup Tool", "Duty Calculator India", "AEO Application Process"]}'::jsonb, 75, 50, 3, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_2_id, 9, 'Multi-Tier Supplier Network Design',
    'Building a resilient multi-tier supplier network in India requires visibility beyond Tier 1 suppliers and managing the complexity of informal sub-supplier relationships. Multi-tier supply chain structure: Tier 1 suppliers (direct relationship, contracted), Tier 2 suppliers (Tier 1''s suppliers, limited visibility), Tier 3+ suppliers (raw material and component sources, often unknown). Indian multi-tier challenges: 80% of Tier 2/3 suppliers are unorganized MSMEs, limited documentation and traceability, quality variations at sub-supplier level, and cash flow constraints causing supply disruptions. Multi-tier visibility strategies: require Tier 1 suppliers to disclose Tier 2 sources, conduct periodic sub-supplier audits, implement traceability systems for critical components, and map supply chain to raw material sources for key inputs. Supplier categorization: Strategic suppliers (high impact, few alternatives - develop deep partnerships), Leverage suppliers (standardized products, many alternatives - negotiate aggressively), Bottleneck suppliers (limited options, low spend - secure supply), and Routine suppliers (low risk, low spend - simplify and automate). Network design decisions: single vs dual vs multiple sourcing (Indian practice leans toward 60-30-10 split for critical items), geographic diversification (spread across states to mitigate regional disruptions), vertical integration consideration (backward integration for critical inputs), and supplier proximity (cluster benefits vs over-concentration risk). Supply chain mapping exercise: document all suppliers with spend, criticality, and risk rating, identify concentration risks (single supplier, single location, single country), map sub-tier dependencies for top 20 critical inputs, and create supplier network visualization. Indian network best practices: maintain warm relationships with backup suppliers (quarterly touch-base), cross-qualify components across multiple suppliers, and build consortium relationships for commodity purchases.',
    '["Map complete supplier network including Tier 2 and Tier 3 for critical components", "Categorize suppliers using strategic-leverage-bottleneck-routine framework", "Assess concentration risks and develop mitigation strategies", "Design target supplier network with optimal diversification"]'::jsonb,
    '{"templates": ["Multi-Tier Supplier Mapping Template", "Supplier Categorization Matrix", "Concentration Risk Assessment", "Network Design Framework"], "tools": ["Supply Chain Visualization Tool", "Risk Scoring Calculator", "Supplier Relationship Tracker", "Network Optimization Model"]}'::jsonb, 75, 50, 4, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_2_id, 10, 'Supply Chain Risk Management India',
    'Supply chain risk management in India must address unique vulnerabilities including monsoon disruptions, infrastructure challenges, regulatory changes, and economic volatility. Risk categories for Indian supply chains: Natural disruptions (monsoon floods affecting logistics June-September, cyclones on eastern coast, drought impact on agri-inputs), Infrastructure risks (port congestion at JNPT and Chennai, power outages, highway conditions), Regulatory risks (GST rate changes, import duty modifications, state-level policy changes), and Economic risks (currency fluctuation, inflation spikes, interest rate changes affecting supplier viability). Risk assessment methodology: identify all potential risks, assess probability (low/medium/high based on historical frequency), assess impact (financial, operational, reputational), calculate risk score (probability x impact), and prioritize mitigation efforts. Risk mitigation strategies: Avoidance (eliminate risk source - exit high-risk suppliers), Reduction (decrease probability or impact - dual sourcing, safety stock), Transfer (shift risk to others - insurance, supplier contracts), and Acceptance (manage residual risk - contingency plans). Indian-specific mitigation: maintain 2-4 weeks additional safety stock for monsoon season, develop alternate logistics routes, build relationships with multiple customs house agents at different ports, and monitor supplier financial health (credit reports from CRISIL, ICRA). Supply chain insurance options: Marine cargo insurance (mandatory for imports), stock throughput insurance (covers inventory in transit and storage), business interruption insurance, and trade credit insurance (protects against customer defaults). Risk monitoring: create supply chain risk dashboard, track leading indicators (supplier delivery performance, logistics delays, commodity prices), conduct quarterly risk reviews, and update risk register annually or after major disruptions.',
    '["Conduct comprehensive supply chain risk assessment", "Develop risk mitigation strategies for top 10 identified risks", "Create supply chain risk monitoring dashboard with leading indicators", "Establish risk review cadence and escalation procedures"]'::jsonb,
    '{"templates": ["Supply Chain Risk Register India", "Risk Assessment Matrix", "Mitigation Strategy Template", "Risk Dashboard Framework"], "tools": ["Risk Scoring Calculator", "Insurance Coverage Checklist", "Supplier Financial Health Monitor", "Risk Alert System"]}'::jsonb, 75, 50, 5, NOW(), NOW());

    -- Module 3: Vendor Management & Development (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'Vendor Management & Development', 'Master supplier qualification, quality audits, payment terms optimization, and long-term vendor relationship building in Indian business context', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'Supplier Qualification Process for India',
    'Supplier qualification in India must account for the diverse formality levels, from organized manufacturing units to informal workshops. Qualification criteria framework: Legal and regulatory (GST registration, Udyam registration for MSME benefits, industry-specific licenses), Financial stability (minimum 3 years operation, positive net worth, credit rating check), Technical capability (equipment, processes, certifications like ISO 9001), Quality systems (inspection capabilities, documentation practices, defect tracking), Capacity and scalability (current capacity, expansion potential, sub-contracting arrangements), and Management and culture (owner involvement, worker welfare, ethical practices). India-specific verification: verify GST registration on GST portal (fake registrations common), confirm Udyam registration for MSME procurement benefits, check MCA portal for company financials (Pvt Ltd companies), and verify industry-specific registrations (FSSAI for food, drug license for pharma). Qualification process: preliminary screening (document check, basic criteria), capability questionnaire (detailed self-assessment), site visit and audit (verify claims, assess conditions), sample evaluation (product quality testing), trial order (small volume to assess performance), and qualification approval (formal vendor registration). Audit focus areas for India: child labor check (mandatory), fire and safety compliance, environmental compliance (pollution control), labor welfare (PF, ESI registration), and fair wage practices. Qualification documentation: create vendor registration form, define mandatory vs desirable criteria, develop audit checklist, establish qualification committee and approval authority, and set re-qualification frequency (annual for critical suppliers). Indian relationship factor: expect relationship-building before transactions, initial meetings focus on trust-building not just business, and personal visits by founders signal serious intent.',
    '["Develop comprehensive supplier qualification criteria covering all key areas", "Create supplier qualification questionnaire and audit checklist", "Establish qualification approval process with clear decision authority", "Define re-qualification triggers and frequency for different supplier categories"]'::jsonb,
    '{"templates": ["Supplier Qualification Criteria India", "Qualification Questionnaire Template", "Site Audit Checklist India", "Qualification Approval Workflow"], "tools": ["GST Verification Tool", "MCA Company Search Guide", "Udyam Registration Verifier", "Credit Rating Check Process"]}'::jsonb, 75, 50, 1, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_3_id, 12, 'Quality Audits and Supplier Assessment',
    'Quality audits in India require understanding local manufacturing practices and common quality issues. Audit types: Pre-qualification audit (before supplier approval), Periodic audit (annual for strategic suppliers), Product-specific audit (for new item qualification), and Issue-driven audit (after quality problems). Audit preparation: define audit scope and objectives, review previous audit findings and corrective actions, gather relevant documentation (specifications, quality records, previous shipment data), notify supplier in advance (unannounced audits for suspected issues), and prepare audit team (quality engineer plus commercial representative). Indian manufacturing audit areas: Facility and equipment (maintenance practices, calibration records, 5S implementation), Process control (work instructions availability, process parameters monitoring, changeover procedures), Quality systems (incoming inspection, in-process checks, final inspection, calibration), Documentation (batch records, traceability, deviation handling), and People (training records, skill matrix, supervisor competence). Common issues in Indian suppliers: missing or outdated work instructions, inadequate measurement systems (gauge R&R not performed), informal first-article inspection, poor housekeeping and 5S, and limited statistical process control. Audit scoring: use standardized scoring system (1-5 scale or percentage), define passing threshold (typically 70% minimum, 80% for strategic suppliers), categorize findings (critical, major, minor, observation), and require corrective action plan for all critical and major findings. Audit follow-up: review corrective action plans within 1 week, verify implementation through documents or re-audit, track closure of all findings, and maintain audit history for trend analysis. Third-party audit options: Bureau Veritas, SGS, TUV, and Intertek offer supplier audit services in India (Rs 25,000-75,000 per audit depending on scope).',
    '["Create standardized quality audit checklist for supplier assessments", "Conduct qualification audits for top 5 prospective suppliers", "Establish audit scoring methodology with clear pass/fail criteria", "Develop corrective action tracking and follow-up process"]'::jsonb,
    '{"templates": ["Quality Audit Checklist India", "Audit Scoring Template", "Corrective Action Request Form", "Audit Report Format"], "tools": ["Audit Planning Calendar", "Finding Classification Guide", "CAPA Tracking System", "Third-Party Audit Provider List"]}'::jsonb, 75, 50, 2, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_3_id, 13, 'Payment Terms and Working Capital Optimization',
    'Payment terms in India are critical for both buyer working capital and supplier relationships, with complex dynamics around credit periods and payment behaviors. Standard payment terms in India: Advance payment (10-30% common for custom items or new suppliers), Cash on delivery (small orders, unregistered suppliers), Net 15/30/45/60 days (from invoice date, 45-60 days most common in B2B), and Progressive payments (milestone-based for projects). Payment term negotiation factors: supplier bargaining power (monopoly suppliers demand advance or quick payment), order volume (higher volumes justify longer credit), relationship duration (new suppliers get shorter credit), and market conditions (supplier markets allow shorter credit). Working capital impact: each 30 days of payment terms equals approximately 8-10% of annual spend locked as payables (positive for buyer working capital). Calculate working capital benefit: if annual procurement is Rs 10 crore, each 30 days credit = Rs 83 lakhs available cash flow. Balance buyer vs supplier needs: MSMEs face acute working capital challenges (average DSO 90-120 days impacts them severely), delayed payments to small suppliers can cause quality issues or supply disruptions, and MSME Delayed Payment portal allows suppliers to file complaints. Payment optimization strategies: negotiate tiered terms (standard terms with early payment discount 1-2% for 10-day payment), implement supply chain financing (TReDS platform connects MSMEs with financiers against approved invoices), and use vendor financing programs from banks (HDFC, ICICI offer supplier payment products). GST and payments: input tax credit available only after payment to supplier (for quarterly filers), verify supplier GST filing before payment, and blocked ITC on payments to non-compliant suppliers.',
    '["Analyze current payment terms across supplier base and working capital impact", "Negotiate optimized payment terms with top 20 suppliers by spend", "Evaluate supply chain financing options (TReDS, bank programs)", "Implement early payment discount program for willing suppliers"]'::jsonb,
    '{"templates": ["Payment Terms Analysis Template", "Negotiation Strategy Framework", "Working Capital Calculator", "Early Payment Discount Policy"], "tools": ["Payment Terms Comparator", "TReDS Platform Guide", "Bank SCF Program Comparison", "GST ITC Impact Calculator"]}'::jsonb, 75, 50, 3, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_3_id, 14, 'Vendor Development Programs India',
    'Vendor development is essential in India given the capability gaps in the MSME supplier base, transforming marginal suppliers into reliable partners. Vendor development concept: investing resources to improve supplier capabilities in quality, delivery, cost, and technology, creating mutual benefit through improved performance. Vendor development need assessment: identify suppliers with potential but current performance gaps, assess gap areas (quality systems, process capability, capacity, management), evaluate supplier willingness to change and invest, and prioritize based on strategic importance and improvement potential. Development program components: Quality improvement (implement basic quality systems, statistical process control training, root cause analysis methodology), Process improvement (lean manufacturing basics, setup time reduction, productivity improvement), Technology upgrade (equipment modernization guidance, automation opportunity identification, Industry 4.0 awareness), and Management development (planning and scheduling, inventory management, financial management). Indian government support: Lean Manufacturing Competitiveness Scheme (LMCS) provides 80% government funding for lean implementation, Credit Linked Capital Subsidy Scheme (CLCSS) offers 15% subsidy on technology upgradation, ZED Certification (Zero Defect Zero Effect) supports quality and environmental improvement, and SIDBI provides low-cost financing for MSME capacity expansion. Vendor development delivery models: resident engineer at supplier (for critical high-volume suppliers), periodic visits by quality/engineering team, third-party vendor development consultants, and online training and certification programs. Success metrics: track quality improvement (defect PPM reduction), delivery performance improvement, productivity gains (cost reduction passed through), and certification achievement. Typical investment: Rs 50,000-5,00,000 per supplier depending on scope, with ROI realized through quality cost reduction and relationship value.',
    '["Identify suppliers with development potential using assessment criteria", "Design vendor development program curriculum for key suppliers", "Explore government scheme benefits for supplier development", "Establish vendor development metrics and tracking system"]'::jsonb,
    '{"templates": ["Vendor Development Need Assessment", "Development Program Curriculum", "Government Scheme Benefit Calculator", "Vendor Development Scorecard"], "tools": ["Supplier Potential Evaluator", "LMCS Application Guide", "CLCSS Eligibility Checker", "Training Module Library"]}'::jsonb, 75, 50, 4, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_3_id, 15, 'Strategic Vendor Relationship Management',
    'Long-term vendor relationship management in India requires understanding cultural factors and building partnerships beyond transactional relationships. Relationship spectrum: Transactional (price-focused, multiple suppliers, short-term), Collaborative (information sharing, joint problem-solving, medium-term commitment), and Strategic (integrated planning, shared investments, long-term partnership). Indian relationship dynamics: personal relationships matter significantly (owner-to-owner connections valued), loyalty is reciprocated (consistent orders earn priority treatment), festive gestures strengthen bonds (Diwali gifts, event invitations), and face-to-face meetings preferred over digital communication. Strategic supplier criteria: high spend concentration, limited alternatives, critical to operations, potential for innovation partnership, and cultural fit. Relationship building activities: regular business reviews (quarterly for strategic suppliers covering performance, forecasts, improvement initiatives), technology sharing (involve suppliers in product development, share roadmaps), joint cost reduction programs (VA/VE workshops, shared savings model), and capacity coordination (share demand forecasts, coordinate investment timing). Governance structure: establish clear escalation paths, define performance expectations and review mechanisms, create joint improvement forums, and agree on conflict resolution processes. Supplier recognition: implement supplier awards program (annual recognition for top performers), public acknowledgment (mention in company communications), and preferential treatment (first right of refusal on new business). Exit strategy: maintain exit option even in strategic relationships, document critical dependencies, develop alternate supplier capabilities in background, and handle relationship termination professionally (90-180 days notice, transition support). Common mistakes: over-dependence on relationship without performance accountability, assuming loyalty without competitive terms, and neglecting smaller suppliers who may become strategic.',
    '["Categorize suppliers on relationship spectrum and identify strategic partners", "Design quarterly business review format for strategic suppliers", "Create supplier recognition program with clear criteria", "Develop relationship governance framework with escalation and conflict resolution"]'::jsonb,
    '{"templates": ["Supplier Relationship Assessment", "Quarterly Business Review Agenda", "Supplier Award Program Design", "Relationship Governance Framework"], "tools": ["Strategic Supplier Identifier", "Relationship Health Scorecard", "Recognition Criteria Calculator", "Escalation Path Designer"]}'::jsonb, 75, 50, 5, NOW(), NOW());

    -- Module 4: Inventory & Warehouse Management (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Inventory & Warehouse Management', 'Master inventory optimization, 3PL provider selection (Delhivery, Shiprocket, Ecom Express), fulfillment center operations, and WMS system implementation', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Inventory Strategy for Indian Market',
    'Inventory strategy in India must balance service levels with high carrying costs and demand volatility. Indian inventory challenges: high cost of capital (inventory carrying cost 18-24% annually vs 12-15% in developed markets), demand unpredictability (festival-driven spikes, regional variations), long supply lead times (domestic supply chains often 2-4 weeks, imports 6-12 weeks), and infrastructure constraints (storage conditions, transit damage). Inventory carrying cost components: Cost of capital (12-15% bank interest rate or opportunity cost), Storage costs (Rs 8-25/sqft/month depending on city - Mumbai Rs 20-25, Chennai Rs 12-18, tier 2 cities Rs 8-12), Insurance (0.5-1% of inventory value), Obsolescence and shrinkage (2-5% for FMCG, 5-15% for fashion), and Handling costs (1-2% of inventory value). Inventory classification: ABC analysis by value (A items 70% value 20% SKUs - tight control, B items 20% value 30% SKUs - moderate control, C items 10% value 50% SKUs - simple control), XYZ analysis by demand predictability (X = stable, Y = variable, Z = highly unpredictable), combine ABC-XYZ for differentiated inventory policies. Inventory strategies by product type: Fast-moving staples (lean inventory, frequent replenishment), Seasonal products (build-ahead strategy, clear exit plan for excess), New products (conservative stocking until demand clarity), and Import-dependent items (higher safety stock, hedging considerations). Service level decisions: define target fill rate (95% for A items, 90% for B, 85% for C typical), calculate safety stock required for each service level, balance stockout cost vs carrying cost, and review service levels quarterly based on customer feedback and competition.',
    '["Conduct ABC-XYZ analysis to classify inventory and set differentiated policies", "Calculate inventory carrying cost for your business with all components", "Define service level targets by product category and customer segment", "Create inventory strategy document with policies for each ABC-XYZ category"]'::jsonb,
    '{"templates": ["ABC-XYZ Analysis Template", "Inventory Carrying Cost Calculator", "Service Level Policy Framework", "Inventory Strategy Document"], "tools": ["SKU Classification Tool", "Cost of Capital Calculator", "Fill Rate vs Safety Stock Model", "Inventory Policy Generator"]}'::jsonb, 75, 50, 1, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_4_id, 17, 'Indian 3PL Provider Landscape',
    'The Indian 3PL market is worth Rs 2.5 lakh crore and growing at 10-12% annually, with diverse options from tech-enabled aggregators to traditional logistics companies. 3PL categories in India: Express logistics (Delhivery, BlueDart, DTDC - fast delivery for e-commerce), PTL/FTL freight (Rivigo, BlackBuck, TCI - B2B logistics), Warehousing specialists (TVS Supply Chain, DHL Supply Chain, Mahindra Logistics), and Tech-enabled aggregators (Shiprocket, Pickrr, Shipway - aggregate multiple carriers). Major 3PL providers comparison: Delhivery - pan-India coverage 18,000+ pincodes, strong express and warehousing, Rs 5,000-8,000 per pallet per month for warehousing; BlueDart - premium express, best for metro deliveries, higher pricing but reliable; Ecom Express - e-commerce focused, 27,000+ pincodes, competitive pricing; Shiprocket - aggregator platform, connect with 17+ couriers, pay-per-shipment, good for D2C startups. 3PL selection criteria: geographic coverage (pin code serviceability critical in India), delivery speed (same-day/next-day availability), pricing structure (fixed vs variable, minimum commitments), technology integration (API availability, tracking, returns management), and value-added services (COD handling, packaging, installation). Pricing models: Per shipment (weight-based, zone-based - Rs 40-150 for 500g package to metros), Per pallet per month for warehousing (Rs 500-1500 depending on location), and Revenue share (2-4% of GMV for fulfillment services). GST on logistics services: Transportation of goods - 5% GST for GTA (no ITC available to transporter) or 12% GST (with ITC), Warehousing - 18% GST, Courier/Express - 18% GST. E-way bill required for interstate movement above Rs 50,000 and for intrastate in most states.',
    '["Map your logistics requirements (volume, geography, speed, special handling)", "Evaluate top 5 3PL providers against your requirements", "Negotiate terms with shortlisted 3PLs and compare total costs", "Select primary and backup 3PL partners with clear scope definition"]'::jsonb,
    '{"templates": ["3PL Requirements Specification", "Provider Evaluation Matrix", "Cost Comparison Template", "3PL Contract Checklist"], "tools": ["Pincode Coverage Analyzer", "Shipping Cost Calculator", "GST on Logistics Guide", "E-way Bill Requirement Checker"]}'::jsonb, 75, 50, 2, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_4_id, 18, 'Fulfillment Center Operations and Design',
    'Fulfillment centers in India are evolving from simple storage to sophisticated operations supporting same-day delivery and complex order profiles. Fulfillment center types: Traditional warehouse (storage focus, batch processing, longer cycle times), E-commerce fulfillment (piece-pick operations, high SKU variety, fast turnaround), Dark stores (small urban facilities for quick commerce, limited SKUs, immediate dispatch), and Micro-fulfillment (automated storage and retrieval, hyperlocal delivery). Location considerations: proximity to demand concentration (60% of e-commerce orders from top 10 cities), real estate costs (Mumbai Rs 20-30/sqft, Delhi NCR Rs 15-25, Bangalore Rs 12-20, tier 2 cities Rs 6-12), labor availability and cost, and transportation connectivity (highway access, rail/air links). Layout design principles: receiving area (5-10% of space), bulk storage (40-50% of space), pick area (20-30% with efficient pick paths), packing station (10-15% of space), dispatch area (5-10% of space), and returns processing (5% of space). Indian fulfillment metrics benchmarks: Orders per person per hour (piece-pick): 15-25 for manual, 40-60 with technology assist; Inventory accuracy: target 99.5%+ with cycle counting; Order accuracy: 99%+ with barcode verification; On-time dispatch: 98%+ for next-day orders. Technology enablers: Warehouse Management System (WMS) for inventory tracking and task management, handheld scanners for picking accuracy, put-to-light systems for multi-order picking, and conveyor systems for high-volume operations. Investment guidance: basic warehouse setup (racking, trolleys, basic WMS) Rs 200-500 per sqft, automated fulfillment Rs 1000-3000 per sqft. Start manual and automate based on volume and accuracy requirements.',
    '["Design fulfillment center layout based on order profiles and volume projections", "Define process flows for receiving, storage, picking, packing, and dispatch", "Establish operational metrics and targets for fulfillment performance", "Plan technology enablement roadmap from manual to automated operations"]'::jsonb,
    '{"templates": ["Fulfillment Center Layout Template", "Process Flow Documentation", "Operations Metrics Dashboard", "Technology Roadmap Framework"], "tools": ["Layout Design Calculator", "Process Time Study Template", "Productivity Benchmarking Tool", "Investment ROI Calculator"]}'::jsonb, 75, 50, 3, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_4_id, 19, 'Warehouse Management System (WMS) Selection',
    'WMS implementation is critical for inventory accuracy and operational efficiency, with options ranging from spreadsheets to sophisticated enterprise systems. WMS capability levels: Level 1 (Basic tracking) - spreadsheets/simple database, location tracking, basic inventory management, suitable for <1000 SKUs and <100 orders/day; Level 2 (Standard WMS) - barcode-based tracking, pick/pack/ship workflows, basic reporting, suitable for 1000-10000 SKUs and 100-1000 orders/day; Level 3 (Advanced WMS) - wave planning, slotting optimization, multi-warehouse, advanced analytics, suitable for 10000+ SKUs and 1000+ orders/day; Level 4 (Enterprise WMS) - integrated with ERP, automation integration, AI/ML capabilities, suitable for complex supply chains. Indian WMS options: Cloud SaaS solutions - Unicommerce (Rs 5,000-50,000/month, strong in e-commerce), Increff (Rs 10,000-1,00,000/month, omnichannel focus), Vinculum (Rs 15,000-75,000/month, B2B and B2C), Eshopbox (fulfillment with WMS included); On-premise solutions - Oracle WMS, SAP EWM (enterprise, Rs 50 lakhs+ implementation); Open source - Odoo inventory (free base, customization costs), ERPNext (Indian origin, warehouse module included). WMS selection criteria: functional fit (e-commerce vs B2B requirements), integration capability (ERP, e-commerce platforms, shipping), scalability (handle 10x volume growth), Indian compliance (GST, e-way bill integration), and total cost of ownership (license, implementation, support, customization). Implementation approach: start with MVP scope (basic receiving, putaway, picking, shipping), parallel run with existing system for 2-4 weeks, train users thoroughly (2-3 days minimum), and iterate based on operational feedback. Implementation timeline: cloud WMS 4-8 weeks, on-premise 3-6 months. Budget guidance: implementation cost typically 1-2x annual license cost.',
    '["Assess current inventory management maturity and identify gaps", "Define WMS requirements based on business needs and growth projections", "Evaluate 3-5 WMS options against requirements and budget", "Create WMS implementation plan with scope, timeline, and resources"]'::jsonb,
    '{"templates": ["WMS Requirements Document", "Vendor Evaluation Scorecard", "Implementation Project Plan", "User Training Curriculum"], "tools": ["Maturity Assessment Tool", "TCO Calculator WMS", "Integration Requirements Checklist", "Go-Live Readiness Assessment"]}'::jsonb, 75, 50, 4, NOW(), NOW()),

    (gen_random_uuid()::text, v_mod_4_id, 20, 'Inventory Optimization and Control',
    'Inventory optimization in India requires balancing high carrying costs with service level requirements and supply chain uncertainties. Safety stock calculation for India: Standard formula = Z x sigma x sqrt(L), where Z = service factor (1.65 for 95%, 2.33 for 99%), sigma = standard deviation of demand, L = lead time in days. India adjustments: add buffer for monsoon delays (additional 1-2 weeks stock June-September), consider supplier reliability factor (add 10-30% to calculated safety stock for unreliable suppliers), and account for festival demand spikes (build 2-4 weeks additional stock before Diwali). Reorder point optimization: ROP = (Average daily demand x Lead time) + Safety stock. Review lead times quarterly as Indian supply chains improve with infrastructure development. Indian lead time benchmarks: local procurement 1-2 weeks, domestic (interstate) 2-4 weeks, imports 6-12 weeks. Economic Order Quantity considerations: EOQ formula assumes stable demand and constant costs, less applicable in high-volatility Indian context. Modified approach: use EOQ as baseline, adjust for supplier minimum order quantities (often dictate order size in India), factor in transportation economics (full truck loads more efficient), and consider storage constraints. Inventory control processes: cycle counting (count 10-20% of SKUs weekly, focus on A items), physical inventory (annual full count, reconcile with books), shrinkage control (security, access control, CCTV), and expiry management (FEFO for perishables, quarterly expiry reviews). Dead stock management: identify slow-moving inventory (no movement in 6+ months), determine disposition (discount sale, donation, scrap), prevent recurrence through better demand planning, and write-off policies (typically 50% write-down after 12 months no movement, 100% after 24 months). Working capital impact: track inventory days of supply (DOS) monthly, benchmark against industry (30-45 days for FMCG, 60-90 days for durables, 90-180 days for fashion).',
    '["Calculate safety stock levels with India-specific adjustments for all A-class items", "Optimize reorder points based on current lead times and reliability", "Implement cycle counting program with focus on high-value inventory", "Create dead stock management process with clear disposition guidelines"]'::jsonb,
    '{"templates": ["Safety Stock Calculator India", "Reorder Point Optimization Template", "Cycle Count Program Design", "Dead Stock Disposition Policy"], "tools": ["Demand Variability Analyzer", "Lead Time Tracker", "Inventory Health Dashboard", "Working Capital Calculator"]}'::jsonb, 75, 50, 5, NOW(), NOW());

END $$;

COMMIT;
