-- P30: International Expansion Mastery Course Migration
-- 55 days, 11 modules, comprehensive global expansion guide

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
    v_mod_10_id TEXT;
    v_mod_11_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;
    v_mod_10_id := gen_random_uuid()::text;
    v_mod_11_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P30',
        'International Expansion Mastery',
        'Complete guide to taking your Indian startup global - 11 modules covering global strategy, FEMA compliance, US market entry, EU expansion, MENA & SEA markets, export procedures, international payments, global hiring with EOR, transfer pricing, international IP protection, and global tax optimization. Join the 500+ Indian startups succeeding globally.',
        9999,
        55,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P30';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: Global Strategy (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'Global Strategy', 'Master global expansion strategy - market selection, timing, entry modes, and building global competitive advantage', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'Global Expansion Fundamentals', 'Understand why and when Indian startups should go global. Learn from success stories of Freshworks, Zoho, InMobi, and others. Assess your readiness for international expansion. Define your global ambition and timeline.', '["Study 5 Indian global expansion success stories", "Complete global readiness assessment", "Define 3-year global vision", "Identify key expansion drivers for your business"]'::jsonb, '{"templates": ["Global Readiness Assessment", "Expansion Vision Framework"], "tools": ["Readiness Scorecard"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'Market Selection Framework', 'Build systematic market selection framework. Evaluate markets on size, growth, competition, and entry complexity. Understand market attractiveness vs competitive strength. Create prioritized market entry roadmap.', '["Research top 15 potential markets", "Score markets on 10 criteria", "Create market prioritization matrix", "Select top 3 markets for initial entry"]'::jsonb, '{"templates": ["Market Evaluation Scorecard", "Prioritization Matrix"], "tools": ["Market Selection Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'Entry Mode Selection', 'Evaluate entry modes: direct export, licensing, partnerships, subsidiaries, acquisitions. Understand trade-offs between control, investment, and risk. Match entry mode to market characteristics and company resources.', '["Evaluate entry modes for top 3 markets", "Analyze control vs investment trade-offs", "Select optimal entry mode per market", "Create entry mode decision framework"]'::jsonb, '{"templates": ["Entry Mode Decision Matrix", "Partnership vs Subsidiary Analysis"], "tools": ["Entry Mode Selector"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'Global Competitive Strategy', 'Build sustainable global competitive advantage. Understand global vs multi-domestic strategies. Leverage India cost advantage while building value proposition. Position against global and local competitors.', '["Define your global competitive advantage", "Analyze global vs local competitor positioning", "Create global value proposition", "Build competitive defense strategy"]'::jsonb, '{"templates": ["Global Competitive Analysis", "Value Proposition Canvas"], "tools": ["Competitive Intelligence Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Global Expansion Roadmap', 'Create comprehensive global expansion roadmap. Define milestones, resources, and success metrics. Build organizational alignment for global growth. Plan for contingencies and pivots.', '["Create 3-year expansion roadmap", "Define quarterly milestones", "Estimate resource requirements", "Build contingency plans"]'::jsonb, '{"templates": ["Global Expansion Roadmap", "Resource Planning Template"], "tools": ["Roadmap Builder"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: FEMA Compliance (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'FEMA Compliance', 'Master Foreign Exchange Management Act compliance for overseas investments, ODI procedures, and remittance regulations', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'FEMA Framework Overview', 'Understand FEMA regulations governing overseas investments. Learn about current account vs capital account transactions. Navigate RBI guidelines for outbound investments. Understand liberalized remittance scheme (LRS) limits.', '["Study FEMA regulations overview", "Understand current vs capital account", "Review RBI Master Directions on ODI", "Assess LRS applicability"]'::jsonb, '{"templates": ["FEMA Compliance Checklist", "Transaction Classification Guide"], "tools": ["FEMA Compliance Tracker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'Overseas Direct Investment', 'Master ODI regulations for setting up foreign subsidiaries. Understand automatic vs approval routes. Learn equity investment and loan limits. Navigate step-down subsidiary structures.', '["Determine ODI route for your expansion", "Calculate investment limits", "Design holding structure", "Prepare ODI documentation"]'::jsonb, '{"templates": ["ODI Application Template", "Investment Structure Framework"], "tools": ["ODI Limit Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'RBI Reporting Requirements', 'Master RBI reporting for overseas investments. Understand Form ODI, APR requirements, and timelines. Handle round-tripping and related party transaction reporting. Maintain compliance documentation.', '["Set up RBI reporting calendar", "Prepare Form ODI templates", "Create APR filing process", "Document compliance procedures"]'::jsonb, '{"templates": ["RBI Reporting Calendar", "Form ODI Guide"], "tools": ["Compliance Dashboard"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Cross-Border Payments', 'Navigate cross-border payment regulations. Understand remittance documentation requirements. Handle import-export payments compliance. Manage foreign currency accounts.', '["Set up cross-border payment workflow", "Prepare remittance documentation", "Open foreign currency accounts", "Create payment compliance checklist"]'::jsonb, '{"templates": ["Remittance Documentation Kit", "FX Account Comparison"], "tools": ["Cross-Border Payment Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'FEMA Compliance Best Practices', 'Build ongoing FEMA compliance system. Handle common compliance issues and penalties. Work with authorized dealers effectively. Stay updated on regulatory changes.', '["Create FEMA compliance manual", "Select AD bank partner", "Set up compliance monitoring", "Build regulatory update process"]'::jsonb, '{"templates": ["FEMA Compliance Manual", "AD Bank RFP"], "tools": ["Regulatory Update Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: US Market Entry (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'US Market Entry', 'Master US market entry - entity setup, Delaware incorporation, US banking, sales strategy, and compliance', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'US Market Opportunity', 'Understand the US market opportunity for Indian startups. Analyze market size, customer preferences, and competitive landscape. Learn cultural nuances affecting B2B and B2C sales. Define US go-to-market strategy.', '["Research US market size for your segment", "Analyze US competitor landscape", "Study cultural selling differences", "Define US GTM strategy"]'::jsonb, '{"templates": ["US Market Analysis Framework", "US GTM Strategy Template"], "tools": ["US Market Research Platform"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'US Entity Formation', 'Set up US legal entity - Delaware C-Corp vs LLC. Understand incorporation process and costs. Handle registered agent and compliance requirements. Structure parent-subsidiary relationship.', '["Select entity type (C-Corp vs LLC)", "Complete Delaware incorporation", "Set up registered agent", "File FEMA ODI documentation"]'::jsonb, '{"templates": ["US Incorporation Checklist", "Entity Comparison Matrix"], "tools": ["Incorporation Cost Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'US Banking & Payments', 'Set up US banking infrastructure. Open US business bank accounts. Integrate US payment gateways. Handle ACH, wire transfers, and card payments.', '["Research US bank options", "Open US business account", "Set up Stripe/payment gateway", "Configure payment methods"]'::jsonb, '{"templates": ["US Bank Comparison", "Payment Integration Checklist"], "tools": ["US Banking Setup Guide"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'US Sales & Marketing', 'Build US sales and marketing engine. Hire US sales team (local vs remote). Adapt marketing for US audience. Handle US customer success and support.', '["Design US sales team structure", "Create US marketing playbook", "Set up US customer support", "Define US pricing strategy"]'::jsonb, '{"templates": ["US Sales Playbook", "US Marketing Framework"], "tools": ["US Hiring Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'US Compliance & Tax', 'Navigate US compliance requirements. Understand state nexus and sales tax. Handle federal and state tax obligations. Maintain ongoing compliance.', '["Determine state nexus obligations", "Set up sales tax collection", "Understand federal tax requirements", "Create compliance calendar"]'::jsonb, '{"templates": ["US Compliance Checklist", "Sales Tax Guide"], "tools": ["US Tax Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: EU Market Entry (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'EU Market Entry', 'Master European Union market entry - single market access, GDPR compliance, VAT, and country selection', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'EU Market Fundamentals', 'Understand EU single market opportunity. Navigate 27-country market with single regulations. Select optimal entry country (Netherlands, Ireland, Germany). Understand post-Brexit UK considerations.', '["Analyze EU market opportunity", "Evaluate entry country options", "Understand single market benefits", "Assess UK market separately"]'::jsonb, '{"templates": ["EU Market Analysis", "Country Selection Matrix"], "tools": ["EU Market Comparator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'EU Entity Setup', 'Set up EU legal entity. Compare Netherlands BV, Irish Limited, German GmbH. Understand local director requirements. Handle parent-subsidiary structuring.', '["Select EU entity jurisdiction", "Complete incorporation process", "Appoint local directors if required", "Structure ownership properly"]'::jsonb, '{"templates": ["EU Entity Comparison", "Incorporation Checklist"], "tools": ["EU Incorporation Guide"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'GDPR Compliance', 'Achieve GDPR compliance for EU operations. Implement data protection requirements. Handle data transfer mechanisms. Appoint DPO if required and manage ongoing compliance.', '["Complete GDPR compliance assessment", "Implement required measures", "Set up data transfer mechanisms", "Create GDPR documentation"]'::jsonb, '{"templates": ["GDPR Compliance Checklist", "DPA Templates"], "tools": ["GDPR Compliance Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'EU VAT Management', 'Navigate EU VAT requirements. Understand VAT registration, OSS, and reverse charge. Handle B2B vs B2C VAT treatment. Implement VAT-compliant invoicing.', '["Determine VAT registration requirements", "Register for OSS if applicable", "Implement VAT-compliant invoicing", "Set up VAT reporting"]'::jsonb, '{"templates": ["EU VAT Guide", "VAT Registration Checklist"], "tools": ["VAT Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'EU Go-to-Market', 'Build EU sales and marketing strategy. Adapt for cultural differences across countries. Handle multi-language requirements. Build EU partner ecosystem.', '["Create EU GTM strategy", "Plan localization priorities", "Build EU partner network", "Set up EU customer success"]'::jsonb, '{"templates": ["EU GTM Framework", "Localization Roadmap"], "tools": ["EU Partner Database"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: MENA & SEA Markets (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'MENA & SEA Markets', 'Expand to Middle East, North Africa, and Southeast Asia - market dynamics, entry strategies, and local partnerships', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'MENA Market Entry', 'Understand MENA market dynamics. Navigate UAE, Saudi Arabia, and other GCC markets. Leverage India-MENA business corridors. Handle cultural and regulatory nuances.', '["Analyze MENA market opportunity", "Select target GCC countries", "Understand regulatory requirements", "Build cultural knowledge"]'::jsonb, '{"templates": ["MENA Market Analysis", "GCC Entry Framework"], "tools": ["MENA Market Guide"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'UAE & Dubai Setup', 'Set up UAE operations. Compare mainland, free zone, and offshore options. Navigate visa and employment requirements. Handle UAE banking and payments.', '["Select UAE setup type", "Complete company formation", "Obtain required licenses", "Set up UAE banking"]'::jsonb, '{"templates": ["UAE Entity Comparison", "Free Zone Guide"], "tools": ["UAE Setup Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Southeast Asia Strategy', 'Enter Southeast Asian markets strategically. Prioritize between Singapore, Indonesia, Vietnam, Thailand. Understand ASEAN trade agreements. Leverage India-SEA proximity.', '["Analyze SEA market priorities", "Select entry countries", "Understand ASEAN benefits", "Plan SEA expansion sequence"]'::jsonb, '{"templates": ["SEA Market Framework", "ASEAN Trade Guide"], "tools": ["SEA Market Comparator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'Singapore as Regional Hub', 'Use Singapore as SEA regional hub. Understand Singapore company formation. Leverage Singapore-India DTAA and investment treaties. Build regional operations from Singapore.', '["Evaluate Singapore hub strategy", "Set up Singapore entity", "Understand tax benefits", "Plan regional operations"]'::jsonb, '{"templates": ["Singapore Incorporation Guide", "Regional Hub Framework"], "tools": ["Singapore Setup Guide"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Emerging Market Partnerships', 'Build local partnerships for emerging market success. Work with distributors and resellers. Navigate local business customs. Handle local payment collection challenges.', '["Identify potential local partners", "Design partnership structure", "Create partner agreements", "Set up local collection methods"]'::jsonb, '{"templates": ["Partner Evaluation Framework", "Distribution Agreement"], "tools": ["Partner Management Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Export Procedures (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Export Procedures', 'Master export procedures - IEC, shipping documentation, customs compliance, and export incentives', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'Export Fundamentals', 'Understand export regulations and procedures from India. Learn about DGFT and export policies. Navigate export of goods vs services. Understand software and SaaS export classification.', '["Study DGFT export policies", "Understand goods vs services export", "Classify your export category", "Review export restrictions"]'::jsonb, '{"templates": ["Export Classification Guide", "DGFT Policy Summary"], "tools": ["Export Classifier"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'IEC Registration', 'Obtain Import Export Code (IEC) for international trade. Complete DGFT registration process. Handle AD Code registration with banks. Maintain IEC compliance and updates.', '["Apply for IEC registration", "Complete AD Code registration", "Set up export banking", "Create compliance calendar"]'::jsonb, '{"templates": ["IEC Application Guide", "AD Code Registration Checklist"], "tools": ["IEC Registration Portal"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Export Documentation', 'Master export documentation - invoices, shipping bills, bills of lading. Handle certificate of origin and other trade documents. Implement documentation automation.', '["Create export invoice templates", "Understand shipping documentation", "Set up certificate of origin process", "Automate documentation workflow"]'::jsonb, '{"templates": ["Export Invoice Template", "Documentation Checklist"], "tools": ["Export Document Generator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Customs & Compliance', 'Navigate customs procedures for exports. Understand HS codes and duty drawback. Handle customs audits and assessments. Build customs compliance program.', '["Determine HS codes for products", "Understand duty drawback eligibility", "Create customs compliance process", "Select customs broker"]'::jsonb, '{"templates": ["HS Code Classification Guide", "Customs Compliance Checklist"], "tools": ["HS Code Finder"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Export Incentives', 'Maximize export incentives - RoDTEP, SEZ benefits, export credit. Understand SEIS and EPCG schemes. Leverage trade agreements and preferential tariffs. Calculate total export benefit potential.', '["Evaluate RoDTEP eligibility", "Assess SEZ benefits", "Understand trade agreement benefits", "Calculate total incentive potential"]'::jsonb, '{"templates": ["Export Incentive Calculator", "Scheme Comparison Matrix"], "tools": ["Incentive Eligibility Checker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: International Payments (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'International Payments', 'Master international payments - multi-currency accounts, payment gateways, FX management, and collection optimization', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'Global Payment Infrastructure', 'Build global payment infrastructure. Understand payment methods by region. Select payment gateways for international markets. Handle multi-currency complexity.', '["Map payment preferences by market", "Evaluate global payment gateways", "Design payment infrastructure", "Plan multi-currency support"]'::jsonb, '{"templates": ["Payment Method Matrix", "Gateway Comparison"], "tools": ["Payment Infrastructure Planner"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Multi-Currency Management', 'Manage multi-currency operations. Set up currency accounts and hedging. Handle FX conversion and optimization. Build treasury management processes.', '["Open multi-currency accounts", "Design FX hedging strategy", "Implement conversion optimization", "Create treasury processes"]'::jsonb, '{"templates": ["Currency Management Guide", "FX Hedging Framework"], "tools": ["FX Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Collection Optimization', 'Optimize international collections. Handle payment failures and retries. Implement dunning for global customers. Reduce involuntary churn from payment failures.', '["Analyze collection success rates", "Implement smart retries", "Design global dunning sequence", "Reduce payment failure churn"]'::jsonb, '{"templates": ["Dunning Sequence Template", "Collection Optimization Guide"], "tools": ["Payment Analytics Dashboard"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Cross-Border Reconciliation', 'Implement cross-border payment reconciliation. Handle multi-entity and multi-currency accounting. Automate reconciliation processes. Build financial controls.', '["Design reconciliation process", "Implement automation tools", "Handle multi-currency accounting", "Build financial controls"]'::jsonb, '{"templates": ["Reconciliation Workflow", "Multi-Currency Accounting Guide"], "tools": ["Reconciliation Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'Payment Compliance', 'Navigate payment compliance globally. Handle KYC and AML requirements. Understand sanctions screening. Build payment compliance program.', '["Understand KYC requirements", "Implement AML screening", "Set up sanctions compliance", "Create compliance documentation"]'::jsonb, '{"templates": ["Payment Compliance Checklist", "KYC Documentation Guide"], "tools": ["Compliance Screening Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Global Hiring (EOR) (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Global Hiring (EOR)', 'Master global hiring with Employer of Record - hire anywhere without entities, compliance, and contractor management', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Global Hiring Options', 'Understand global hiring options: own entity, EOR, contractors. Compare cost, compliance, and control trade-offs. Decide when to use each option. Build global hiring strategy.', '["Evaluate hiring options by country", "Compare EOR vs entity costs", "Define hiring strategy by market", "Create decision framework"]'::jsonb, '{"templates": ["Hiring Options Comparison", "Global Hiring Strategy"], "tools": ["Hiring Cost Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Employer of Record (EOR)', 'Master EOR model for global hiring. Select EOR provider (Deel, Remote, Oyster, Velocity Global). Understand EOR compliance and limitations. Manage EOR relationships.', '["Evaluate EOR providers", "Understand service scope and limits", "Negotiate EOR contracts", "Set up EOR partnership"]'::jsonb, '{"templates": ["EOR Provider Comparison", "EOR Contract Checklist"], "tools": ["EOR Selection Tool"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Contractor Compliance', 'Manage international contractors compliantly. Understand contractor vs employee classification risks. Handle contractor agreements across jurisdictions. Avoid permanent establishment risks.', '["Assess contractor classification", "Create compliant contractor agreements", "Understand PE risks", "Set up contractor management"]'::jsonb, '{"templates": ["Contractor Agreement Template", "Classification Checklist"], "tools": ["Contractor Compliance Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Global Compensation Design', 'Design globally competitive compensation. Handle geographic pay differentials. Build global equity programs. Navigate local benefits requirements.', '["Research global compensation benchmarks", "Design geographic pay policy", "Structure global equity grants", "Plan local benefits"]'::jsonb, '{"templates": ["Global Compensation Framework", "Equity Grant Guidelines"], "tools": ["Global Salary Benchmarking"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Global Team Operations', 'Build effective global team operations. Handle timezone collaboration. Create global onboarding and culture. Manage distributed team performance.', '["Design global team structure", "Create timezone collaboration norms", "Build global onboarding program", "Set up distributed performance management"]'::jsonb, '{"templates": ["Global Team Playbook", "Distributed Work Guide"], "tools": ["Global Team Collaboration Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: Transfer Pricing (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'Transfer Pricing', 'Master transfer pricing for multi-entity structures - arm''s length pricing, documentation, and compliance', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'Transfer Pricing Fundamentals', 'Understand transfer pricing principles. Learn arm''s length standard and its application. Navigate OECD guidelines and Indian TP regulations. Identify intercompany transactions requiring TP.', '["Study transfer pricing fundamentals", "Identify intercompany transactions", "Understand arm''s length principle", "Map TP requirements"]'::jsonb, '{"templates": ["Transfer Pricing Overview", "Transaction Mapping Template"], "tools": ["TP Requirement Checker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Transfer Pricing Methods', 'Master TP methods: CUP, TNMM, cost plus, resale price, profit split. Select appropriate methods for different transactions. Document method selection rationale. Handle benchmarking studies.', '["Understand TP methods", "Select methods for your transactions", "Document selection rationale", "Plan benchmarking approach"]'::jsonb, '{"templates": ["TP Method Selection Guide", "Benchmarking Framework"], "tools": ["TP Method Selector"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'TP Documentation', 'Build transfer pricing documentation. Prepare Master File and Local File. Handle Country-by-Country Reporting. Maintain contemporaneous documentation.', '["Create Master File structure", "Prepare Local File", "Understand CbCR requirements", "Set up documentation process"]'::jsonb, '{"templates": ["Master File Template", "Local File Template"], "tools": ["TP Documentation Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'Intercompany Agreements', 'Structure intercompany agreements for TP compliance. Handle service agreements, IP licenses, and cost sharing. Document business rationale. Align agreements with TP policy.', '["Draft intercompany service agreement", "Create IP licensing framework", "Document business rationale", "Align with TP documentation"]'::jsonb, '{"templates": ["Intercompany Agreement Templates", "IP License Framework"], "tools": ["Agreement Generator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'TP Compliance & Audits', 'Manage ongoing TP compliance. Handle TP audits and assessments. Navigate dispute resolution mechanisms. Build TP risk management.', '["Set up TP compliance calendar", "Prepare for potential audits", "Understand dispute resolution", "Build TP risk framework"]'::jsonb, '{"templates": ["TP Compliance Calendar", "Audit Preparation Guide"], "tools": ["TP Risk Assessment"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 10: International IP (Days 46-50)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_10_id, v_product_id, 'International IP', 'Protect intellectual property globally - international patents, trademarks, and IP strategy for global expansion', 10, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_10_id, 46, 'Global IP Strategy', 'Build global IP protection strategy. Prioritize markets for IP registration. Understand territorial nature of IP rights. Balance protection costs with business value.', '["Assess IP portfolio", "Prioritize markets for protection", "Create IP protection roadmap", "Budget for global IP"]'::jsonb, '{"templates": ["Global IP Strategy Framework", "Market Prioritization Matrix"], "tools": ["IP Budget Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 47, 'International Patents', 'Navigate international patent protection. Understand PCT system and national phase. Handle patent prosecution in key markets. Manage patent portfolio globally.', '["Evaluate PCT filing strategy", "Plan national phase entries", "Select patent counsel by country", "Create patent management process"]'::jsonb, '{"templates": ["PCT Filing Guide", "Patent Portfolio Tracker"], "tools": ["Patent Cost Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 48, 'Global Trademark Protection', 'Protect trademarks internationally. Use Madrid Protocol for multi-country registration. Handle trademark prosecution and opposition. Build trademark monitoring program.', '["Conduct global trademark search", "File Madrid Protocol application", "Monitor for infringement", "Handle oppositions"]'::jsonb, '{"templates": ["Madrid Filing Guide", "Trademark Monitoring Checklist"], "tools": ["Trademark Search Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 49, 'IP Licensing International', 'Structure international IP licensing. Handle cross-border royalties and withholding taxes. Draft international license agreements. Manage IP holding company structures.', '["Design IP licensing structure", "Understand withholding tax implications", "Draft international license", "Evaluate IP holding options"]'::jsonb, '{"templates": ["International License Template", "IP Structure Analysis"], "tools": ["Royalty Tax Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 50, 'IP Enforcement Global', 'Enforce IP rights globally. Handle cross-border infringement. Work with customs for border protection. Build enforcement strategy and budget.', '["Identify infringement risks", "Develop enforcement strategy", "Register with customs authorities", "Budget for enforcement actions"]'::jsonb, '{"templates": ["Enforcement Strategy Template", "Customs Registration Guide"], "tools": ["Infringement Monitoring Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 11: Global Tax Optimization (Days 51-55)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_11_id, v_product_id, 'Global Tax Optimization', 'Optimize global tax structure - DTAA benefits, holding structures, permanent establishment, and compliance', 11, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_11_id, 51, 'International Tax Fundamentals', 'Understand international tax principles. Navigate residence vs source taxation. Learn about tax treaties and their benefits. Build tax-efficient global structure.', '["Study international tax basics", "Map taxation of global income", "Review relevant tax treaties", "Design tax-efficient structure"]'::jsonb, '{"templates": ["International Tax Overview", "Tax Structure Framework"], "tools": ["Tax Treaty Database"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 52, 'DTAA Optimization', 'Leverage Double Tax Avoidance Agreements. Understand India''s DTAA network. Optimize withholding taxes on cross-border payments. Handle treaty benefit claims.', '["Review applicable DTAAs", "Optimize withholding tax rates", "Set up treaty benefit claims", "Document treaty positions"]'::jsonb, '{"templates": ["DTAA Analysis Template", "WHT Optimization Guide"], "tools": ["DTAA Rate Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 53, 'Holding Structure Design', 'Design optimal holding structure. Evaluate Singapore, Netherlands, UAE options. Handle substance requirements. Navigate CFC and POEM rules.', '["Evaluate holding company jurisdictions", "Design holding structure", "Plan substance requirements", "Understand CFC implications"]'::jsonb, '{"templates": ["Holding Structure Comparison", "Substance Checklist"], "tools": ["Structure Optimizer"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 54, 'Permanent Establishment', 'Manage permanent establishment risks. Understand PE triggers in key markets. Handle digital PE and service PE rules. Build PE risk mitigation.', '["Assess PE risks by country", "Understand digital PE rules", "Create PE mitigation strategies", "Monitor activities for PE"]'::jsonb, '{"templates": ["PE Risk Assessment", "PE Mitigation Checklist"], "tools": ["PE Risk Analyzer"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 55, 'Global Tax Compliance', 'Build global tax compliance program. Handle multi-jurisdiction filing requirements. Manage tax audits across countries. Stay current on global tax changes.', '["Create global tax calendar", "Set up multi-country compliance", "Build audit management process", "Monitor regulatory changes"]'::jsonb, '{"templates": ["Global Tax Calendar", "Compliance Tracker"], "tools": ["Tax Compliance Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
