-- P23: EV & Clean Mobility Course Migration
-- 55 days, 11 modules, comprehensive EV startup mastery for India

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
    v_mod_10_id TEXT;
    v_mod_11_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;
    v_mod_10_id := gen_random_uuid()::text;
    v_mod_11_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P23',
        'EV & Clean Mobility Mastery',
        'Complete guide to building EV startups in India - 11 modules covering FAME II subsidies, PLI schemes, battery supply chain, vehicle homologation, charging infrastructure, and scaling strategies. India targets 30% EV penetration by 2030.',
        8999,
        55,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P23';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: EV Landscape India (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'EV Landscape India', 'Understand India''s EV ecosystem - market size, key players, government vision, and emerging opportunities', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'India EV Market Overview', 'India''s EV market is projected to reach $206 billion by 2030. Understand the current state: 2-wheelers dominate with 70% share, 3-wheelers at 20%, and 4-wheelers growing rapidly. Key players include Ola Electric, Ather Energy, Tata Motors, and MG Motor. The government''s vision targets 30% EV penetration by 2030 under the National Electric Mobility Mission Plan.', '["Research current EV sales data by segment", "Map top 10 EV players in your target segment", "Identify 3 underserved EV niches in India", "Calculate TAM, SAM, SOM for your EV opportunity"]'::jsonb, '{"templates": ["EV Market Analysis Framework", "Competitor Mapping Matrix"], "tools": ["EV Market Size Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'EV Value Chain Deep Dive', 'Master the EV value chain: raw materials (lithium, cobalt, nickel), cell manufacturing, battery packs, motors, controllers, vehicle assembly, charging infrastructure, and aftermarket services. Understand where value is created and margins are highest. Identify India-specific supply chain gaps and import dependencies.', '["Map the complete EV value chain for your segment", "Identify 5 value chain positions for startups", "Calculate import dependency percentage", "List domestic vs imported component ratios"]'::jsonb, '{"templates": ["EV Value Chain Map", "Supply Chain Analysis Template"], "tools": ["Value Chain Position Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'Government EV Vision & Policy', 'Navigate India''s EV policy framework: National Electric Mobility Mission Plan (NEMMP), FAME I & II, PLI schemes, state EV policies. Understand the policy timeline and upcoming changes. Learn how different ministries (Heavy Industries, Power, Road Transport) coordinate on EV policy.', '["Study NEMMP 2020 key objectives", "Map FAME II subsidy structure", "List all state EV policies relevant to your segment", "Create policy compliance checklist"]'::jsonb, '{"templates": ["Policy Compliance Matrix", "Government Scheme Navigator"], "tools": ["Policy Update Tracker"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'EV Startup Success Stories', 'Learn from Indian EV unicorns and emerging players. Ola Electric: ₹7,000 crore valuation, from ride-hailing to manufacturing. Ather Energy: premium positioning, vertical integration. Euler Motors: B2B focus on commercial EVs. Sun Mobility: battery swapping innovation. Understand their strategies, pivots, and funding journeys.', '["Analyze 5 successful Indian EV startups", "Document their go-to-market strategies", "Identify their key differentiators", "Map their funding rounds and investors"]'::jsonb, '{"templates": ["Startup Case Study Template", "Success Factor Analysis"], "tools": ["Funding Journey Mapper"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Identifying Your EV Opportunity', 'Define your EV startup opportunity based on market gaps, your expertise, and available capital. Choose between manufacturing, charging infrastructure, software/fleet management, battery services, or aftermarket. Validate with customer interviews and competitive analysis.', '["Complete EV opportunity assessment", "Conduct 10 customer discovery interviews", "Define your unique value proposition", "Create initial business model canvas"]'::jsonb, '{"templates": ["EV Opportunity Canvas", "Customer Interview Guide"], "tools": ["Opportunity Scoring Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: FAME II Subsidies (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'FAME II Subsidies', 'Master FAME II scheme navigation - eligibility, application process, subsidy calculations, and compliance requirements', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'FAME II Scheme Overview', 'FAME II (Faster Adoption and Manufacturing of Electric Vehicles) has ₹10,000 crore outlay till 2024. Understand the three components: Demand Incentive (subsidies to buyers), Charging Infrastructure, and Administrative/publicity. Learn eligibility criteria: minimum 50% localization, speed and range requirements, and battery specifications.', '["Study FAME II scheme document thoroughly", "Calculate applicable subsidy for your vehicle category", "Verify 50% localization requirement feasibility", "List all technical specifications to meet"]'::jsonb, '{"templates": ["FAME II Eligibility Checklist", "Subsidy Calculation Sheet"], "tools": ["Localization Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'FAME II Application Process', 'Navigate the application process through the FAME portal. Understand OEM registration requirements, model approval process, and demand incentive claims. Learn documentation requirements: type approval certificates, battery test reports, localization certificates, and ICAT/ARAI approvals.', '["Register on FAME India portal", "Compile documentation checklist", "Prepare localization value addition certificate", "Schedule pre-submission consultation with DHI"]'::jsonb, '{"templates": ["FAME Application Checklist", "Document Preparation Guide"], "tools": ["Application Tracker"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'Subsidy Calculations by Segment', 'Master subsidy calculations: 2-wheelers get ₹15,000/kWh (max 40% of vehicle cost), 3-wheelers get ₹10,000/kWh, buses get ₹20,000/kWh. Understand the cap limits and how to optimize vehicle design for maximum subsidy. Calculate effective price reduction and competitive advantage.', '["Calculate subsidy for each planned vehicle model", "Optimize battery size for maximum subsidy benefit", "Model final customer price with subsidy", "Compare with non-FAME competitors"]'::jsonb, '{"templates": ["Subsidy Calculator by Segment", "Price Optimization Model"], "tools": ["FAME Subsidy Optimizer"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Localization Requirements', 'Achieve 50% localization value addition as per phased manufacturing program (PMP). Understand which components count: motors (local), batteries (assembly), controllers, chargers. Navigate the value addition calculation methodology. Plan for increasing localization over time as per government roadmap.', '["Map current localization percentage", "Identify components for domestic sourcing", "Calculate value addition for each component", "Create phased localization roadmap"]'::jsonb, '{"templates": ["Localization Calculation Sheet", "PMP Compliance Tracker"], "tools": ["Value Addition Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'FAME II Compliance & Reporting', 'Maintain ongoing compliance: quarterly sales reporting, subsidy claim process, audit requirements. Handle common issues: delayed approvals, document rejections, compliance notices. Stay updated on policy changes and extensions. Build relationships with DHI officials.', '["Set up quarterly reporting calendar", "Create compliance documentation system", "Establish DHI relationship contacts", "Prepare for FAME II audit"]'::jsonb, '{"templates": ["Compliance Reporting Template", "Audit Preparation Guide"], "tools": ["FAME Compliance Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: PLI Scheme Navigation (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'PLI Scheme Navigation', 'Access ₹26,000 crore PLI schemes for Advanced Chemistry Cells and Auto components', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'PLI ACC Battery Scheme', 'The PLI scheme for Advanced Chemistry Cell (ACC) has ₹18,100 crore outlay. Understand eligibility: minimum 5 GWh capacity, domestic value addition of 60% by year 5. Learn about the 10 selected companies and opportunity for component suppliers. Subsidy of ₹2,000-3,000/kWh for 5 years based on capacity utilization.', '["Study PLI ACC scheme guidelines", "Assess eligibility for your company", "Identify partnership opportunities with selected companies", "Calculate potential subsidy value"]'::jsonb, '{"templates": ["PLI ACC Application Guide", "Capacity Planning Template"], "tools": ["PLI Subsidy Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'PLI Auto Components Scheme', 'PLI for Auto and Auto Components has ₹25,938 crore outlay. Focus areas: EV components (motors, controllers, battery management systems), hydrogen fuel cells, and advanced automotive technology products. Minimum investment of ₹500 crore for Champion OEM Incentive and ₹10 crore for Component Champion Incentive.', '["Review PLI auto components categories", "Identify applicable product categories", "Calculate minimum investment requirements", "Assess 5-year sales growth targets"]'::jsonb, '{"templates": ["PLI Auto Application Template", "Investment Planning Sheet"], "tools": ["Sales Projection Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'PLI Application Strategy', 'Build a winning PLI application. Understand evaluation criteria: investment commitment, job creation, technology capability, and export potential. Prepare detailed project reports with 5-year projections. Navigate the application portal and submission requirements.', '["Create detailed project report (DPR)", "Document technology capabilities", "Prepare investment and employment projections", "Submit letter of intent"]'::jsonb, '{"templates": ["PLI DPR Template", "Project Feasibility Report"], "tools": ["PLI Application Tracker"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'Combining FAME II and PLI Benefits', 'Maximize benefits by combining schemes. A manufacturer can get FAME II demand-side subsidy AND PLI production-side incentive. Understand how to structure operations for dual benefit. Navigate compliance requirements for multiple schemes simultaneously.', '["Map all applicable government schemes", "Calculate combined benefit potential", "Structure entity for maximum benefit capture", "Create unified compliance calendar"]'::jsonb, '{"templates": ["Multi-Scheme Benefit Calculator", "Scheme Stacking Strategy"], "tools": ["Combined Compliance Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'State-Level EV Incentives', 'Layer state incentives on top of central schemes. Gujarat offers 100% road tax exemption and ₹10,000/kWh capital subsidy. Maharashtra provides 15% capital subsidy. Karnataka, Tamil Nadu, and Telangana have aggressive EV policies. Choose manufacturing location based on combined incentive optimization.', '["Compare state EV policies for your segment", "Calculate location-wise incentive value", "Identify optimal manufacturing state", "Apply for state-level incentives"]'::jsonb, '{"templates": ["State Incentive Comparison", "Location Decision Matrix"], "tools": ["State Benefit Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Battery Supply Chain (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Battery Supply Chain', 'Master lithium-ion battery sourcing, cell procurement, pack assembly, and BMS development', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Battery Technology Fundamentals', 'Understand lithium-ion chemistry options: NMC (high energy density, expensive), LFP (safer, longer life, cheaper), and NCA (Tesla''s choice). Compare for Indian conditions: temperature sensitivity, cycle life, cost per kWh. LFP is increasingly preferred for price-sensitive Indian market. Learn about solid-state batteries as future technology.', '["Compare battery chemistries for your application", "Calculate cost per kWh for each chemistry", "Assess thermal management requirements", "Select optimal chemistry for your product"]'::jsonb, '{"templates": ["Battery Chemistry Comparison", "Cost Analysis Template"], "tools": ["Battery Selection Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'Cell Sourcing from China & Korea', 'Navigate international cell procurement. Major suppliers: CATL, BYD, EVE, CALB (China), Samsung SDI, LG Chem, SK Innovation (Korea). Understand pricing dynamics: $100-150/kWh for cells. Handle import duties (5-15%), minimum order quantities, and lead times. Build relationships with tier-1 suppliers.', '["Identify 5 potential cell suppliers", "Request quotes from 3 suppliers", "Negotiate MOQs and payment terms", "Evaluate supplier reliability and certifications"]'::jsonb, '{"templates": ["Supplier Evaluation Scorecard", "RFQ Template"], "tools": ["Import Duty Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'Battery Pack Assembly', 'Set up battery pack assembly operations. Design pack architecture: modules, cooling system, housing. Choose between air cooling and liquid cooling based on application. Understand spot welding, laser welding, and wire bonding. Calculate assembly costs: typically 20-30% of cell cost. Plan for ARAI/ICAT battery testing and certification.', '["Design battery pack architecture", "Calculate assembly cost per unit", "Plan production line layout", "Get quotes for assembly equipment"]'::jsonb, '{"templates": ["Pack Assembly Checklist", "Production Line Layout"], "tools": ["Assembly Cost Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Battery Management System (BMS)', 'Develop or source BMS - the brain of the battery. Key functions: cell balancing, thermal management, state of charge estimation, safety cutoffs. Options: buy proven BMS (Orion, Daly, JBD) or develop in-house for differentiation. Understand BMS-vehicle communication protocols (CAN bus). BMS software is critical IP.', '["Define BMS requirements for your application", "Evaluate buy vs build decision", "Get quotes from BMS suppliers", "Plan BMS software development if building"]'::jsonb, '{"templates": ["BMS Specification Template", "Make vs Buy Analysis"], "tools": ["BMS Comparison Tool"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Battery Testing & Certification', 'Navigate AIS 156 and AIS 038 battery safety standards. Understand test requirements: nail penetration, thermal runaway, crush test, vibration. Get testing done at ICAT, ARAI, or CIRT. Typical testing takes 3-6 months and costs ₹10-25 lakhs. Plan for battery warranty and replacement strategy.', '["Study AIS 156 and AIS 038 requirements", "Schedule testing slots at approved agencies", "Prepare battery samples for testing", "Create battery warranty policy"]'::jsonb, '{"templates": ["AIS Compliance Checklist", "Testing Schedule Template"], "tools": ["Battery Certification Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: Vehicle Homologation (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'Vehicle Homologation', 'Navigate CMVR compliance, type approval, ARAI/ICAT testing, and road-worthiness certification', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'CMVR Compliance Framework', 'Master Central Motor Vehicles Rules (CMVR) requirements for EVs. Understand vehicle categories: L1/L2 (2-wheelers), L5 (3-wheelers), M1 (cars), M2/M3 (buses), N1/N2/N3 (commercial). Each category has specific requirements. Learn about AIS standards that apply to your vehicle type.', '["Identify CMVR category for your vehicle", "List all applicable AIS standards", "Create compliance requirement matrix", "Plan type approval timeline"]'::jsonb, '{"templates": ["CMVR Category Guide", "AIS Standards Matrix"], "tools": ["Compliance Requirement Checker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'Type Approval Process', 'Navigate the type approval process through ARAI (Pune) or ICAT (Manesar). Understand the sequence: component approval → prototype submission → testing → certification. Timeline: 4-8 months typically. Cost: ₹30-80 lakhs depending on vehicle type. Handle common rejection reasons and resubmission process.', '["Book slots at ARAI/ICAT", "Prepare complete vehicle documentation", "Submit prototype for evaluation", "Create timeline with milestones"]'::jsonb, '{"templates": ["Type Approval Checklist", "Documentation Guide"], "tools": ["Approval Timeline Tracker"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Vehicle Testing Requirements', 'Understand mandatory tests: performance (speed, range, gradeability), safety (crash test for M1 vehicles, ABS for 2-wheelers), EMC/EMI compliance, noise levels. Prepare test vehicles and documentation. Handle test failures and retesting. Budget for testing: ₹20-50 lakhs.', '["List all mandatory tests for your vehicle", "Prepare test vehicle to specifications", "Budget for testing costs", "Create contingency plan for test failures"]'::jsonb, '{"templates": ["Testing Requirements Checklist", "Test Vehicle Preparation Guide"], "tools": ["Testing Cost Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'Production Conformity (CoP)', 'Obtain Conformity of Production (CoP) certification. Demonstrate that production vehicles match type-approved prototype. Set up quality management system (QMS). Handle CoP audits: initial and surveillance. Maintain production records and traceability.', '["Implement quality management system", "Set up production traceability", "Prepare for CoP audit", "Create audit documentation"]'::jsonb, '{"templates": ["QMS Implementation Guide", "CoP Audit Checklist"], "tools": ["Production Conformity Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Registration & Road Permit', 'Navigate vehicle registration process for EVs. Understand green number plates and registration exemptions. Handle commercial vehicle permits for e-rickshaws and cargo EVs. Process state transport authority (STA) approvals. Manage fleet registration for B2B customers.', '["Understand registration requirements by state", "Prepare registration documentation", "Apply for commercial permits if applicable", "Create customer registration support process"]'::jsonb, '{"templates": ["Registration Guide by State", "Permit Application Template"], "tools": ["Registration Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: EV Charging Infrastructure (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'EV Charging Infrastructure', 'Build or integrate charging solutions - home, public, and DC fast charging networks', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'Charging Technology Overview', 'Understand charging types: AC slow (3.3-7 kW home charging), AC fast (11-22 kW workplace), DC fast (50-150 kW highway). Learn about charging standards: Bharat DC-001, CCS2, CHAdeMO, and GB/T. India mandates CCS2 for DC charging. Understand charging time calculations and battery health impact.', '["Map charging requirements for your vehicle", "Select charging connector standards", "Calculate charging times for different scenarios", "Design home charger specifications"]'::jsonb, '{"templates": ["Charging Standards Guide", "Connector Selection Matrix"], "tools": ["Charging Time Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'Home Charging Solutions', 'Design home charging offerings. Most EV charging happens at home (80%+). Understand electrical requirements: single phase vs three phase, meter upgrades. Navigate DISCOM approvals and EV tariffs. Develop installation partnerships and portable charger options.', '["Design home charger product/service", "Identify installation partners", "Understand EV tariff structure by DISCOM", "Create customer installation guide"]'::jsonb, '{"templates": ["Home Charger Installation Guide", "DISCOM Approval Template"], "tools": ["Home Charging Cost Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Public Charging Network', 'Build or partner for public charging. Understand FAME II charging infrastructure scheme: ₹500 crore for 2,700 stations. Navigate MNRE and state-level charging incentives. Plan station locations: highways, malls, parking lots. Understand charging station business models: CPSE, franchise, asset-light.', '["Evaluate public charging business model", "Identify strategic station locations", "Apply for FAME II charging incentive", "Partner with property owners/fuel stations"]'::jsonb, '{"templates": ["Charging Station Business Plan", "Location Assessment Tool"], "tools": ["Station Profitability Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Battery Swapping Model', 'Evaluate battery swapping as alternative to charging. Understand the battery-as-a-service (BaaS) model. Learn from Sun Mobility and Battery Smart approaches. Navigate interoperability challenges and standardization efforts. Calculate swapping station economics and pricing models.', '["Assess swapping viability for your segment", "Design battery pack for swapping", "Calculate swapping station economics", "Explore swapping partnerships"]'::jsonb, '{"templates": ["Swapping Business Model Canvas", "Station Economics Template"], "tools": ["Swap Station ROI Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Charging Software & Payments', 'Build charging management software: station discovery, booking, payments, load management. Understand OCPP protocol for charger-backend communication. Integrate UPI and wallet payments. Enable roaming between charging networks. Build customer app and analytics dashboard.', '["Define charging app features", "Select OCPP-compliant backend", "Integrate payment gateways", "Plan network roaming partnerships"]'::jsonb, '{"templates": ["Charging App Feature Spec", "OCPP Integration Guide"], "tools": ["Charging Network Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: Manufacturing Setup (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'Manufacturing Setup', 'Set up EV manufacturing - facility planning, equipment, assembly lines, and production scaling', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'Manufacturing Strategy', 'Choose manufacturing approach: fully integrated (high capex, better margins), semi-knocked down (SKD), or contract manufacturing. Ola Electric invested ₹2,400 crore in Futurefactory. Understand minimum viable manufacturing and scaling path. Calculate make vs buy decisions for each component.', '["Define manufacturing strategy", "Calculate capex requirements", "Evaluate contract manufacturing partners", "Plan phased capacity expansion"]'::jsonb, '{"templates": ["Manufacturing Strategy Framework", "Capex Planning Template"], "tools": ["Make vs Buy Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Facility Planning & Location', 'Select manufacturing location based on: state incentives, port access, supplier proximity, skilled labor. Key EV hubs: Pune (auto ecosystem), Chennai (supplier base), Gujarat (incentives), Hosur (2-wheeler cluster). Plan facility layout: production lines, testing, warehouse, office. Estimate land and construction costs.', '["Evaluate 5 potential locations", "Visit shortlisted sites", "Negotiate land/lease terms", "Design facility layout"]'::jsonb, '{"templates": ["Location Comparison Matrix", "Facility Layout Template"], "tools": ["Site Selection Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Production Line Design', 'Design assembly line for optimal efficiency. Understand takt time and line balancing. Plan workstations: frame assembly, motor mounting, battery installation, wiring harness, final assembly. Implement lean manufacturing principles. Calculate line capacity and shift planning.', '["Design production line flow", "Calculate takt time and line speed", "Plan workstation layout", "Implement quality check points"]'::jsonb, '{"templates": ["Production Line Design Guide", "Workstation Planning Template"], "tools": ["Takt Time Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Manufacturing Equipment', 'Source manufacturing equipment: welding machines, paint booth, EOL testing equipment, material handling. Balance new vs used equipment decisions. Identify key equipment suppliers in India and internationally. Plan maintenance and spare parts inventory.', '["List required manufacturing equipment", "Get quotes from 3 suppliers each", "Plan equipment financing", "Create maintenance schedule"]'::jsonb, '{"templates": ["Equipment List Template", "Supplier Comparison Sheet"], "tools": ["Equipment Investment Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'Quality Management System', 'Implement quality management: incoming inspection, in-process quality, final testing. Work towards IATF 16949 automotive quality certification. Set up SPC (Statistical Process Control). Handle customer quality issues and warranty claims. Build quality culture from day one.', '["Define quality control plan", "Set up incoming inspection", "Implement EOL testing protocol", "Plan IATF 16949 certification"]'::jsonb, '{"templates": ["Quality Control Plan", "Inspection Checklist"], "tools": ["Quality Metrics Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Component Sourcing (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Component Sourcing', 'Master EV component procurement - motors, controllers, chargers, and drivetrain', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Electric Motor Sourcing', 'Source electric motors: BLDC (brushless DC) for 2-wheelers, PMSM (permanent magnet synchronous) for higher power. Key Indian suppliers: Rexnord, Minda, Greaves. Chinese suppliers: QS Motor, Golden Motor. Evaluate on efficiency, torque curve, cooling requirements. Understand motor specifications and testing.', '["Define motor specifications", "Get quotes from 5 motor suppliers", "Evaluate motor test reports", "Negotiate pricing and MOQs"]'::jsonb, '{"templates": ["Motor Specification Sheet", "Supplier Evaluation Matrix"], "tools": ["Motor Selection Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Motor Controller Sourcing', 'Source motor controllers (inverters): key to vehicle performance. Indian options: Aevt, ElMeasure. Chinese: Fardriver, Kelly, Votol. Evaluate on power handling, efficiency, regen braking capability. Understand controller-motor matching and customization possibilities.', '["Define controller specifications", "Match controller to motor", "Get samples for testing", "Negotiate development support"]'::jsonb, '{"templates": ["Controller Specification Template", "Motor-Controller Matching Guide"], "tools": ["Controller Comparison Tool"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Charger & DC-DC Converter', 'Source onboard chargers and DC-DC converters. Charger converts AC to DC for battery charging. DC-DC converter steps down high voltage to 12V for lights, horn, etc. Indian suppliers: Delta Electronics, Exicom. Ensure charger efficiency >90% and appropriate power rating.', '["Define charger and DC-DC specifications", "Source from 3 suppliers", "Test samples for efficiency", "Plan for BIS certification"]'::jsonb, '{"templates": ["Charger Specification Sheet", "DC-DC Converter Guide"], "tools": ["Charger Efficiency Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Vehicle Control Unit (VCU)', 'Develop or source Vehicle Control Unit - the vehicle''s brain. VCU manages: motor control commands, battery monitoring, user interface, diagnostics. Options: develop in-house (₹50L-1Cr), source from Tier-1 (₹15-30K per unit). Understand CAN bus integration and OBD compliance.', '["Define VCU requirements", "Evaluate build vs buy", "Select development partner if outsourcing", "Plan software development roadmap"]'::jsonb, '{"templates": ["VCU Specification Document", "Software Requirements Spec"], "tools": ["VCU Development Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Supply Chain Management', 'Build resilient EV supply chain. Manage multiple suppliers for critical components. Handle long lead times (batteries: 8-12 weeks). Plan inventory levels and safety stock. Navigate import regulations and forex risk. Build supplier relationships for innovation partnership.', '["Map complete BOM with suppliers", "Implement dual sourcing for critical parts", "Set up inventory management system", "Create supplier development program"]'::jsonb, '{"templates": ["BOM Management Template", "Supplier Scorecard"], "tools": ["Inventory Planning Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: EV Financing (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'EV Financing', 'Enable customer financing - bank partnerships, NBFCs, leasing models, and EMI structures', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'EV Retail Finance Landscape', 'Understand EV financing challenges: low resale value perception, limited lender experience, higher ticket sizes. Current players: HDFC Bank, ICICI Bank, Bajaj Finance, Mahindra Finance for EVs. Interest rates: 9-14% for established OEMs, higher for new players. Build lender confidence in your product.', '["Map EV finance providers", "Understand lender evaluation criteria", "Prepare lender presentation", "Build relationships with 3 financiers"]'::jsonb, '{"templates": ["Lender Pitch Deck", "Finance Partner Comparison"], "tools": ["EMI Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Bank Partnership Strategy', 'Build OEM-bank financing partnerships. Offer first-loss default guarantee (FLDG) to reduce lender risk. Negotiate interest subvention programs. Create instant approval processes at dealerships. Understand RBI regulations on digital lending and FLDG caps.', '["Design FLDG structure", "Negotiate bank partnership terms", "Set up digital loan processing", "Train sales team on finance products"]'::jsonb, '{"templates": ["Bank Partnership Agreement", "FLDG Structure Template"], "tools": ["Partnership ROI Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'NBFC & Fintech Solutions', 'Partner with NBFCs and fintechs for faster, wider reach. Players: Rupifi, CredAble, Lendingkart for B2B. Consumer fintechs: Bajaj Finserv, TVS Credit. Understand NBFC appetite for EV risk. Create co-lending arrangements for scale.', '["Identify NBFC partners for your segment", "Structure co-lending arrangement", "Integrate with fintech APIs", "Build customer financing journey"]'::jsonb, '{"templates": ["NBFC Partnership Template", "API Integration Guide"], "tools": ["Co-lending Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'Leasing & Subscription Models', 'Design vehicle leasing for commercial customers. Understand operating lease vs finance lease tax implications. Create subscription models: vehicle + charging + maintenance packages. Calculate residual value assumptions and lease pricing. Build lease management operations.', '["Design leasing product", "Calculate lease pricing", "Create subscription packages", "Set up lease management system"]'::jsonb, '{"templates": ["Lease Pricing Model", "Subscription Package Template"], "tools": ["Lease vs Buy Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'Fleet Finance Solutions', 'Enable fleet financing for B2B customers. Design asset-light models for delivery fleets. Create pay-per-use or pay-per-km financing. Partner with fleet financiers: Edelweiss, Mahindra Finance. Understand fleet customer creditworthiness assessment.', '["Design fleet finance products", "Partner with fleet financiers", "Create usage-based payment models", "Build fleet customer credit assessment"]'::jsonb, '{"templates": ["Fleet Finance Structure", "Usage-Based Pricing Model"], "tools": ["Fleet Finance Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 10: Fleet & B2B Models (Days 46-50)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_10_id, v_product_id, 'Fleet & B2B Models', 'Capture B2B opportunity - delivery fleets, ride-hailing, corporate mobility, and government tenders', 10, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_10_id, 46, 'Last-Mile Delivery Fleet', 'Target last-mile delivery: Amazon, Flipkart, Zomato, Swiggy, BigBasket. Understand fleet requirements: range 80-100 km, payload 200-500 kg, TCO focus. Navigate tender processes and pilot programs. Build relationships with fleet procurement teams. Create TCO calculators showing EV advantage.', '["Identify target delivery fleet customers", "Create TCO comparison vs ICE", "Propose pilot program structure", "Build delivery fleet case studies"]'::jsonb, '{"templates": ["Fleet TCO Calculator", "Pilot Program Proposal"], "tools": ["Delivery Fleet ROI Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 47, 'Ride-Hailing & Taxi Fleets', 'Serve ride-hailing partners: Ola, Uber, Blu Smart, MoEVing. Understand driver economics and fleet operator requirements. Design for high utilization: 150-200 km daily. Create driver-friendly financing and charging solutions. Handle warranty for commercial use patterns.', '["Analyze ride-hailing driver economics", "Design high-utilization product", "Create driver finance packages", "Partner with ride-hailing platforms"]'::jsonb, '{"templates": ["Driver Economics Model", "Fleet Partner Agreement"], "tools": ["Ride-Hailing TCO Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 48, 'Corporate Mobility Solutions', 'Sell to corporate fleets: employee transportation, executive cars, company vehicles. Understand corporate procurement cycles and sustainability commitments. Create comprehensive solutions: vehicles + charging + maintenance. Target ESG-focused companies and MNCs.', '["Identify corporate fleet targets", "Create corporate mobility package", "Build sustainability impact report", "Navigate corporate procurement"]'::jsonb, '{"templates": ["Corporate Fleet Proposal", "ESG Impact Calculator"], "tools": ["Corporate Mobility Planner"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 49, 'Government & PSU Tenders', 'Win government EV tenders: EESL bulk procurement, state transport corporations, municipal corporations. Understand GeM (Government e-Marketplace) registration and bidding. Navigate tender specifications and compliance requirements. Handle payment delays and government procurement cycles.', '["Register on GeM portal", "Track government EV tenders", "Prepare tender documentation", "Build PSU relationships"]'::jsonb, '{"templates": ["GeM Registration Guide", "Tender Response Template"], "tools": ["Tender Tracking System"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 50, 'B2B Sales & Account Management', 'Build B2B sales capability. Create enterprise sales team structure. Develop key account management processes. Handle complex B2B negotiations and contracts. Build fleet management and service infrastructure for B2B customers.', '["Build B2B sales team", "Create enterprise sales process", "Develop key account plans", "Set up B2B service infrastructure"]'::jsonb, '{"templates": ["B2B Sales Playbook", "Key Account Plan Template"], "tools": ["B2B Pipeline Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 11: Scaling & Exits (Days 51-55)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_11_id, v_product_id, 'Scaling & Exits', 'Scale operations and plan for growth - fundraising, partnerships, geographic expansion, and exit strategies', 11, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_11_id, 51, 'EV Startup Fundraising', 'Raise capital for EV ventures. Understand investor landscape: climate-focused VCs (Lightrock, Blue Ashva), strategic investors (Mahindra, Hero), and international EV specialists. Learn from Ola Electric ($200M+ raised), Ather ($128M), Euler ($60M). Create compelling EV investment thesis.', '["Build investor target list", "Create EV-specific pitch deck", "Prepare financial model with unit economics", "Start investor conversations"]'::jsonb, '{"templates": ["EV Investor Pitch Deck", "Financial Model Template"], "tools": ["Investor CRM"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 52, 'Strategic Partnerships', 'Build strategic partnerships for scale. Partner with auto OEMs for distribution, energy companies for charging, and technology companies for software. Create win-win partnership structures. Navigate partnership negotiations and governance.', '["Identify strategic partner targets", "Create partnership value proposition", "Negotiate partnership terms", "Set up partnership governance"]'::jsonb, '{"templates": ["Partnership Proposal Template", "JV Structure Guide"], "tools": ["Partnership Value Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 53, 'Geographic Expansion', 'Expand across India and internationally. Prioritize state expansion based on EV policy and demand. Explore export markets: Nepal, Bangladesh, Sri Lanka, Africa. Navigate export regulations and homologation requirements. Build distribution and service network.', '["Create state expansion roadmap", "Evaluate export market potential", "Study export homologation requirements", "Plan distribution network expansion"]'::jsonb, '{"templates": ["Market Expansion Framework", "Export Readiness Checklist"], "tools": ["Market Prioritization Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 54, 'IPO & Public Market Path', 'Prepare for IPO or public market listing. Understand SEBI regulations for EV companies. Learn from Ola Electric''s IPO journey. Build corporate governance and compliance infrastructure. Create investor relations function.', '["Assess IPO readiness", "Implement corporate governance", "Build investor relations capability", "Prepare for due diligence"]'::jsonb, '{"templates": ["IPO Readiness Checklist", "Corporate Governance Framework"], "tools": ["IPO Timeline Planner"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 55, 'M&A & Exit Strategies', 'Plan exit strategies: strategic acquisition by auto OEM, financial sale to PE, or IPO. Understand EV company valuations: revenue multiples, technology premium. Prepare for M&A due diligence. Build relationships with potential acquirers: Tata Motors, M&M, TVS, international players.', '["Define preferred exit path", "Build acquirer relationships", "Prepare data room for due diligence", "Understand valuation benchmarks"]'::jsonb, '{"templates": ["Exit Planning Framework", "Data Room Checklist"], "tools": ["Valuation Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
