-- P28: Biotech & Life Sciences Course Migration
-- 60 days, 12 modules, comprehensive biotech mastery for Indian startups

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
    v_mod_10_id TEXT;
    v_mod_11_id TEXT;
    v_mod_12_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;
    v_mod_10_id := gen_random_uuid()::text;
    v_mod_11_id := gen_random_uuid()::text;
    v_mod_12_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P28',
        'Biotech & Life Sciences Mastery',
        'Complete guide to building biotech startups in India - from drug development to global expansion. 12 modules covering CDSCO regulations, clinical trials, GMP manufacturing, biosimilars, medical devices, IP strategy, contract manufacturing, and biotech funding. India $80B+ pharmaceutical market and emerging biotech hub.',
        9999,
        60,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P28';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: Biotech Landscape (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'Biotech Landscape', 'Understand India biotech ecosystem - market segments, regulations, and innovation opportunities', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'India Biotech Industry Overview', 'Explore India $80B+ biotech sector: biopharma (65%), bio-services (18%), bio-agriculture (12%), bio-industrial (5%). Understand India as pharmacy of the world (20% global generics). Study key clusters: Hyderabad, Bangalore, Pune, Ahmedabad. Learn about government vision for $150B by 2025.', '["Study biotech sector segments and growth rates", "Research key biotech clusters in India", "Identify top 20 Indian biotech companies", "Map government biotech initiatives"]'::jsonb, '{"templates": ["India Biotech Landscape Map", "Cluster Analysis Template"], "tools": ["Biotech Market Intelligence"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'Biotech Startup Segments', 'Deep dive into biotech verticals: therapeutics (novel drugs, biosimilars), diagnostics, vaccines, gene therapy, stem cells, synthetic biology, agri-biotech. Study successful Indian biotech startups: Biocon, Bharat Biotech, Syngene. Identify emerging opportunities.', '["Map all biotech segments with market potential", "Research 10 successful Indian biotech companies", "Identify your target segment based on expertise", "Analyze competitive landscape"]'::jsonb, '{"templates": ["Biotech Segment Matrix", "Startup Case Study Framework"], "tools": ["Biotech Opportunity Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'Regulatory Landscape Overview', 'Navigate biotech regulations: CDSCO (drugs), GEAC (GM organisms), DBT (biosafety), FSSAI (functional foods), BIS (standards). Understand approval pathways for different product categories. Learn about regulatory harmonization with global standards.', '["Map regulatory bodies and their jurisdictions", "Study approval pathways for your product category", "Understand timeline and cost estimates", "Research regulatory consultants"]'::jsonb, '{"templates": ["Regulatory Body Matrix", "Approval Pathway Guide"], "tools": ["Regulatory Compliance Navigator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'Science to Startup Journey', 'Understand drug discovery pipeline: target identification, hit screening, lead optimization, preclinical, clinical, approval. Learn about translational research and IP creation. Study academic-industry collaboration models in India.', '["Map drug development stages and timelines", "Understand preclinical requirements", "Study academic-startup models", "Identify technology transfer opportunities"]'::jsonb, '{"templates": ["Drug Development Pipeline", "Technology Transfer Framework"], "tools": ["Discovery Stage Assessment"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Building Biotech Strategy', 'Define biotech startup strategy: therapeutic area, modality, target market, development path, partnership strategy. Create realistic timelines and milestones. Plan for capital-intensive development cycles.', '["Define therapeutic focus and target indication", "Create development milestone timeline", "Design partnership and licensing strategy", "Build capital planning for development"]'::jsonb, '{"templates": ["Biotech Business Model Canvas", "Development Roadmap Template"], "tools": ["Biotech Strategy Builder"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: Drug Development (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'Drug Development', 'Master drug discovery and development - target validation, lead optimization, preclinical studies', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'Target Identification and Validation', 'Master target discovery: disease biology, target selection criteria, validation approaches. Understand genomics, proteomics, and bioinformatics tools. Learn about target-based vs phenotypic screening. Study successful target validation strategies.', '["Define disease area and target rationale", "Design target validation experiments", "Access bioinformatics databases", "Create target validation data package"]'::jsonb, '{"templates": ["Target Selection Framework", "Validation Protocol Template"], "tools": ["Bioinformatics Tool Guide"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'Hit Discovery and Screening', 'Implement screening strategies: high-throughput screening (HTS), fragment-based drug discovery, virtual screening. Access compound libraries and screening platforms. Understand hit-to-lead criteria. Partner with screening service providers.', '["Design screening cascade", "Access compound libraries", "Select screening assays", "Define hit criteria and prioritization"]'::jsonb, '{"templates": ["Screening Strategy Template", "Hit Selection Criteria"], "tools": ["Screening Platform Database"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'Lead Optimization', 'Optimize lead compounds: medicinal chemistry, ADMET properties, selectivity, potency. Understand structure-activity relationships (SAR). Build CRO partnerships for chemistry services. Create lead optimization strategy.', '["Define optimization objectives", "Design SAR studies", "Partner with chemistry CROs", "Establish lead optimization criteria"]'::jsonb, '{"templates": ["Lead Optimization Checklist", "SAR Analysis Framework"], "tools": ["Med Chem Design Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Preclinical Development', 'Navigate preclinical requirements: pharmacology, toxicology, pharmacokinetics, formulation. Understand IND-enabling studies. Partner with preclinical CROs in India. Prepare preclinical data package for regulatory submission.', '["Design preclinical study plan", "Select preclinical CRO partners", "Plan GLP toxicology studies", "Prepare IND-enabling package"]'::jsonb, '{"templates": ["Preclinical Development Plan", "CRO Selection Guide"], "tools": ["Preclinical Study Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'Drug Formulation and CMC', 'Master Chemistry, Manufacturing, and Controls: formulation development, analytical methods, stability studies, process development. Understand CMC requirements for IND and NDA. Partner with formulation service providers.', '["Design formulation strategy", "Develop analytical methods", "Plan stability studies", "Create CMC documentation"]'::jsonb, '{"templates": ["CMC Development Guide", "Formulation Strategy Template"], "tools": ["Formulation Development Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: CDSCO Regulations (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'CDSCO Regulations', 'Navigate drug regulatory framework - New Drugs Rules, approval pathways, and compliance', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'CDSCO Structure and Functions', 'Understand Central Drugs Standard Control Organization: structure, divisions, licensing authority. Learn about Drugs and Cosmetics Act 1940 and Rules 2019. Navigate SUGAM online portal for submissions. Study inspection and compliance processes.', '["Study CDSCO organizational structure", "Understand D&C Act key provisions", "Register on SUGAM portal", "Map approval authority by product type"]'::jsonb, '{"templates": ["CDSCO Organization Guide", "Regulatory Authority Matrix"], "tools": ["SUGAM Portal Navigator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'New Drug Approval Process', 'Master New Drug approval: definition of new drug, approval pathways (NCE, NME, NDC), application requirements. Understand phased submission approach. Prepare Form 44 for new drug permission. Study timeline expectations.', '["Determine new drug classification", "Understand approval pathway requirements", "Prepare Form 44 application", "Create submission timeline"]'::jsonb, '{"templates": ["New Drug Application Guide", "Form 44 Preparation Checklist"], "tools": ["Approval Timeline Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'Import and Manufacturing Licenses', 'Navigate licensing: import license (Form 8), manufacturing license (Form 25/28), loan license arrangements. Understand WHO-GMP certification requirements. Prepare for CDSCO inspections. Handle license variations and renewals.', '["Determine license type required", "Prepare license application documentation", "Understand GMP requirements", "Plan for regulatory inspections"]'::jsonb, '{"templates": ["License Application Guide", "GMP Compliance Checklist"], "tools": ["License Requirement Finder"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'Orphan Drugs and Fast Track', 'Access expedited pathways: orphan drug designation, breakthrough therapy, accelerated approval, priority review. Understand Drugs for Rare Diseases policy. Navigate CDSCO consultation meetings. Build regulatory strategy for expedited approval.', '["Evaluate eligibility for expedited pathways", "Apply for orphan drug designation", "Request CDSCO consultation", "Design expedited development plan"]'::jsonb, '{"templates": ["Expedited Pathway Guide", "Orphan Drug Application"], "tools": ["Pathway Eligibility Checker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'Post-Market Compliance', 'Master post-approval requirements: pharmacovigilance, periodic safety reports (PSUR), labeling updates, batch release. Understand adverse event reporting to ADR monitoring centres. Build post-market surveillance systems.', '["Establish pharmacovigilance system", "Set up adverse event reporting", "Create PSUR submission process", "Design post-market study protocol"]'::jsonb, '{"templates": ["Pharmacovigilance SOP", "PSUR Template"], "tools": ["Adverse Event Database"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Clinical Trials (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Clinical Trials', 'Design and execute clinical trials - protocol development, ethics, site selection, and data management', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Clinical Trial Regulations in India', 'Navigate New Drugs and Clinical Trials Rules 2019: CT approval process, compensation provisions, ethics requirements. Understand CTRI registration. Learn about global vs local development strategies. Study India advantages for clinical trials.', '["Study NDCT Rules 2019 requirements", "Understand CT approval process", "Register on CTRI portal", "Map India clinical trial advantages"]'::jsonb, '{"templates": ["CT Regulatory Guide", "CTRI Registration Checklist"], "tools": ["CT Approval Timeline"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'Protocol Development', 'Design robust protocols: study objectives, endpoints, sample size, inclusion/exclusion criteria, statistical plan. Understand ICH-GCP requirements. Create protocol synopsis and full protocol. Navigate protocol amendments.', '["Define study objectives and endpoints", "Calculate sample size requirements", "Develop inclusion/exclusion criteria", "Create statistical analysis plan"]'::jsonb, '{"templates": ["Protocol Template", "SAP Template"], "tools": ["Sample Size Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'Ethics Committee Approval', 'Navigate ethics approval: EC registration, application requirements, informed consent development. Understand central vs local EC requirements. Handle ethics committee queries. Manage ongoing ethics compliance.', '["Identify appropriate ethics committees", "Prepare EC application package", "Develop informed consent form", "Create patient information sheet"]'::jsonb, '{"templates": ["EC Application Template", "ICF Template"], "tools": ["EC Database India"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Site Selection and Management', 'Select and manage clinical sites: investigator qualification, site assessment, contract negotiation, patient recruitment. Partner with clinical research organizations (CROs). Create site monitoring plans. Handle site issues effectively.', '["Develop site selection criteria", "Conduct site feasibility assessment", "Negotiate site contracts", "Create monitoring plan"]'::jsonb, '{"templates": ["Site Assessment Form", "Site Contract Template"], "tools": ["Clinical Site Database"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Data Management and Submission', 'Build clinical data systems: EDC selection, data management plan, medical coding, database lock. Prepare clinical study reports (CSR). Submit data for regulatory approval. Understand eCTD format requirements.', '["Select EDC platform", "Create data management plan", "Design CRF and database", "Prepare CSR outline"]'::jsonb, '{"templates": ["Data Management Plan", "CSR Template"], "tools": ["EDC Platform Comparison"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: GMP Manufacturing (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'GMP Manufacturing', 'Master pharmaceutical manufacturing - facility design, GMP compliance, quality systems, and validation', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'GMP Fundamentals', 'Master Good Manufacturing Practice: Schedule M requirements, WHO-GMP guidelines, ICH Q7-Q12. Understand GMP principles: quality systems, personnel, premises, equipment, documentation, production, QC. Build GMP culture.', '["Study Schedule M requirements", "Understand WHO-GMP guidelines", "Compare ICH GMP guidance", "Create GMP implementation roadmap"]'::jsonb, '{"templates": ["GMP Compliance Guide", "Schedule M Checklist"], "tools": ["GMP Gap Assessment"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'Manufacturing Facility Design', 'Design GMP-compliant facilities: cleanroom classifications, HVAC design, water systems, material flow, personnel flow. Understand facility qualification requirements. Plan for regulatory inspections. Study facility design for biologics vs small molecules.', '["Design facility layout with flows", "Specify cleanroom requirements", "Plan utility systems", "Create facility qualification plan"]'::jsonb, '{"templates": ["Facility Design Template", "Cleanroom Classification Guide"], "tools": ["Facility Design Software"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Quality Management Systems', 'Build robust QMS: quality policy, SOPs, change control, CAPA, deviation management, complaints, recalls. Understand QP/QA responsibilities. Implement quality risk management (ICH Q9). Prepare for quality audits.', '["Develop quality policy and objectives", "Create SOP framework", "Implement change control system", "Design CAPA process"]'::jsonb, '{"templates": ["QMS Manual Template", "SOP Template Library"], "tools": ["QMS Implementation Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'Process Validation', 'Master validation: process validation stages (PPQ), analytical method validation, cleaning validation, computer system validation. Understand validation master plan development. Create validation protocols and reports.', '["Develop validation master plan", "Design process validation protocol", "Create analytical method validation plan", "Implement validation documentation"]'::jsonb, '{"templates": ["Validation Master Plan", "Process Validation Protocol"], "tools": ["Validation Management System"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Regulatory Inspections', 'Prepare for inspections: CDSCO, WHO, US FDA, EU GMP. Understand inspection types: pre-approval, routine, for-cause. Create inspection readiness program. Handle observations and responses. Build audit management systems.', '["Create inspection readiness checklist", "Train staff for inspections", "Prepare inspection documentation", "Develop 483/observation response process"]'::jsonb, '{"templates": ["Inspection Readiness Guide", "Response Letter Template"], "tools": ["Audit Management Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Biosimilars & Biologics (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Biosimilars & Biologics', 'Master biologic development - biosimilar guidelines, characterization, and manufacturing', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'Biologics and Biosimilars Overview', 'Understand biologics market: therapeutic proteins, monoclonal antibodies, vaccines, cell/gene therapy. Study biosimilar opportunity (patent cliffs). Learn about Indian biosimilar guidelines 2016. Identify development opportunities.', '["Study biologic product categories", "Research biosimilar market opportunities", "Understand reference product selection", "Map patent expiry timelines"]'::jsonb, '{"templates": ["Biosimilar Opportunity Matrix", "Reference Product Analysis"], "tools": ["Patent Cliff Database"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'Biosimilar Development Pathway', 'Navigate biosimilar guidelines: totality of evidence approach, analytical similarity, functional characterization, clinical requirements. Understand bridging study requirements. Create biosimilar development plan.', '["Study biosimilar guidelines", "Design similarity assessment plan", "Plan bridging studies if needed", "Create development timeline"]'::jsonb, '{"templates": ["Biosimilar Development Guide", "Similarity Assessment Framework"], "tools": ["Biosimilar Pathway Navigator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Analytical Characterization', 'Master biosimilar characterization: primary structure, higher-order structure, biological activity, process-related impurities. Build analytical comparability studies. Understand tier-based approach. Partner with analytical labs.', '["Design analytical characterization plan", "Select analytical methods", "Plan comparability studies", "Partner with specialized labs"]'::jsonb, '{"templates": ["Analytical Comparability Protocol", "Method Selection Guide"], "tools": ["Analytical Lab Database"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Biologics Manufacturing', 'Master biologics manufacturing: cell line development, upstream processing, downstream purification, fill-finish. Understand single-use technologies. Plan scale-up and tech transfer. Study contract biologics manufacturing.', '["Design manufacturing process", "Plan cell line development", "Create purification strategy", "Identify CMO partnerships"]'::jsonb, '{"templates": ["Biologics Manufacturing Plan", "CMO Selection Guide"], "tools": ["Biologics Process Design"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Clinical Development for Biosimilars', 'Design biosimilar clinical program: PK/PD studies, efficacy trials, immunogenicity assessment, extrapolation. Understand switching and interchangeability. Create clinical development strategy.', '["Design PK/PD study protocol", "Plan efficacy confirmation study", "Develop immunogenicity testing plan", "Create extrapolation justification"]'::jsonb, '{"templates": ["Biosimilar Clinical Protocol", "Extrapolation Strategy"], "tools": ["Biosimilar Trial Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: Medical Device Regulations (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'Medical Device Regulations', 'Navigate medical device rules - classification, registration, clinical evidence, and quality systems', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'Medical Device Regulatory Framework', 'Understand Medical Devices Rules 2017: definition, classification (A/B/C/D), regulatory authority (CDSCO). Study notified body system. Learn about import and manufacturing license requirements. Navigate online submission process.', '["Study Medical Devices Rules 2017", "Determine device classification", "Understand license requirements", "Register on CDSCO portal"]'::jsonb, '{"templates": ["MDR 2017 Guide", "Classification Decision Tree"], "tools": ["Device Classification Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Device Classification and Registration', 'Navigate device registration: Class A/B through notified bodies, Class C/D through CDSCO. Prepare technical documentation. Understand registration validity and renewal. Handle classification disputes.', '["Determine correct classification", "Select appropriate notified body", "Prepare registration dossier", "Submit registration application"]'::jsonb, '{"templates": ["Registration Dossier Template", "Technical File Checklist"], "tools": ["Notified Body Database"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Clinical Evidence for Devices', 'Build clinical evidence: clinical evaluation, performance studies, clinical investigation requirements. Understand risk-based approach to clinical data. Navigate ethics approval for device trials. Create clinical evidence strategy.', '["Determine clinical evidence requirements", "Conduct literature search and analysis", "Design clinical investigation if needed", "Prepare clinical evaluation report"]'::jsonb, '{"templates": ["Clinical Evaluation Template", "CER Writing Guide"], "tools": ["Clinical Evidence Database"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Quality Management for Devices', 'Implement device QMS: ISO 13485 requirements, design controls, risk management (ISO 14971), software validation (IEC 62304). Prepare for notified body audits. Build compliant development processes.', '["Implement ISO 13485 QMS", "Establish design control process", "Create risk management file", "Prepare for certification audit"]'::jsonb, '{"templates": ["ISO 13485 Manual", "Design History File Template"], "tools": ["QMS Implementation Guide"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'In-Vitro Diagnostics', 'Navigate IVD regulations: IVDR requirements, performance evaluation, clinical evidence, companion diagnostics. Understand IVD classification. Study emerging areas: molecular diagnostics, point-of-care, digital diagnostics.', '["Determine IVD regulatory pathway", "Design performance evaluation study", "Prepare IVD technical documentation", "Understand companion diagnostics requirements"]'::jsonb, '{"templates": ["IVD Regulatory Guide", "Performance Evaluation Protocol"], "tools": ["IVD Classification Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: IP & Patents (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'IP & Patents', 'Build biotech IP portfolio - patent strategy, FTO, licensing, and IP monetization', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Biotech Patent Fundamentals', 'Master biotech IP: patentable subject matter, novelty, inventive step, industrial application. Understand Section 3(d) for pharmaceuticals. Learn about sequence patents, method patents, formulation patents. Study patent prosecution strategies.', '["Study biotech patentability criteria", "Understand Section 3(d) requirements", "Identify patentable inventions", "Create patent strategy roadmap"]'::jsonb, '{"templates": ["Biotech Patent Guide", "Patentability Assessment"], "tools": ["Patent Strategy Builder"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Patent Filing Strategy', 'Design patent portfolio: provisional vs complete applications, PCT strategy, country selection for national phase. Understand patent term extensions. Plan continuation and divisional strategies. Build comprehensive patent protection.', '["Design patent filing strategy", "Prepare provisional application", "Plan PCT and national phase", "Create patent portfolio roadmap"]'::jsonb, '{"templates": ["Patent Strategy Template", "PCT Timeline Guide"], "tools": ["Filing Cost Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Freedom to Operate Analysis', 'Conduct FTO analysis: patent landscape search, claim analysis, infringement risk assessment, design-around strategies. Understand compulsory licensing provisions. Create FTO clearance process for development programs.', '["Conduct patent landscape search", "Analyze key patent claims", "Assess infringement risk", "Develop design-around strategies"]'::jsonb, '{"templates": ["FTO Analysis Template", "Landscape Search Guide"], "tools": ["Patent Database Access"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Licensing and Technology Transfer', 'Master licensing: in-licensing for platform technologies, out-licensing for monetization. Understand term sheet negotiation, royalty structures, milestone payments. Navigate technology transfer from academia. Create licensing strategy.', '["Identify licensing opportunities", "Prepare licensing term sheet", "Negotiate favorable terms", "Execute license agreements"]'::jsonb, '{"templates": ["License Agreement Template", "Term Sheet Template"], "tools": ["Licensing Deal Database"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'IP Portfolio Management', 'Build IP management systems: docket management, renewal tracking, competitor monitoring, enforcement strategy. Create IP valuation for fundraising. Plan defensive publication strategy. Build IP committee governance.', '["Implement IP docket system", "Create renewal tracking process", "Build competitor monitoring", "Develop enforcement strategy"]'::jsonb, '{"templates": ["IP Portfolio Dashboard", "IP Governance Framework"], "tools": ["IP Management Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: Contract Manufacturing (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'Contract Manufacturing', 'Build CMO/CDMO relationships - partner selection, tech transfer, quality agreements', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'CDMO Landscape in India', 'Explore India CDMO industry: API manufacturing, formulation development, biologics production. Study top CDMOs: Syngene, Piramal Pharma, Aragen, Jubilant. Understand CDMO capabilities and specializations. Identify partnership opportunities.', '["Map India CDMO landscape", "Research CDMO capabilities", "Identify potential partners", "Understand pricing models"]'::jsonb, '{"templates": ["CDMO Database", "Capability Assessment Matrix"], "tools": ["CDMO Comparison Platform"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Partner Selection Process', 'Design CDMO selection: capability requirements, quality assessment, capacity evaluation, financial stability. Conduct audits and due diligence. Create RFI/RFP process. Evaluate and select optimal partners.', '["Define CDMO requirements", "Create RFI questionnaire", "Conduct capability audits", "Evaluate and select partners"]'::jsonb, '{"templates": ["RFI Template", "Audit Checklist"], "tools": ["CDMO Selection Scorecard"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'Quality and Supply Agreements', 'Negotiate agreements: Master Service Agreement, Quality Agreement, Supply Agreement. Define quality responsibilities, specifications, testing, release. Establish change control and deviation management. Create governance structure.', '["Draft Master Service Agreement", "Create Quality Agreement", "Define supply terms", "Establish governance model"]'::jsonb, '{"templates": ["MSA Template", "Quality Agreement Template"], "tools": ["Agreement Management System"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'Technology Transfer', 'Execute tech transfer: documentation requirements, process validation, analytical method transfer, stability studies. Create tech transfer protocols and reports. Handle scale-up challenges. Build successful transfer teams.', '["Create tech transfer plan", "Prepare process documentation", "Execute analytical transfer", "Validate transferred process"]'::jsonb, '{"templates": ["Tech Transfer Protocol", "Transfer Report Template"], "tools": ["Tech Transfer Tracker"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'CDMO Relationship Management', 'Manage ongoing partnerships: performance metrics, quality reviews, capacity planning, cost optimization. Handle supply chain risks. Create continuous improvement programs. Build strategic long-term relationships.', '["Define performance KPIs", "Establish review cadence", "Create capacity planning process", "Build risk management plan"]'::jsonb, '{"templates": ["Partner KPI Dashboard", "Supply Risk Matrix"], "tools": ["Partner Management Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 10: Biotech Funding (Days 46-50)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_10_id, v_product_id, 'Biotech Funding', 'Secure biotech funding - grants, VC, strategic investors, and non-dilutive funding', 10, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_10_id, 46, 'Biotech Investment Landscape', 'Navigate biotech funding: early-stage challenges, development milestones as value inflection points. Study biotech investors: specialist VCs (OrbiMed, Lightstone), crossover funds, pharma corporate ventures. Understand biotech valuations.', '["Map biotech investors in India", "Study recent funding rounds", "Understand valuation methodologies", "Identify potential investors"]'::jsonb, '{"templates": ["Biotech Investor Database", "Valuation Guide"], "tools": ["Biotech Funding Tracker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 47, 'Government Grants and Support', 'Access government funding: BIRAC schemes (BIG, SBIRI, BIPP), DBT grants, DST programs, state biotechnology programs. Understand eligibility and application process. Navigate BIRAC startup ecosystem.', '["Identify eligible grant programs", "Prepare grant applications", "Submit to BIRAC schemes", "Access state biotech support"]'::jsonb, '{"templates": ["Grant Application Guide", "BIRAC Scheme Navigator"], "tools": ["Grant Finder Platform"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 48, 'Strategic and Pharma Partnerships', 'Build pharma partnerships: licensing deals, co-development agreements, strategic investments. Understand deal structures and terms. Navigate business development process. Create partnering strategy.', '["Identify strategic partner targets", "Prepare partnering materials", "Navigate business development", "Negotiate partnership terms"]'::jsonb, '{"templates": ["Partnership Strategy", "Term Sheet Guide"], "tools": ["Pharma Partnering Database"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 49, 'Biotech Pitch Preparation', 'Craft compelling biotech pitch: science, clinical differentiation, competitive advantage, development plan, team, financials. Address common investor concerns: risk, timeline, capital efficiency. Prepare data room.', '["Create biotech pitch deck", "Prepare scientific presentation", "Build investor data room", "Practice pitch with mentors"]'::jsonb, '{"templates": ["Biotech Pitch Deck", "Data Room Checklist"], "tools": ["Pitch Preparation Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_10_id, 50, 'Managing Biotech Financing', 'Plan staged financing: seed, Series A/B/C, milestone-based funding. Manage cash runway and burn rate. Create investor relations program. Prepare for exit through IPO or M&A.', '["Create financing roadmap", "Build investor relations process", "Manage cash and runway", "Plan long-term exit strategy"]'::jsonb, '{"templates": ["Financing Plan Template", "Investor Relations Guide"], "tools": ["Runway Calculator"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 11: Global Expansion (Days 51-55)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_11_id, v_product_id, 'Global Expansion', 'Take biotech global - US FDA, EMA, emerging markets, and international partnerships', 11, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_11_id, 51, 'US FDA Pathway', 'Navigate FDA approval: IND application, clinical development, NDA/BLA submission. Understand FDA meetings (pre-IND, EOP2, pre-NDA). Study expedited pathways: Fast Track, Breakthrough, Accelerated Approval. Plan US market entry.', '["Study FDA approval pathway", "Plan IND submission strategy", "Request FDA meetings", "Design US clinical program"]'::jsonb, '{"templates": ["FDA Regulatory Guide", "IND Template"], "tools": ["FDA Meeting Preparation"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 52, 'European Medicines Agency', 'Master EMA pathway: centralized vs national procedures, scientific advice, PRIME designation. Understand CTD/eCTD format. Navigate rapporteur system. Plan EU market access and HTA requirements.', '["Study EMA regulatory pathway", "Plan centralized procedure", "Request EMA scientific advice", "Design EU submission strategy"]'::jsonb, '{"templates": ["EMA Submission Guide", "CTD Structure"], "tools": ["EU Market Access Platform"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 53, 'Emerging Markets Strategy', 'Plan emerging market entry: China (NMPA), Japan (PMDA), Brazil (ANVISA), Russia, GCC. Understand country-specific requirements. Navigate local partner requirements. Create emerging market prioritization.', '["Research emerging market requirements", "Prioritize markets for entry", "Identify local partners", "Create market entry timeline"]'::jsonb, '{"templates": ["Emerging Market Guide", "Partner Selection Matrix"], "tools": ["Global Market Database"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 54, 'Global Clinical Development', 'Design global clinical program: multi-regional trials, ethnic bridging, site selection across regions. Understand ICH E5 for ethnic factors. Create global development strategy balancing speed, cost, and regulatory acceptance.', '["Design global clinical program", "Plan multi-regional trials", "Address ethnic bridging needs", "Create global site strategy"]'::jsonb, '{"templates": ["Global Clinical Strategy", "MRCT Planning Guide"], "tools": ["Global Site Database"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_11_id, 55, 'International Partnerships', 'Build international presence: licensing partners, distribution agreements, joint ventures. Understand cross-border deal structures. Navigate technology transfer internationally. Create global partnership strategy.', '["Identify international partners", "Structure cross-border deals", "Navigate international tech transfer", "Build global business development"]'::jsonb, '{"templates": ["International Partnership Guide", "Cross-border Agreement"], "tools": ["Global Partner Database"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 12: Biotech Parks & Incubators (Days 56-60)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_12_id, v_product_id, 'Biotech Parks & Incubators', 'Leverage biotech ecosystem - incubators, parks, mentorship, and support infrastructure', 12, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_12_id, 56, 'Biotech Incubators in India', 'Explore biotech incubators: BIRAC-supported BioNEST, university incubators, private accelerators. Study top incubators: C-CAMP, KIIT-TBI, Venture Center, NCL Ventures. Understand incubator benefits: facilities, mentorship, funding access.', '["Research biotech incubators", "Evaluate incubator programs", "Apply to relevant incubators", "Access incubator resources"]'::jsonb, '{"templates": ["Incubator Comparison Guide", "Application Template"], "tools": ["Biotech Incubator Database"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_12_id, 57, 'Biotech Parks and Clusters', 'Leverage biotech parks: Genome Valley (Hyderabad), Bangalore Biotech Park, TICEL Chennai, KIADB Biotech Park. Understand park benefits: infrastructure, regulatory support, tax incentives. Navigate park admission and setup.', '["Research biotech parks", "Evaluate park facilities", "Apply for park admission", "Plan facility setup"]'::jsonb, '{"templates": ["Biotech Park Guide", "Facility Planning Template"], "tools": ["Park Comparison Platform"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_12_id, 58, 'Shared Infrastructure Access', 'Access shared facilities: analytical instruments, pilot plants, BSL2/3 labs, clinical trial support. Navigate facility booking and usage. Partner with research institutions for infrastructure. Optimize capital efficiency.', '["Identify shared facility needs", "Access research institution resources", "Book analytical services", "Plan pilot manufacturing"]'::jsonb, '{"templates": ["Shared Facility Guide", "Service Provider Database"], "tools": ["Research Infrastructure Platform"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_12_id, 59, 'Mentorship and Advisory', 'Build advisory support: scientific advisory board, regulatory advisors, commercial advisors. Connect with industry mentors through incubators. Access BIRAC mentor network. Create effective board governance.', '["Identify SAB candidates", "Build advisory relationships", "Access mentor networks", "Create board governance"]'::jsonb, '{"templates": ["SAB Formation Guide", "Advisory Agreement"], "tools": ["Mentor Matching Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_12_id, 60, 'Scaling Biotech Venture', 'Plan biotech scale-up: from incubator to independent operations, team building, infrastructure expansion. Navigate growth challenges specific to biotech. Create sustainable biotech organization. Plan long-term vision and exit.', '["Create scale-up roadmap", "Plan infrastructure transition", "Build core team capabilities", "Develop long-term vision"]'::jsonb, '{"templates": ["Biotech Scale-up Guide", "Team Building Framework"], "tools": ["Growth Planning Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
