-- P19: Technology Stack & Infrastructure Course Migration
-- 45 days, 9 modules, comprehensive technology infrastructure

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P19',
        'Technology Stack & Infrastructure',
        'Build bulletproof technical infrastructure from architecture to scaling - 9 modules covering system design, cloud strategy, DevOps, database design, security, scalability, technical debt, engineering teams, and CTO-level decision making. 78% of startup failures cite technical issues.',
        6999,
        45,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P19';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: Architecture Design (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'Architecture Design', 'Master system design fundamentals - microservices vs monolith, API design, and architectural patterns for startups', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'System Design Fundamentals', 'Learn why architecture decisions make or break startups. Understand the core principles of system design: scalability, reliability, maintainability. Study real-world architectures of successful Indian startups like Razorpay, Zerodha, and Freshworks. Define your architectural principles based on business requirements.', '["Document your current system architecture (or planned architecture)", "Define 5 core architectural principles for your startup", "Identify your top 3 technical constraints", "Create architectural decision record (ADR) template"]'::jsonb, '{"templates": ["System Architecture Template", "ADR Template"], "tools": ["Architecture Diagramming Tool Guide"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'Monolith vs Microservices Decision', 'Understand when to use monolith vs microservices. Learn why most startups should start with monolith. Study the strangler fig pattern for gradual migration. Analyze cost and complexity trade-offs. Make the right choice for your stage.', '["Assess your current architecture against growth projections", "List services that could be extracted in future", "Calculate infrastructure cost for both approaches", "Document your architecture decision with rationale"]'::jsonb, '{"templates": ["Architecture Decision Matrix", "Service Boundary Analyzer"], "tools": ["Cost Comparison Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'API Design Best Practices', 'Master RESTful API design principles. Learn GraphQL vs REST trade-offs. Design APIs for mobile-first India. Implement versioning strategies. Create comprehensive API documentation.', '["Design API structure for 3 core features", "Create API versioning strategy", "Document authentication and rate limiting approach", "Set up API documentation with Swagger/OpenAPI"]'::jsonb, '{"templates": ["API Design Guidelines", "OpenAPI Specification Template"], "tools": ["API Documentation Generator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'Event-Driven Architecture', 'Understand event-driven patterns for scalability. Learn message queues: RabbitMQ, Kafka, AWS SQS. Design async workflows for high-volume operations. Implement event sourcing where appropriate.', '["Identify 5 operations that should be async", "Design event schema for core business events", "Choose message queue technology", "Create event flow diagram"]'::jsonb, '{"templates": ["Event Schema Template", "Async Workflow Designer"], "tools": ["Message Queue Comparison Matrix"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Domain-Driven Design for Startups', 'Apply DDD principles to startup development. Define bounded contexts and aggregates. Create ubiquitous language with your team. Design domain models that evolve with business.', '["Map your business domains and bounded contexts", "Define core entities and aggregates", "Create domain glossary document", "Design domain events for key workflows"]'::jsonb, '{"templates": ["Domain Model Template", "Bounded Context Canvas"], "tools": ["Event Storming Guide"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: Cloud Strategy (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'Cloud Strategy', 'Navigate cloud choices - AWS vs GCP vs Azure, cost optimization, multi-cloud strategies, and India-specific considerations', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'Cloud Provider Selection', 'Compare AWS, GCP, and Azure for Indian startups. Understand pricing models, India region availability, and startup credits. Evaluate DigitalOcean, Linode for early stage. Make informed cloud provider decisions.', '["Compare cloud providers for your use case", "Calculate estimated monthly costs", "Apply for startup credits (AWS Activate, GCP for Startups)", "Document cloud provider selection rationale"]'::jsonb, '{"templates": ["Cloud Provider Comparison Matrix", "Cost Estimation Spreadsheet"], "tools": ["Cloud Cost Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'Infrastructure as Code', 'Master IaC principles with Terraform, CloudFormation, or Pulumi. Version control your infrastructure. Create reusable modules. Implement infrastructure testing.', '["Set up Terraform or CloudFormation for core infrastructure", "Create modules for common resources", "Implement state management strategy", "Add infrastructure to version control"]'::jsonb, '{"templates": ["Terraform Module Templates", "IaC Best Practices Guide"], "tools": ["Infrastructure Testing Framework"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'Cloud Cost Optimization', 'Implement cost monitoring and alerts. Use reserved instances and spot instances effectively. Right-size your resources. Identify and eliminate waste. Set up cost allocation tags.', '["Set up cloud cost monitoring dashboard", "Identify top 5 cost reduction opportunities", "Implement reserved instance strategy", "Create cost allocation tags for all resources"]'::jsonb, '{"templates": ["Cost Optimization Checklist", "Reserved Instance Calculator"], "tools": ["Cloud Cost Analyzer"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'Multi-Cloud and Hybrid Strategies', 'Understand multi-cloud benefits and complexities. Design for cloud portability. Implement hybrid cloud for compliance requirements. Handle data residency requirements in India.', '["Assess multi-cloud requirements", "Design cloud-agnostic core services", "Plan data residency compliance", "Create vendor lock-in mitigation strategy"]'::jsonb, '{"templates": ["Multi-Cloud Architecture Template", "Data Residency Compliance Guide"], "tools": ["Cloud Portability Assessment"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'Serverless Architecture', 'Leverage serverless for cost-effective scaling. Understand AWS Lambda, GCP Cloud Functions, Azure Functions. Design serverless-first applications. Handle cold starts and limitations.', '["Identify 3 workloads suitable for serverless", "Design serverless architecture for one feature", "Implement cost monitoring for serverless", "Create fallback strategy for cold starts"]'::jsonb, '{"templates": ["Serverless Design Patterns", "Lambda Best Practices"], "tools": ["Serverless Framework Guide"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: DevOps Setup (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'DevOps Setup', 'Implement CI/CD, containerization with Docker, Kubernetes orchestration, and modern deployment strategies', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'CI/CD Pipeline Design', 'Build robust CI/CD pipelines with GitHub Actions, GitLab CI, or Jenkins. Implement automated testing in pipelines. Design deployment workflows. Handle secrets management.', '["Set up CI pipeline with automated tests", "Implement code quality gates", "Design deployment workflow (dev/staging/prod)", "Set up secrets management"]'::jsonb, '{"templates": ["GitHub Actions Workflow Templates", "CI/CD Pipeline Design"], "tools": ["Pipeline Monitoring Dashboard"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'Docker Containerization', 'Master Docker for consistent development and deployment. Write efficient Dockerfiles. Implement multi-stage builds. Set up local development with Docker Compose.', '["Containerize your main application", "Optimize Dockerfile for production", "Create Docker Compose for local development", "Set up container registry"]'::jsonb, '{"templates": ["Dockerfile Best Practices", "Docker Compose Templates"], "tools": ["Container Security Scanner"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'Kubernetes Fundamentals', 'Understand Kubernetes for production workloads. Learn pods, services, deployments, and ingress. Evaluate managed Kubernetes: EKS, GKE, AKS. Decide if K8s is right for your stage.', '["Assess Kubernetes readiness for your startup", "Set up local Kubernetes with minikube/kind", "Create deployment manifests for core services", "Design namespace and resource strategy"]'::jsonb, '{"templates": ["Kubernetes Manifest Templates", "K8s Resource Planning Guide"], "tools": ["Kubernetes Cost Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'Deployment Strategies', 'Master blue-green, canary, and rolling deployments. Implement feature flags for safe releases. Design rollback procedures. Handle database migrations in deployments.', '["Choose deployment strategy for your application", "Implement feature flag system", "Create rollback runbook", "Design database migration workflow"]'::jsonb, '{"templates": ["Deployment Strategy Guide", "Rollback Procedure Template"], "tools": ["Feature Flag Platform Comparison"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'Monitoring and Observability', 'Implement comprehensive monitoring with Prometheus, Grafana, or Datadog. Set up logging with ELK or CloudWatch. Create meaningful alerts. Build observability culture.', '["Set up application monitoring dashboard", "Implement structured logging", "Create alert policies for critical metrics", "Design on-call rotation and escalation"]'::jsonb, '{"templates": ["Monitoring Dashboard Templates", "Alert Policy Framework"], "tools": ["Observability Platform Comparison"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Database Design (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Database Design', 'Master database selection, scaling strategies, sharding patterns, and caching for high performance', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'SQL vs NoSQL Decision Making', 'Choose the right database for each use case. Understand PostgreSQL, MySQL, MongoDB, DynamoDB trade-offs. Learn polyglot persistence. Design for your data access patterns.', '["Analyze your data access patterns", "Evaluate SQL vs NoSQL for each data type", "Document database selection rationale", "Create data model diagram"]'::jsonb, '{"templates": ["Database Selection Matrix", "Data Model Template"], "tools": ["Database Comparison Tool"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'Database Schema Design', 'Design efficient database schemas. Implement proper indexing strategies. Handle schema migrations safely. Design for query performance.', '["Design schema for core entities", "Create indexing strategy document", "Set up migration management tool", "Implement query performance testing"]'::jsonb, '{"templates": ["Schema Design Best Practices", "Migration Strategy Guide"], "tools": ["Query Performance Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'Database Scaling Strategies', 'Implement read replicas for scale. Understand vertical vs horizontal scaling. Design for high availability. Handle connection pooling efficiently.', '["Assess current database performance bottlenecks", "Design read replica strategy", "Implement connection pooling", "Create database scaling roadmap"]'::jsonb, '{"templates": ["Database Scaling Playbook", "HA Architecture Template"], "tools": ["Database Load Testing Framework"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Sharding and Partitioning', 'Learn database sharding patterns. Implement table partitioning for large datasets. Choose sharding keys wisely. Handle cross-shard queries.', '["Identify tables needing partitioning", "Design sharding strategy for high-volume data", "Implement partition pruning", "Create shard management procedures"]'::jsonb, '{"templates": ["Sharding Strategy Guide", "Partition Design Template"], "tools": ["Sharding Key Analyzer"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Caching Strategies', 'Implement caching with Redis or Memcached. Design cache invalidation strategies. Handle cache warming and thundering herd. Build multi-layer caching architecture.', '["Identify top caching opportunities", "Implement Redis caching for hot data", "Design cache invalidation strategy", "Create cache monitoring dashboard"]'::jsonb, '{"templates": ["Caching Strategy Guide", "Redis Best Practices"], "tools": ["Cache Hit Rate Analyzer"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: Security Framework (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'Security Framework', 'Build bulletproof security - OWASP compliance, authentication systems, encryption, and security audits', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'OWASP Top 10 Protection', 'Understand and protect against OWASP Top 10 vulnerabilities. Implement input validation and sanitization. Prevent SQL injection and XSS attacks. Set up security headers.', '["Audit application against OWASP Top 10", "Implement input validation framework", "Add security headers to all responses", "Set up automated security scanning"]'::jsonb, '{"templates": ["OWASP Compliance Checklist", "Security Header Configuration"], "tools": ["Vulnerability Scanner Setup Guide"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'Authentication and Authorization', 'Implement secure authentication with OAuth 2.0, JWT, and session management. Design role-based access control (RBAC). Handle multi-tenancy security. Implement MFA.', '["Design authentication architecture", "Implement JWT with proper security", "Create RBAC system for your application", "Add MFA for sensitive operations"]'::jsonb, '{"templates": ["Authentication Flow Diagrams", "RBAC Design Template"], "tools": ["Auth0/Cognito Comparison Guide"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Data Encryption', 'Implement encryption at rest and in transit. Manage encryption keys securely. Handle PII and sensitive data. Comply with data protection requirements.', '["Implement TLS for all communications", "Set up encryption at rest for databases", "Design key management strategy", "Create data classification system"]'::jsonb, '{"templates": ["Encryption Implementation Guide", "Key Management Policy"], "tools": ["Certificate Management Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'Security Audits and Penetration Testing', 'Plan and execute security audits. Work with penetration testing firms. Handle vulnerability disclosure. Create security incident response plan.', '["Schedule quarterly security audit", "Engage penetration testing partner", "Create vulnerability disclosure policy", "Design incident response runbook"]'::jsonb, '{"templates": ["Security Audit Checklist", "Incident Response Template"], "tools": ["Pen Testing Vendor Comparison"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Compliance and Security Certifications', 'Understand SOC 2, ISO 27001, and PCI DSS requirements. Plan certification roadmap. Implement compliance controls. Handle security questionnaires from enterprise customers.', '["Assess compliance requirements for your industry", "Create SOC 2 compliance roadmap", "Implement logging and audit trails", "Prepare security questionnaire responses"]'::jsonb, '{"templates": ["SOC 2 Compliance Checklist", "Security Questionnaire Template"], "tools": ["Compliance Management Platform Guide"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Scalability Patterns (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Scalability Patterns', 'Master load balancing, horizontal scaling, performance optimization, and handling traffic spikes', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'Load Balancing Strategies', 'Implement effective load balancing with ALB, NLB, or HAProxy. Design health checks and failover. Handle sticky sessions when needed. Optimize for Indian traffic patterns.', '["Set up load balancer for production", "Configure health checks for all services", "Implement graceful shutdown handling", "Design multi-region load balancing strategy"]'::jsonb, '{"templates": ["Load Balancer Configuration Guide", "Health Check Design"], "tools": ["Load Balancer Comparison Matrix"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'Horizontal Scaling Architecture', 'Design stateless services for horizontal scaling. Implement auto-scaling policies. Handle session management in distributed systems. Scale without downtime.', '["Identify stateful components to refactor", "Design auto-scaling policies", "Implement distributed session management", "Create scaling runbook"]'::jsonb, '{"templates": ["Auto-Scaling Policy Templates", "Stateless Service Design Guide"], "tools": ["Scaling Cost Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Performance Optimization', 'Optimize application performance end-to-end. Profile and fix bottlenecks. Implement lazy loading and code splitting. Optimize for mobile networks in India.', '["Profile application performance", "Identify and fix top 5 bottlenecks", "Implement frontend performance optimizations", "Set up performance monitoring"]'::jsonb, '{"templates": ["Performance Optimization Checklist", "Profiling Guide"], "tools": ["APM Tool Comparison"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'CDN and Edge Computing', 'Leverage CDNs for global performance. Implement edge caching strategies. Use Cloudflare, CloudFront, or Fastly effectively. Handle dynamic content at the edge.', '["Set up CDN for static assets", "Configure caching rules", "Implement edge functions for personalization", "Measure CDN performance improvements"]'::jsonb, '{"templates": ["CDN Configuration Guide", "Cache Header Strategy"], "tools": ["CDN Performance Analyzer"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Handling Traffic Spikes', 'Prepare for viral moments and flash sales. Implement queue-based load leveling. Design graceful degradation. Create capacity planning models.', '["Create traffic spike response plan", "Implement queue-based processing for spikes", "Design graceful degradation strategy", "Build capacity planning model"]'::jsonb, '{"templates": ["Capacity Planning Template", "Graceful Degradation Patterns"], "tools": ["Load Testing Framework"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: Technical Debt Management (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'Technical Debt Management', 'Manage code quality, strategic refactoring, technical documentation, and sustainable development practices', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'Code Quality Standards', 'Establish coding standards and style guides. Implement linting and formatting. Set up code quality gates. Create automated code review tools.', '["Create coding standards document", "Set up ESLint/Prettier or equivalent", "Implement code quality gates in CI", "Configure SonarQube or similar tool"]'::jsonb, '{"templates": ["Coding Standards Template", "Code Review Checklist"], "tools": ["Code Quality Tool Comparison"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Technical Debt Inventory', 'Identify and categorize technical debt. Create debt tracking system. Prioritize debt based on business impact. Communicate debt to stakeholders.', '["Audit codebase for technical debt", "Create technical debt register", "Prioritize debt items by impact/effort", "Present debt status to leadership"]'::jsonb, '{"templates": ["Technical Debt Register Template", "Impact Assessment Matrix"], "tools": ["Code Complexity Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Strategic Refactoring', 'Plan and execute refactoring safely. Use feature flags for incremental changes. Test refactored code thoroughly. Measure refactoring success.', '["Identify top 3 refactoring priorities", "Create refactoring plan with milestones", "Set up comprehensive tests before refactoring", "Define success metrics for refactoring"]'::jsonb, '{"templates": ["Refactoring Plan Template", "Testing Strategy for Refactoring"], "tools": ["Refactoring Progress Tracker"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Technical Documentation', 'Create living technical documentation. Document architecture decisions. Maintain runbooks and playbooks. Keep docs updated with automation.', '["Create architecture documentation", "Write runbooks for critical operations", "Set up documentation automation", "Implement doc review in PR process"]'::jsonb, '{"templates": ["Architecture Doc Template", "Runbook Template"], "tools": ["Documentation Platform Comparison"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'Sustainable Development Velocity', 'Balance speed with quality. Implement sustainable sprint practices. Allocate time for maintenance and improvements. Create technical excellence culture.', '["Define quality vs speed guidelines", "Allocate 20% time for tech improvements", "Create maintenance sprint cadence", "Build technical excellence metrics"]'::jsonb, '{"templates": ["Sprint Planning Guide", "Tech Excellence Scorecard"], "tools": ["Velocity Tracking Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Team & Processes (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Team & Processes', 'Build high-performing engineering teams - hiring, code reviews, agile practices, and engineering culture', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Engineering Hiring Excellence', 'Design technical interviews that predict success. Build diverse engineering teams. Create compelling engineering brand. Compete for talent in Indian market.', '["Design technical interview process", "Create engineering career ladder", "Build engineering employer brand", "Set up technical assessment system"]'::jsonb, '{"templates": ["Technical Interview Guide", "Engineering Levels Framework"], "tools": ["Candidate Assessment Matrix"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'Effective Code Reviews', 'Create code review culture that improves quality. Balance thoroughness with velocity. Handle review feedback constructively. Automate what can be automated.', '["Create code review guidelines", "Set up review metrics and SLAs", "Implement automated code checks", "Train team on effective reviewing"]'::jsonb, '{"templates": ["Code Review Guidelines", "PR Template"], "tools": ["Code Review Analytics Tool"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Agile for Startups', 'Implement agile practices that fit startup pace. Choose between Scrum, Kanban, or hybrid. Run effective ceremonies. Measure and improve team performance.', '["Choose agile methodology for your team", "Set up sprint cadence and ceremonies", "Create backlog management system", "Implement team performance metrics"]'::jsonb, '{"templates": ["Sprint Planning Template", "Retrospective Formats"], "tools": ["Agile Project Management Tool Guide"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Engineering Culture Building', 'Build culture of ownership and innovation. Create psychological safety for experimentation. Implement blameless postmortems. Foster continuous learning.', '["Define engineering cultural values", "Implement blameless postmortem process", "Create learning and development program", "Set up innovation time or hackathons"]'::jsonb, '{"templates": ["Postmortem Template", "Engineering Values Document"], "tools": ["Team Health Check Framework"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Remote Engineering Teams', 'Manage distributed engineering teams effectively. Create async communication practices. Build virtual collaboration culture. Handle timezone challenges.', '["Create async communication guidelines", "Set up collaboration tools and practices", "Design remote-first meeting culture", "Build virtual team bonding activities"]'::jsonb, '{"templates": ["Remote Work Policy for Engineers", "Async Communication Guide"], "tools": ["Remote Collaboration Tool Stack"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: CTO Decision Making (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'CTO Decision Making', 'Strategic technology leadership - roadmap planning, build vs buy decisions, vendor management, and tech strategy', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'Technology Roadmap Planning', 'Create technology roadmap aligned with business goals. Balance new features with technical investments. Communicate roadmap to stakeholders. Handle roadmap changes.', '["Create 12-month technology roadmap", "Align tech initiatives with business goals", "Define tech investment vs feature ratio", "Present roadmap to leadership"]'::jsonb, '{"templates": ["Technology Roadmap Template", "Tech Strategy Document"], "tools": ["Roadmap Planning Tool Guide"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Build vs Buy Decisions', 'Make informed build vs buy decisions. Evaluate SaaS, open source, and custom solutions. Calculate total cost of ownership. Handle vendor dependencies strategically.', '["Create build vs buy decision framework", "Evaluate 3 key systems for build vs buy", "Calculate TCO for major systems", "Document decision rationale"]'::jsonb, '{"templates": ["Build vs Buy Analysis Template", "TCO Calculator"], "tools": ["Vendor Evaluation Scorecard"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'Vendor Management', 'Select and manage technology vendors effectively. Negotiate contracts and SLAs. Handle vendor risk and dependencies. Plan for vendor transitions.', '["Create vendor evaluation criteria", "Negotiate key vendor contracts", "Set up vendor performance tracking", "Create vendor risk mitigation plan"]'::jsonb, '{"templates": ["Vendor Selection Matrix", "SLA Template"], "tools": ["Vendor Management Dashboard"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'Technology Due Diligence', 'Prepare for investor and M&A due diligence. Document your technology stack and practices. Address common due diligence concerns. Build investor-ready technical documentation.', '["Create technical due diligence package", "Document key technical decisions", "Address potential technical risks", "Prepare tech team for DD interviews"]'::jsonb, '{"templates": ["Tech DD Preparation Guide", "Technical Documentation Pack"], "tools": ["DD Checklist"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'CTO as Business Leader', 'Transition from technical leader to business leader. Communicate tech in business terms. Build relationships with non-technical stakeholders. Shape company strategy as CTO.', '["Create tech-to-business translation guide", "Build relationships with key stakeholders", "Participate in business strategy discussions", "Define CTO success metrics beyond tech"]'::jsonb, '{"templates": ["CTO Communication Framework", "Business-Tech Alignment Matrix"], "tools": ["CTO Leadership Development Plan"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
