-- P26: AgriTech & Farm-to-Fork Course Migration
-- 45 days, 9 modules, comprehensive agritech mastery for Indian startups

BEGIN;

-- Declare variables for IDs
DO $$
DECLARE
    v_product_id TEXT;
    v_mod_1_id TEXT;
    v_mod_2_id TEXT;
    v_mod_3_id TEXT;
    v_mod_4_id TEXT;
    v_mod_5_id TEXT;
    v_mod_6_id TEXT;
    v_mod_7_id TEXT;
    v_mod_8_id TEXT;
    v_mod_9_id TEXT;
BEGIN
    -- Generate IDs
    v_product_id := gen_random_uuid()::text;
    v_mod_1_id := gen_random_uuid()::text;
    v_mod_2_id := gen_random_uuid()::text;
    v_mod_3_id := gen_random_uuid()::text;
    v_mod_4_id := gen_random_uuid()::text;
    v_mod_5_id := gen_random_uuid()::text;
    v_mod_6_id := gen_random_uuid()::text;
    v_mod_7_id := gen_random_uuid()::text;
    v_mod_8_id := gen_random_uuid()::text;
    v_mod_9_id := gen_random_uuid()::text;

    -- Insert Product
    INSERT INTO "Product" (id, code, title, description, price, "estimatedDays", "createdAt", "updatedAt")
    VALUES (
        v_product_id,
        'P26',
        'AgriTech & Farm-to-Fork Mastery',
        'Complete guide to building agritech startups in India - from FPO formation to cold chain infrastructure. 9 modules covering agricultural value chain, APMC reforms, e-NAM integration, farm mechanization, government schemes, and export opportunities. India has 140M+ farmers and $350B agriculture market.',
        6999,
        45,
        NOW(),
        NOW()
    )
    ON CONFLICT (code) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        "estimatedDays" = EXCLUDED."estimatedDays",
        "updatedAt" = NOW();

    -- Get the product ID (in case of conflict)
    SELECT id INTO v_product_id FROM "Product" WHERE code = 'P26';

    -- Clean existing modules and lessons for this product
    DELETE FROM "Lesson" WHERE "moduleId" IN (SELECT id FROM "Module" WHERE "productId" = v_product_id);
    DELETE FROM "Module" WHERE "productId" = v_product_id;

    -- Module 1: AgriTech Landscape (Days 1-5)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_1_id, v_product_id, 'AgriTech Landscape', 'Understand India agritech ecosystem - market size, segments, regulations, and opportunities', 1, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_1_id, 1, 'India Agriculture Overview', 'Explore India $350B agriculture sector - 140M+ farmers, 55% rural employment, diverse cropping patterns. Understand key challenges: fragmented landholdings (avg 1.08 hectares), low productivity, price volatility, and market access. Learn about transformative opportunity for agritech startups to solve real farmer problems.', '["Study state-wise crop patterns and agricultural zones", "Identify top 5 agricultural challenges in your target region", "Research farmer income levels and spending patterns", "Map the agricultural value chain from farm to fork"]'::jsonb, '{"templates": ["India Agriculture Market Map", "Farmer Persona Template"], "tools": ["Crop Pattern Analyzer", "Regional Agriculture Database"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 2, 'AgriTech Startup Segments', 'Deep dive into agritech verticals: precision farming, farm management software, agri-fintech, market linkage, supply chain tech, drone services, IoT solutions. Study successful Indian agritech startups: DeHaat, Ninjacart, AgroStar, CropIn, Stellapps. Identify underserved segments with high growth potential.', '["Map all agritech segments with market size estimates", "Research 10 successful Indian agritech startups", "Identify your target segment based on expertise and opportunity", "Create competitive landscape for chosen segment"]'::jsonb, '{"templates": ["AgriTech Segment Matrix", "Startup Case Study Template"], "tools": ["AgriTech Landscape Analyzer"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 3, 'Agricultural Regulations Framework', 'Navigate Indian agricultural regulations: Essential Commodities Act, APMC Acts, Model Contract Farming Act 2018, Farm Laws 2020 (status and implications). Understand state-wise variations in agricultural marketing regulations. Learn about FSSAI requirements for food business.', '["Study Essential Commodities Act and recent amendments", "Research your state APMC regulations", "Understand Contract Farming Act provisions", "Map FSSAI license requirements for your business"]'::jsonb, '{"templates": ["Agricultural Regulation Checklist", "State-wise APMC Guide"], "tools": ["Compliance Requirement Mapper"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 4, 'Technology in Agriculture', 'Explore technology applications: satellite imagery for crop monitoring, IoT sensors for precision farming, AI/ML for yield prediction, blockchain for traceability, drones for spraying and surveillance. Understand technology adoption barriers among Indian farmers and solutions.', '["Identify 5 technology applications for your agritech idea", "Research technology adoption rates among target farmers", "Study successful tech deployment models in Indian agriculture", "Create technology integration roadmap"]'::jsonb, '{"templates": ["AgriTech Technology Stack", "Technology Adoption Framework"], "tools": ["Agricultural Technology Database"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_1_id, 5, 'Building Your AgriTech Strategy', 'Define your agritech startup strategy: target crops, geography, farmer segments, technology stack, business model. Create go-to-market approach considering farmer acquisition challenges. Plan for seasonal nature of agricultural business.', '["Define target crops and geography for first 2 years", "Create farmer acquisition strategy", "Design revenue model with unit economics", "Plan for agricultural seasonality"]'::jsonb, '{"templates": ["AgriTech Business Model Canvas", "Farmer Acquisition Playbook"], "tools": ["AgriTech Strategy Builder"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 2: FPO Formation (Days 6-10)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_2_id, v_product_id, 'FPO Formation', 'Master Farmer Producer Organization setup - registration, governance, NABARD support, and operations', 2, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_2_id, 6, 'Understanding FPOs', 'Learn about Farmer Producer Organizations - collective entities empowering small farmers. Understand FPO structures: Producer Companies under Companies Act, Cooperative Societies, Trusts. Study government 10,000 FPO scheme with ₹6865 crore allocation. Learn benefits: collective bargaining, input access, market linkage.', '["Study different FPO legal structures", "Research government 10,000 FPO formation scheme", "Identify successful FPOs in your target region", "Understand FPO economics and viability factors"]'::jsonb, '{"templates": ["FPO Structure Comparison Guide", "FPO Viability Assessment"], "tools": ["FPO Database India"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 7, 'FPO Registration Process', 'Master FPO registration as Producer Company under Companies Act 2013 Section 581B. Prepare documents: MOA, AOA, member consent, farmer details. Navigate MCA filing process. Understand capital requirements and shareholding structure. Timeline: 45-90 days for registration.', '["Prepare member farmer database with required details", "Draft Memorandum and Articles of Association", "Compile all required registration documents", "Begin MCA registration process"]'::jsonb, '{"templates": ["FPO MOA Template", "FPO Registration Checklist"], "tools": ["MCA Filing Guide for FPOs"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 8, 'FPO Governance Structure', 'Design effective FPO governance: Board of Directors election, CEO appointment, member participation. Create bylaws covering meetings, voting rights, profit sharing. Establish internal committees: procurement, marketing, finance. Build transparent decision-making processes.', '["Design board composition and election process", "Create FPO bylaws document", "Establish committee structure", "Define profit sharing mechanism"]'::jsonb, '{"templates": ["FPO Bylaws Template", "FPO Governance Manual"], "tools": ["FPO Meeting Management Tool"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 9, 'NABARD and SFAC Support', 'Access government support for FPOs through NABARD, SFAC, and state agencies. Understand equity grant scheme (₹15 lakh per FPO), credit guarantee fund, management cost support. Navigate application process. Connect with Cluster Based Business Organizations (CBBOs).', '["Identify eligible support schemes for your FPO", "Prepare equity grant application", "Connect with NABARD district office", "Engage with CBBO for handholding support"]'::jsonb, '{"templates": ["NABARD Application Guide", "SFAC Scheme Navigator"], "tools": ["FPO Support Scheme Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_2_id, 10, 'FPO Business Operations', 'Operationalize FPO business activities: input supply (seeds, fertilizers), output aggregation, primary processing, market linkage. Build relationships with input companies and buyers. Create member services: credit linkage, technical advice, insurance. Develop sustainable FPO business model.', '["Design FPO service portfolio for members", "Establish input supplier partnerships", "Create buyer network for output marketing", "Build member credit linkage program"]'::jsonb, '{"templates": ["FPO Business Plan Template", "Member Services Catalog"], "tools": ["FPO Operations Dashboard"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 3: APMC & e-NAM (Days 11-15)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_3_id, v_product_id, 'APMC & e-NAM', 'Navigate APMC reforms, e-NAM integration, direct marketing, and mandi operations', 3, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_3_id, 11, 'APMC System Deep Dive', 'Understand Agricultural Produce Market Committee system: history, structure, fee mechanisms. Study state-wise APMC variations - some reformed, others restrictive. Learn about market yard operations, commission agents (arhatiyas), auction systems. Identify opportunities from APMC reforms.', '["Study your state APMC Act and amendments", "Visit local APMC mandi to understand operations", "Map stakeholders: farmers, traders, commission agents", "Identify inefficiencies as startup opportunities"]'::jsonb, '{"templates": ["APMC State-wise Comparison", "Mandi Operations Guide"], "tools": ["APMC Fee Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 12, 'e-NAM Platform Integration', 'Master electronic National Agriculture Market (e-NAM) - unified national market for agricultural commodities. Understand e-NAM features: online bidding, quality assaying, electronic payment. Learn integration requirements for traders and FPOs. Study 1000+ mandis connected to e-NAM.', '["Register on e-NAM portal", "Understand e-NAM trading process", "Study quality assaying requirements", "Create integration plan for your platform"]'::jsonb, '{"templates": ["e-NAM Registration Guide", "e-NAM Trading Workflow"], "tools": ["e-NAM Price Discovery Dashboard"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 13, 'Direct Marketing Channels', 'Explore alternatives to APMC: direct marketing licenses, private market yards, farmer consumer markets. Understand legal requirements for direct procurement from farmers. Build direct farmer-buyer linkage models. Navigate interstate agricultural trade.', '["Apply for direct marketing license if required", "Identify private market yard opportunities", "Design direct farmer-buyer model", "Understand interstate trade permits"]'::jsonb, '{"templates": ["Direct Marketing License Application", "Farmer-Buyer Contract Template"], "tools": ["Direct Procurement Compliance Checker"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 14, 'Price Discovery Mechanisms', 'Learn agricultural price discovery: spot markets, futures trading (NCDEX, MCX), government MSP, contract pricing. Build price intelligence for farmers. Create transparent pricing models. Understand price volatility management strategies.', '["Set up commodity price tracking system", "Study MSP mechanism for major crops", "Explore futures market hedging options", "Design price communication for farmers"]'::jsonb, '{"templates": ["Commodity Price Tracker", "MSP Comparison Guide"], "tools": ["Agricultural Price Intelligence Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_3_id, 15, 'Building Market Linkage Platform', 'Design and build market linkage solution: farmer onboarding, buyer network, logistics integration, payment systems. Create value proposition for both sides. Learn from successful platforms: Ninjacart, DeHaat, WayCool. Plan technology and operations.', '["Design two-sided marketplace architecture", "Create farmer onboarding workflow", "Build buyer acquisition strategy", "Plan logistics and payment integration"]'::jsonb, '{"templates": ["Market Linkage Platform Blueprint", "Two-sided Marketplace Playbook"], "tools": ["AgriTech Platform Builder"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 4: Input Business (Days 16-20)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_4_id, v_product_id, 'Input Business', 'Build agri-input business - seeds, fertilizers, pesticides, licenses, and farmer advisory', 4, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_4_id, 16, 'Agri-Input Market Overview', 'Explore India $8B+ agri-input market: seeds ($3B), fertilizers ($20B+), crop protection ($5B+), farm equipment. Understand market structure: multinational companies, domestic players, dealer networks. Identify opportunities in input distribution and advisory.', '["Map agri-input market segments and players", "Study farmer input purchase behavior", "Identify underserved input segments", "Analyze distribution channel structure"]'::jsonb, '{"templates": ["Agri-Input Market Analysis", "Farmer Input Journey Map"], "tools": ["Input Market Size Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 17, 'Seeds Business Fundamentals', 'Navigate seed business: certification requirements, variety development, production, marketing. Understand Seed Act 1966, PPV&FR Act for variety protection. Learn about seed licensing from state agriculture departments. Build seed quality assurance systems.', '["Study seed certification process", "Research PPV&FR Act for variety protection", "Map seed licensing requirements in target states", "Design seed quality testing protocol"]'::jsonb, '{"templates": ["Seed Business Setup Guide", "Seed Certification Checklist"], "tools": ["Seed Variety Database"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 18, 'Fertilizers and Crop Protection', 'Master fertilizer and pesticide business: licensing under Fertilizer Control Order and Insecticides Act. Navigate state-level license requirements. Understand subsidy mechanisms (urea, P&K). Build compliant agrochemical distribution network.', '["Obtain fertilizer and pesticide sale licenses", "Understand subsidy claiming process", "Design compliant storage and handling", "Create product portfolio strategy"]'::jsonb, '{"templates": ["Fertilizer License Guide", "Pesticide Compliance Checklist"], "tools": ["Fertilizer Subsidy Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 19, 'Agricultural Advisory Services', 'Build farmer advisory business: crop recommendations, pest management, soil testing. Leverage technology: AI-based advisory, satellite imagery, weather integration. Create revenue models: subscription, input bundling, commission. Study AgroStar and BigHaat models.', '["Design advisory service framework", "Build crop recommendation engine", "Create pest and disease identification system", "Plan monetization through input linkage"]'::jsonb, '{"templates": ["Advisory Service Design Template", "Crop Recommendation Framework"], "tools": ["Agricultural Knowledge Base Builder"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_4_id, 20, 'Agri-Input E-commerce', 'Build online agri-input platform: product catalog, farmer app, delivery network, payment systems. Navigate e-commerce compliance for agri-inputs. Create farmer acquisition and retention strategies. Manage inventory and working capital efficiently.', '["Design agri-input e-commerce platform", "Build farmer mobile app", "Create last-mile delivery network", "Plan working capital and inventory management"]'::jsonb, '{"templates": ["Agri E-commerce Platform Architecture", "Rural Delivery Network Plan"], "tools": ["Inventory Management for AgriTech"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 5: Farm Mechanization (Days 21-25)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_5_id, v_product_id, 'Farm Mechanization', 'Master farm equipment business - rentals, CHCs, drones, government subsidies, and financing', 5, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_5_id, 21, 'Farm Mechanization Landscape', 'Explore India farm mechanization: 47% power tiller penetration vs 95%+ in developed countries. Understand equipment segments: tractors, tillers, harvesters, sprayers, irrigation. Study government Sub-Mission on Agricultural Mechanization (SMAM). Identify mechanization gaps by crop and region.', '["Map mechanization levels in target region", "Study SMAM scheme benefits and subsidies", "Identify equipment gaps for target crops", "Research successful mechanization startups"]'::jsonb, '{"templates": ["Mechanization Gap Analysis", "SMAM Subsidy Guide"], "tools": ["Farm Equipment Market Database"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 22, 'Custom Hiring Centers', 'Build Custom Hiring Centers (CHCs) for farm equipment rental. Understand CHC models: individual, FPO-based, government-supported. Navigate government subsidies (up to 80% for SC/ST). Design CHC operations: equipment mix, pricing, maintenance, booking systems.', '["Design CHC business model", "Select equipment portfolio for target region", "Apply for CHC establishment subsidy", "Create equipment booking and dispatch system"]'::jsonb, '{"templates": ["CHC Business Plan Template", "Equipment Selection Matrix"], "tools": ["CHC Viability Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 23, 'Drone Services in Agriculture', 'Master agricultural drone services: spraying, surveillance, mapping. Navigate DGCA drone regulations and exemptions for agriculture. Obtain Remote Pilot License and permissions. Build drone service operations: fleet management, pilot training, pricing.', '["Understand DGCA drone regulations for agriculture", "Apply for drone operator permissions", "Design drone service operations", "Create pilot training program"]'::jsonb, '{"templates": ["Drone License Application Guide", "Drone Operations SOP"], "tools": ["Agricultural Drone Service Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 24, 'Equipment Financing Models', 'Create equipment financing solutions for farmers: lease, rental, pay-per-use. Partner with NBFCs and banks for equipment loans. Understand interest subvention schemes. Build asset financing models with equipment as collateral.', '["Design equipment financing products", "Partner with 2-3 financial institutions", "Create loan documentation process", "Build collection and recovery systems"]'::jsonb, '{"templates": ["Equipment Lease Agreement", "Loan Documentation Checklist"], "tools": ["EMI Calculator for Farm Equipment"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_5_id, 25, 'Building Equipment Marketplace', 'Build farm equipment marketplace: new equipment, used equipment, rentals, spare parts. Create dealer network. Integrate financing and insurance. Design after-sales service model. Study EM3 AgriServices and TractorJunction models.', '["Design equipment marketplace platform", "Onboard equipment dealers and owners", "Integrate financing partners", "Create service network for maintenance"]'::jsonb, '{"templates": ["Equipment Marketplace Blueprint", "Dealer Onboarding Kit"], "tools": ["Farm Equipment Valuation Tool"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 6: Government Schemes (Days 26-30)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_6_id, v_product_id, 'Government Schemes', 'Navigate PM-KISAN, crop insurance, subsidies, and state agriculture programs', 6, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_6_id, 26, 'Central Agriculture Schemes', 'Master central government schemes: PM-KISAN (₹6000/year), PMFBY (crop insurance), PKVY (organic farming), MIDH (horticulture). Understand eligibility, application process, and benefits. Learn how startups can integrate scheme benefits into products.', '["Map all central agriculture schemes relevant to your model", "Understand PM-KISAN beneficiary database", "Study PMFBY integration opportunities", "Create scheme navigator for farmers"]'::jsonb, '{"templates": ["Central Schemes Database", "Farmer Eligibility Checker"], "tools": ["Agriculture Scheme Navigator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 27, 'State Agriculture Programs', 'Navigate state-specific schemes: input subsidies, market intervention, infrastructure support. Study progressive states: Maharashtra, MP, Karnataka, Andhra Pradesh agriculture policies. Understand state agriculture budget priorities. Build relationships with state agriculture departments.', '["Research your state agriculture schemes", "Map state agriculture department structure", "Identify partnership opportunities", "Create state-wise scheme comparison"]'::jsonb, '{"templates": ["State Scheme Comparison Matrix", "Agriculture Department Contact Directory"], "tools": ["State Agriculture Portal Guide"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 28, 'Subsidy and Grant Applications', 'Master agriculture subsidy applications: equipment subsidies (25-50%), infrastructure grants, interest subvention. Navigate online application portals. Prepare documentation for successful applications. Understand disbursement processes and timelines.', '["Identify applicable subsidies for your startup", "Prepare subsidy application documentation", "Submit applications through DBT portals", "Track application status and follow up"]'::jsonb, '{"templates": ["Subsidy Application Checklist", "DBT Registration Guide"], "tools": ["Subsidy Tracking Dashboard"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 29, 'Crop Insurance Integration', 'Integrate PMFBY into your platform: farmer enrollment, premium collection, claim processing. Partner with insurance companies for crop insurance distribution. Build weather-based index insurance products. Create insurance awareness for farmers.', '["Understand PMFBY enrollment process", "Partner with crop insurance companies", "Design insurance integration in your platform", "Create farmer insurance education content"]'::jsonb, '{"templates": ["PMFBY Integration Guide", "Insurance Partnership Template"], "tools": ["Crop Insurance Premium Calculator"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_6_id, 30, 'Building Government Partnerships', 'Develop government partnerships for agriculture: state procurement, scheme implementation partner, technology provider. Navigate government tendering process. Build credibility with agriculture departments. Create win-win collaboration models.', '["Identify government partnership opportunities", "Register on GeM and state procurement portals", "Prepare capability presentation", "Build relationships with key officials"]'::jsonb, '{"templates": ["Government Partnership Proposal", "GeM Registration Guide"], "tools": ["Government Tender Tracker"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 7: Cold Chain (Days 31-35)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_7_id, v_product_id, 'Cold Chain', 'Build cold chain infrastructure - warehousing, pack houses, logistics, and MIDH subsidies', 7, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_7_id, 31, 'Cold Chain Landscape in India', 'Understand India cold chain: 35% of produce wasted due to inadequate infrastructure. Study cold chain segments: pre-cooling, cold storage, refrigerated transport, retail refrigeration. Analyze gap of 35M MT cold storage capacity. Identify investment opportunities in cold chain.', '["Map cold chain gaps in your target region", "Study perishable crop volumes and wastage", "Identify cold chain infrastructure requirements", "Research successful cold chain startups"]'::jsonb, '{"templates": ["Cold Chain Gap Analysis", "Perishable Produce Matrix"], "tools": ["Cold Chain Investment Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 32, 'Pack House and Pre-cooling', 'Design pack house operations: sorting, grading, washing, packing, pre-cooling. Understand pack house infrastructure requirements. Navigate MIDH subsidies (35-55%) for pack houses. Create pack house business models with throughput planning.', '["Design pack house layout and workflow", "Calculate pack house capacity requirements", "Apply for MIDH pack house subsidy", "Create pack house operations SOP"]'::jsonb, '{"templates": ["Pack House Design Template", "MIDH Subsidy Application"], "tools": ["Pack House Capacity Calculator"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 33, 'Cold Storage Operations', 'Master cold storage business: single commodity vs multi-commodity, controlled atmosphere, ripening chambers. Understand capital costs (₹8000-15000/MT) and operating economics. Navigate financing through NCDC, NABARD. Build cold storage management systems.', '["Design cold storage facility specifications", "Calculate project cost and viability", "Apply for cold storage financing", "Create storage management system"]'::jsonb, '{"templates": ["Cold Storage DPR Template", "Financing Application Guide"], "tools": ["Cold Storage ROI Calculator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 34, 'Refrigerated Transport', 'Build reefer transport business: vehicles, routes, temperature monitoring, last-mile delivery. Understand vehicle financing and fleet management. Create reefer logistics network. Integrate IoT for cold chain visibility and compliance.', '["Design reefer transport network", "Acquire reefer vehicles with financing", "Implement temperature monitoring systems", "Create last-mile cold delivery model"]'::jsonb, '{"templates": ["Reefer Fleet Business Plan", "Cold Chain SLA Template"], "tools": ["Reefer Route Optimizer"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_7_id, 35, 'Technology in Cold Chain', 'Implement cold chain technology: IoT sensors, GPS tracking, temperature monitoring, blockchain traceability. Build cold chain visibility platform. Create compliance and audit trails. Study successful models: Tessol, Ecozen, Inficold.', '["Select cold chain IoT solution", "Implement temperature monitoring system", "Build traceability and compliance dashboard", "Create customer visibility portal"]'::jsonb, '{"templates": ["Cold Chain IoT Architecture", "Traceability System Design"], "tools": ["Cold Chain Monitoring Platform"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 8: Export & Processing (Days 36-40)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_8_id, v_product_id, 'Export & Processing', 'Master food processing business - FSSAI, exports, APEDA, and value addition', 8, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_8_id, 36, 'Food Processing Fundamentals', 'Explore India $500B food processing opportunity: only 10% of produce processed vs 70% in developed countries. Understand processing segments: primary, secondary, tertiary. Study PM Formalization of Micro Food Processing Enterprises (PMFME) scheme with 35% subsidy.', '["Identify food processing opportunities for target crops", "Study PMFME scheme benefits and eligibility", "Research processing technology requirements", "Map food processing clusters in region"]'::jsonb, '{"templates": ["Food Processing Opportunity Assessment", "PMFME Application Guide"], "tools": ["Processing Unit Economics Calculator"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 37, 'FSSAI Licensing and Compliance', 'Master FSSAI requirements: registration, state license, central license. Understand license categories based on turnover and business type. Navigate FSSAI portal and application process. Implement food safety and quality systems.', '["Determine FSSAI license category required", "Prepare FSSAI application documents", "Apply through FoSCoS portal", "Implement food safety management system"]'::jsonb, '{"templates": ["FSSAI License Application Guide", "Food Safety Compliance Checklist"], "tools": ["FSSAI License Category Finder"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 38, 'Agricultural Exports', 'Navigate agricultural exports: APEDA registration, phytosanitary certification, export quality requirements. Understand key export commodities: rice, spices, fresh produce, processed foods. Build export compliance and documentation systems.', '["Register with APEDA as exporter", "Understand phytosanitary requirements", "Study target market import regulations", "Create export documentation system"]'::jsonb, '{"templates": ["APEDA Registration Guide", "Export Documentation Checklist"], "tools": ["Export Compliance Navigator"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 39, 'Quality Certifications', 'Obtain quality certifications: Organic (NPOP, USDA, EU), GlobalGAP, HACCP, ISO 22000. Understand certification process and costs. Build traceability for certified produce. Create premium pricing through certifications.', '["Identify required certifications for target markets", "Select certification bodies", "Implement quality management systems", "Build certification traceability"]'::jsonb, '{"templates": ["Certification Roadmap Template", "Quality Management System Guide"], "tools": ["Certification Cost-Benefit Analyzer"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_8_id, 40, 'Value Addition and Branding', 'Create consumer brands from farm produce: packaging, branding, distribution. Build D2C channels for premium products. Navigate retail and e-commerce channels. Study successful farm-to-fork brands: Farmley, Country Delight, Licious.', '["Develop brand identity for processed products", "Design premium packaging", "Build D2C sales channel", "Create retail distribution strategy"]'::jsonb, '{"templates": ["Farm Brand Building Guide", "D2C Channel Strategy"], "tools": ["Farm Brand Launch Toolkit"]}'::jsonb, 60, 50, 5, NOW(), NOW());

    -- Module 9: AgriTech Funding (Days 41-45)
    INSERT INTO "Module" (id, "productId", title, description, "orderIndex", "createdAt", "updatedAt")
    VALUES (v_mod_9_id, v_product_id, 'AgriTech Funding', 'Secure agritech funding - NABARD, impact investors, agri-focused VCs, and government grants', 9, NOW(), NOW());

    INSERT INTO "Lesson" (id, "moduleId", day, title, "briefContent", "actionItems", resources, "estimatedTime", "xpReward", "orderIndex", "createdAt", "updatedAt") VALUES
    (gen_random_uuid()::text, v_mod_9_id, 41, 'AgriTech Investment Landscape', 'Understand agritech funding: $1B+ invested in Indian agritech since 2020. Study agri-focused investors: Omnivore, Ankur Capital, Accel, Sequoia. Learn agritech valuation metrics. Understand investor focus areas and return expectations.', '["Map agritech investors and their portfolio", "Study recent agritech funding rounds", "Understand agritech valuation benchmarks", "Identify potential investors for your stage"]'::jsonb, '{"templates": ["AgriTech Investor Database", "Investment Round Comparison"], "tools": ["AgriTech Funding Tracker"]}'::jsonb, 60, 50, 1, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 42, 'Government Funding Sources', 'Access government funding: NABARD VBMSSY scheme, Startup India Seed Fund, RKVY-RAFTAAR, Agri-Udaan accelerator. Understand eligibility and application processes. Navigate biotechnology funding through DBT. Apply for state innovation funds.', '["Identify eligible government funding schemes", "Prepare NABARD loan application", "Apply to RKVY-RAFTAAR program", "Register on Startup India portal"]'::jsonb, '{"templates": ["Government Funding Application Kit", "NABARD Loan Preparation Guide"], "tools": ["AgriTech Grant Finder"]}'::jsonb, 60, 50, 2, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 43, 'Impact Investment in AgriTech', 'Attract impact investors focused on farmer welfare. Understand impact metrics: farmer income improvement, smallholder reach, environmental sustainability. Build impact measurement systems. Study impact investors: Acumen, Aavishkaar, Caspian.', '["Define impact metrics for your startup", "Create impact measurement framework", "Research impact investors in agritech", "Prepare impact investment pitch"]'::jsonb, '{"templates": ["Impact Metrics Framework", "Impact Investment Pitch Deck"], "tools": ["Impact Measurement Dashboard"]}'::jsonb, 60, 50, 3, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 44, 'AgriTech Pitch Preparation', 'Craft compelling agritech pitch: problem, solution, farmer value proposition, market size, business model, traction. Address common investor concerns: unit economics, farmer acquisition cost, seasonality, scalability. Practice pitch with feedback.', '["Create agritech-specific pitch deck", "Prepare for agri-sector specific questions", "Build traction dashboard with key metrics", "Practice pitch with industry mentors"]'::jsonb, '{"templates": ["AgriTech Pitch Deck Template", "Investor Q&A Preparation"], "tools": ["Pitch Practice Platform"]}'::jsonb, 60, 50, 4, NOW(), NOW()),
    (gen_random_uuid()::text, v_mod_9_id, 45, 'Scaling AgriTech Venture', 'Plan agritech scale-up: geographic expansion, crop diversification, vertical integration. Manage working capital for agriculture seasonality. Build defensible moats in agritech. Create sustainable growth strategy with investor alignment.', '["Create 3-year expansion roadmap", "Plan working capital for scale", "Identify competitive moats to build", "Develop investor update and governance"]'::jsonb, '{"templates": ["AgriTech Scale-up Playbook", "Working Capital Management Guide"], "tools": ["AgriTech Growth Planner"]}'::jsonb, 60, 50, 5, NOW(), NOW());

END $$;

COMMIT;
